codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Contact for this particular Account.</description>
        <inlineHelpText>Status of the Contact for this particular Account.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending OES Review</fullName>
                </value>
                <value>
                    <fullName>Analyst Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Analyst Review Complete</fullName>
                </value>
                <value>
                    <fullName>OES RFI In Progress</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>OES Subapplication Review Complete</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Selected for Submission to FEMA</fullName>
                </value>
                <value>
                    <fullName>Not Selected - Pending Future Consideration</fullName>
                </value>
                <value>
                    <fullName>Submitted to FEMA</fullName>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Pending</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Review Pending</fullName>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>By Subapplicant after funds are obligated</fullName>
                </value>
                <value>
                    <fullName>By Subapplicant with no funds obligated</fullName>
                </value>
                <value>
                    <fullName>By OES</fullName>
                </value>
                <value>
                    <fullName>Waitlist Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>OES Review</fullName>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Contact Junction</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Working Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Responsible Representative</fullName>
                </value>
                <value>
                    <fullName>Match Commitment</fullName>
                </value>
                <value>
                    <fullName>Maintenance Commitment</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic Analyst</fullName>
                </value>
                <value>
                    <fullName>Authorized Agent</fullName>
                    <isActive>false</isActive>
                    <label>Authorized Agent</label>
                </value>
                <value>
                    <fullName>Requestor</fullName>
                    <isActive>false</isActive>
                    <label>Requestor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HMA_ContactRoleTriggerHandler.cls
public without sharing class HMA_ContactRoleTriggerHandler extends TriggerHandler implements TriggerInterface {
    static Map<String, Contact> contactDetailsMap = new Map<String, Contact>();
    static  Set<Id> contactIds = new Set<Id>();
    static  Set<Id> accountIds = new Set<Id>();
    public HMA_ContactRoleTriggerHandler() {

    }

    public override void beforeInsert() {
        processContactRoles();
        if(contactIds.size() >0){
            prepareContactDetails();
            processAccountContactJunctionRecord((List<Contact_Role__c>) Trigger.new);
        }
    }

    public override void afterInsert() {
        processContactRoles((List<Contact_Role__c>) Trigger.new);
    }

    private static void processContactRoles(){
        for(Contact_Role__c contactRole: (List<Contact_Role__c>)Trigger.new){
            if(isValidaContactRoleForAcContactRelationship(contactRole.Role__c)){
                contactIds.add(contactRole.Contact__c);
            }
        }
    }

    private static void prepareContactDetails(){
        Contact[] contacts = [SELECT Id, AccountId FROM Contact WHERE Id IN:contactIds AND AccountId != null];
        for(Contact contact: contacts){
            if(contactDetailsMap.get(contact.Id) == null){
                contactDetailsMap.put(contact.Id, contact);
            }else{
                contactDetailsMap.put(contact.Id, contact);
            }
            /*Prepare account set*/
            if(contact.AccountId != null){
                accountIds.add(contact.AccountId);
            }
        }
    }

    /************************************
    * Author : Rakesh
    * Date : 10th August 2021
    * Method : processContactRoles
    * Parameters : List of Contact_Role__c
    * Description : Check User and create community ApplicationUser send invitation to fema users only
    TODO: We are only processing for FEMA Users
    *************************************/

    private static void processContactRoles(List<Contact_Role__c> contactRoleRecords) {
        Set<Id> appIds = new Set<Id>();
        Set<Id> contactRoleIds = new Set<Id>();
        for(Contact_Role__c contactRole : contactRoleRecords) {
            appIds.add(contactRole.Application__c);
            if(isValidaContactRoleForAcContactRelationship(contactRole.Role__c)) {
                    contactRoleIds.add(contactRole.Id);
            }
            
        }
        if(contactRoleIds.size() == 0) return;
        Map<Id, Application__c> appIdToApplicationMap = new Map<Id, Application__c>([SELECT Id, Status_Reason__c, Status__c, (SELECT Id, Contact__c, Contact__r.Email, Role__c FROM Contact_Roles__r
                                                                                        WHERE Id IN :contactRoleIds)
                                                                                        FROM Application__c
                                                                                        WHERE Id IN :appIds]);
                                                                                               
        if(appIdToApplicationMap.size() > 0) {
	        HMA_ApplicationHelper.checkUserAndCreateCommunityApplicationUser(appIdToApplicationMap.keySet());
	        HMA_ApplicationHelper.sendInviteToContactRoleUsers(appIdToApplicationMap);
         }
    }
    //TODO : Do we need to consider update contact role scenarios

    private static void processAccountContactJunctionRecord(List<Contact_Role__c> contactRoleRecords) {
        //List<Id> contactIds = new List<Id>();
                //collect contact Ids from List of ContactRole
        /*for(Contact_Role__c crole : contactRoleRecords) {
            if(crole.Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_FEMA_EHP_ANALYST) ||
                    crole.Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_FEMA_REVIEW) ||
                    crole.Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_FEMA_PROGRAMMATIC_ANALYST) ||
                    crole.Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_REQUESTOR) ||
                    crole.Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_RESPONSIBLE_REPRESENTATIVE) ||
                    crole.Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_VIEWER) ||
                    crole.Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_CONTRIBUTOR)
                    ){
                        contactIds.add(crole.Contact__c);
                }

        }*/
        //String femaAccountName = KeyValueHelper.getTextValue('FEMA_Account_Name');
        //List<Account> accountList = [SELECT Id, Name FROM Account WHERE Name = :femaAccountName];
        //&& accountList.size() > 0
        if(contactIds.size() > 0) {
            Map<Id, AccountContactRole__c> contactIdAccountContactRoleMap = new Map<Id, AccountContactRole__c>();
                List<AccountContactRole__c> accountContactRoles = [SELECT Id, Name, Status__c, Contact_Name__c FROM AccountContactRole__c 
                                                                    WHERE Account_Name__c IN :accountIds
                                                                        AND Contact_Name__c IN :contactDetailsMap.values()];
                if(accountContactRoles.size() > 0) {
                    for(AccountContactRole__c acr : accountContactRoles) {
                        contactIdAccountContactRoleMap.put(acr.Contact_Name__c, acr);
                    }
                    for(Contact_Role__c conRole : contactRoleRecords) {
                    if(isValidaContactRoleForAcContactRelationship(conRole.Role__c)){
                        if(contactIdAccountContactRoleMap.containsKey(conRole.Contact__c)) {
                            conRole.AccountContactJunction__c = contactIdAccountContactRoleMap.get(conRole.Contact__c)?.Id;
                        } else {
                            //This is the case where some of the contact role do not have accountContactRole records then we should create
                            // accountContactRole records.
                            AccountContactRole__c acr = createAccountContactRoleRecord(contactDetailsMap.get(conRole.Contact__c)?.AccountId, conRole.Contact__c, conRole);
                            if(acr != null) contactIdAccountContactRoleMap.put(conRole.Contact__c, acr);
                        }
                    }
                }
                    upsert contactIdAccountContactRoleMap.values();
                    //This for loop for newly created accountContactRole records
                    for(Contact_Role__c conRole : contactRoleRecords) {
                    if(isValidaContactRoleForAcContactRelationship(conRole.Role__c)) {
                        conRole.accountContactJunction__c = contactIdAccountContactRoleMap.get(conRole.Contact__c)?.Id;
                    }
                }
                } else {
                    for(Contact_Role__c conRole : contactRoleRecords) {
                    if(isValidaContactRoleForAcContactRelationship(conRole.Role__c)) {
                        AccountContactRole__c acr = createAccountContactRoleRecord(contactDetailsMap.get(conRole.Contact__c)?.AccountId, conRole.Contact__c, conRole);
                        if(acr != null) contactIdAccountContactRoleMap.put(conRole.Contact__c, acr);
                    }
                }
                    insert contactIdAccountContactRoleMap.values();
                    for(Contact_Role__c conRole : contactRoleRecords) {
                    if(isValidaContactRoleForAcContactRelationship(conRole.Role__c)) {
                        conRole.accountContactJunction__c = contactIdAccountContactRoleMap.get(conRole.Contact__c)?.Id;
                    }
                }
        }
    }
    }

    private static AccountContactRole__c createAccountContactRoleRecord(Id accountId, Id contactId, Contact_Role__c conRole) {
        if(accountId == null || contactId == null) return null;
        if(conRole.Application__c == null) return null;
        AccountContactRole__c acr = new AccountContactRole__c();
        acr.Account_Name__c = accountId;
        acr.Contact_Name__c = contactId;
        acr.Status__c = 'Active';
        return acr;
    }

    private static Boolean isValidaContactRoleForAcContactRelationship(String role){
        List<String> roles = role?.split(';');
        if(roles != null){
            if(roles.indexOf(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_FEMA_EHP_ANALYST) != -1 ||
                    roles.indexOf(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_FEMA_PROGRAMMATIC_ANALYST) != -1 ||
                    roles.indexOf(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_FEMA_REVIEW) != -1 ||
                    roles.indexOf(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_REQUESTOR) != -1 ||
                    roles.indexOf(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_RESPONSIBLE_REPRESENTATIVE) != -1 ||
                    roles.indexOf(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_VIEWER) != -1 ||
                    roles.indexOf(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_CONTRIBUTOR) != -1
                    ){
                return true;
            }
        }
        return false;
    }
}