codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Global_List__c</fullName>
        <description>Shows Contact Role List of Picklist values on LWC Component.</description>
        <inlineHelpText>Role of this Contact for this particular Account.</inlineHelpText>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Role_List</valueSetName>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/ALS_ContactAccounts_CtrlTest.cls
@isTest
public with sharing class ALS_ContactAccounts_CtrlTest {
    @isTest
    public static void testContactAccount(){
        Account acc = new Account(Name='test12f', Entity_Type__c=ALS_CONSTANTS.Account_EntityType_City);
        insert acc;
        Contact con =new Contact(LastName='Test con', AccountId=acc.Id);
        insert con;
        AccountContactRole__c accCon = new AccountContactRole__c(Account_Name__c=acc.Id,Contact_Name__c=con.Id, Contact_Role_Global_List__c = ALS_CONSTANTS.ACRole_ContactRole_Employee);
        insert accCon;
        test.startTest();
        ALS_ContactAccounts_Ctrl.getContactAccountsInfo(con.Id,'');
        ALS_ContactAccounts_Ctrl.deleteRecords(accCon.Id);
        test.stopTest();
    }
}