codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Global_List__c</fullName>
        <description>Shows Contact Role List of Picklist values on LWC Component.</description>
        <inlineHelpText>Role of this Contact for this particular Account.</inlineHelpText>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Role_List</valueSetName>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Incident_Subrecipient_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Sub - Recipient  to which this junction record is related.</description>
        <inlineHelpText>Sub - Recipient  to which this junction record is related.</inlineHelpText>
        <label>Sub Recipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Incident_Subrecipient_Stages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <description>Incident to which this junction is related.</description>
        <inlineHelpText>Incident to which this junction is related.</inlineHelpText>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipName>Incident_sub_recipient_stage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Incident Subrecipient Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Subrecipient Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incident Subrecipient summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Incident_Subrecipient_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look Up to Incident Sub Recipient Summary which is having the same Sub Recipient and same Incident as the Project.</description>
        <inlineHelpText>Links to summary of all Projects within this Incident for this Subrecipient.</inlineHelpText>
        <label>Incident Subrecipient Summary</label>
        <referenceTo>Incident_Subrecipient_Stage__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project_Role__c.object
<CustomObject>
    <description>It is a junction object between Project object and Contact object.</description>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is a lookup field to Contact Role object, which is a junction object between Account and Contact.</description>
        <label>Contact Role</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>This field defines what type of contact this particular person is.</description>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_Signing_Authority__c</fullName>
        <label>Has Signing Authority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incident_Subrecipient_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Subrecipient Summary</label>
        <referenceTo>Incident_Subrecipient_Stage__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Mailing_Contact__c</fullName>
        <label>Is Mailing Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <label>Programs</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public Assistance</fullName>
                </value>
                <value>
                    <fullName>Hazard Mitigation Assistance</fullName>
                </value>
                <value>
                    <fullName>FMAG</fullName>
                </value>
                <value>
                    <fullName>Grants</fullName>
                </value>
                <value>
                    <fullName>IA - (Parent)</fullName>
                </value>
                <value>
                    <fullName>ISP - (Parent)</fullName>
                </value>
                <value>
                    <fullName>NEHRP - (Parent)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It Stores the id of the project record for this project role.</description>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Role_Global_List__c</fullName>
        <description>Shows list of Roles related to Project Role</description>
        <label>Project Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Project_Role_List</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subrecipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subrecipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <displayFormat>PRN-{000000}</displayFormat>
        <label>Project Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/ALS_ProjectJunctionEditController_Ctrl.cls
public with sharing class ALS_ProjectJunctionEditController_Ctrl {
    @AuraEnabled
    public Static Map<String,Object> saveDetails(String projectRecordId, String AccountDetail, String ProjectRoleDetail, String ContactDetail, String contactRole, Boolean isEdit, String srcObject, String programs) {
        //Project__c projectDetails = (Project__c) JSON.deserialize(projectDetail, Project__c.class);//Deserialization of Project Record
        String projectId = projectRecordId;
        Account accountDetails = (Account) JSON.deserialize(AccountDetail, Account.class);//Deserialization of Account Record
        Contact contactDetails = (Contact) JSON.deserialize(ContactDetail, Contact.class);//Deserialization of Contact Record
        AccountContactRole__c contactRoles = (AccountContactRole__c) JSON.deserialize(contactRole, AccountContactRole__c.class);//Deserialization of Contact Role Record
        Project_Role__c projectRoleDetails = (Project_Role__c) JSON.deserialize(ProjectRoleDetail, Project_Role__c.class);//Deserialization of Project Role Record
        if(isEdit != true){ //Create a new Project Role..
           if(ContactDetails.Id != null){
               if(contactRoles.Contact_Role_Global_List__c==null){
                   // Scenario : Existing Contact role
                   AccountContactRole__c cRole = [SElect Id from AccountContactRole__c Where Contact_Name__c=:contactDetails.Id AND Account_Name__c=: accountDetails.Id LIMIT 1];
                   projectRoleDetails.AccountContactJunction__c = cRole.Id;
               }else if(contactRoles.Contact_Role_Global_List__c!=null){
                    // Existing Contact and New contact role
                   contactRoles.Account_Name__c = accountDetails.Id;
                   contactRoles.Contact_Name__c = contactDetails.Id;
                   string msg='';
                   try{
                   insert contactRoles;
                  }catch (DmlException e){
                    System.debug('Inside the error for duplicate records');
                          for(Integer i = 0; i < e.getNumDml(); i++){
                        //Get Validation Rule & Trigger Error Messages
                        msg =+ e.getDmlMessage(i) +  '\n' ;
                    }
                    throw new AuraHandledException(msg);
                }
                   projectRoleDetails.AccountContactJunction__c = contactRoles.Id;
               }
           }else{
                // Creating new contact and New contact role
               string msg='';
                try{
                insert contactDetails;
                  }catch (DmlException e){
                System.debug('Inside the error for duplicate records');
                for (Integer i = 0; i < e.getNumDml(); i++) {
                    //Get Validation Rule & Trigger Error Messages
                    msg =+ e.getDmlMessage(i) +  '\n' ;
                }
                throw new AuraHandledException(msg);
            }
               contactRoles.Account_Name__c = accountDetails.Id;
               contactRoles.Contact_Name__c = contactDetails.Id;
                insert contactRoles;
               projectRoleDetails.AccountContactJunction__c = contactRoles.Id;
             }
            List<Project__c> projectList = new List<Project__c>();
            switch on srcObject {
                when 'Project__c' {
                    projectRoleDetails.Project_Name__c =projectId;
                }
                when 'Incident_Subrecipient_Stage__c' {
                    projectRoleDetails.Incident_Subrecipient_Summary__c =projectId;

                }
                when 'Account' {
                    projectRoleDetails.Subrecipient__c =projectId;
                }
            }
            if(programs != null) {
                    projectRoleDetails.Programs__c = programs;

           }


           string msg='';
           try{
             insert projectRoleDetails;
           }catch (DmlException e){
            System.debug('Inside the error for duplicate records');
            for (Integer i = 0; i < e.getNumDml(); i++) {
                //Get Validation Rule & Trigger Error Messages
                msg =+ e.getDmlMessage(i) +  '\n' ;
            }
              throw new AuraHandledException(msg);
            }
       
          }else if(isEdit == true){//Update a Existing Project Role..
        string msg='';
            try{
              UPDATE projectRoleDetails;
            }catch (DmlException e){
              System.debug('Inside the error for duplicate records');

              for(Integer i = 0; i < e.getNumDml(); i++) {
                  //Get Validation Rule & Trigger Error Messages
                  msg =+ e.getDmlMessage(i) +  '\n' ;
              }
              throw new AuraHandledException(msg);
            }
      }

          //send the email if project role is authorized Agent
            ProjectSharingHelper.shareRecords(projectRoleDetails.Id);
          
        Map<String,Object> resultMap = new Map<String,Object>();
        resultMap.put('Success','success');
        return resultMap;
    }

    @AuraEnabled
    //Get detail of selected record
    public Static Map<String,Object> getDetails(String junctionIds ){
        String objId = junctionIds;
        Map<String, Object> resultMap = new Map<String, Object>();
        Project_Role__c projecRoleRecord = [SELECT Id, Has_Signing_Authority__c, Is_Mailing_Contact__c, Contact_Type__c,Programs__c, Project_Name__c, AccountContactJunction__c, AccountContactJunction__r.Account_Name__c, AccountContactJunction__r.Contact_Name__c, Project_Role_Global_List__c  FROM Project_Role__c WHERE Id =: objId]; //Role__c **
        resultMap.put('JunctionObj',projecRoleRecord);
        return resultMap;
    }
    @AuraEnabled
    public static Map<String, String> getIncidentAndSubrecipientName(String incidentSubrecipientSummaryId) {
        Map<String, String> resultMap = new Map<String, String>();
        resultMap.put('incidentName', '');
        resultMap.put('subrecipientName', '');
        List<Incident_Subrecipient_Stage__c> issRecord = [
                SELECT Incident__r.Name, Account__r.Name FROM Incident_Subrecipient_Stage__c
                WHERE Id =:incidentSubrecipientSummaryId
        ];
        if(issRecord.size() > 0) {
            resultMap.put('incidentName', issRecord[0].Incident__r.Name);
            resultMap.put('subrecipientName', issRecord[0].Account__r.Name);
        }
        return resultMap;
    }
}