codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/ALS_AccountContacts_CtrlTest.cls
@isTest
public with sharing class ALS_AccountContacts_CtrlTest {
    @testSetup private static void setup(){
        Account acc = new Account(Name='test12f', Entity_Type__c= ALS_CONSTANTS.Account_EntityType_City);
        insert acc;
        Contact con =new Contact(LastName='Test con', AccountId=acc.Id);
        insert con;
        AccountContactRole__c accCon = new AccountContactRole__c(Account_Name__c=acc.Id,Contact_Name__c=con.Id);
        insert accCon;
    }
    @isTest
	public static void testAccountContact(){
        test.startTest();
        AccountContactRole__c getAccountContactRoleId = [SELECT Id FROM AccountContactRole__c WHERE Account_Name__r.Name = 'test12f'];

        ALS_AccountContacts_Ctrl.getAccountContactsInfo(getAccountContactRoleId.Id,'');
        AccountContactRole__c getAccountContact = [SELECT Id FROM AccountContactRole__c WHERE Id = :getAccountContactRoleId.Id ];
        System.assertEquals(getAccountContactRoleId.Id, getAccountContact.Id);

        ALS_AccountContacts_Ctrl.deleteRecords(getAccountContactRoleId.Id);
        List<AccountContactRole__c> deleteAccountContactsList = [SELECT Id FROM AccountContactRole__c WHERE Id = : getAccountContactRoleId.Id ];
        System.assertEquals(0, deleteAccountContactsList.size());
        test.stopTest();
    }
}