codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Contact for this particular Account.</description>
        <inlineHelpText>Status of the Contact for this particular Account.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Disaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Disaster</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Plan_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The project/plan title must include the subapplicant name and subapplication type or project type. Do not use abbreviations in the title. For example, Marin County Marin Center Exhibit Hall - Seismic Retrofit Project, City of Los Angeles Stormwater Analys</inlineHelpText>
        <label>Project / Plan Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>OES Review</fullName>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Application_Due_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Subapplication Due Date</label>
        <type>Date</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Contact Junction</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Working Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Responsible Representative</fullName>
                </value>
                <value>
                    <fullName>Match Commitment</fullName>
                </value>
                <value>
                    <fullName>Maintenance Commitment</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic Analyst</fullName>
                </value>
                <value>
                    <fullName>Authorized Agent</fullName>
                    <isActive>false</isActive>
                    <label>Authorized Agent</label>
                </value>
                <value>
                    <fullName>Requestor</fullName>
                    <isActive>false</isActive>
                    <label>Requestor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Federal Incident Declaration Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Incident Declaration Number. DR number if a Major Disaster, CDAA Number if CDAA-Only, etc.</inlineHelpText>
        <label>Declaration Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Pre_Application__c.object
<CustomObject>
    <fields>
        <fullName>Disaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Disaster</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Pre-Applications</relationshipLabel>
        <relationshipName>Pre_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
                <value>
                    <fullName>Analyst Review</fullName>
                </value>
                <value>
                    <fullName>Request for Information</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Manager Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Application_Due_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sub-Application Due Date</label>
        <type>Date</type>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HMA_FundingDeadlineReminderBatch.cls
global class HMA_FundingDeadlineReminderBatch implements Database.Batchable<SObject>{
    Integer nDays = 30;
    Boolean isError = false;
    String errorMessage = '';
    List<String> applicationNames = new List<String>();
    public HMA_FundingDeadlineReminderBatch(Integer days){
        nDays = days;
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Date dueDate = system.today().addDays(nDays);
        System.debug('dueDate======='+dueDate);
        return Database.getQueryLocator('SELECT id, Name, Sub_Application_Due_Date__c , Project_Plan_Title__c, Pre_Application__c, Pre_Application__r.Name, Disaster__r.Declaration_Number__c, ' +
                '(SELECT Id, Role__c, AccountContactJunction__c, AccountContactJunction__r.Contact_Name__c, AccountContactJunction__r.Contact_Name__r.Email, AccountContactJunction__r.Contact_Name__r.Name FROM Contact_Roles__r ' +
                'WHERE Role__c includes(\'Responsible Representative\', \'Primary Contact\', \'Contributor\')) '+
                'from Application__c ' +
                'WHERE Sub_Application_Due_Date__c =:dueDate AND Status__c = \'Draft\' ORDER BY Name');
    }
    global void execute(Database.BatchableContext bc, List<Application__c> apps) {
        try {
            List<OrgWideEmailAddress> fromAddresses = new List<OrgWideEmailAddress>();
            List<Messaging.SingleEmailMessage> allMails = new List<Messaging.SingleEmailMessage>();
            EmailTemplate templateToSend = [Select id, HtmlValue, Subject from EmailTemplate where name = 'HMA_Funding_Deadline_Notification' LIMIT 1];
            String fromAddr = KeyValueHelper.getTextValue('HMA_From_Email_Addresses');
            
            Id OrgWideEmailAddressId;
            if(String.isNotBlank(fromAddr)){
                fromAddresses =  [Select Id from OrgWideEmailAddress where DisplayName=: fromAddr];
            }
            if(fromAddresses.size()>0){
                OrgWideEmailAddressId = fromAddresses[0].Id;
            }
            for(Application__c app : apps) {
                System.debug('app=='+app);
                for(Contact_Role__c role : app.Contact_Roles__r) {
                    List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
                    if(role.AccountContactJunction__r.Contact_Name__r.Email != null){
                        mails = sendEmail(  app, 
                                            new List<String>{role.AccountContactJunction__r.Contact_Name__r.Email}, 
                                            new List<String>{}, 
                                            templateToSend, 
                                            OrgWideEmailAddressId, 
                                            role.AccountContactJunction__r.Contact_Name__c);
                        for(Messaging.SingleEmailMessage mail : mails) {

                            mail.htmlBody = mail.htmlBody.replace('subAppDueDate',(app.Sub_Application_Due_Date__c == null ? '' : String.valueOf(app.Sub_Application_Due_Date__c)));
                            mail.htmlBody = mail.htmlBody.replace('incidentDeclarationNumber',(app.Disaster__r.Declaration_Number__c == null ? '' : String.valueOf(app.Disaster__r.Declaration_Number__c)));
                            mail.htmlBody = mail.htmlBody.replace('remainingDays', String.valueOf(nDays));
                            mail.htmlBody = mail.htmlBody.replace('{{{Recipient.Name}}}', role.AccountContactJunction__r.Contact_Name__r.Name);
                            mail.htmlBody = mail.htmlBody.replace('{{{Application__c.Project_Plan_Title__c}}}', app.Project_Plan_Title__c);
                            mail.htmlBody = mail.htmlBody.replace('{{{Application__c.Pre_Application__c}}}', app.Pre_Application__r.Name);
                        }
                        allMails.addAll(mails);
                    }
                }
                applicationNames.add(app.Name);
            }
            Messaging.sendEmail(allMails);
        } catch(Exception e) {
            isError = true;
            errorMessage = e.getMessage();
            System.debug('Exception===='+e.getStackTraceString());
        }
    }
    global void finish(Database.BatchableContext bc) { 
        System.debug('finish--');
        //TODO: Create Object CALOES Log - Type HMA,PA,ALS etc, Operation Type - Class(Text), Description (Long Text Area), IsError = true, false, Error Message (Long Text Area)
    }

   /* public static String getApplicationDueDates(Integer nDays) {
        Date dueDate = system.today().addDays(nDays);
        System.debug('dueDate======='+dueDate);
        String query = 'SELECT id, Name, Sub_Application_Due_Date__c, Disaster__r.Declaration_Number__c, ' +
                            '(SELECT Id, Role__c, AccountContactJunction__c, AccountContactJunction__r.Contact_Name__c, AccountContactJunction__r.Contact_Name__r.Email FROM Contact_Roles__r ' + 
                            'WHERE Role__c includes(\'Responsible Representative\', \'Primary Contact\', \'Contributor\')) '+
                            'from Application__c ' +
                            'WHERE Sub_Application_Due_Date__c = :dueDate '+
                            ' AND Status__c = \'Draft\' ORDER BY Name';

        return query;
    }*/

    public static List<Messaging.SingleEmailMessage> sendEmail(SObject sObj, List<String> toAddresses ,List<String> ccAddresses, EmailTemplate templateToSend, Id OrgWideEmailAddressId, Id targetId){
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        try {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(toAddresses);
            mail.setCcAddresses(ccAddresses);
            mail.setTemplateId(templateToSend.Id);
            mail.setOrgWideEmailAddressId(OrgWideEmailAddressId);
            mail.htmlBody = templateToSend.HtmlValue;
            // Messaging.SingleEmailMessage singleEmail = Messaging.renderStoredEmailTemplate(templateToSend.Id, targetId, (String.isNotEmpty(sObj.Id) ? sObj.Id : null));
            // mail.htmlBody=String.isNotEmpty(singleEmail.htmlBody) ? singleEmail.htmlBody : formatPlainBody(singleEmail.plainTextBody);
            // mail.subject= String.isNotEmpty(singleEmail.subject) ? singleEmail.subject : '';
            mail.subject = String.isNotEmpty(templateToSend.Subject) ? templateToSend.Subject : '' ;
            mail.setWhatId(sObj.Id);
            mail.setTargetObjectId(targetId);
            mail.setSaveAsActivity(true);
            mails.add(mail);
            return mails;
        } catch(Exception e) {
            System.debug('Exception in mail---'+e);
        }
        return mails;
    }
/*    @TestVisible
    private static String formatPlainBody(String plainBody) {
        if (String.isEmpty(plainBody)) return '';
        return plainBody.replace('\n', '<br/>');
    }*/
}