codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Project_Role__c.object
<CustomObject>
    <description>It is a junction object between Project object and Contact object.</description>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is a lookup field to Contact Role object, which is a junction object between Account and Contact.</description>
        <label>Contact Role</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Subrecipient_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Subrecipient Summary</label>
        <referenceTo>Incident_Subrecipient_Stage__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It Stores the id of the project record for this project role.</description>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sharing_Batch_Executed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sharing Batch Executed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subrecipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subrecipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <displayFormat>PRN-{000000}</displayFormat>
        <label>Project Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/PA_ProjectSharingBatch.cls
/***********************************************************************************************************************************
* Class Name   : PA_ProjectSharingBatch
* Description  : This Batch is run as one time activity to update existing project roles and share projects with users.
* Author       : Prajakta
* Created On   : 26/08/2021
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj            26/08/2021       Initial Implementation
**************************************************************************************************************************************/

global with sharing class PA_ProjectSharingBatch implements Database.Batchable<sObject>, Database.Stateful{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, Incident_Subrecipient_Summary__c, AccountContactJunction__r.Contact_Name__c,  Project_Name__c,Sharing_Batch_Executed__c, Subrecipient__c FROM Project_Role__c where Sharing_Batch_Executed__c = false');
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Project_Role__c> roleList = new List<Project_Role__c>();
        List<Contact> contactList = new  List<Contact>();
        for(Project_Role__c  role : (List<Project_Role__c>)scope) {
            system.debug('role'+role.id);
            contactList  = [SELECT Id, PA_Invitation_Send__c from Contact WHERE Id=:role.AccountContactJunction__r.Contact_Name__c];
            if(contactList.size() > 0 && contactList[0].PA_Invitation_Send__c == true){
            ProjectSharingHelper.skipSendEmail = true;
            }else{
                ProjectSharingHelper.skipSendEmail = false;
                contactList[0].PA_Invitation_Send__c = true;
            }
            ProjectSharingHelper.shareRecords(role.Id);
            role.Sharing_Batch_Executed__c = true;
            roleList.add(role);
            system.debug('roleList------------'+roleList);
            system.debug('contactList[0]------------'+contactList[0]);
        }
        update contactList[0];
        update roleList;

    }

    global void finish(Database.BatchableContext BC) {

    }
}