codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Global_List__c</fullName>
        <description>Shows Contact Role List of Picklist values on LWC Component.</description>
        <inlineHelpText>Role of this Contact for this particular Account.</inlineHelpText>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Role_List</valueSetName>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Incident_Subrecipient_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look Up to Incident Sub Recipient Summary which is having the same Sub Recipient and same Incident as the Project.</description>
        <inlineHelpText>Links to summary of all Projects within this Incident for this Subrecipient.</inlineHelpText>
        <label>Incident Subrecipient Summary</label>
        <referenceTo>Incident_Subrecipient_Stage__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project_Role__c.object
<CustomObject>
    <description>It is a junction object between Project object and Contact object.</description>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is a lookup field to Contact Role object, which is a junction object between Account and Contact.</description>
        <label>Contact Role</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Subrecipient_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Subrecipient Summary</label>
        <referenceTo>Incident_Subrecipient_Stage__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It Stores the id of the project record for this project role.</description>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Role_Global_List__c</fullName>
        <description>Shows list of Roles related to Project Role</description>
        <label>Project Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Project_Role_List</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subrecipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subrecipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <displayFormat>PRN-{000000}</displayFormat>
        <label>Project Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/ALS_ProjectsPreviewController_Ctrl.cls
/**
         * Created by nehab
         */

public with sharing class ALS_ProjectsPreviewController_Ctrl {
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getProjectsInfo(String masterRecordId, String refreshDate, String srcObject){//Get details of selected record
        Map<String, Object> resultMap = new Map<String, Object>();
        String query = ' Select Id, Name, Project_Name__r.Name, AccountContactJunction__r.Name, Project_Role_Global_List__c, AccountContactJunction__r.Contact_Role_Global_List__c, AccountContactJunction__c,' +
                ' AccountContactJunction__r.Contact_Name__r.Name,AccountContactJunction__r.Contact_Name__r.Title, AccountContactJunction__r.Account_Name__r.Name, Owner.Name' +
                ' from Project_Role__c where ';

        switch on srcObject {
            when 'Incident' {
                query += ' Incident__c = :masterRecordId ';
            }
            when 'Incident-Subrecipient' {
                query += ' Incident_Subrecipient_Summary__c = :masterRecordId ';
            }
            when 'Subrecipient' {
                query += ' Subrecipient__c = :masterRecordId ';
            }
            when else {
                query += ' Project_Name__c = : masterRecordId ';
            }
        }

        List<Project_Role__c> getProjectsList = Database.query(query);

        resultMap.put('projectJunctions',getProjectsList);
        return resultMap;
    }

     @AuraEnabled
     //Delete Selected Record
     public Static Map<String,Object> deleteRecords(String recordToDelete){
     String objId = recordToDelete;
     Map<String, Object> resultMap = new Map<String, Object>();
     Project_Role__c projectsRole =[SELECT Id FROM Project_Role__c WHERE Id = : objId ] ;
     if (projectsRole != null) {
        Delete projectsRole;
     }
     return null;
    }
}