codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Funding_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <formula>IF(  Program_Name__r.Name   = &quot;PA - Federal&quot;  || Program_Name__r.Name  = &quot;PA - FMAG&quot;, Incident_Name__r.Declaration_Number__c, 
IF(Program_Name__r.Name = &quot;CDAA (State Funding)&quot;, Incident_Name__r.State_Declaration_Number__c, &quot;&quot;)
)</formula>
        <label>Declaration Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Incident / Disaster Name</description>
        <inlineHelpText>The Incident Name related to this Funding Opportunity</inlineHelpText>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The record owner. Should be a Programs Profile or Role</description>
        <inlineHelpText>The Staff Member who owns the record</inlineHelpText>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program that issued with this Funding Opportunity</description>
        <inlineHelpText>Program Name for the funding Opportunity ( Ex: PA-Federal, HMGP etc.).</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>What is the Stage of this Funding Opportunity.</description>
        <inlineHelpText>Status of Funding Opportunity ( Ex: Draft, Pending, Approved etc.).</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Disaster Grant / Funding Opportunity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disaster Grants / Funding Opps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Federal Incident Declaration Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Incident Declaration Number. DR number if a Major Disaster, CDAA Number if CDAA-Only, etc.</inlineHelpText>
        <label>Declaration Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Federal_Small_Project_Threshold__c</fullName>
        <description>The Federal Small Project Threshold Amount</description>
        <inlineHelpText>The Federal Small Project Threshold Amount</inlineHelpText>
        <label>Federal Small Project Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Financial Closeout - FPU In Progress</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout FPU - Closed</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - In Review</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - Awaiting FEMA Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Small_Project_Threshold__c</fullName>
        <description>The State Small Project Threshold Amount</description>
        <inlineHelpText>The State Small Project Threshold Amount</inlineHelpText>
        <label>State Small Project Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Parent Program</description>
        <inlineHelpText>If the Program you are adding is not one of the Programs in this list, please select the parent Program from this list.</inlineHelpText>
        <label>Parent Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Related Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The Stage of this program in its lifecycle</description>
        <inlineHelpText>What is the Stage is this Program?</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>DUNS_Expiration_Date__c</fullName>
        <description>DUNS Expiration Date of Obligating Sub Recipient.</description>
        <formula>Obligating_Sub_Recipient__r.DUNS_Expiration_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date when the DUNS registration expires on SAM.gov</inlineHelpText>
        <label>SAM Registration Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Declaration Number of the Incident.</description>
        <formula>Incident_Name__r.Declaration_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Declaration Number assigned to a Disaster/Incident.</inlineHelpText>
        <label>Declaration Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date of Project Work Completed</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>End Date of Project Work</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Funding Opportunity Name</description>
        <inlineHelpText>Specific Funding Opportunity for the Grant (Program+Incident+Declaration Number).</inlineHelpText>
        <label>Disaster Grant/FO</label>
        <referenceTo>Funding_Opportunity__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The name of the Incident</description>
        <inlineHelpText>Disaster/Incident for which the project is related. Not all projects will have an associated Incident.</inlineHelpText>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obligating_Sub_Recipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required because the documents 130 and 130SA creation depends upon Sub-recipient Entity Type.</description>
        <inlineHelpText>The Subrecipient for which the project has been obligated.</inlineHelpText>
        <label>Obligated Sub - Recipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Name, Derives from Disaster Grant/FO.</description>
        <inlineHelpText>The grant program from which the Project originates. This field is used for reporting.</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The Project Stage.</description>
        <inlineHelpText>The current processing stage of the Project. (e.g. New, Obligated, Compliance Verification, Payment, etc.)</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Obligating</fullName>
                    <label>Obligated</label>
                </value>
                <value>
                    <fullName>Compliance Verification</fullName>
                </value>
                <value>
                    <fullName>Active Payment</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Deobligation</fullName>
                    <isActive>false</isActive>
                    <label>Deobligation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date of Project Work Completed</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Start Date of Project Work</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/ProjectRoleTriggerHelperTest.cls
@IsTest
public with sharing class ProjectRoleTriggerHelperTest {
     @IsTest public static void testBehaviour() {
         Profile pf= [Select Id from profile where Name='System Administrator'];
         String orgId=UserInfo.getOrganizationId();
         String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
         Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000));
         String uniqueName=orgId+dateString+RandomId;
         User uu=new User(firstname = 'ABC',
                          lastName = 'XYZ',
                          email = uniqueName + '@test' + orgId + '.org',
                          Username = uniqueName + '@test' + orgId + '.org',
                          EmailEncodingKey = 'ISO-8859-1',
                          Alias = uniqueName.substring(18, 23),
                          TimeZoneSidKey = 'America/Los_Angeles',
                          LocaleSidKey = 'en_US',
                          LanguageLocaleKey = 'en_US',
                          ProfileId = pf.Id
                         );
         insert uu;
         Date startDate = system.today()+1;
         Date EndDate = system.today()+90;
         Program__c prP = new Program__c(Name='Test Program Parent');
         insert prP;
         Program__c prC = new Program__c(Name='Test Program Child', Parent_Program__c=prP.Id);
         insert prC;
         Incident__c inc = new Incident__c(Name = 'Test Incident FP',Declaration_Number__c = '4456',
                 State_Small_Project_Threshold__c=200,Federal_Small_Project_Threshold__c=200);
         insert inc;
         Funding_Opportunity__c fp1=new Funding_Opportunity__c(Name='Test FP ',Program_Name__c=prC.Id,
                 Incident_Name__c=inc.Id, Owner__c=uu.Id);
         insert fp1;
         Account acc = new Account(Sub_Recipient_FIPS__c='1234',Email_Address__c='test@gmail.com',Name ='Test Account',
                 Entity_Type__c=ALS_CONSTANTS.Account_EntityType_City,DUNS_Expiration_Date__c =startDate,
                 FFATAExpirationDate__c =EndDate );
         insert acc;
         List<Project__c> projectList = new List<Project__c>();
         Project__c pr1=new Project__c(Obligating_Sub_Recipient__c=acc.Id,Start_Date__c=startDate,End_Date__c=EndDate,
                 Name='Test Project 1', Funding_Opportunity_Name__c=fp1.Id, Stage__c=ALS_CONSTANTS.Project_Stage_New);
         projectList.add(pr1);
         Project__c pr2=new Project__c(Obligating_Sub_Recipient__c=acc.Id,Start_Date__c=startDate,End_Date__c=EndDate,
                 Name='Test Project 2', Funding_Opportunity_Name__c=fp1.Id, Stage__c=ALS_CONSTANTS.Project_Stage_New);
         projectList.add(pr2);
         insert projectList;
         Contact con = new Contact(lastName = 'Test Contact', AccountId=acc.Id);
         insert con;
         AccountContactRole__c aconRole=new AccountContactRole__c(Account_Name__c=acc.Id, Contact_Name__c=con.Id,
                 Contact_Role_Global_List__c=ALS_CONSTANTS.ACRole_ContactRole_Employee);
         insert aconRole;
         Project_Role__c pRole1 = new Project_Role__c( AccountContactJunction__c=aconRole.Id, Project_Name__c=projectList[0].Id,
                 Project_Role_Global_List__c=ALS_CONSTANTS.ProjectRole_Role_Accounting);
         insert pRole1;
         Project_Role__c pRole3 = new Project_Role__c( AccountContactJunction__c=aconRole.Id, Project_Name__c=projectList[0].Id,
                 Project_Role_Global_List__c=ALS_CONSTANTS.ProjectRole_Role_Accounting);
         Project_Role__c pRole2 = new Project_Role__c( AccountContactJunction__c=aconRole.Id, Project_Name__c=projectList[0].Id,
                 Project_Role_Global_List__c=ALS_CONSTANTS.ProjectRole_Role_Applicant);

         Project_Role__c pRole4 = new Project_Role__c( AccountContactJunction__c=aconRole.Id, Project_Name__c=projectList[1].Id,
                 Project_Role_Global_List__c=ALS_CONSTANTS.ProjectRole_Role_AuthorizedAgent,
                 Contact_Type__c = ALS_CONSTANTS.ProjectRole_ContactType);

        test.startTest();
             try{
                 insert pRole3;
             }
             catch(Exception e)
             {
                 System.assert(e.getMessage().contains(System.Label.REAL_ProjectRole_DuplicateError));
             }
             try{
                 insert pRole2;
             }
             catch(Exception e)
             {
                 System.assert(e.getMessage().contains(System.Label.REAL_ProjectRole_DuplicateError));
             }
             try{
                 Project_Role__c projectRole2 =new Project_Role__c();
                 projectRole2.Id=pRole2.Id;
                 projectRole2.Project_Role_Global_List__c=ALS_CONSTANTS.ProjectRole_Role_Accounting;
                 Update projectRole2;
             }
             catch(Exception e)
             {
                 System.assert(e.getMessage().contains(System.Label.REAL_ProjectRole_DuplicateError));
             }

         insert pRole4;
         pRole4.Project_Role_Global_List__c = ALS_CONSTANTS.ProjectRole_Role_Applicant;
         update pRole4;

         pRole4.Project_Role_Global_List__c = ALS_CONSTANTS.ProjectRole_Role_AuthorizedAgent;
         update pRole4;

         test.stopTest();
     }
}