codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Authorized_Agent_FirstName__c</fullName>
        <description>The FirstName of Primary Authorized agent for Docusign Template</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The FirstName of Primary Authorized agent for Docusign Template</inlineHelpText>
        <label>Authorized Agent FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorized_Agent_LastName__c</fullName>
        <description>The LastName of Primary Authorized agent for Docusign Template</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The LastName of Primary Authorized agent for Docusign Template</inlineHelpText>
        <label>Authorized Agent LastName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorized_Agent_Salutation__c</fullName>
        <description>The salutation of Primary Authorized agent for Docusign Template</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The salutation of Primary Authorized agent for Docusign Template</inlineHelpText>
        <label>Authorized Agent Salutation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorized_Agent_Title__c</fullName>
        <description>The Title of Primary Authorized agent for Docusign Template</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Title of Primary Authorized agent for Docusign Template</inlineHelpText>
        <label>Authorized Agent Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project_Role__c.object
<CustomObject>
    <description>It is a junction object between Project object and Contact object.</description>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is a lookup field to Contact Role object, which is a junction object between Account and Contact.</description>
        <label>Contact Role</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It Stores the id of the project record for this project role.</description>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <displayFormat>PRN-{000000}</displayFormat>
        <label>Project Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/REAL_UpdateAuthorizedAgentDetailsJob.cls
/***********************************************************************************************************************************
* Class Name   : REAL_UpdateAuthorizedAgentDetailsJob
* Description  : This batch job is created to update the Primary Authorized Agent Details on project.
* Author       : Ricky
* Created On   : 19/07/2020
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Ricky              17/07/2020       Initial Implementation
**************************************************************************************************************************************/

public with sharing class REAL_UpdateAuthorizedAgentDetailsJob implements Database.Batchable<SObject>, Schedulable {
    private final String query;

    public REAL_UpdateAuthorizedAgentDetailsJob(String query) {
        this.query = query;
    }

    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new REAL_UpdateAuthorizedAgentDetailsJob(query));
    }

    // Database.Batchable methods
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Project__c> projectWithPrimaryAuthorizedAgentList = (List<Project__c>) scope;
        List<Project__c> projectToUpdateList = new List<Project__c>();

        for (Project__c project : projectWithPrimaryAuthorizedAgentList) {
            if (project?.Project_Roles__r?.size() == 1) {
                Project_Role__c authorizedAgent = project?.Project_Roles__r[0];

                project.Authorized_Agent_LastName__c = authorizedAgent.AccountContactJunction__r.Contact_Name__r.LastName;
                if (authorizedAgent.AccountContactJunction__r.Contact_Name__r.FirstName != null) {
                    project.Authorized_Agent_FirstName__c = authorizedAgent.AccountContactJunction__r.Contact_Name__r.FirstName;
                }
                if (authorizedAgent.AccountContactJunction__r.Contact_Name__r.Title != null) {
                    project.Authorized_Agent_Title__c = authorizedAgent.AccountContactJunction__r.Contact_Name__r.Title;
                }
                if (authorizedAgent.AccountContactJunction__r.Contact_Name__r.Salutation != null) {
                    project.Authorized_Agent_Salutation__c = authorizedAgent.AccountContactJunction__r.Contact_Name__r.Salutation;
                }

                projectToUpdateList.add(project);
            }
        }
        if (projectToUpdateList?.size() > 0) {
            update  projectToUpdateList;
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}