codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/ALS_ContactAcountEdit_CtrlTest.cls
@isTest
public with sharing class ALS_ContactAcountEdit_CtrlTest {
    @isTest
    public static void testALS_ContactAcountEdit_CtrlMethod1() {
        Account acc = new Account(Name='test12f', Entity_Type__c=ALS_CONSTANTS.Account_EntityType_City);
        insert acc;
        Contact con =new Contact(LastName='Test con', AccountId=acc.Id );
        insert con;
        AccountContactRole__c accCon = new AccountContactRole__c(Account_Name__c=acc.Id,Contact_Name__c=con.Id);
        insert accCon;

        String accountDetail2 =JSON.serialize(acc);
        String accountContac2 =JSON.serialize(accCon);
        String contactIds =con.Id;
        Boolean isEdit2 =TRUE;
        Boolean isAccount2 =TRUE;
        String accountDetail3 =null;
        String accountContac3 =null;
        Boolean isAccount3 =TRUE;
        Boolean isEdit3 =FALSE;

        test.startTest();
            try{
            ALS_ContactAcountEdit_Ctrl.saveDetails(accountDetail2,accountContac2 ,isAccount2,isEdit2,contactIds);
            }
            catch(exception e)
            {
            System.assert(e.getMessage().contains('Script-thrown exception'));
            }

            try{
            ALS_ContactAcountEdit_Ctrl.saveDetails(accountDetail2,accountContac2 ,isAccount2,isEdit3,contactIds);
            }
            catch(exception e)
            {
            System.assert(e.getMessage().contains('Script-thrown exception'));
            }

            try{
            ALS_ContactAcountEdit_Ctrl.saveDetails(accountDetail2,accountContac2 ,isAccount3,isEdit3,contactIds);
            }
            catch(exception e)
            {
            System.assert(e.getMessage().contains('Script-thrown exception'));
            }

            ALS_ContactAcountEdit_Ctrl.getDetails(accCon.Id);
        test.stopTest();
    }
}