codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Project_Role__c.object
<CustomObject>
    <description>It is a junction object between Project object and Contact object.</description>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is a lookup field to Contact Role object, which is a junction object between Account and Contact.</description>
        <label>Contact Role</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sharing_Batch_Executed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sharing Batch Executed</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <displayFormat>PRN-{000000}</displayFormat>
        <label>Project Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/PA_ProjectSharingBatchTest.cls
/**
 * Created by hp on 06-09-2021.
 */
@isTest
public with sharing class PA_ProjectSharingBatchTest {

    @testSetup static void setup() {
        Account acc = PA_TestHelper.getAccountSubrecipent(true);

        Contact con =  PA_TestHelper.getContact(true,acc);

        AccountContactRole__c accCon = new AccountContactRole__c();
        accCon.Account_Name__c = acc.id;
        accCon.Contact_Name__c = con.id;
        insert accCon;

        List<Project_Role__c> roleList = new List<Project_Role__c>();
        roleList.add(new Project_Role__c(AccountContactJunction__c = accCon.Id,Sharing_Batch_Executed__c = false));
        insert roleList;
    }

    static testmethod void testProjectRoleSharingBatch() {
        Database.executebatch(new PA_ProjectSharingBatch(), 1);
    }

}