codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Contact for this particular Account.</description>
        <inlineHelpText>Status of the Contact for this particular Account.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Is_Any_Open_RFI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is checked if we have any RFI Open on application.</description>
        <label>RFI Pending?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending OES Review</fullName>
                </value>
                <value>
                    <fullName>Analyst Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Analyst Review Complete</fullName>
                </value>
                <value>
                    <fullName>OES RFI In Progress</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>OES Subapplication Review Complete</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Selected for Submission to FEMA</fullName>
                </value>
                <value>
                    <fullName>Not Selected - Pending Future Consideration</fullName>
                </value>
                <value>
                    <fullName>Submitted to FEMA</fullName>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Pending</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Review Pending</fullName>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>By Subapplicant after funds are obligated</fullName>
                </value>
                <value>
                    <fullName>By Subapplicant with no funds obligated</fullName>
                </value>
                <value>
                    <fullName>By OES</fullName>
                </value>
                <value>
                    <fullName>Waitlist Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>OES Review</fullName>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Contact Junction</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Working Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Responsible Representative</fullName>
                </value>
                <value>
                    <fullName>Match Commitment</fullName>
                </value>
                <value>
                    <fullName>Maintenance Commitment</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic Analyst</fullName>
                </value>
                <value>
                    <fullName>Authorized Agent</fullName>
                    <isActive>false</isActive>
                    <label>Authorized Agent</label>
                </value>
                <value>
                    <fullName>Requestor</fullName>
                    <isActive>false</isActive>
                    <label>Requestor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Request_For_Information__c.object
<CustomObject>
    <fields>
        <fullName>Analyst_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Analyst Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Request For Informations</relationshipLabel>
        <relationshipName>Request_For_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFI_Deadline__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>RFI Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFI_Type__c</fullName>
        <label>RFI Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OES BCA</fullName>
                </value>
                <value>
                    <fullName>OES Programmatic</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP</fullName>
                </value>
                <value>
                    <fullName>FEMA OES Programmatic</fullName>
                </value>
                <value>
                    <fullName>FEMA OES EHP</fullName>
                </value>
                <value>
                    <fullName>CWMP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RFI_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Sent to Subapplicant</fullName>
                </value>
                <value>
                    <fullName>Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted</fullName>
                </value>
                <value>
                    <fullName>Response Accepted</fullName>
                </value>
                <value>
                    <fullName>Response Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted to Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA EHP RFI</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA Programmatic RFI</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted by Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>RFI Requested</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Withdrawal</fullName>
                </value>
                <value>
                    <fullName>Submitted to HMA Analyst</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to HMA Analyst</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subapplicant_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Subapplicant Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Request For Information</label>
    <nameField>
        <displayFormat>RFI-{00000}</displayFormat>
        <label>Request For Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HMA_EditApplicationButton.cls
public without sharing class HMA_EditApplicationButton {
    @AuraEnabled
    public static Map<String, Object> getInitData(String appId) {
        Map<String, Object> returnMap  = new Map<String, Object>();
        try {
            Boolean isEdit;
            List<Request_For_Information__c> openRFIList = new List<Request_For_Information__c>();
            User[] user = [Select Id, ContactId from User where Id=: UserInfo.getUserId()];
            Contact_Role__c[] contactRoles = [SELECT Id,Role__c, Application__c, Application__r.Status__c, Application__r.Status_Reason__c, Application__r.Is_Any_Open_RFI__c, AccountContactJunction__r.Contact_Name__c FROM Contact_Role__c 
                                                WHERE Application__c =:appId AND AccountContactJunction__r.Contact_Name__c=:user[0].ContactId];
            //TODO: Crete new class HMA_EditApplicationButton
            //TODO: Not a FEMA User
            //TODO: first 4 RFI Types and i9f any open RFI

            System.debug('contactRoles----'+contactRoles);

            if(contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_RESPONSIBLE_REPRESENTATIVE) || 
                contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_REQUESTOR) ||
                contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_CONTRIBUTOR) ||
                contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_VIEWER)) {
                    Set<String> rfiTypes = new Set<String>{HMA_CONSTANTS.REQUEST_FOR_INFORMATION_TYPE_OES_BCA, 
                                                            HMA_CONSTANTS.REQUEST_FOR_INFORMATION_TYPE_OES_PROGRAMMATIC, 
                                                            HMA_CONSTANTS.REQUEST_FOR_INFORMATION_TYPE_FEMA_PROGRAMMATIC, 
                                                            HMA_CONSTANTS.REQUEST_FOR_INFORMATION_TYPE_FEMA_EHP};
                    Set<String> rfiStatus = new Set<String>{HMA_CONSTANTS.REQUEST_FOR_INFORMATION_STATUS_SENT_TO_SUBAPPLICANT, 
                                                            HMA_CONSTANTS.REQUEST_FOR_INFORMATION_STATUS_TIME_EXTENSION_REQUESTED};
                    openRFIList = [ SELECT Id, 
                                            Analyst_Comment__c, 
                                            Subapplicant_Comment__c, 
                                            RFI_Deadline__c, 
                                            Name, 
                                            Application__c
                                            FROM Request_For_Information__c 
                                            WHERE Application__c =: appId AND RFI_Type__c IN: rfiTypes AND Status__c IN: rfiStatus];

            }

            if((contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_RESPONSIBLE_REPRESENTATIVE) || 
                contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_REQUESTOR) ||
                contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_CONTRIBUTOR) ||
                contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_VIEWER)) && 
                (contactRoles[0].Application__r.Status__c == HMA_CONSTANTS.APPLICATION_STATUS_DRAFT || openRFIList.size() > 0)) {
                isEdit = true;
            }else if( (contactRoles[0].Application__r.Status__c == HMA_CONSTANTS.APPLICATION_STATUS_FEMA_REVIEW ||
                      contactRoles[0].Application__r.Status__c == HMA_CONSTANTS.APPLICATION_STATUS_FEMA_DECISION) &&
                        (contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_FEMA_EHP_ANALYST) || 
                        contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_FEMA_PROGRAMMATIC_ANALYST) ||
                        contactRoles[0].Role__c.contains(HMA_CONSTANTS.CONTACT_ROLE_PICKLIST_FEMA_REVIEW))) {
                isEdit = true;
            }else {
                isEdit = false;
            }
            if(contactRoles[0].Application__r.Status__c == HMA_CONSTANTS.APPLICATION_STATUS_WITHDRAWN){
                isEdit = false;
            }
                returnMap.put('isEdit', isEdit);
        } catch (Exception e) {
            System.debug('Error : '+e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
        return returnMap;
    }
}