codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/ContactRoleTriggerHelperTest.cls
/**
 * Created by StackNexus Admin on 02-02-2021.
 */
@IsTest
public with sharing class ContactRoleTriggerHelperTest {
    @IsTest
    public static void testContactRile() {
        Account acc = new Account(Name='test12f', Entity_Type__c=ALS_CONSTANTS.Account_EntityType_City);
        insert acc;
        Contact con =new Contact(LastName='Test con', AccountId=acc.Id);
        insert con;
        AccountContactRole__c accCon1 = new AccountContactRole__c(Account_Name__c=acc.Id,Contact_Name__c=con.Id);
        insert accCon1;
        AccountContactRole__c accCon2 = new AccountContactRole__c(Account_Name__c=acc.Id,Contact_Name__c=con.Id);
        Test.startTest();
            try{
                insert accCon2;
            }
            catch (Exception e) {
                system.assert(e.getMessage().contains(System.Label.REAL_ContactRole_DuplicateError));
            }
        Test.stopTest();
    }
}