codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Is_BCR_verified_at_1_0_or_greater__c</fullName>
        <label>Is BCR verified at 1.0 or greater?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_this_an_eligible_Activity__c</fullName>
        <label>Is this an eligible Activity?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_this_an_eligible_Subapplicant__c</fullName>
        <label>Is this an eligible Subapplicant?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Maintenance_Letter__c</fullName>
        <label>Maintenance Letter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Match_Letter__c</fullName>
        <label>Match Letter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subapplicant_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subapplicant Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subapplication_Complete__c</fullName>
        <label>Ready to Submit?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Contact Junction</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Working Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Responsible Representative</fullName>
                </value>
                <value>
                    <fullName>Match Commitment</fullName>
                </value>
                <value>
                    <fullName>Maintenance Commitment</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic Analyst</fullName>
                </value>
                <value>
                    <fullName>Authorized Agent</fullName>
                    <isActive>false</isActive>
                    <label>Authorized Agent</label>
                </value>
                <value>
                    <fullName>Requestor</fullName>
                    <isActive>false</isActive>
                    <label>Requestor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Key_Value_Store__mdt.object
<CustomObject>
    <fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Key Value Store</label>
    <pluralLabel>Key Value Stores</pluralLabel>
</CustomObject>

codepkg/objects/Pre_Application__c.object
<CustomObject>
    <fields>
        <fullName>Subapplicant_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subapplicant Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pre-Applications</relationshipLabel>
        <relationshipName>Pre_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Scoring_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application Number</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Scoring Checklists</relationshipLabel>
        <relationshipName>Scoring_Checklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_BCR_verified_at_1_0_or_greater__c</fullName>
        <formula>TEXT(Application__r.Is_BCR_verified_at_1_0_or_greater__c)</formula>
        <label>Is BCR verified at 1.0 or greater?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_this_an_eligible_Activity__c</fullName>
        <formula>TEXT(Application__r.Is_this_an_eligible_Activity__c)</formula>
        <label>Is this an eligible Activity?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_this_an_eligible_Subapplicant__c</fullName>
        <formula>TEXT( Application__r.Is_this_an_eligible_Subapplicant__c )</formula>
        <label>Is this an eligible Subapplicant?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maintenance_Letter__c</fullName>
        <formula>Text(Application__r.Maintenance_Letter__c)</formula>
        <label>Maintenance Letter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_Letter__c</fullName>
        <formula>Text( Application__r.Match_Letter__c )</formula>
        <label>Match Letter</label>
        <type>Text</type>
    </fields>
    <label>Scoring Checklist</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Scoring Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/HMA_ApplicationHelperTest.cls
@isTest public with sharing class HMA_ApplicationHelperTest {
    @isTest public static void testCheckACRoleAndCreateContactRoleForApplication() {
        Map<Id, Application__c> preAppIdToApplicationMap = new Map<Id, Application__c>();
        Contact portalCon = HMA_TestHelper.getPortalContact(true);
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        AccountContactRole__c acRole = new AccountContactRole__c(Contact_Name__c = portalCon.Id, Account_Name__c = portalCon.AccountId);
        insert acRole;
        Contact_Role__c conRole = HMA_TestHelper.getContactRole(false);
        conRole.Application__c = newApplication.Id;
        conRole.Contact__c = portalCon.Id;
        conRole.AccountContactJunction__c = acRole.Id;
        conRole.Pre_Application__c  = newApplication.Pre_Application__c;
        insert conRole;
        preAppIdToApplicationMap.put(newApplication.Pre_Application__c, newApplication);
        
        Test.startTest();
        HMA_ApplicationHelper.checkACRoleAndCreateContactRoleForApplication(preAppIdToApplicationMap);
        Test.stopTest();
    }

    @isTest public static void testCheckACRoleAndCreateContactRoleForApplication1() {
        Map<Id, Application__c> preAppIdToApplicationMap = new Map<Id, Application__c>();
        Contact portalCon = HMA_TestHelper.getPortalContact(true);
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        AccountContactRole__c acRole = new AccountContactRole__c(Contact_Name__c = portalCon.Id, Account_Name__c = newApplication.Subapplicant_Entity__c);
        insert acRole;
        Contact_Role__c conRole = HMA_TestHelper.getContactRole(false);
        conRole.Application__c = newApplication.Id;
        conRole.Contact__c = portalCon.Id;
        conRole.AccountContactJunction__c = acRole.Id;
        conRole.Pre_Application__c  = newApplication.Pre_Application__c;
        insert conRole;
        preAppIdToApplicationMap.put(newApplication.Pre_Application__c, newApplication);
        
        Test.startTest();
        HMA_ApplicationHelper.checkACRoleAndCreateContactRoleForApplication(preAppIdToApplicationMap);
        Test.stopTest();
    }

    @isTest public static void testProcessAccountContactRole() {
        Contact portalCon = HMA_TestHelper.getPortalContact(true);
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        AccountContactRole__c acRole = new AccountContactRole__c(Contact_Name__c = portalCon.Id);
        insert acRole;
        Contact_Role__c conRole = HMA_TestHelper.getContactRole(false);
        conRole.Application__c = newApplication.Id;
        conRole.Contact__c = portalCon.Id;
        conRole.AccountContactJunction__c = acRole.Id;
        conRole.Pre_Application__c  = newApplication.Pre_Application__c;
        insert conRole;

        Test.startTest();
        HMA_ApplicationHelper.processAccountContactRole(portalCon, conRole, newApplication.Subapplicant_Entity__c);

        acRole.Account_Name__c = portalCon.AccountId;
        update acRole;
        HMA_ApplicationHelper.processAccountContactRole(portalCon, conRole, portalCon.AccountId);
        Test.stopTest();
    }

    @isTest public static void testPrepareDataForSendingEmail() {
        Contact portalCon = HMA_TestHelper.getPortalContact(true);
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        AccountContactRole__c acRole = new AccountContactRole__c(Contact_Name__c = portalCon.Id, Account_Name__c = portalCon.AccountId);
        insert acRole;
        Contact_Role__c conRole = HMA_TestHelper.getContactRole(false);
        conRole.Application__c = newApplication.Id;
        conRole.Contact__c = portalCon.Id;
        conRole.AccountContactJunction__c = acRole.Id;
        conRole.Pre_Application__c  = newApplication.Pre_Application__c;
        insert conRole;

        Test.startTest();
        HMA_ApplicationHelper.prepareDataForSendingEmail(portalCon, conRole);
        Test.stopTest();
    }

    @isTest public static void testProcessCommunityUser() {
        Contact portalCon = HMA_TestHelper.getPortalContact(true);
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        AccountContactRole__c acRole = new AccountContactRole__c(Contact_Name__c = portalCon.Id, Account_Name__c = portalCon.AccountId);
        insert acRole;
        Contact_Role__c conRole = HMA_TestHelper.getContactRole(false);
        conRole.Application__c = newApplication.Id;
        conRole.Contact__c = portalCon.Id;
        conRole.AccountContactJunction__c = acRole.Id;
        conRole.Pre_Application__c  = newApplication.Pre_Application__c;
        insert conRole;

        Test.startTest();
        HMA_ApplicationHelper.processCommunityUser(portalCon, conRole, new List<User>() );
        Test.stopTest();
    }

    @isTest public static void testProcessCommunityUser1() {
        Contact portalCon = HMA_TestHelper.getPortalContact(true);
        Contact_Role__c conRole = HMA_TestHelper.getContactRole(false);
        conRole.Contact__c = portalCon.Id;
        insert conRole;

        Test.startTest();
        HMA_ApplicationHelper.processCommunityUser(portalCon, conRole, new List<User>() );
        Test.stopTest();
    }

    @isTest public static void testShareSubApplication() {
        Contact portalCon = HMA_TestHelper.getPortalContact(true);
        User u = HMA_TestHelper.getPortalUserHMA(false);
        u.ContactId = portalCon.Id;
        insert u;
        List<User> userList = new List<User>();
        userList.add(u);
        System.runAs(u) {
            Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
            AccountContactRole__c acRole = new AccountContactRole__c(Contact_Name__c = portalCon.Id, Account_Name__c = portalCon.AccountId);
            insert acRole;
            Contact_Role__c conRole = HMA_TestHelper.getContactRole(false);
            conRole.Role__c = 'Contributor';
            conRole.Application__c = newApplication.Id;
            conRole.Contact__c = portalCon.Id;
            conRole.AccountContactJunction__c = acRole.Id;
            conRole.Pre_Application__c  = newApplication.Pre_Application__c;
            insert conRole;

            Test.startTest();
            HMA_ApplicationHelper.shareSubApplication(portalCon, conRole, userList);

            //Document__c doc = HMA_TestHelper.createCustomDocumentRecord(newApplication.Id);
            conRole.Role__c = 'Viewer';
            update conRole;
            HMA_ApplicationHelper.shareSubApplication(portalCon, conRole, userList);
            Test.stopTest();
        }
    }

    @isTest public static void testProcessAccount() {
        Map<String, Object> recordDetailsMap = new Map<String, Object>();
        Key_Value_Store__mdt kvStore = HMA_TestMetadataHelper.getKeyValue('SOC_OPS_Non_GovernmentOwnerId');
        Account newParentAccount = HMA_TestHelper.getParentAccount(true);
        Account acc = HMA_TestHelper.getPortalAccount(false);
        acc.OwnerId = kvStore.Text_Value__c;
        acc.Entity_Type__c = 'County';
        acc.ParentId = newParentAccount.Id;
        acc.ShippingStreet = '207 N Butte St';
        acc.ShippingCity = 'Willows';
        acc.ShippingState = 'CA';
        acc.ShippingPostalCode  = '95988';
        insert acc;
        AccountRecordWrapper obj = new AccountRecordWrapper();
        obj.NonGovernmentalEntity = 'Test';
        obj.FederalTaxID = acc.Entity_Id__c;
        obj.FacilityName = acc.Name;
        obj.FacilityID = acc.Entity_Id__c;
        //obj.FacilityID = '125486';
        obj.StreetAddress = acc.ShippingStreet;
        obj.CityName = acc.ShippingCity;
        obj.County = null;
        obj.State = acc.ShippingState;
        obj.ZipPostalCode = acc.ShippingPostalCode;

        recordDetailsMap.put('accountRecord', obj);
        Test.startTest();
        HMA_ApplicationHelper.processAccount(recordDetailsMap);

        obj.NonGovernmentalEntity = acc.Name;
        recordDetailsMap.put('accountRecord', obj);
        HMA_ApplicationHelper.processAccount(recordDetailsMap);

        obj.County = acc.Name;
        recordDetailsMap.put('accountRecord', obj);
        HMA_ApplicationHelper.processAccount(recordDetailsMap);
        Test.stopTest();
    }

    @isTest public static void testUpdateScoringChecklistOESBriefSummary() {
        Map<Id, Application__c> appIdToApplicationMap = new Map<Id, Application__c>();
        Contact portalCon = HMA_TestHelper.getPortalContact(true);
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        Scoring_Checklist__c sc = HMA_TestHelper.getScoringChecklist(true, newApplication.Id, '');
        appIdToApplicationMap.put(newApplication.Id, newApplication);
        Test.startTest();
        HMA_ApplicationHelper.updateScoringChecklistOESBriefSummary(appIdToApplicationMap);
        Test.stopTest();
    }

    @isTest public static void testValidateAppWhenStatusIsFEMAReview() {
        List<Application__c> femaApplications = new List<Application__c>();
        Application__c newApplication = HMA_TestHelper.getApplication(false, '', '', '');
        newApplication.Is_this_an_eligible_Activity__c = 'No';
        newApplication.Is_this_an_eligible_Subapplicant__c  = 'No';
        newApplication.Is_BCR_verified_at_1_0_or_greater__c  = 'No';
        newApplication.Match_Letter__c  = 'No';
        newApplication.Maintenance_Letter__c  = 'No';
        newApplication.Subapplication_Complete__c   = 'No';

        femaApplications.add(newApplication);
        Test.startTest();
        HMA_ApplicationHelper.validateAppWhenStatusIsFEMAReview(femaApplications);
        Test.stopTest();
    }

    public class AccountRecordWrapper {
        public String NonGovernmentalEntity;
        public String FederalTaxID;
        public String Facility;
        public String FacilityName;
        public String FacilityID;
        public String StreetAddress;
        public String CityName;
        public String County;
        public String State;
        public String ZipPostalCode;
    }
}