codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Funding_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The record owner. Should be a Programs Profile or Role</description>
        <inlineHelpText>The Staff Member who owns the record</inlineHelpText>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program that issued with this Funding Opportunity</description>
        <inlineHelpText>Program Name for the funding Opportunity ( Ex: PA-Federal, HMGP etc.).</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Disaster Grant / Funding Opportunity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disaster Grants / Funding Opps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Parent Program</description>
        <inlineHelpText>If the Program you are adding is not one of the Programs in this list, please select the parent Program from this list.</inlineHelpText>
        <label>Parent Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Related Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date of Project Work Completed</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>End Date of Project Work</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Funding Opportunity Name</description>
        <inlineHelpText>Specific Funding Opportunity for the Grant (Program+Incident+Declaration Number).</inlineHelpText>
        <label>Disaster Grant/FO</label>
        <referenceTo>Funding_Opportunity__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obligating_Sub_Recipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required because the documents 130 and 130SA creation depends upon Sub-recipient Entity Type.</description>
        <inlineHelpText>The Subrecipient for which the project has been obligated.</inlineHelpText>
        <label>Obligated Sub - Recipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Name, Derives from Disaster Grant/FO.</description>
        <inlineHelpText>The grant program from which the Project originates. This field is used for reporting.</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date of Project Work Completed</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Start Date of Project Work</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project_Role__c.object
<CustomObject>
    <description>It is a junction object between Project object and Contact object.</description>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is a lookup field to Contact Role object, which is a junction object between Account and Contact.</description>
        <label>Contact Role</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project Role</label>
    <nameField>
        <displayFormat>PRN-{000000}</displayFormat>
        <label>Project Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/ALS_ProjectsPreviewController_CtrlTest.cls
@isTest
public with sharing class ALS_ProjectsPreviewController_CtrlTest {
    @isTest
    public static void Testals_ProjectTestMethod() {
        Date startDate = system.today()+1;
        Date EndDate = system.today()+10;
        Profile pf= [Select Id from profile where Name='System Administrator'];
        String orgId=UserInfo.getOrganizationId();
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000));
        String uniqueName=orgId+dateString+RandomId;
        User uu=new User(firstname = 'ABC',
                lastName = 'XYZ',
                email = uniqueName + '@test' + orgId + '.org',
                Username = uniqueName + '@test' + orgId + '.org',
                EmailEncodingKey = 'ISO-8859-1',
                Alias = uniqueName.substring(18, 23),
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                ProfileId = pf.Id
        );
        insert uu;

        Program__c parentProg =new Program__c(Name='Test ParentProgram');
        insert parentProg;
        Program__c prog =new Program__c(Name='Test program',Parent_Program__c =parentProg.Id);
        insert prog;
        Funding_Opportunity__c fOpp = new Funding_Opportunity__c(Name='Funding Opp Name',Owner__c = uu.Id, Program_Name__c = prog.Id);
        insert fOpp;
        Account acc = new Account(Name='test1222',Entity_Type__c=ALS_CONSTANTS.Account_EntityType_City);
        insert acc;
        Contact con =new Contact(LastName='Test contact',AccountId=acc.Id);
        insert con;
        Project__c proj =new Project__c(Name='Test project',Funding_Opportunity_Name__c =fOpp.Id,Obligating_Sub_Recipient__c = acc.Id,Start_Date__c=startDate,End_Date__c=EndDate);
        insert proj;
        AccountContactRole__c accConRole = new AccountContactRole__c(Account_Name__c=acc.ID,Contact_Name__c=con.Id);
        insert accConRole;
        Project_Role__c pRole=new Project_Role__c(AccountContactJunction__c = accConRole.Id);
        insert pRole;
        test.startTest();
            ALS_ProjectsPreviewController_Ctrl.getProjectsInfo(pRole.Id,'','Project');
            ALS_ProjectsPreviewController_Ctrl.deleteRecords(pRole.Id);
        test.stopTest();
    }
}