codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account for which this Contact Role is created.</description>
        <inlineHelpText>Account for which this Contact Role is created.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Global_List__c</fullName>
        <description>Shows Contact Role List of Picklist values on LWC Component.</description>
        <inlineHelpText>Role of this Contact for this particular Account.</inlineHelpText>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Role_List</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Contact for this particular Account.</description>
        <inlineHelpText>Status of the Contact for this particular Account.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/ALS_ContactAccounts_Ctrl.cls
/**
 * Created by nehab on 28-10-2020.
 */

public with sharing class ALS_ContactAccounts_Ctrl {

    @AuraEnabled(cacheable=true)
    //Get Contact role data related to Contact record
    public static Map<String, Object> getContactAccountsInfo(String masterRecordId, String refreshDate){
        Map<String, Object> resultMap = new Map<String, Object>();

        List<AccountContactRole__c> getContactAccountsList = [Select Id ,Account_Name__c , Contact_Name__c  ,Contact_Role_Global_List__c , Status__c, Account_Name__r.Name
                                                          From AccountContactRole__c where Contact_Name__c =:masterRecordId]; //Role__c **

        resultMap.put('contactAccounts',getContactAccountsList);
        return resultMap;
    }

    //Call on Delete
    @AuraEnabled
    public Static Map<String,Object> deleteRecords(String recordToDelete){//To Delete selected Contact Role Record

    String objId = recordToDelete;
    Map<String, Object> resultMap = new Map<String, Object>();
    AccountContactRole__c accountContactsRole =[SELECT Id FROM AccountContactRole__c WHERE Id = : objId ] ;
    if (accountContactsRole != null) {
        Delete accountContactsRole;
    }
    return null;
}
}