codepkg/objects/Account_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account of the Contractor</description>
        <inlineHelpText>Account of the Contractor</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CWMP_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CWMP Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CWMP_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CWMP Project</label>
        <referenceTo>CWMP_Project__c</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Contract_Amount__c</fullName>
        <label>Original Contract Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Point_of_Contact__c</fullName>
        <description>Required when setting the Project Stage to “Tri-Party Agreement Finalized”</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Point of Contact Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contractor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Role</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Account Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/CWMP_Project__c.object
<CustomObject>
    <description>Project for California wildfire mitigation program</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CWMP Projects</relationshipLabel>
        <relationshipName>CWMP_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CWMP_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CWMP Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>CWMP Projects</relationshipLabel>
        <relationshipName>CWMP_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CWMP Project</label>
    <nameField>
        <displayFormat>CWMPP-{000000}</displayFormat>
        <label>CWMP Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Draw__c.object
<CustomObject>
    <fields>
        <fullName>Account_Role__c</fullName>
        <label>Account Role</label>
        <referenceTo>Account_Role__c</referenceTo>
        <relationshipLabel>Draws</relationshipLabel>
        <relationshipName>Draws</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Draw</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>Draw Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Draws</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>HH_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>County of Property</description>
        <inlineHelpText>County of Property</inlineHelpText>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Shasta</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                    <isActive>false</isActive>
                    <label>Los Angeles</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Order_Change__c.object
<CustomObject>
    <fields>
        <fullName>Account_Role__c</fullName>
        <label>Account Role</label>
        <referenceTo>Account_Role__c</referenceTo>
        <relationshipName>Order_changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Homeowner_provided_check_payment__c</fullName>
        <description>Has the Homeowner provided a contribution check/payment for the change order?</description>
        <inlineHelpText>Has the Homeowner provided a contribution check/payment for the change order?</inlineHelpText>
        <label>Has Homeowner provided check/payment</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Homeowner_check_payment_amount__c</fullName>
        <description>Change order Homeowner contribution check/payment amount</description>
        <inlineHelpText>Change order Homeowner contribution check/payment amount</inlineHelpText>
        <label>Homeowner check/payment amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Change</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Order Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/HH_CreateUpdateAccountRoleCtrlTest.cls
@isTest
public with sharing class HH_CreateUpdateAccountRoleCtrlTest {
    @isTest 
    public static void searchAccountRoleTest() {
        Account acc= new Account(Name ='Contractor',Email_Address__c ='test@xyz.com',Phone = '1234567890');
        insert acc;
        Account acc1= new Account(Name ='Contractor1',Email_Address__c ='test@xyz.com',Phone = '1234567890');
        Contact con = new Contact (AccountId = acc.Id,LastName = 'Test',Email = 'Test@xyz.com');
        insert con;
        HH_Application__c hhApp = new HH_Application__c(County__c = 'Shasta',Applicant__c = con.Id);
        insert hhApp;
        CWMP_Project__c hhProj = new CWMP_Project__c (Applicant__c = con.Id,CWMP_Application__c = hhApp.Id);
        insert hhProj;
        Account_Role__c aRole= new Account_Role__c(CWMP_Application__c =hhApp.Id, Point_of_Contact__c= 'XYZ', Original_Contract_Amount__c = 5000, Role__c = 'Contractor', Account__c = acc.Id);
        insert aRole;
        Draw__c dr =new Draw__c(Account_Role__c = aRole.Id,Amount__c = 2000,Date__c = Date.Today()-1);
        insert dr;
        Order_Change__c oChange = new Order_Change__c(Account_Role__c = aRole.Id,Has_Homeowner_provided_check_payment__c = 'Yes',Homeowner_check_payment_amount__c = 2000);
        insert oChange;
        Test.startTest();
        String accoutDetail = JSON.serialize(acc);
        String accoutDetail1 = JSON.serialize(acc1);
        String accoutRoleDetail = JSON.serialize(aRole);
        HH_CreateUpdateAccountRoleCtrl.searchAccountRole('Contr');
        HH_CreateUpdateAccountRoleCtrl.saveDetails(hhApp.Id,accoutDetail,accoutRoleDetail);
        HH_CreateUpdateAccountRoleCtrl.saveDetails(hhProj.Id,accoutDetail1,accoutRoleDetail);
        HH_CreateUpdateAccountRoleCtrl.getDetails(hhApp.Id,aRole.Id);
        HH_CreateUpdateAccountRoleCtrl.getDetails(hhProj.Id,aRole.Id);
        Test.stopTest();
}
}