codepkg/objects/AccountContactRole__c.object
<CustomObject>
    <description>This object is a custom junction object between Account and Contact.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact for which this Contact Role is created.</description>
        <inlineHelpText>Contact for which this Contact Role is created.</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>AccountContactJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>ACJ-{000000}</displayFormat>
        <label>AccountContactJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>County</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>County__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>HMGP</fullName>
        <active>true</active>
        <label>HMGP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>AccountContactJunction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Contact Junction</label>
        <referenceTo>AccountContactRole__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Working Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Responsible Representative</fullName>
                </value>
                <value>
                    <fullName>Match Commitment</fullName>
                </value>
                <value>
                    <fullName>Maintenance Commitment</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic Analyst</fullName>
                </value>
                <value>
                    <fullName>Authorized Agent</fullName>
                    <isActive>false</isActive>
                    <label>Authorized Agent</label>
                </value>
                <value>
                    <fullName>Requestor</fullName>
                    <isActive>false</isActive>
                    <label>Requestor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Page_Field__mdt.object
<CustomObject>
    <label>Page Field</label>
    <pluralLabel>Page Fields</pluralLabel>
</CustomObject>

codepkg/objects/Page_Layout__mdt.object
<CustomObject>
    <label>Page Layout Config</label>
    <pluralLabel>Page Layouts</pluralLabel>
</CustomObject>

codepkg/objects/Pre_Application__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <inlineHelpText>Only use &quot;Multi-county&quot; if the project is located in more than one county.</inlineHelpText>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Statewide</fullName>
                </value>
                <value>
                    <fullName>Multi-County</fullName>
                </value>
                <value>
                    <fullName>Alameda</fullName>
                </value>
                <value>
                    <fullName>Alpine</fullName>
                </value>
                <value>
                    <fullName>Amador</fullName>
                </value>
                <value>
                    <fullName>Butte</fullName>
                </value>
                <value>
                    <fullName>Calaveras</fullName>
                </value>
                <value>
                    <fullName>Colusa</fullName>
                </value>
                <value>
                    <fullName>Contra Costa</fullName>
                </value>
                <value>
                    <fullName>Del Norte</fullName>
                </value>
                <value>
                    <fullName>El Dorado</fullName>
                </value>
                <value>
                    <fullName>Fresno</fullName>
                </value>
                <value>
                    <fullName>Glenn</fullName>
                </value>
                <value>
                    <fullName>Humboldt</fullName>
                </value>
                <value>
                    <fullName>Imperial</fullName>
                </value>
                <value>
                    <fullName>Inyo</fullName>
                </value>
                <value>
                    <fullName>Kern</fullName>
                </value>
                <value>
                    <fullName>Kings</fullName>
                </value>
                <value>
                    <fullName>Lake</fullName>
                </value>
                <value>
                    <fullName>Lassen</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Madera</fullName>
                </value>
                <value>
                    <fullName>Marin</fullName>
                </value>
                <value>
                    <fullName>Mariposa</fullName>
                </value>
                <value>
                    <fullName>Mendocino</fullName>
                </value>
                <value>
                    <fullName>Merced</fullName>
                </value>
                <value>
                    <fullName>Modoc</fullName>
                </value>
                <value>
                    <fullName>Mono</fullName>
                </value>
                <value>
                    <fullName>Monterey</fullName>
                </value>
                <value>
                    <fullName>Napa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Pre-Applications</relationshipLabel>
        <relationshipName>Pre_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>County__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Coastal</fullName>
                </value>
                <value>
                    <fullName>Inland</fullName>
                </value>
                <value>
                    <fullName>Southern</fullName>
                </value>
                <value>
                    <fullName>Statewide</fullName>
                </value>
                <value>
                    <fullName>Multi-County</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <recordTypes>
        <fullName>HMGP</fullName>
        <active>true</active>
        <description>For HMGP NOI Requests</description>
        <label>HMGP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Parent Program</description>
        <inlineHelpText>If the Program you are adding is not one of the Programs in this list, please select the parent Program from this list.</inlineHelpText>
        <label>Parent Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Related Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Program_Template_Page__mdt.object
<CustomObject>
    <label>Program Template Page</label>
    <pluralLabel>Program Template Pages</pluralLabel>
</CustomObject>

codepkg/classes/PageLayoutCtrlTest.cls
@isTest 
public with sharing class PageLayoutCtrlTest {
    @isTest public static void testGetPageDetails() {
        Map<String, Object> returnMap = new Map<String, Object>();
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        returnMap = PageLayoutCtrl.getPageDetails(newApplication.Id, '');
        System.assert(returnMap.size() > 0);
    }
    @isTest public static void testGetPageDetails1() {
        Map<String, Object> returnMap = new Map<String, Object>();
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        Program_Template_Page__mdt ptMdt = HMA_TestMetadataHelper.getProgramTemplatePageMdt('HMGP_Scope_Of_Work_General');

        returnMap = PageLayoutCtrl.getPageDetails(newApplication.Id, ptMdt.Id);
        System.assert(returnMap.size() > 0);
    }

    @isTest public static void testGetPageLayoutDetails() {
        Map<String, Object> returnMap = new Map<String, Object>();
        //Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        Page_Layout__mdt plMdt = HMA_TestMetadataHelper.getPageLayoutMdt('HMGP_Acquisition_Demo_Relocation');

        returnMap = PageLayoutCtrl.getPageLayoutDetails(plMdt.Id);
        System.assert(returnMap.size() > 0);
    }

    @isTest public static void testGetProjectSitePageDetailsByPageLayoutId() {
        Map<String, Object> returnMap = new Map<String, Object>();
        //Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        Page_Layout__mdt plMdt = HMA_TestMetadataHelper.getPageLayoutMdt('HMGP_Acquisition_Demo_Relocation');
        
        returnMap = PageLayoutCtrl.getProjectSitePageDetailsByPageLayoutId(plMdt.Id);
        System.assert(returnMap.size() > 0);
    }

    @isTest public static void testGetRecordDetails() {
        Map<String, Object> returnMap = new Map<String, Object>();
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        Page_Layout__mdt plMdt = HMA_TestMetadataHelper.getPageLayoutMdt('HMGP_Acquisition_Demo_Relocation');

        returnMap = PageLayoutCtrl.getRecordDetails(newApplication.Id, plMdt.Id);
        System.assert(returnMap.size() > 0);
    }

    @isTest public static void testGetRecordDetails1() {
        Map<String, Object> returnMap = new Map<String, Object>();
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        //Page_Layout__mdt plMdt = HMA_TestMetadataHelper.getPageLayoutMdt('HMGP_Acquisition_Demo_Relocation');

        returnMap = PageLayoutCtrl.getRecordDetails(newApplication.Id, '');
        System.assert(returnMap.size() > 0);
    }

    // @isTest public static void testGetRecordDetails2() {
    //     Map<String, Object> returnMap = new Map<String, Object>();
    //     Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
    //     Page_Layout__mdt plMdt = HMA_TestMetadataHelper.getPageLayoutMdt('HMGP_Acquisition_Demo_Relocation');

    //     returnMap = PageLayoutCtrl.getRecordDetails(newApplication.Pre_Application__c, plMdt.Id);
    //     System.assert(returnMap.size() > 0);
    // }
    @isTest public static void testGetLoggedInUsrDetails() {
        Map<String, Object> returnMap = new Map<String, Object>();
        returnMap = PageLayoutCtrl.getLoggedInUsrDetails();
        System.assert(returnMap.size() > 0);
    }

    /*@isTest public static void testGetPathDetails() {
        Map<String, Object> returnMap = new Map<String, Object>();
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');

        returnMap = PageLayoutCtrl.getPathDetails(newApplication.Id);
        System.assert(returnMap.size() > 0);
    }*/

    @isTest public static void testGetListofTable() {
        Map<String, Object> returnMap = new Map<String, Object>();

        returnMap = PageLayoutCtrl.getListofTable('SELECT Id, DeveloperName FROM Page_Field__mdt');
        System.assert(returnMap.size() > 0);
    }

    @isTest public static void testDynamicTableClassApex() {
        Contact portalCon = HMA_TestHelper.getPortalContact(true);
        User portalUser = HMA_TestHelper.getPortalUser(false);
        portalUser.ContactId = portalCon.Id;
        insert portalUser;
        System.runAs(portalUser) {
            Map<String, Object> returnMap = new Map<String, Object>();
            Map<String, Object> returnMap1 = new Map<String, Object>();
            Map<String, Object> returnMap2 = new Map<String, Object>();
            Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
            AccountContactRole__c acRole = new AccountContactRole__c(Contact_Name__c = portalCon.Id );
            insert acRole;
            Contact_Role__c conRole = HMA_TestHelper.getContactRole(false);
            conRole.Application__c = newApplication.Id;
            conRole.Contact__c = portalCon.Id;
            conRole.AccountContactJunction__c = acRole.Id;
            insert conRole;
            
            returnMap = PageLayoutCtrl.dynamicTableClassApex(newApplication.Id, 'HMA_SubApplicationRole', 'Contact_Role_Confirmation_Table');
            System.assert(returnMap.size() > 0);

            /**This is used for cover else condition from HMA_SubApplicationRole.executeClass */
            returnMap2 = PageLayoutCtrl.dynamicTableClassApex(newApplication.Id, 'HMA_SubApplicationRole', 'Contact_Roles');
            System.assert(returnMap2.size() > 0);

            /**This is used for cover else condition from HMA_SubApplicationRole.executeClass */
            conRole.Role__c = 'FEMA Programmatic Analyst';
            update conRole;
            returnMap1 = PageLayoutCtrl.dynamicTableClassApex(newApplication.Id, 'HMA_SubApplicationRole', 'FEMA_Request_For_Information');
            System.assert(returnMap1.size() > 0);
        }
        
    }

    @isTest public static void testSearch() {
        List<LookupSearchResult> returnList = new List<LookupSearchResult>();
        /**Program records are created for cover SearchProgramsCtrl class */
        Program__c parentPro = HMA_TestHelper.getProgram(false);
        parentPro.Name = 'Hazard Mitigation Assistance';
        insert parentPro;
        Program__c pro = HMA_TestHelper.getProgram(false);
        pro.Name = 'HMGP';
        pro.Parent_Program__c  = parentPro.Id;
        insert pro;
        returnList = PageLayoutCtrl.search('HMGP', new List<String>{}, 'SearchProgramsCtrl');
    }

    @isTest public static void testGetFieldDependencies() {
        Map<String, Object> returnMap = new Map<String, Object>();
        returnMap = PageLayoutCtrl.getFieldDependencies('Application__c', 'County__c', 'Region__c');
        System.assert(returnMap.size() > 0);
    }
}