codepkg/objects/Agency_Admin_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Administrative_Rates__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Administrative Rates</label>
        <referenceTo>Agency_Admin_Rates__c</referenceTo>
        <relationshipLabel>Agency Admin Line Items</relationshipLabel>
        <relationshipName>Agency_Admin_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direct__c</fullName>
        <label>Direct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Indirect__c</fullName>
        <label>Indirect</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Admin Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Admin Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Admin_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Administrative_Rate_Indirect_Cost_Direct__c</fullName>
        <label>Administrative Rate(Indirect/Direct)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Administrative_Total_Indirect_Direct__c</fullName>
        <label>Grand  Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Administrative Rates</relationshipLabel>
        <relationshipName>Agency_Administrative_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_For_Use_In__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Data For Use In</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FY_From__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>FY From</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FY_To__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>FY To</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MACS_ID__c</fullName>
        <formula>Agency__r.MACS_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MACS ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Direct_Amount__c</fullName>
        <label>Direct Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Indirect_Amount__c</fullName>
        <label>Indirect Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Administrative Rates</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Administrative Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Administrative Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_AgencyAdminRates_PDF.cls
public without sharing class MARS_AgencyAdminRates_PDF {
    public String signature {get; set;}
    public Agency_Admin_Rates__c  agencyAdminRate {get; set;}
    public list<string> programNames {get; set;}
    public MARS_AgencyAdminRates_PDF() {
        agencyAdminRate = [SELECT Id, Start_Date__c, END_Date__c, Approval_Status__c, Name, Agency__r.MACS_ID__c,Agency__r.Name,Administrative_Rate_Indirect_Cost_Direct__c,CreatedBy.Name,
                                Data_For_Use_In__c, Total_Direct_Amount__c,FY_From__c, FY_To__c, Administrative_Total_Indirect_Direct__c, Total_Indirect_Amount__c,
                                (SELECT Id, Name, Direct__c,Indirect__c, Effective_Date__c, Total__c
                                FROM Agency_Admin_Line_Items__r) 
                            FROM Agency_Admin_Rates__c WHERE Id =:ApexPages.currentPage().getParameters().get('id')];
       
        List<ContentVersion> signDco = getContentVersions(new List<String>{ApexPages.currentPage().getParameters().get('id')});
        if(signDco.size() > 0){
            signature ='/sfc/servlet.shepherd/version/download/'+signDco[0].Id ;
        }
        programNames = new list<string>{'Emergency Medical Services','General Administration','Information Technology','Logistics/Procurement/Supply/Minor Fire Equipment',
                                        'Public Information Office',
                                        'Telecommunications',
                                        'Arson Investigation', 
                                        'Community Education',
                                        'Facilities',
                                        'Fire Comm. Center/Dispatch/Comm. & Control Center',
                                        'Fire Hazard Reduction Program',
                                        'Fleet',
                                        'Hazardous Materials Response Program',
                                        'Mapping',
                                        'Operations',
                                        'Prevention',
                                        'Training',
                                        'Urban Search and Rescue'
                                    };
    }

   
    private static List<ContentVersion> getContentVersions(List<String> recordIds) {
        Set<Id> contentDocIds = new Set<Id>();
        // added dynamic query due to weired issue with static query - ContentDocumentLink requires a filter by a single Id on ContentDocumentId or LinkedEntityId using the equals operator or multiple Id's using the IN operator.
        String query = 'SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId in(\'' + String.join(recordIds, '\',\'') + '\')';
        for(ContentDocumentLink contentDocLink : Database.query(query)) {
            contentDocIds.add(contentDocLink.ContentDocumentId);
        }
        return [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
        from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true AND Title LIKE 'Signature%' order by ContentModifiedDate desc];
    }
}