codepkg/objects/Agency_Non_Suppression_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Non_Suppression_Personnel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Non-Suppression Personnel</label>
        <referenceTo>Agency_Non_Suppression_Personnel__c</referenceTo>
        <relationshipLabel>Agency Non-Suppression Line Items</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MOU_MOA_GBR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portal-to-Portal w/Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate (ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Non-Suppression Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Personnel__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Non-Suppression Personnels</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Personnels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Non-Suppression Personnel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARSNonSuppressionScreenCtrl_Test.cls
@isTest
private class MARSNonSuppressionScreenCtrl_Test {
    @isTest
    static void test(){
        Account testAccount = MARS_TestHelper.getAccount(true);
        Agency_Non_Suppression_Line_Item__c agenNONSuppPerLI = new Agency_Non_Suppression_Line_Item__c();
        agenNONSuppPerLI.Classification_Title__c = 'testAgenNONSuppPerLI';
        agenNONSuppPerLI.Revised_Rate__c = 20.0;
        agenNONSuppPerLI.Current_Rate__c = 20.0;
        agenNONSuppPerLI.MOU_MOA_GBR__c = false;
        List<Agency_Non_Suppression_Line_Item__c> itemList = new List<Agency_Non_Suppression_Line_Item__c>();
        itemList.add(agenNONSuppPerLI);
        String data = JSON.serialize(itemList);
        String effDate = String.valueOf(Date.today());
        MARSNonSuppressionScreenCtrl.getAgencyNonSuppressionLatest(testAccount.Id);
        MARSNonSuppressionScreenCtrl.getData(testAccount.Id);
        MARSNonSuppressionScreenCtrl.submitNonSuppLines(data, testAccount.Id, effDate, 'test');
    }
        @isTest
    static void test1(){
        Account testAccount = MARS_TestHelper.getAccount(true);
        Agency_Non_Suppression_Personnel__c agenNONSuppPer = new Agency_Non_Suppression_Personnel__c();
        agenNONSuppPer.Name = 'testAgenNonSuppPer';
        agenNONSuppPer.Agency__c = testAccount.Id;
        agenNONSuppPer.Approval_Status__c = 'Pending Review';
        agenNONSuppPer.Start_Date__c = Date.today();
        agenNONSuppPer.End_Date__c = Date.today().addDays(10);
        agenNONSuppPer.Reject_Reason__c = 'test';
        insert agenNONSuppPer;
        
        Agency_Non_Suppression_Line_Item__c agenNONSuppPerLI = new Agency_Non_Suppression_Line_Item__c();
        agenNONSuppPerLI.Agency_Non_Suppression_Personnel__c = agenNONSuppPer.Id;
        agenNONSuppPerLI.Classification_Title__c = 'testAgenNONSuppPerLI';
        agenNONSuppPerLI.Revised_Rate__c = 20.0;
        agenNONSuppPerLI.Current_Rate__c = 20.0;
        agenNONSuppPerLI.MOU_MOA_GBR__c = false;
        insert agenNONSuppPerLI;
        MARSNonSuppressionScreenCtrl.getAgencyNonSuppressionLineItems(agenNONSuppPer.Id);
    }

}