codepkg/objects/Agency_Admin_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Administrative_Rates__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Administrative Rates</label>
        <referenceTo>Agency_Admin_Rates__c</referenceTo>
        <relationshipLabel>Agency Admin Line Items</relationshipLabel>
        <relationshipName>Agency_Admin_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direct__c</fullName>
        <label>Direct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Indirect__c</fullName>
        <label>Indirect</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Admin Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Admin Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Admin_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Administrative_Rate_Indirect_Cost_Direct__c</fullName>
        <label>Administrative Rate(Indirect/Direct)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Administrative_Total_Indirect_Direct__c</fullName>
        <label>Grand  Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Administrative Rates</relationshipLabel>
        <relationshipName>Agency_Administrative_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Direct_Amount__c</fullName>
        <label>Direct Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Indirect_Amount__c</fullName>
        <label>Indirect Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Administrative Rates</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Administrative Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Administrative Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_AdministrativeRateHistoryCtrl.cls
/**
 * Created by Chandrabhan on 016-04-2021.
 */
public without sharing class MARS_AdministrativeRateHistoryCtrl {
    @AuraEnabled
    public static List<Agency_Admin_Rates__c> getAdminRateHistory(String accountId) {
        return [SELECT Id, Start_Date__c, End_Date__c, Approval_Status__c, Name
                FROM Agency_Admin_Rates__c WHERE Agency__c=:accountId ORDER BY Start_Date__c,CreatedDate DESC NULLS FIRST LIMIT 10];
                
    }
    @AuraEnabled
    public static List<Agency_Admin_Line_Items__c> getAdminRateLineItems(String agencyAdminRateId) {
        return [SELECT Id, Direct__c,Indirect__c,Effective_Date__c,Name,Status__c,Total__c
               FROM Agency_Admin_Line_Items__c WHERE Agency_Administrative_Rates__c=:agencyAdminRateId];
    }
    @AuraEnabled
    public static Map<String, Object> getData(String agencyAdminRateId) {
        Map<String, Object> returnMap = new Map<String, Object>();
        returnMap.put('adminRateLines', getAdminRateLineItems(agencyAdminRateId));

        Agency_Admin_Rates__c agencyAdminRate = [SELECT Id, Approval_Status__c, Name,Reject_Reason__c,Administrative_Total_Indirect_Direct__c,
                                                Administrative_Rate_Indirect_Cost_Direct__c, Total_Direct_Amount__c,Total_Indirect_Amount__c,Start_Date__c
                                                FROM Agency_Admin_Rates__c WHERE Id=:agencyAdminRateId LIMIT 1];
        returnMap.put('agencyAdminRate', agencyAdminRate);
        returnMap.put('contentVersions', getContentVersions(new List<String>{agencyAdminRateId}));
        return returnMap;
    }
    private static List<ContentVersion> getContentVersions(List<String> recordIds) {
        Set<Id> contentDocIds = new Set<Id>();
        // added dynamic query due to weired issue with static query - ContentDocumentLink requires a filter by a single Id on ContentDocumentId or LinkedEntityId using the equals operator or multiple Id's using the IN operator.
        String query = 'SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId in(\'' + String.join(recordIds, '\',\'') + '\')';
        for(ContentDocumentLink contentDocLink : Database.query(query)) {
            contentDocIds.add(contentDocLink.ContentDocumentId);
        }

        system.debug('==contentDocIds==='+contentDocIds);
        return [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
        from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true AND (NOT Title LIKE '%signature%') order by ContentModifiedDate desc];
    }
}