codepkg/objects/Agency_Special_Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Special Equipments</relationshipLabel>
        <relationshipName>Agency_Special_Equipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Special Equipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Special_Equipment_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Special_Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Special Equipment</label>
        <referenceTo>Agency_Special_Equipment__c</referenceTo>
        <relationshipLabel>Agency Special Equipment Line Items</relationshipLabel>
        <relationshipName>Agency_Special_Equipment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Special Equipment Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipment Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_SpecialEquipmentHistoryCtrl_Test.cls
@isTest
private class MARS_SpecialEquipmentHistoryCtrl_Test {
	@isTest
    static void createRecData(){
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
        
        Agency_Special_Equipment__c ase = new Agency_Special_Equipment__c();
        ase.Agency__c = acc.Id;
        ase.Start_Date__c = System.today();
        ase.End_Date__c = System.today().addDays(10);
        ase.Approval_Status__c = 'Reviewed';
        insert ase;
        
        Agency_Special_Equipment_Line_Item__c aseLineItem = new Agency_Special_Equipment_Line_Item__c();
        aseLineItem.Agency_Special_Equipment__c = ase.Id;
        insert aseLineItem;
        
        MARS_SpecialEquipmentHistoryCtrl.getAgencySpecialEquipHistory(acc.Id);
        MARS_SpecialEquipmentHistoryCtrl.getAgencySpecialEquipLineItems(ase.Id);
        MARS_SpecialEquipmentHistoryCtrl.getData(ase.Id);
    }
    
}