codepkg/objects/Agency_Non_Suppression_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Non_Suppression_Personnel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Non-Suppression Personnel</label>
        <referenceTo>Agency_Non_Suppression_Personnel__c</referenceTo>
        <relationshipLabel>Agency Non-Suppression Line Items</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Non-Suppression Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Personnel__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Non-Suppression Personnels</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Personnels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Non-Suppression Personnel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Rate Agreements</relationshipLabel>
        <relationshipName>Agency_Rate_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Rate Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Rate_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Rate Agreement</label>
        <referenceTo>Agency_Rate_Agreement__c</referenceTo>
        <relationshipLabel>Agency Rate Agreement Line Items</relationshipLabel>
        <relationshipName>Agency_Rate_Agreement_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Rate Agreement Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreement Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_ResourceAgreementCtrl_Test.cls
@isTest
private class MARS_ResourceAgreementCtrl_Test {    
    @isTest
    static void test(){
        Account testAccount = MARS_TestHelper.getAccount(true);
        List<Agency_Rate_Agreement_Line_Item__c> agenRateAgreeLI = new List<Agency_Rate_Agreement_Line_Item__c>();
        Agency_Rate_Agreement__c agenRateAgr = new Agency_Rate_Agreement__c();
        agenRateAgr.Name = 'testAgenRateAgr';
        agenRateAgr.Agency__c = testAccount.Id;
        agenRateAgr.Agreement_Type__c = 'GBR';
        agenRateAgr.Approval_Status__c = 'Expired'; 
        insert agenRateAgr;
        
        Agency_Rate_Agreement_Line_Item__c agenRateAgrLI = new Agency_Rate_Agreement_Line_Item__c();
        agenRateAgrLI.Name = 'testAgenRateAgrLI';
        agenRateAgrLI.Agency_Rate_Agreement__c = agenRateAgr.Id;
        insert agenRateAgrLI;
        Agency_Non_Suppression_Personnel__c nonSupPer = new Agency_Non_Suppression_Personnel__c();
        nonSupPer.Agency__c = testAccount.Id;
        nonSupPer.Start_Date__c =  DateTime.Now().AddDays(-3).date();
        nonSupPer.Approval_Status__c = 'Reviewed';
        insert nonSupPer;
        Agency_Non_Suppression_Line_Item__c nonSupPerItem = new Agency_Non_Suppression_Line_Item__c();
        nonSupPerItem.Classification_Title__c = 'Test';
        nonSupPerItem.Current_Rate__c = 25.00;
        nonSupPerItem.Status__c = 'Active';
        nonSupPerItem.Agency_Non_Suppression_Personnel__c = nonSupPer.Id;
        insert nonSupPerItem;
        
        MARS_ResourceAgreementCtrl.apexSearchCFAA_Line_Items('Test', testAccount.Id);
        MARS_ResourceAgreementCtrl.getData(testAccount.Id);
        
    }
    @isTest
    static void test1(){
        Account testAccount = MARS_TestHelper.getAccount(true);
        List<Agency_Rate_Agreement_Line_Item__c> agenRateAgreeLI = new List<Agency_Rate_Agreement_Line_Item__c>();
        Agency_Rate_Agreement__c agenRateAgr = new Agency_Rate_Agreement__c();
        agenRateAgr.Name = 'testAgenRateAgr';
        agenRateAgr.Agency__c = testAccount.Id;
        agenRateAgr.Agreement_Type__c = 'GBR';
        agenRateAgr.Approval_Status__c = 'Expired'; //MARS_Constants.SURVEY_STATUS_PENDING_REVIEW;
        insert agenRateAgr;
 		 
        Id profileId = [Select Id From Profile Where Name ='CalOES Portal User'].Id;
        Account acct = TestUtility.createAccount('test');
        Contact cont = TestUtility.createContact('test', 'tes', 'test@gmail.vom', acct.Id);
        User u = TestUtility.createCommunityUser(cont.Id, profileId, 'Amit', 'Singh');        
        
        Agency_Rate_Agreement_Line_Item__c agenRateAgrLI = new Agency_Rate_Agreement_Line_Item__c();
        agenRateAgrLI.Name = 'testAgenRateAgrLI';
        agenRateAgrLI.Start_Date__c = DateTime.Now().date();
		agenRateAgrLI.Agency_Rate_Agreement__c = agenRateAgr.Id;
        //insert agenRateAgrLI;
        
        String agrList = JSON.serialize(agenRateAgreeLI);
        String startDate = String.valueOf(Date.today());
        String endDate = String.valueOf(Date.today().addDays(10));

        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = testAccount.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        
        List<FileUpdateWrapper> fileUpdWrapperLst = new List<FileUpdateWrapper>();
        FileUpdateWrapper fileUpdWrapper = new FileUpdateWrapper();
        fileUpdWrapper.name = 'test';
        fileUpdWrapper.documentId = conDocId;
        fileUpdWrapper.contentVersionId = cv.Id;
        fileUpdWrapper.Type = 'V';
        fileUpdWrapperLst.add(fileUpdWrapper);
        String fileUpdateWrap = JSON.serialize(fileUpdWrapperLst);
        
        //System.runAs(u){
            //MARS_ResourceAgreementCtrl.createAgreeLineItem(agrList, testAccount.Id, startDate, endDate, fileUpdateWrap, 'GBR');
            //MARS_ResourceAgreementCtrl.deleteFile(cv.Id);
    	//}
    }
    
    public class FileUpdateWrapper {
        public String name{get;set;}
        public String documentId{get;set;}
        public String contentVersionId{get;set;}
        public String Type{get;set;}
    }
}