codepkg/objects/Agency_Rate_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Rate Agreements</relationshipLabel>
        <relationshipName>Agency_Rate_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MACS_ID__c</fullName>
        <formula>Agency__r.MACS_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MACS ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Rate Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Rate_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Rate Agreement</label>
        <referenceTo>Agency_Rate_Agreement__c</referenceTo>
        <relationshipLabel>Agency Rate Agreement Line Items</relationshipLabel>
        <relationshipName>Agency_Rate_Agreement_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PTP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PTP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Rate Agreement Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreement Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Salary_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Salary Surveys</relationshipLabel>
        <relationshipName>Agency_Salary_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>END_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Agency Salary Survey</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Salary Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/CFAA__c.object
<CustomObject>
    <fields>
        <fullName>END_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>CFAA Rate Letter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CFAA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CFAA Rate Letter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/CFAA_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>CFAA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA</label>
        <referenceTo>CFAA__c</referenceTo>
        <relationshipLabel>CFAA Line Items</relationshipLabel>
        <relationshipName>CFAA_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Personnel_Role__c</fullName>
        <label>Personnel Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chief</fullName>
                </value>
                <value>
                    <fullName>Deputy Chief</fullName>
                </value>
                <value>
                    <fullName>Division Chief</fullName>
                </value>
                <value>
                    <fullName>Assistant Chief</fullName>
                </value>
                <value>
                    <fullName>Battalion Chief</fullName>
                </value>
                <value>
                    <fullName>Co. Officer/Capt./Lt.</fullName>
                </value>
                <value>
                    <fullName>App. Officer/Eng</fullName>
                </value>
                <value>
                    <fullName>Firefighter/FF-PMedic</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Straight_Time_Rate__c</fullName>
        <label>Straight Time Rate</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>CFAA Line Item</label>
    <nameField>
        <label>CFAA Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CFAA Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Salary_Survey_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Salary_Survey__c</fullName>
        <label>Agency Salary Survey</label>
        <referenceTo>Agency_Salary_Survey__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CFAA_Line_Items__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA Line Item</label>
        <referenceTo>CFAA_Line_Items__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CFAA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA</label>
        <referenceTo>CFAA__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salary Survey Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salary Survey Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/MARS_SalarySurveyCrl_Test.cls
@isTest
private class MARS_SalarySurveyCrl_Test {
    @isTest
static void getDataTest(){
Account acc = new Account();
acc.Name = 'test';
insert acc;

Agency_Salary_Survey__c agencyRecord = new Agency_Salary_Survey__c();
agencyRecord.Account__c = acc.Id;
agencyRecord.Status__c = 'Reviewed';
insert agencyRecord;

CFAA__c cfaaRecord = new CFAA__c();
cfaaRecord.Name = 'test';
cfaaRecord.Start_Date__c = System.today();
cfaaRecord.END_Date__c = System.today() + 10;
insert cfaaRecord;

Id recId = Schema.SObjectType.CFAA_Line_Items__c.getRecordTypeInfosByName().get('Personnel Base Rate').getRecordTypeId();

CFAA_Line_Items__c cfaaLI = new CFAA_Line_Items__c();
cfaaLI.Personnel_Role__c = 'Chief';
cfaaLI.CFAA__c = cfaaRecord.Id;
cfaaLI.Order_No__c = 1;
cfaaLI.Straight_Time_Rate__c = 100;
cfaaLI.RecordTypeId = recId;
insert cfaaLI;

MARS_SalarySurveyCrl.getData(acc.Id);
String dat = String.valueOf(System.today());
//MARS_SalarySurveyCrl.submitSalarySurveyLines('test', acc.Id, dat, 'null');

}
    
    @testSetup
    static void createRec(){
        Account acc = new Account();
        acc.Name = 'test';
        acc.MACS_ID__c = '1234321';
        insert acc;
        
        Agency_Rate_Agreement__c ageRateAgr = new Agency_Rate_Agreement__c();
        ageRateAgr.Name = 'testAgeRateAgr';
        ageRateAgr.Agency__c = acc.Id;
        ageRateAgr.Approval_Status__c = 'Approved';
        insert ageRateAgr;
        
        Agency_Rate_Agreement_Line_Item__c ageRateAgrLI = new Agency_Rate_Agreement_Line_Item__c();
        ageRateAgrLI.Agency_Rate_Agreement__c = ageRateAgr.Id;
        ageRateAgrLI.Name = 'Chief';
        ageRateAgrLI.OT__c = false;
        ageRateAgrLI.PTP__c = false;
        insert ageRateAgrLI;
        
        Agency_Salary_Survey__c agenSalSur = new Agency_Salary_Survey__c();
        agenSalSur.Name = 'testAgenSalSur';
        agenSalSur.Account__c = acc.Id;
        agenSalSur.Status__c = MARS_Constants.SURVEY_STATUS_REVISED;
        agenSalSur.Start_Date__c = System.today() - 10;
        agenSalSur.END_Date__c = System.today() + 10;
        insert agenSalSur;
        
        Agency_Salary_Survey__c agenSalSur1 = new Agency_Salary_Survey__c();
        agenSalSur1.Name = 'testAgenSalSur1';
        agenSalSur1.Account__c = acc.Id;
        agenSalSur1.Status__c = MARS_Constants.SURVEY_STATUS_PENDING_REVIEW;
        
        insert agenSalSur1;
        
        Salary_Survey_Line_Items__c salSurLI = new Salary_Survey_Line_Items__c();
        salSurLI.Name = 'testSalSurLI';
        salSurLI.Agency_Salary_Survey__c = agenSalSur.Id;
        salSurLI.Classification_Title__c = 'Chief';
        salSurLI.Current_Rate__c = 20.0;
        salSurLI.Status__c = MARS_Constants.SURVEY_STATUS_ACTIVE;
        insert salSurLI;
        
        CFAA__c cfaaRecord = new CFAA__c();
        cfaaRecord.Name = 'test';
        cfaaRecord.Start_Date__c = System.today();
        cfaaRecord.END_Date__c = System.today() + 10;
        insert cfaaRecord;
        
        Id recTypeId = Schema.SObjectType.CFAA_Line_Items__c.getRecordTypeInfosByName().get('Personnel Base Rate').getRecordTypeId();
        
        CFAA_Line_Items__c cfaaLI = new CFAA_Line_Items__c();
        cfaaLI.Personnel_Role__c = 'Chief';
        cfaaLI.CFAA__c = cfaaRecord.Id;
        cfaaLI.Order_No__c = 1;
        cfaaLI.Straight_Time_Rate__c = 100;
        cfaaLI.RecordTypeId = recTypeId;
        insert cfaaLI;
    }
    
    @isTest
    static void test(){
        Account acct = [SELECT Id, Name FROM Account WHERE Name = 'test' LIMIT 1];
        String accId = acct.Id;
        List<Salary_Survey_Line_Items__c> salSurveyLI = [SELECT Id, Name FROM Salary_Survey_Line_Items__c WHERE Name = 'testSalSurLI'];
        String data = JSON.serialize(salSurveyLI);
        MARS_SalarySurveyCrl.getData(acct.Id);
        String effDate = String.valueOf(Date.today());
       // MARS_SalarySurveyCrl.submitSalarySurveyLines(data, accId, effDate, 'test');
    }
}