codepkg/objects/Agency_Admin_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Admin Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Admin Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Admin_Rates__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Administrative Rates</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Administrative Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Administrative Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate (ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Non-Suppression Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Personnel__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Non-Suppression Personnel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Deputy Chief of Administration Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Rate Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Rate Agreement Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreement Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Salary_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Salary Surveys</relationshipLabel>
        <relationshipName>Agency_Salary_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>END_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Agency Salary Survey</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Salary Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Special_Equipment__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Special Equipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Special_Equipment_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Special Equipment Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipment Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/FEMA_Code__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FEMA Code</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FEMA Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Salary_Survey_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Salary_Survey__c</fullName>
        <label>Agency Salary Survey</label>
        <referenceTo>Agency_Salary_Survey__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Are_you_adding_WC_UI__c</fullName>
        <label>Are you adding WC/UI?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Base_Rates__c</fullName>
        <label>Base Rates</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate(ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Rate FILLABLE</fullName>
                </value>
                <value>
                    <fullName>Non-Suppression Personnel - FILLABLE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WC_and_or_UI__c</fullName>
        <label>Is Revised Rate is Same as Base Rate ?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salary Survey Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salary Survey Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/MARS_FireAgency_Research_Ctrl.cls
public without sharing class MARS_FireAgency_Research_Ctrl {
    
    @AuraEnabled
    public static list<Salary_Survey_Line_Items__c> getSalarySurveyItems(string accountId, Date dayOfRecord){
        try {
            string parentId;
            list<Agency_Salary_Survey__c> surveys = [SELECT Id, Status__c, Start_Date__c , End_Date__c
                                                    FROM Agency_Salary_Survey__c
                                                    WHERE Account__c = :accountId
                                                    AND Status__c != 'Rejected' AND (NOT Status__c LIKE '%Pending%')
                                                    AND (Start_Date__c <= :dayOfRecord and (END_Date__c = null or End_Date__c >= :dayOfRecord))
                                                    order by Start_Date__c desc 
                                                    LIMIT 1];

            if(!surveys.isEmpty()){
                parentId = surveys[0].Id;
                List<String> contentDocIds = new List<String>();
                for(ContentDocumentLink contentDocLink : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: parentId]) {
                    contentDocIds.add(contentDocLink.ContentDocumentId);
                }
                List<ContentVersion> cvs = [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
                from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true order by ContentModifiedDate desc];

                LIST<Salary_Survey_Line_Items__c> items = [SELECT Id, Name, Classification_Title__c, Base_Rates__c, WC_and_or_UI__c, Are_you_adding_WC_UI__c, Revised_Rate__c, Agency_Salary_Survey__r.Start_Date__c, 
                            Agency_Salary_Survey__r.End_Date__c, Agency_Salary_Survey__r.Status__c, Agency_Salary_Survey__r.Reject_Reason__c,Agency_Salary_Survey__c,
                            Agency_Salary_Survey__r.Name, Agency_Salary_Survey__r.CreatedBy.LastName, Agency_Salary_Survey__r.CreatedBy.FirstName
                        FROM Salary_Survey_Line_Items__c 
                        WHERE Agency_Salary_Survey__c = :parentId];
                if(cvs.Size() > 0){
                    items[0].Name = '/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId='+ cvs[0].Id + '&operationContext=CHATTER&contentId=' + contentDocIds[0];
                }
                return items;
            }else{
                return new list<Salary_Survey_Line_Items__c>();
            }
           
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    //'/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId='+ pacvId + '&operationContext=CHATTER&contentId=' + pacdId;

    @AuraEnabled
    public static list<Agency_Non_Suppression_Line_Item__c> getNonsupressionItems(string accountId, Date dayOfRecord){
        try {
            string parentId;
            list<Agency_Non_Suppression_Personnel__c> parentRecords = [SELECT Id, Approval_Status__c, Start_Date__c , End_Date__c
                                                    FROM Agency_Non_Suppression_Personnel__c
                                                    WHERE Agency__c = :accountId
                                                    AND Approval_Status__c != 'Rejected' AND (NOT Approval_Status__c LIKE '%Pending%')
                                                    AND (Start_Date__c <= :dayOfRecord and (END_Date__c = null or End_Date__c >= :dayOfRecord))
                                                    order by Start_Date__c desc 
                                                    LIMIT 1];
          
                if(!parentRecords.isEmpty()) {  
                    parentId = parentRecords[0].Id;   

                List<String> contentDocIds = new List<String>();
                for(ContentDocumentLink contentDocLink : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: parentId]) {
                    contentDocIds.add(contentDocLink.ContentDocumentId);
                }
                List<ContentVersion> cvs = [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
                    from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true order by ContentModifiedDate desc];                     
                List<Agency_Non_Suppression_Line_Item__c> items = [SELECT Id, Name, Classification_Title__c,Current_Rate__c, Revised_Rate__c,  Agency_Non_Suppression_Personnel__r.Start_Date__c, 
                Agency_Non_Suppression_Personnel__r.Reject_Reason__c, Agency_Non_Suppression_Personnel__r.Approval_Status__c,
                Agency_Non_Suppression_Personnel__r.Name, Agency_Non_Suppression_Personnel__r.CreatedBy.LastName,
                 Agency_Non_Suppression_Personnel__r.CreatedBy.FirstName,Agency_Non_Suppression_Personnel__c
                        FROM Agency_Non_Suppression_Line_Item__c 
                        WHERE Agency_Non_Suppression_Personnel__c = :parentId];
                if(cvs.Size() > 0){
                    items[0].Name = '/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId='+ cvs[0].Id + '&operationContext=CHATTER&contentId=' + contentDocIds[0];                        
                }
                 return items;
            }else{
                return new list<Agency_Non_Suppression_Line_Item__c>();
            }
           
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static list<Agency_Special_Equipment_Line_Item__c> getSpecialEquipmentItems(string accountId, Date dayOfRecord){
        try {
            string parentId;
            list<Agency_Special_Equipment__c> parentRecords = [SELECT Id, Approval_Status__c, Start_Date__c , End_Date__c
                                                    FROM Agency_Special_Equipment__c
                                                    WHERE Agency__c = :accountId
                                                    AND Approval_Status__c != 'Rejected' AND (NOT Approval_Status__c LIKE '%Pending%')
                                                    AND (Start_Date__c <= :dayOfRecord and (END_Date__c = null or End_Date__c >= :dayOfRecord))
                                                    order by Start_Date__c desc 
                                                    LIMIT 1];
         
                                                            
            if(!parentRecords.isEmpty()) {  
                parentId = parentRecords[0].Id;    

                List<String> contentDocIds = new List<String>();
                for(ContentDocumentLink contentDocLink : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: parentId]) {
                    contentDocIds.add(contentDocLink.ContentDocumentId);
                }
                List<ContentVersion> cvs = [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
                    from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true order by ContentModifiedDate desc];          
           // if(string.isNotBlank(parentId)){
                List<Agency_Special_Equipment_Line_Item__c> items = [SELECT Id, Name, Special_Equipment_Type__c,FEMA_CODE__c, Current_Rate__c, Revised_Rate__c, Description__c,
                        Agency_Special_Equipment__r.Start_Date__c, Agency_Special_Equipment__r.Approval_Status__c,
                        Agency_Special_Equipment__r.Reject_Reason__c, Agency_Special_Equipment__r.End_Date__c,
                        Agency_Special_Equipment__r.CreatedBy.LastName, Agency_Special_Equipment__r.CreatedBy.FirstName,Agency_Special_Equipment__c
                        FROM Agency_Special_Equipment_Line_Item__c 
                        WHERE Agency_Special_Equipment__c = :parentId];
            if(cvs.Size() > 0){
                items[0].Name = '/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId='+ cvs[0].Id + '&operationContext=CHATTER&contentId=' + contentDocIds[0];                        
            }
                return items;                
            }else{
                return new list<Agency_Special_Equipment_Line_Item__c>();
            }
           
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static agreementResearch getAgreementLineItems(string accountId, Date dayOfRecord){
        try {
            set<string> parentIds = new set<string>();
            list<Agency_Rate_Agreement__c> parentRecords = [SELECT Id, Approval_Status__c, Start_Date__c , End_Date__c
                                                    FROM Agency_Rate_Agreement__c
                                                    WHERE Agency__c = :accountId
                                                    AND Approval_Status__c != 'Rejected' AND (NOT Approval_Status__c LIKE '%Pending%')
                                                    AND (Start_Date__c <= :dayOfRecord and (END_Date__c = null or End_Date__c >= :dayOfRecord))
                                                    order by Start_Date__c desc 
                                                    LIMIT 1000];
            for(Agency_Rate_Agreement__c parent: parentRecords){
                parentIds.add(parent.Id);

            }
            agreementResearch result = new agreementResearch();
            if(!parentIds.isEmpty()){
                result.agreementLines = [SELECT Id, Name, Start_Date__c, End_Date__c,MOU_MOA__c, OT__c, PTP__c,Agency_Rate_Agreement__r.Start_Date__c,
                            Agency_Rate_Agreement__r.End_Date__c , Agency_Rate_Agreement__r.Reject_Reason__c,Agency_Rate_Agreement__r.Approval_Status__c,
                            Agency_Rate_Agreement__r.Level_2_Comments__c
                        FROM Agency_Rate_Agreement_Line_Item__c 
                        WHERE Agency_Rate_Agreement__c = :parentIds];

                set<String> contentDocIds = new set<String>();
                for(ContentDocumentLink contentDocLink : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId in: parentIds]) {
                    contentDocIds.add(contentDocLink.ContentDocumentId);
                }
                result.contentVersions = [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
                from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true order by ContentModifiedDate desc];
            
            }else{
                result.agreementLines =  new list<Agency_Rate_Agreement_Line_Item__c>();
                result.contentVersions = new list<ContentVersion>();
            }

            return result;
           
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static list<Agency_Admin_Line_Items__c> getAdminLineItems(string accountId, Date dayOfRecord){
        try {
            string parentId;
            list<Agency_Admin_Rates__c> parentRecords = [SELECT Id, Approval_Status__c, Start_Date__c , End_Date__c
                                                    FROM Agency_Admin_Rates__c
                                                    WHERE Agency__c = :accountId
                                                    AND Approval_Status__c != 'Rejected' AND (NOT Approval_Status__c LIKE '%Pending%')
                                                    AND (Start_Date__c <= :dayOfRecord and (END_Date__c = null or End_Date__c >= :dayOfRecord))
                                                    order by Start_Date__c desc 
                                                    LIMIT 1];
        

            //if(string.isNotBlank(parentId)){
            if(!parentRecords.isEmpty()) {  
                parentId = parentRecords[0].Id;    
                List<String> contentDocIds = new List<String>();
                for(ContentDocumentLink contentDocLink : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: parentId]) {
                        contentDocIds.add(contentDocLink.ContentDocumentId);
                }
                List<ContentVersion> cvs = [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
                    from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true order by ContentModifiedDate desc];                       
                List<Agency_Admin_Line_Items__c> items = [SELECT Id, Name, Direct__c, Indirect__c, Effective_Date__c, Total__c, 
                        Agency_Administrative_Rates__r.Total_Indirect_Amount__c, 
                        Agency_Administrative_Rates__r.Total_Direct_Amount__c,
                        Agency_Administrative_Rates__r.Administrative_Total_Indirect_Direct__c,
                        Agency_Administrative_Rates__r.Administrative_Rate_Indirect_Cost_Direct__c,
                        Agency_Administrative_Rates__r.Start_Date__c,
                        Agency_Administrative_Rates__r.Approval_Status__c,
                        Agency_Administrative_Rates__r.Reject_Reason__c,Agency_Administrative_Rates__c,
                        Agency_Administrative_Rates__r.CreatedBy.LastName, Agency_Administrative_Rates__r.CreatedBy.FirstName
                        FROM Agency_Admin_Line_Items__c 
                        WHERE Agency_Administrative_Rates__c = :parentId];
                if(cvs.Size() > 0){
                    items[0].Name = '/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId='+ cvs[0].Id + '&operationContext=CHATTER&contentId=' + contentDocIds[0];                        
                }
                return items;   
            }else{
                return new list<Agency_Admin_Line_Items__c>();
            }
           
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class agreementResearch{
        @AuraEnabled
        public list<ContentVersion> contentVersions {get; set;}
        @AuraEnabled
        public list<Agency_Rate_Agreement_Line_Item__c> agreementLines {get; set;}
    }

    

}