codepkg/objects/Agency_Non_Suppression_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Non_Suppression_Personnel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Non-Suppression Personnel</label>
        <referenceTo>Agency_Non_Suppression_Personnel__c</referenceTo>
        <relationshipLabel>Agency Non-Suppression Line Items</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MOU_MOA_GBR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portal-to-Portal w/Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate (ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Non-Suppression Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Personnel__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Non-Suppression Personnels</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Personnels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Non-Suppression Personnel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_NonSuppressionHistoryCtrl.cls
public without sharing class MARS_NonSuppressionHistoryCtrl {
    
    @AuraEnabled
    public static List<Agency_Non_Suppression_Personnel__c > getAgencyNonSuppressionHistory(String accountId) {
        return [SELECT Id, Start_Date__c, End_Date__c, Approval_Status__c, Name, Reject_Reason__c
                FROM Agency_Non_Suppression_Personnel__c WHERE Agency__c=:accountId ORDER BY Start_Date__c,CreatedDate DESC NULLS FIRST LIMIT 10];
    }
    
    @AuraEnabled
    public static List<Agency_Non_Suppression_Line_Item__c > getAgencyNonSuppressionLineItems(String agencyNonSuppId) {
        return [SELECT Id, Classification_Title__c,Revised_Rate__c,MOU_MOA_GBR__c,
                Current_Rate__c,Effective_Date__c
               FROM Agency_Non_Suppression_Line_Item__c  WHERE Agency_Non_Suppression_Personnel__c=:agencyNonSuppId];
    }
    
    @AuraEnabled
    public static Map<String, Object> getData(String agencyNonSuppId) {
        Map<String, Object> returnMap = new Map<String, Object>();
        returnMap.put('nonSuppLines', getAgencyNonSuppressionLineItems(agencyNonSuppId));

        Agency_Non_Suppression_Personnel__c nonSuppSurvey = [SELECT Id, Approval_Status__c, Name,Reject_Reason__c,Start_Date__c
                                                FROM Agency_Non_Suppression_Personnel__c WHERE Id=:agencyNonSuppId LIMIT 1];
        returnMap.put('nonSuppSurvey', nonSuppSurvey);
        returnMap.put('contentVersions', getContentVersions(new List<String>{agencyNonSuppId}));
        return returnMap;
    }
    private static List<ContentVersion> getContentVersions(List<String> recordIds) {
        Set<Id> contentDocIds = new Set<Id>();
        // added dynamic query due to weired issue with static query - ContentDocumentLink requires a filter by a single Id on ContentDocumentId or LinkedEntityId using the equals operator or multiple Id's using the IN operator.
        String query = 'SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId in(\'' + String.join(recordIds, '\',\'') + '\')';
        for(ContentDocumentLink contentDocLink : Database.query(query)) {
            contentDocIds.add(contentDocLink.ContentDocumentId);
        }

        system.debug('==contentDocIds==='+contentDocIds);
        return [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
        from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true AND (NOT Title LIKE '%signature%') order by ContentModifiedDate desc];
    }

}