codepkg/objects/Agency_Non_Suppression_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Non_Suppression_Personnel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Non-Suppression Personnel</label>
        <referenceTo>Agency_Non_Suppression_Personnel__c</referenceTo>
        <relationshipLabel>Agency Non-Suppression Line Items</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MOU_MOA_GBR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portal-to-Portal w/Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate (ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Non-Suppression Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Personnel__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Non-Suppression Personnels</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Personnels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MACS_ID__c</fullName>
        <formula>Agency__r.MACS_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MACS ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Non-Suppression Personnel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Rate Agreements</relationshipLabel>
        <relationshipName>Agency_Rate_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MACS_ID__c</fullName>
        <formula>Agency__r.MACS_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MACS ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Deputy Chief of Administration Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Rate Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Rate_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Rate Agreement</label>
        <referenceTo>Agency_Rate_Agreement__c</referenceTo>
        <relationshipLabel>Agency Rate Agreement Line Items</relationshipLabel>
        <relationshipName>Agency_Rate_Agreement_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PTP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PTP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Rate Agreement Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreement Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARSNonSuppressionScreenCtrl.cls
public class MARSNonSuppressionScreenCtrl {
    @AuraEnabled
    public static List<Agency_Non_Suppression_Personnel__c> getAgencyNonSuppressionLatest(String accountId) {
        
        return [SELECT Id, Start_Date__c, END_Date__c, Approval_Status__c, Name, Reject_Reason__c
                FROM Agency_Non_Suppression_Personnel__c WHERE Agency__c=:accountId AND (Approval_Status__c =: MARS_Constants.SURVEY_STATUS_PENDING_REVIEW OR Approval_Status__c =: MARS_Constants.SURVEY_STATUS_REVIEWED) ORDER BY CreatedDate DESC NULLS FIRST LIMIT 1];
    }
    
    @AuraEnabled
    public static List<Agency_Non_Suppression_Line_Item__c > getAgencyNonSuppressionLineItems(String agencyNonSuppId) {
        return [SELECT Classification_Title__c,Revised_Rate__c,MOU_MOA_GBR__c,
                Current_Rate__c,Effective_Date__c
               FROM Agency_Non_Suppression_Line_Item__c  WHERE Agency_Non_Suppression_Personnel__c=:agencyNonSuppId];
    }
    
    @AuraEnabled
    public static responseWrapper getData(String accountId) {
        Map<String, Agency_Rate_Agreement_Line_Item__c> agencyAgreementMap = getAgreementLineItemMap(accountId);
        List<Agency_Non_Suppression_Personnel__c> obj = getAgencyNonSuppressionLatest(accountId);
        List<Agency_Non_Suppression_Line_Item__c> lstNonSupLineItems = new List<Agency_Non_Suppression_Line_Item__c>();
         responseWrapper objWrap = new responseWrapper();
        if (!obj.isEmpty()) {
            objWrap.agencyNonSuppPer = obj[0];
            lstNonSupLineItems = getAgencyNonSuppressionLineItems(obj[0].id);
             objWrap.disableSubmit = obj[0].Approval_Status__c == MARS_Constants.SURVEY_STATUS_PENDING_REVIEW ? true:false;
  
        }
        
        for(Agency_Non_Suppression_Line_Item__c objItem: lstNonSupLineItems){
            objItem.MOU_MOA_GBR__c = agencyAgreementMap.containsKey(objItem.Classification_Title__c)? agencyAgreementMap.get(objItem.Classification_Title__c).PTP__c:false;
        }
        objWrap.nonSuppItemList = lstNonSupLineItems;
       
       
        return objWrap;
    }
    
    @AuraEnabled
    public static void submitNonSuppLines(String data, String accountId, String effectiveDate, String signatureBlob) {
        List<Agency_Non_Suppression_Line_Item__c> lineItemsForUpdateList = (List<Agency_Non_Suppression_Line_Item__c>)JSON.deserialize( data, List<Agency_Non_Suppression_Line_Item__c>.class);
        Account accountRecord = [SELECT Id,MACS_ID__c FROM Account WHERE Id =: accountId];
        Agency_Non_Suppression_Personnel__c agencynonSupp = processAgencyNonSuppPendingForApproval(accountId, Date.valueOf(effectiveDate));
        for (Agency_Non_Suppression_Line_Item__c nonSuppLineItems : lineItemsForUpdateList) {
            nonSuppLineItems.Effective_Date__c = Date.valueOf(effectiveDate);
            nonSuppLineItems.Name = nonSuppLineItems.Classification_Title__c+'-'+accountRecord.MACS_ID__c;
            nonSuppLineItems.Agency_Non_Suppression_Personnel__c = agencynonSupp.Id;
        }
        insert lineItemsForUpdateList;

        if(signatureBlob != null) {
            SignatureHelper.saveSign(signatureBlob, agencynonSupp.Id);
        }
        Map<String, String> paramMap = new Map<String, String>();
        paramMap.put('RecordId', agencynonSupp.Id);
        Flow.Interview.MARS_Non_Suppression_Submittion_Notify_Internal_People flow1 = new Flow.Interview.MARS_Non_Suppression_Submittion_Notify_Internal_People( paramMap );
        flow1.start();
    }
    
    private static Agency_Non_Suppression_Personnel__c processAgencyNonSuppPendingForApproval(String accountId, Date effectDate) {
       /* List<Agency_Non_Suppression_Personnel__c> agentSalarySurvey =
        [ Select Id, Approval_Status__c From Agency_Non_Suppression_Personnel__c Where Agency__c
                =:accountId and Approval_Status__c = :MARS_Constants.SURVEY_STATUS_PENDING_REVIEW LIMIT 1 ];*/

        Agency_Non_Suppression_Personnel__c ass = new Agency_Non_Suppression_Personnel__c();
            ass.Agency__c = accountId;
            ass.Name = 'Non Suppression For Agency ' + System.now().format();
            ass.Approval_Status__c = MARS_Constants.SURVEY_STATUS_PENDING_REVIEW;
        	ass.Start_Date__c = effectDate;
        insert ass;
        return ass;
    }
    
    private static Map<String, Agency_Rate_Agreement_Line_Item__c> getAgreementLineItemMap(String accountId) {
        Map<String, Agency_Rate_Agreement_Line_Item__c> agencyAgreementMap =
                new Map<String, Agency_Rate_Agreement_Line_Item__c>();
        for (Agency_Rate_Agreement_Line_Item__c eachRecord :
        [ SELECT Id, Name, OT__c,
                PTP__c FROM Agency_Rate_Agreement_Line_Item__c Where
                Agency_Rate_Agreement__r.Agency__c =:accountId ]) {
            for (String name : eachRecord.Name.split(';')) {
                agencyAgreementMap.put(name, eachRecord);
            }
        }
        return agencyAgreementMap;
    }
    
    
    public class responseWrapper{
        @AuraEnabled 
        public List<Agency_Non_Suppression_Line_Item__c> nonSuppItemList = new List<Agency_Non_Suppression_Line_Item__c>();
        @AuraEnabled
        public boolean disableSubmit;
        @AuraEnabled
        public Agency_Non_Suppression_Personnel__c agencyNonSuppPer = new Agency_Non_Suppression_Personnel__c();
    }

}