codepkg/objects/Agency_Rate_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Rate Agreements</relationshipLabel>
        <relationshipName>Agency_Rate_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MACS_ID__c</fullName>
        <formula>Agency__r.MACS_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MACS ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Deputy Chief of Administration Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Rate Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Rate_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Rate Agreement</label>
        <referenceTo>Agency_Rate_Agreement__c</referenceTo>
        <relationshipLabel>Agency Rate Agreement Line Items</relationshipLabel>
        <relationshipName>Agency_Rate_Agreement_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MOU_MOA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MOU/MOA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PTP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PTP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Rate Agreement Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreement Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_DeniedAgreementPDFCtrl.cls
public without sharing class MARS_DeniedAgreementPDFCtrl {
    public String signature {get; set;}
    public Agency_Rate_Agreement__c  agency_Rate_Agreement {get; set;}
    public Datetime CurrentDateTime { get;set;}

    public MARS_DeniedAgreementPDFCtrl() {
        Datetime now = Datetime.now(); 
        Integer offset = UserInfo.getTimezone().getOffset(now); 
        CurrentDateTime = now.addSeconds(offset/1000);
        
        agency_Rate_Agreement = [SELECT Id, Start_Date__c, End_Date__c,Approval_Status__c, Name,Agreement_Type__c, Agency__r.MACS_ID__c,Agency__r.Name,CreatedBy.Name,Reject_Reason__c,
            (SELECT Id, Name,Start_Date__c,End_Date__c,OT__c,
            MOU_MOA__c,PTP__c, Status__c
            FROM Agency_Rate_Agreement_Line_Items__r) FROM Agency_Rate_Agreement__c WHERE Id =:ApexPages.currentPage().getParameters().get('id')];

        List<ContentVersion> signDco = getContentVersions(new List<String>{ApexPages.currentPage().getParameters().get('id')});
        if(signDco.size() > 0)
            signature ='/sfc/servlet.shepherd/version/download/'+signDco[0].Id;

    }
    private static List<ContentVersion> getContentVersions(List<String> recordIds) {

        Set<Id> contentDocIds = new Set<Id>();
        // added dynamic query due to weired issue with static query - ContentDocumentLink requires a filter by a single Id on ContentDocumentId or LinkedEntityId using the equals operator or multiple Id's using the IN operator.
        String query = 'SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId in(\'' + String.join(recordIds, '\',\'') + '\')';
        for(ContentDocumentLink contentDocLink : Database.query(query)) {
            contentDocIds.add(contentDocLink.ContentDocumentId);
        }
        return [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
        from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true AND Title LIKE 'Signature%' order by ContentModifiedDate desc];
    }
}