codepkg/objects/Agency_Salary_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Salary Surveys</relationshipLabel>
        <relationshipName>Agency_Salary_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Agency Salary Survey</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Salary Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_AgencySalarySurveyCtrl_Test.cls
@isTest
public class MARS_AgencySalarySurveyCtrl_Test {
 @isTest
  static void testAgencySalarySurvey(){
      	Account acc = new Account();
        acc.Name = 'test';
        insert acc;
        
        Agency_Salary_Survey__c salarySurvey = new Agency_Salary_Survey__c();
        salarySurvey.Account__c = acc.Id;
        salarySurvey.Status__c = 'Reviewed';
        insert salarySurvey;
        
 		 ContentVersion cv = MARS_TestHelper.getContentVersion();
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = salarySurvey.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        PageReference testPage = Page.MARS_AgencySalarySurveyPDF; 
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', String.valueOf(salarySurvey.Id));
        MARS_AgencySalarySurveyCtrl testObject = new MARS_AgencySalarySurveyCtrl(); 
  }
}