codepkg/objects/Agency_Salary_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Salary Surveys</relationshipLabel>
        <relationshipName>Agency_Salary_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Salary Survey</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Salary Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Salary_Survey_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Salary_Survey__c</fullName>
        <label>Agency Salary Survey</label>
        <referenceTo>Agency_Salary_Survey__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Are_you_adding_WC_UI__c</fullName>
        <label>Are you adding WC/UI?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Base_Rates__c</fullName>
        <label>Base Rates</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MOU_MOA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MOU/MOA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P_T_P__c</fullName>
        <defaultValue>false</defaultValue>
        <label>P-T-P</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate(ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WC_and_or_UI__c</fullName>
        <label>Is Revised Rate is Same as Base Rate ?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salary Survey Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salary Survey Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/MARS_SalarySurveyHistoryCtrl_Test.cls
@isTest
private class MARS_SalarySurveyHistoryCtrl_Test {
    @isTest
    static void createRecData(){
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
        
        Agency_Salary_Survey__c agSalSurvey = new Agency_Salary_Survey__c();
        agSalSurvey.Account__c = acc.Id;
        agSalSurvey.Name = 'Salary survey test';
        insert agSalSurvey;
        
        Salary_Survey_Line_Items__c agSalSurveyLI = new Salary_Survey_Line_Items__c();
        agSalSurveyLI.Agency_Salary_Survey__c = agSalSurvey.Id;
        agSalSurveyLI.Classification_Title__c = 'Chief';
        agSalSurveyLI.Base_Rates__c=27.14;
        agSalSurveyLI.WC_and_or_UI__c='Yes';
        agSalSurveyLI.Are_you_adding_WC_UI__c='No'; 
        agSalSurveyLI.Current_Rate__c=27.14;
        agSalSurveyLI.Revised_Rate__c=27.14; 
        agSalSurveyLI.MOU_MOA__c=false;
        agSalSurveyLI.P_T_P__c=true;
        insert agSalSurveyLI;
        
        MARS_SalarySurveyHistoryCtrl.getAgencySalarySurveyHistory(acc.Id);
        MARS_SalarySurveyHistoryCtrl.getData(agSalSurvey.Id);
    }
}