codepkg/objects/Agency_Special_Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Special Equipments</relationshipLabel>
        <relationshipName>Agency_Special_Equipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Agency Special Equipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_SpecialEquipment_PDF_Test.cls
@isTest
public without sharing class MARS_SpecialEquipment_PDF_Test {
    static testmethod void simpleTests(){
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
        
        Agency_Special_Equipment__c spEquip = new Agency_Special_Equipment__c();
        spEquip.Agency__c = acc.Id;
        spEquip.Approval_Status__c = 'Reviewed';
        insert spEquip;
 		ContentVersion cv = MARS_TestHelper.getContentVersion();
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = spEquip.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        PageReference testPage = Page.MARS_AdministrativeRate_PDF; 
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', String.valueOf(spEquip.Id));
        MARS_SpecialEquipment_PDF test = new MARS_SpecialEquipment_PDF();
    } 
}