codepkg/objects/Agency_Special_Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Special Equipments</relationshipLabel>
        <relationshipName>Agency_Special_Equipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Special Equipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Special_Equipment_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Special_Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Special Equipment</label>
        <referenceTo>Agency_Special_Equipment__c</referenceTo>
        <relationshipLabel>Agency Special Equipment Line Items</relationshipLabel>
        <relationshipName>Agency_Special_Equipment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEMA_CODE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>FEMA CODE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Special_Equipment_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agency Special Equipment Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipment Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/FEMA_Code__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>FEMA Code</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FEMA Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARSSpecialEquipmentScreenCtrl_Test.cls
@isTest
private class MARSSpecialEquipmentScreenCtrl_Test {
    @isTest
    static void test(){
        Account testAccount = MARS_TestHelper.getAccount(true);
        Agency_Special_Equipment_Line_Item__c agenSpeEquipLI = new Agency_Special_Equipment_Line_Item__c();
        agenSpeEquipLI.Special_Equipment_Type__c = 'testAgenSpeEquip';
        agenSpeEquipLI.Description__c = 'test';
        agenSpeEquipLI.FEMA_CODE__c = '1234';
        agenSpeEquipLI.Revised_Rate__c = 10;
        List<Agency_Special_Equipment_Line_Item__c> lineItemsForUpdateList = new List<Agency_Special_Equipment_Line_Item__c>();
        lineItemsForUpdateList.add(agenSpeEquipLI);
        String data = JSON.serialize(lineItemsForUpdateList);
        String effDate = String.valueOf(Date.today());
        String searchTerm = 'testFEMACodeLI';
        List<String> salId = new List<String>{'', ''};
        MARSSpecialEquipmentScreenCtrl.getSpecialEquipmentLatest(testAccount.Id);
        //MARSSpecialEquipmentScreenCtrl.getSpecialEquipmentLineItems(agenSpecEqp.Id);
        MARSSpecialEquipmentScreenCtrl.getData(testAccount.Id);
        MARSSpecialEquipmentScreenCtrl.apexSearchFemaCode(searchTerm, salId);
        MARSSpecialEquipmentScreenCtrl.submitSpecEquipLines(data, testAccount.Id, effDate, 'test');
    }
    @isTest
    static void test1(){
        Account testAccount = MARS_TestHelper.getAccount(true);
        Agency_Special_Equipment__c agenSpeEquip = new Agency_Special_Equipment__c();
        agenSpeEquip.Name = 'testAgenSpeEquip';
        agenSpeEquip.Agency__c = testAccount.Id;
        agenSpeEquip.Approval_Status__c = 'Pending Review';
        agenSpeEquip.Start_Date__c = Date.today();
        agenSpeEquip.End_Date__c = Date.today().addDays(10);
        agenSpeEquip.Reject_Reason__c = 'test';
        insert agenSpeEquip;
        
        Agency_Special_Equipment_Line_Item__c agenSpeEquipLI = new Agency_Special_Equipment_Line_Item__c();
        agenSpeEquipLI.Agency_Special_Equipment__c = agenSpeEquip.Id;
        agenSpeEquipLI.Special_Equipment_Type__c = 'testAgenSpeEquip';
        agenSpeEquipLI.Description__c = 'test';
        agenSpeEquipLI.FEMA_CODE__c = '1234';
        agenSpeEquipLI.Revised_Rate__c = 10;
        insert agenSpeEquipLI;
        MARSSpecialEquipmentScreenCtrl.getSpecialEquipmentLineItems(agenSpeEquip.Id);

    }
}