codepkg/objects/Agency_Admin_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Administrative_Rates__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Administrative Rates</label>
        <referenceTo>Agency_Admin_Rates__c</referenceTo>
        <relationshipLabel>Agency Admin Line Items</relationshipLabel>
        <relationshipName>Agency_Admin_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Admin Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Admin Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Admin_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agency Administrative Rates</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Administrative Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Administrative Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Non_Suppression_Personnel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Non-Suppression Personnel</label>
        <referenceTo>Agency_Non_Suppression_Personnel__c</referenceTo>
        <relationshipLabel>Agency Non-Suppression Line Items</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate (ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Non-Suppression Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Personnel__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agency Non-Suppression Personnel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Deputy Chief of Administration Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agency Rate Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Rate_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Rate Agreement</label>
        <referenceTo>Agency_Rate_Agreement__c</referenceTo>
        <relationshipLabel>Agency Rate Agreement Line Items</relationshipLabel>
        <relationshipName>Agency_Rate_Agreement_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Rate Agreement Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreement Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Salary_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Agency Salary Survey</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Salary Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Special_Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agency Special Equipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Special_Equipment_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Special_Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Special Equipment</label>
        <referenceTo>Agency_Special_Equipment__c</referenceTo>
        <relationshipLabel>Agency Special Equipment Line Items</relationshipLabel>
        <relationshipName>Agency_Special_Equipment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Special_Equipment_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Special Equipment Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipment Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Salary_Survey_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Salary_Survey__c</fullName>
        <label>Agency Salary Survey</label>
        <referenceTo>Agency_Salary_Survey__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Base_Rates__c</fullName>
        <label>Base Rates</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate(ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Special_Equipment_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WC_and_or_UI__c</fullName>
        <label>Is Revised Rate is Same as Base Rate ?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salary Survey Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salary Survey Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/MARSAgencyController.cls
public
class MARSAgencyController {
  @AuraEnabled public static Boolean updateTheParentToApproved(
      String salaryId) {
    try {
      Id sObjectID = (salaryId != null ? Id.valueOf(salaryId) : null);
      String sObjName = sObjectID.getSObjectType().getDescribe().getName();
      if (sObjName == 'Agency_Salary_Survey__c') {
        Agency_Salary_Survey__c ass = new Agency_Salary_Survey__c();
        ass.Id = salaryId;
        ass.Status__c = 'Approved';
        update ass;
        MARSSalarySurveyHelper.updateRelatedSurveyLineItemsToActive(
            new Set<Id>{salaryId});
        return true;
      } else if (sObjName == 'Agency_Special_Equipment__c') {
        Agency_Special_Equipment__c ase = new Agency_Special_Equipment__c();
        ase.Id = salaryId; 
        ase.Approval_Status__c = 'Approved';
        update ase;
        updateRelatedSurveyLineItemsToActive(
            new Set<Id>{salaryId});
        return true;
      } else if (sObjName == 'Agency_Non_Suppression_Personnel__c') {
        Agency_Non_Suppression_Personnel__c ase =
            new Agency_Non_Suppression_Personnel__c();
        ase.Id = salaryId;
        ase.Approval_Status__c = 'Approved';
        update ase;
        MARSNonSuppressionPersnlHelper.updateRelatedSurveyLineItemsToActive(
            new Set<Id>{salaryId});
        return true;
      } else if (sObjName == 'Agency_Rate_Agreement__c') {
        Agency_Rate_Agreement__c ase = new Agency_Rate_Agreement__c();
        ase.Id = salaryId;
        ase.Approval_Status__c = 'Approved';
        update ase;
        MarsAgencyRateAgreementHelper.updateRelatedSurveyLineItemsToActive(
            new Set<Id>{salaryId});
      } else if (sObjName == 'Agency_Admin_Rates__c') {
        Agency_Admin_Rates__c ase = new Agency_Admin_Rates__c();
        ase.Id = salaryId;
        ase.Approval_Status__c = 'Approved';
        update ase;
        MARSAdministrativeRateHelper.updateRelatedSurveyLineItemsToActive(
            new Set<Id>{salaryId});
      }

    } catch (exception e) {
      return false;
    }
    return false;
  }

  /*@AuraEnabled public static Boolean checkingExistingStatus(String salaryId) {
    String currentStatus =
        [ Select Id, Status__c from Agency_Salary_Survey__c where Id
          =:salaryId LIMIT 1 ]
            .Status__c;
    system.debug('===========' + currentStatus);
    if (currentStatus != 'Pending for Approval') {
      return true;
    } else {
      return false;
    }
  }*/

  @AuraEnabled public static Boolean updateTheParentToExpired(String salaryId,String rejectReason) {
    try {
      Id sObjectID = (salaryId != null ? Id.valueOf(salaryId) : null);
      String sObjName = sObjectID.getSObjectType().getDescribe().getName();
      if (sObjName == 'Agency_Salary_Survey__c') {
        Agency_Salary_Survey__c ass = new Agency_Salary_Survey__c();
        ass.Id = salaryId;
        ass.Status__c = 'Expired';
        ass.Reject_Reason__c=rejectReason;
        update ass;
        List<Salary_Survey_Line_Items__c> updateSsli =
            new List<Salary_Survey_Line_Items__c>();
        for (Salary_Survey_Line_Items__c ssli :
             [ SELECT Id, Base_Rates__c, WC_and_or_UI__c, Current_Rate__c,
               Revised_Rate__c,
               Status__c from Salary_Survey_Line_Items__c WHere
                   Agency_Salary_Survey__c
               =:salaryId and Status__c != 'Expired' ]) {
          System.debug('###: ssli: ' + ssli);

          ssli.WC_and_or_UI__c = 'No';
          ssli.Current_Rate__c = ssli.Revised_Rate__c;
          ssli.Revised_Rate__c = null;
          ssli.Status__c = 'Expired';
          updateSsli.add(ssli);
        }
        System.debug('### updateSsli: ' + updateSsli);
        Database.update(updateSsli, true);
        return true;
      } else if (sObjName == 'Agency_Special_Equipment__c') {
        Agency_Special_Equipment__c ase = new Agency_Special_Equipment__c();
        ase.Id = salaryId;
        ase.Approval_Status__c = 'Expired';
        ase.Reject_Reason__c=rejectReason;
        update ase;
        List<Agency_Special_Equipment_Line_Item__c> updateSsli =
            new List<Agency_Special_Equipment_Line_Item__c>();
        for (Agency_Special_Equipment_Line_Item__c ssli :
             [ SELECT Id, Current_Rate__c, Effective_Date__c, Revised_Rate__c,
               Special_Equipment_Type__c from
                   Agency_Special_Equipment_Line_Item__c WHERE
                       Agency_Special_Equipment__c
               =:salaryId and Status__c != 'Expired' ]) {
          ssli.Status__c = 'Expired';
          updateSsli.add(ssli);
        }
        Database.update(updateSsli, true);
        return true;
      } else if (sObjName == 'Agency_Non_Suppression_Personnel__c') {
        Agency_Non_Suppression_Personnel__c ase =
            new Agency_Non_Suppression_Personnel__c();
        ase.Id = salaryId;
        ase.Approval_Status__c = 'Expired';
        ase.Reject_Reason__c=rejectReason;
        update ase;
        List<Agency_Non_Suppression_Line_Item__c> updateSsli =
            new List<Agency_Non_Suppression_Line_Item__c>();
        for (Agency_Non_Suppression_Line_Item__c ssli :
             [ SELECT Id, Status__c from Agency_Non_Suppression_Line_Item__c
                              WHere Agency_Non_Suppression_Personnel__c
               =:salaryId and Status__c != 'Expired' ]) {
          System.debug('###: ssli: ' + ssli);
          ssli.Status__c = 'Expired';
          updateSsli.add(ssli);
        }
        Database.update(updateSsli, true);
        return true;
      } else if (sObjName == 'Agency_Rate_Agreement__c') {
        Agency_Rate_Agreement__c ase = new Agency_Rate_Agreement__c();
        ase.Id = salaryId;
        ase.Approval_Status__c = 'Expired';
        ase.Reject_Reason__c=rejectReason;
        update ase;
        List<Agency_Rate_Agreement_Line_Item__c> updateSsli =
            new List<Agency_Rate_Agreement_Line_Item__c>();
        for (Agency_Rate_Agreement_Line_Item__c ssli :
             [ SELECT Id, Status__c from Agency_Rate_Agreement_Line_Item__c
                              WHere Agency_Rate_Agreement__c
               =:salaryId and Status__c != 'Expired' ]) {
          System.debug('###: ssli: ' + ssli);
          ssli.Status__c = 'Expired';
          updateSsli.add(ssli);
        }
        Database.update(updateSsli, true);
        return true;
      } else if (sObjName == 'Agency_Admin_Rates__c') {
        Agency_Admin_Rates__c ase = new Agency_Admin_Rates__c();
        ase.Id = salaryId;
        ase.Approval_Status__c = 'Expired';
        ase.Reject_Reason__c=rejectReason;
        update ase;
        List<Agency_Admin_Line_Items__c> updateSsli =
            new List<Agency_Admin_Line_Items__c>();
        for (Agency_Admin_Line_Items__c ssli :
             [ SELECT Id, Status__c from Agency_Admin_Line_Items__c WHere
                              Agency_Administrative_Rates__c
               =:salaryId and Status__c != 'Expired' ]) {
          System.debug('###: ssli: ' + ssli);
          ssli.Status__c = 'Expired';
          updateSsli.add(ssli);
        }
        Database.update(updateSsli, true);
        return true;
      }
    } catch (exception e) {
      return false;
    }
    return false;
  }

  public static void updateRelatedSurveyLineItemsToActive(Set<Id> approvedAgencySurveyList) {
    List<Agency_Special_Equipment_Line_Item__c> updateSsli = new List<Agency_Special_Equipment_Line_Item__c>();
    for (Agency_Special_Equipment_Line_Item__c ssli :
         [ SELECT Id,Current_Rate__c, Revised_Rate__c, Status__c
          from Agency_Special_Equipment_Line_Item__c WHere Agency_Special_Equipment__c IN: approvedAgencySurveyList]){
              System.debug('###: ssli: ' + ssli);
              ssli.Current_Rate__c = ssli.Revised_Rate__c;
              ssli.Revised_Rate__c = null;
              ssli.Status__c = 'Active';
              updateSsli.add(ssli);
          }
    System.debug('### updateSsli: ' + updateSsli);
    Database.update(updateSsli, true);
}
}