codepkg/objects/Agency_Salary_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Salary Surveys</relationshipLabel>
        <relationshipName>Agency_Salary_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Admin_Rate__c</fullName>
        <label>Actual Admin Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>END_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revised_From_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Revised From Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_as_Base_Rate_Count__c</fullName>
        <description>This field gives a count of Line item records that have the same as base rate</description>
        <label>Same as Base Rate Count</label>
        <summaryFilterItems>
            <field>Salary_Survey_Line_Items__c.WC_and_or_UI__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </summaryFilterItems>
        <summaryForeignKey>Salary_Survey_Line_Items__c.Agency_Salary_Survey__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unemployment_Insurance_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unemployment Insurance Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Workers_Comp_Insurance_Rate__c</fullName>
        <label>Workers Comp Insurance Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Salary Survey</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Salary Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/CFAA__c.object
<CustomObject>
    <fields>
        <fullName>CFAA_Processed_for_Salary_Surveys__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates that after the creation of new CFAA records, batch job is run to make sure copies of Salary Survey records are created and new CFAA rates are applied</description>
        <label>CFAA Processed for Salary Surveys</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>END_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>CFAA Rate Letter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CFAA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CFAA Rate Letter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/CFAA_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>CFAA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA</label>
        <referenceTo>CFAA__c</referenceTo>
        <relationshipLabel>CFAA Line Items</relationshipLabel>
        <relationshipName>CFAA_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Over_Time_Rate__c</fullName>
        <label>Over Time Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personnel_Role__c</fullName>
        <label>Personnel Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chief</fullName>
                </value>
                <value>
                    <fullName>Deputy Chief</fullName>
                </value>
                <value>
                    <fullName>Division Chief</fullName>
                </value>
                <value>
                    <fullName>Assistant Chief</fullName>
                </value>
                <value>
                    <fullName>Battalion Chief</fullName>
                </value>
                <value>
                    <fullName>Co. Officer/Capt./Lt.</fullName>
                </value>
                <value>
                    <fullName>App. Officer/Eng</fullName>
                </value>
                <value>
                    <fullName>Firefighter/FF-PMedic</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Straight_Time_Rate__c</fullName>
        <label>Straight Time Rate</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>CFAA Line Item</label>
    <nameField>
        <label>CFAA Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CFAA Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Salary_Survey_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Salary_Survey__c</fullName>
        <label>Agency Salary Survey</label>
        <referenceTo>Agency_Salary_Survey__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Are_you_adding_WC_UI__c</fullName>
        <label>Are you adding WC/UI?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Base_Rates__c</fullName>
        <label>Base Rates</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CFAA_Line_Items__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA Line Item</label>
        <referenceTo>CFAA_Line_Items__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CFAA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA</label>
        <referenceTo>CFAA__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Line_Item_Type__c</fullName>
        <label>Line Item Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personnel</fullName>
                </value>
                <value>
                    <fullName>Special Equipment</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Resource Agreements</fullName>
                </value>
                <value>
                    <fullName>Non-Supression</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate(ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WC_and_or_UI__c</fullName>
        <label>Is Revised Rate is Same as Base Rate ?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salary Survey Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salary Survey Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/MARS_CFAAProcessing_Batch.cls
public with sharing class MARS_CFAAProcessing_Batch implements Database.Batchable<sObject>{
    public string CFAArecId;
    Public CFAA__c cfaa;

    public Database.QueryLocator start(Database.BatchableContext BC) {
        if(string.isBlank(cfaarecId)){
            throw new IllegalArgumentException('CFAArecId must not be null. You must pass a CFAA record Id that should be base for creating salary surveys');
        }
        cfaa = [SELECT Id, Start_Date__c FROM CFAA__c WHERE Id =:CFAArecId LIMIT 1 ];
        return Database.getQueryLocator([SELECT Id, Name, Account__c, Account__r.Macs_Id__c, Start_Date__c, END_Date__c, Status__c,
                                        Revised_From_Id__c, Unemployment_Insurance_Rate__c, Workers_Comp_Insurance_Rate__c,
                                        Actual_Admin_Rate__c, Same_as_Base_Rate_Count__c,
                                        (SELECT Id,Agency_Salary_Survey__c, Base_Rates__c, Classification_Title__c, 
                                        Line_Item_Type__c, Are_you_adding_WC_UI__c, WC_and_or_UI__c,Current_Rate__c,
                                        Revised_Rate__c FROM Salary_Survey_Line_Items__r)
                                        FROM Agency_Salary_Survey__c
                                        WHERE (end_date__c = null or (end_date__c >= :cfaa.Start_Date__c))
                                        AND Status__c != 'Rejected'
                                        AND Same_as_Base_Rate_Count__c	> 0
                                        
                                    ]);
                                        
    }
    
    public void execute(Database.BatchableContext BC, List<Agency_Salary_Survey__c> scope) {
        list<Agency_Salary_Survey__c> surveysToCreate = new list<Agency_Salary_Survey__c>();
        list<Agency_Salary_Survey__c> surveysToClone = new list<Agency_Salary_Survey__c>();
        list<Agency_Salary_Survey__c> surveysToUpdate = new list<Agency_Salary_Survey__c>();
        list<Salary_Survey_Line_Items__c> lineItemstoCreate = new list<Salary_Survey_Line_Items__c>();
        map<string,CFAA_Line_Items__c> CFAAtitletoRateMap = new map<string,CFAA_Line_Items__c>();
        map<string,list<Salary_Survey_Line_Items__c>> lineitemsMap = new map<string, list<Salary_Survey_Line_Items__c>>();
        map<string,string> newSurveysIdMap = new map<string,string>();
        list<Salary_Survey_Line_Items__c> lineItemstoUpdate = new list<Salary_Survey_Line_Items__c>();
		cfaa = [SELECT Id, Start_Date__c FROM CFAA__c WHERE Id =:CFAArecId LIMIT 1 ];

        list<CFAA_Line_Items__c> newCFAAitems = [SELECT Id, Name, Personnel_Role__c, Straight_Time_Rate__c, 
                                                        CFAA__r.Start_Date__c, Over_Time_Rate__c
                                                 FROM CFAA_Line_Items__c 
                                                 WHERE CFAA__c = :CFAArecId];
        for(CFAA_Line_Items__c cf: newCFAAitems){
            CFAAtitletoRateMap.put(cf.Personnel_Role__c, cf);
        }

        Date endDate = newCFAAitems[0].CFAA__r.Start_Date__c.addDays(-1);
        Date startDatefornewSalary  = newCFAAitems[0].CFAA__r.Start_Date__c;
        Agency_Salary_Survey__c newSurvey;

        for(Agency_Salary_Survey__c survey: scope){
            //identify the salary survey records that need a clone of line items
            if(survey.Start_Date__c <= cfaa.Start_Date__c && (survey.End_Date__c == null || survey.End_Date__c >= cfaa.start_Date__c)){
                newSurvey = new Agency_Salary_Survey__c();
                newSurvey = survey.clone(false, false, false, false);
                newSurvey.Revised_From_Id__c = survey.Id;
                newSurvey.Name = 'Salary Survey for Agency '+survey.Account__r.Macs_Id__c+' '+startDatefornewSalary;
                newSurvey.Start_Date__c = startDatefornewSalary;
                surveysToCreate.add(newSurvey);
                lineitemsMap.put(survey.Id, survey.Salary_Survey_Line_Items__r);

                surveysToUpdate.add(new Agency_Salary_Survey__c(Id=survey.Id, 
                                                                Status__c = 'Revised',
                                                                End_Date__c = endDate)
                                                              );//since we are cloning a copy for the new period, existing surveys should be marked as Revised
                                                            //If end date is in the past, Automated flow will set it to Expired
            } 

            //identify the surveys where lineitems data have to be updated without touching the actual salary survey
            if(survey.Start_Date__c > cfaa.Start_Date__c || survey.Start_Date__c == null){
                lineItemstoUpdate.addAll(survey.Salary_Survey_Line_Items__r);
            }
        }
        update surveysToUpdate;
        insert surveysToCreate;

        for(Agency_Salary_Survey__c survey: surveysToCreate){
            newSurveysIdMap.put(survey.Revised_From_Id__c, survey.Id);
        }

        for(Salary_Survey_Line_Items__c li: lineItemstoUpdate){
            if(CFAAtitletoRateMap.containsKey(li.Classification_Title__c)){
                li.Base_Rates__c = CFAAtitletoRateMap.get(li.Classification_Title__c).Straight_Time_Rate__c;
            }
            if(li.WC_and_or_UI__c == 'Yes' && li.Are_you_adding_WC_UI__c == 'No' && CFAAtitletoRateMap.containsKey(li.Classification_Title__c)){
                li.Revised_Rate__c =  CFAAtitletoRateMap.get(li.Classification_Title__c).Straight_Time_Rate__c;
                li.CFAA_Line_Items__c = CFAAtitletoRateMap.get(li.Classification_Title__c).Id;
            }
        }

        update lineItemstoUpdate;
        
        Salary_Survey_Line_Items__c lineItem;
        for(string surveyId: lineitemsMap.keySet()){
            for(Salary_Survey_Line_Items__c li: lineitemsMap.get(surveyId)){
                lineItem = new Salary_Survey_Line_Items__c();
                lineItem = li.clone(false, false, false, false);
                lineitem.Agency_Salary_Survey__c = newSurveysIdMap.get(surveyId);
                lineitem.CFAA__c = CFAArecId;
                lineItem.CFAA_Line_Items__c = null;
                if(CFAAtitletoRateMap.containsKey(li.Classification_Title__c)){
                    lineitem.Base_Rates__c = CFAAtitletoRateMap.get(li.Classification_Title__c).Straight_Time_Rate__c;
                }
                if(li.WC_and_or_UI__c == 'Yes' && li.Are_you_adding_WC_UI__c == 'No' && CFAAtitletoRateMap.containsKey(li.Classification_Title__c)){
                    lineitem.Revised_Rate__c =  CFAAtitletoRateMap.get(li.Classification_Title__c).Straight_Time_Rate__c;
                    lineItem.CFAA_Line_Items__c = CFAAtitletoRateMap.get(li.Classification_Title__c).Id;
                }
                lineItemstoCreate.add(lineItem);
            }

        }
        insert lineItemstoCreate;
        
    }   
    
    public void finish(Database.BatchableContext BC) {
        update new CFAA__c(Id=CFAArecId, CFAA_Processed_for_Salary_Surveys__c = true);
        AsyncApexJob job = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors FROM AsyncApexJob WHERE ID = :BC.getJobId() ];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId(Userinfo.getUserId());
        mail.setSaveAsActivity(false);
        mail.subject = 'CFAA Processing for Salary Survey Creation Job is Completed';
        mail.plainTextBody = 'Batch job is completed. Total job items are '+job.TotalJobitems+' Number of Errors '+ job.NumberOfErrors;
        
        Messaging.sendEmail(new list<Messaging.SingleEmailMessage>{mail});
    }
    	
}