codepkg/objects/Agency_Admin_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Administrative_Rates__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Administrative Rates</label>
        <referenceTo>Agency_Admin_Rates__c</referenceTo>
        <relationshipLabel>Agency Admin Line Items</relationshipLabel>
        <relationshipName>Agency_Admin_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Admin Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Admin Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Admin_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Administrative Rates</relationshipLabel>
        <relationshipName>Agency_Administrative_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Agency Administrative Rates</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Administrative Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Administrative Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_AdministrativeRateCtrl_Test.cls
@isTest
private class MARS_AdministrativeRateCtrl_Test {
    @isTest
    static void test(){
       Id profileId = [Select Id From Profile Where Name ='CalOES Portal User'].Id;
         Account acct = TestUtility.createAccount('test');
        
        Contact cont = TestUtility.createContact('test', 'tes', 'test@gmail.vom', acct.Id);
        User u = TestUtility.createCommunityUser(cont.Id, profileId, 'Amit', 'Singh');
        //PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'MARS Community User'];
		//insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        
        AccountContactRelation acr = [SELECT AccountId,ContactId FROM AccountContactRelation WHERE AccountId = :acct.Id AND ContactId = :cont.Id];
      
        acr.Relationship_Strength__c = 'Strong';
        update acr;
        
        Agency_Admin_Rates__c agAdmRate = new Agency_Admin_Rates__c();
        agAdmRate.Agency__c = acct.Id;
        agAdmRate.Name = 'testAgAdmRate';
        agAdmRate.Approval_Status__c = MARS_Constants.SURVEY_STATUS_PENDING_REVIEW;
        //insert agAdmRate;
        String objParentData = JSON.serialize(agAdmRate);
        
        Agency_Admin_Line_Items__c agAdmRateLI = new Agency_Admin_Line_Items__c();
        agAdmRateLI.Agency_Administrative_Rates__c = agAdmRate.Id;
        agAdmRateLI.Name = 'Telecommunications';
        //insert agAdmRateLI;
        List<Agency_Admin_Line_Items__c> agAdmRateLILst = [SELECT Id FROM Agency_Admin_Line_Items__c WHERE Agency_Administrative_Rates__c = :agAdmRate.Id];
        String lineItemsString = JSON.serialize(agAdmRateLILst);
        
        System.runAs(u){
            MARS_AdministrativeRateCtrl.retrivePrograms(acct.Id);
            String effDate = String.valueOf(System.today());
          // MARS_AdministrativeRateCtrl.createLineItems(lineItemsString, acr.Id, effDate, '', objParentData);
           MARS_AdministrativeRateCtrl.createLineItems(lineItemsString, acct.Id, effDate, '', objParentData);
          // MARS_AdministrativeRateCtrl.createLineItems(lineItemsString, '', effDate, '', objParentData);
        }
    }
    
    
}