codepkg/objects/Agency_Salary_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Salary Surveys</relationshipLabel>
        <relationshipName>Agency_Salary_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Admin_Rate__c</fullName>
        <label>Actual Admin Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>END_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsArchive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Archive?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revised_From_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Revised From Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unemployment_Insurance_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unemployment Insurance Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Workers_Comp_Insurance_Rate__c</fullName>
        <label>Workers Comp Insurance Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Salary Survey</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Salary Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/CFAA__c.object
<CustomObject>
    <fields>
        <fullName>END_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>CFAA Rate Letter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CFAA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CFAA Rate Letter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/CFAA_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>CFAA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA</label>
        <referenceTo>CFAA__c</referenceTo>
        <relationshipLabel>CFAA Line Items</relationshipLabel>
        <relationshipName>CFAA_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personnel Base Rates</fullName>
                </value>
                <value>
                    <fullName>Support Equipment Rates</fullName>
                </value>
                <value>
                    <fullName>Emergency Apparatus Rates</fullName>
                </value>
                <value>
                    <fullName>Privately Owned Vehicle (POV) Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CFAA Line Item</label>
    <nameField>
        <label>CFAA Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CFAA Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Salary_Survey_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Salary_Survey__c</fullName>
        <label>Agency Salary Survey</label>
        <referenceTo>Agency_Salary_Survey__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Base_Rates__c</fullName>
        <label>Base Rates</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CFAA_Line_Items__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA Line Item</label>
        <referenceTo>CFAA_Line_Items__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CFAA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA</label>
        <referenceTo>CFAA__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Classification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_Item_Type__c</fullName>
        <label>Line Item Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personnel</fullName>
                </value>
                <value>
                    <fullName>Special Equipment</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Resource Agreements</fullName>
                </value>
                <value>
                    <fullName>Non-Supression</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revised_Rate__c</fullName>
        <label>Salary Rate(ST)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Rate FILLABLE</fullName>
                </value>
                <value>
                    <fullName>Non-Suppression Personnel - FILLABLE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WC_and_or_UI__c</fullName>
        <label>Is Revised Rate is Same as Base Rate ?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salary Survey Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salary Survey Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/MARSSalarySurveyHelper.cls
/***********************************************************************************************************************************
 * Class Name   : SalarySurveyHelper
 * Description  : This is Helper class for SalarySurveyTrigger
 * Author       : Aneesha
 * Created On   : 03/14/2020
 * Modification Log:
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Developer             Date             Description
 * ---------------------------------------------------------------------------------------------------------------------------------------
 * Aneesha                03/14/2020       Initial Implementation
 **************************************************************************************************************************************/
public without sharing
class MARSSalarySurveyHelper{
    //using this approval controller
    public static void updateRelatedSurveyLineItemsToActive(Set<Id> approvedAgencySurveyList) {
        List<Salary_Survey_Line_Items__c> updateSsli = new List<Salary_Survey_Line_Items__c>();
        for (Salary_Survey_Line_Items__c ssli :
         [ SELECT Id, Base_Rates__c, WC_and_or_UI__c, Current_Rate__c, Revised_Rate__c, Status__c
           from Salary_Survey_Line_Items__c WHere Agency_Salary_Survey__c IN: approvedAgencySurveyList]){
               System.debug('###: ssli: ' + ssli);
             
             ssli.WC_and_or_UI__c = 'No';
               ssli.Current_Rate__c = ssli.Revised_Rate__c; 
               ssli.Revised_Rate__c = null;
               ssli.Status__c = 'Active';
              updateSsli.add(ssli);
          }
        System.debug('### updateSsli: ' + updateSsli);
        Database.update(updateSsli, true);
    }

  public static void cloneTheSurveyLineItems(Id surveyId) {
    Map<Id, List<Salary_Survey_Line_Items__c>> surveyWithLineItems =
        new Map<Id, List<Salary_Survey_Line_Items__c>>();
    List<Agency_Salary_Survey__c> updateAgencySurvey =
        new List<Agency_Salary_Survey__c>();
    List<Agency_Salary_Survey__c> InsertAgencySurvey =
        new List<Agency_Salary_Survey__c>();
    for (Agency_Salary_Survey__c assc :
         [ SELECT Id, Status__c, Account__c, Start_Date__c, END_Date__c,
           Actual_Admin_Rate__c, Workers_Comp_Insurance_Rate__c,
           Unemployment_Insurance_Rate__c, Revised_From_Id__c,
           (SELECT Id, Account__c, Base_Rates__c, CFAA__c, CFAA_Line_Items__c,
            Classification_Title__c, Current_Rate__c, Effective_Date__c,
            WC_and_or_UI__c, Line_Item_Type__c, Revised_Rate__c,
            Type__c from Salary_Survey_Line_Items__r)
               FROM Agency_Salary_Survey__c WHERE Id =: surveyId ]) {
      surveyWithLineItems.put(assc.id, assc.Salary_Survey_Line_Items__r);
      Agency_Salary_Survey__c aupdate = new Agency_Salary_Survey__c();
      aupdate.Id = assc.Id;
      aupdate.END_Date__c = System.today();
      aupdate.Status__c = 'Expired';
      aupdate.IsArchive__c = true;
      updateAgencySurvey.add(aupdate);
      // Inserting new Parent
      Agency_Salary_Survey__c ainsert = new Agency_Salary_Survey__c();
      ainsert.Name = 'Salary Survey For Agency :' + system.now();
      ainsert.Account__c = assc.Account__c;
      ainsert.Revised_From_Id__c = assc.Id;
      ainsert.Start_Date__c = System.today();
      ainsert.Actual_Admin_Rate__c = assc.Actual_Admin_Rate__c;
      ainsert.Unemployment_Insurance_Rate__c =
          assc.Unemployment_Insurance_Rate__c;
      ainsert.Workers_Comp_Insurance_Rate__c =
          assc.Workers_Comp_Insurance_Rate__c;
      InsertAgencySurvey.add(ainsert);
    }

    if (InsertAgencySurvey.size() > 0) {
      insert InsertAgencySurvey;
      Map<Id, Id> oldwithNewId = new Map<Id, Id>();
      List<Agency_Salary_Survey__c> finalAgencySurvey =
          new List<Agency_Salary_Survey__c>();
      for (Agency_Salary_Survey__c ass : InsertAgencySurvey) {
        ass.status__c = MARS_Constants.SURVEY_STATUS_PENDING_REVIEW;
        finalAgencySurvey.add(ass);
        oldwithNewId.put(ass.Revised_From_Id__c, ass.Id);
      }
      List<Salary_Survey_Line_Items__c> insertLineItems =
          new List<Salary_Survey_Line_Items__c>();
      List<Salary_Survey_Line_Items__c> oldLineItems =
          new List<Salary_Survey_Line_Items__c>();
      for (Id parentOldSurvey : surveyWithLineItems.keySet()) {
        if (oldwithNewId.containsKey(parentOldSurvey)) {
          for (Salary_Survey_Line_Items__c ssl :
               surveyWithLineItems.get(parentOldSurvey)) {
            Salary_Survey_Line_Items__c newLineItem =
                ssl.clone(false, false, false, false);
            ssl.Status__c = 'Expired';
            oldLineItems.add(ssl);
            newLineItem.Agency_Salary_Survey__c =
                oldwithNewId.get(parentOldSurvey);
            insertLineItems.add(newLineItem);
          }
        }
      }
      try {
        insert insertLineItems;
        update oldLineItems;
        update finalAgencySurvey;
        update updateAgencySurvey;
      } catch (exception e) {
        system.debug('-------------' + e.getMessage());
      }
    }
  }
        
    
}