codepkg/objects/Agency_Admin_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Administrative_Rates__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Administrative Rates</label>
        <referenceTo>Agency_Admin_Rates__c</referenceTo>
        <relationshipLabel>Agency Admin Line Items</relationshipLabel>
        <relationshipName>Agency_Admin_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Admin Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Admin Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Admin_Rates__c.object
<CustomObject>
    <label>Agency Administrative Rates</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Administrative Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Administrative Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Non_Suppression_Personnel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Non-Suppression Personnel</label>
        <referenceTo>Agency_Non_Suppression_Personnel__c</referenceTo>
        <relationshipLabel>Agency Non-Suppression Line Items</relationshipLabel>
        <relationshipName>Agency_Non_Suppression_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Non-Suppression Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Non_Suppression_Personnel__c.object
<CustomObject>
    <label>Agency Non-Suppression Personnel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Non-Suppression Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Non-Suppression Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement__c.object
<CustomObject>
    <label>Agency Rate Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Rate_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Rate_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Rate Agreement</label>
        <referenceTo>Agency_Rate_Agreement__c</referenceTo>
        <relationshipLabel>Agency Rate Agreement Line Items</relationshipLabel>
        <relationshipName>Agency_Rate_Agreement_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Rate Agreement Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Rate Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Rate Agreement Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Salary_Survey__c.object
<CustomObject>
    <label>Agency Salary Survey</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Salary Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Special_Equipment__c.object
<CustomObject>
    <label>Agency Special Equipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Agency_Special_Equipment_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Special_Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Special Equipment</label>
        <referenceTo>Agency_Special_Equipment__c</referenceTo>
        <relationshipLabel>Agency Special Equipment Line Items</relationshipLabel>
        <relationshipName>Agency_Special_Equipment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Special Equipment Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Equipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Special Equipment Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Salary_Survey_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Salary_Survey__c</fullName>
        <label>Agency Salary Survey</label>
        <referenceTo>Agency_Salary_Survey__c</referenceTo>
        <relationshipLabel>Salary Survey Line Items</relationshipLabel>
        <relationshipName>Salary_Survey_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Salary Survey Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Salary Survey Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salary Survey Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/MARSAgencyController_Test.cls
@isTest
private class MARSAgencyController_Test {
	@testSetup
    static void createRecData(){
        //Salary Id is used as record ID.
        Agency_Salary_Survey__c ass = new Agency_Salary_Survey__c();
        ass.Name = 'testAss';
        insert ass;
        
        Salary_Survey_Line_Items__c salSurLI = new Salary_Survey_Line_Items__c();
        salSurLI.Agency_Salary_Survey__c = ass.Id;
        insert salSurLI;
        
        Agency_Special_Equipment__c ase = new Agency_Special_Equipment__c();
        ase.Name = 'testAse';
        insert ase;
        
        Agency_Special_Equipment_Line_Item__c aseLI = new Agency_Special_Equipment_Line_Item__c();
        aseLI.Agency_Special_Equipment__c = ase.Id;
        insert aseLI;
        
        Agency_Non_Suppression_Personnel__c agNonSupPer = new Agency_Non_Suppression_Personnel__c();
        agNonSupPer.Name = 'testAgNonSupPer';
        insert agNonSupPer;
        
        Agency_Non_Suppression_Line_Item__c agNonSupPerLI = new Agency_Non_Suppression_Line_Item__c();
        agNonSupPerLI.Agency_Non_Suppression_Personnel__c = agNonSupPer.Id;
        insert agNonSupPerLI;
        
        Agency_Rate_Agreement__c agRateAgr = new Agency_Rate_Agreement__c();
        agRateAgr.Name = 'testAgRateAgr';
        insert agRateAgr;
        
        Agency_Rate_Agreement_Line_Item__c agRateAgrLI = new Agency_Rate_Agreement_Line_Item__c();
        agRateAgrLI.Agency_Rate_Agreement__c = agRateAgr.Id;
        insert agRateAgrLI;
        
        Agency_Admin_Rates__c agAdmRate = new Agency_Admin_Rates__c();
        agAdmRate.Name = 'testAgAdmRate';
        insert agAdmRate;
        
        Agency_Admin_Line_Items__c agAdmRateLI = new Agency_Admin_Line_Items__c();
        agAdmRateLI.Agency_Administrative_Rates__c = agAdmRate.Id;
        insert agAdmRateLI;
    }
    
    @isTest
    static void test(){
        Agency_Salary_Survey__c ass = [SELECT Id FROM Agency_Salary_Survey__c WHERE Name = 'testAss' LIMIT 1];
        String assId = ass.Id;
        Agency_Special_Equipment__c ase = [SELECT Id FROM Agency_Special_Equipment__c WHERE Name = 'testAse' LIMIT 1];
        String aseId = ase.Id;
        Agency_Non_Suppression_Personnel__c agNonSup = [SELECT Id FROM Agency_Non_Suppression_Personnel__c WHERE Name = 'testAgNonSupPer' LIMIT 1];
        String agNonSupId = agNonSup.Id;
        Agency_Rate_Agreement__c agRateAgr = [SELECT Id FROM Agency_Rate_Agreement__c WHERE Name = 'testAgRateAgr' LIMIT 1];
        String agRateAgrId = agRateAgr.Id;
        Agency_Admin_Rates__c agAdmnRate = [SELECT Id FROM Agency_Admin_Rates__c WHERE Name = 'testAgAdmRate' LIMIT 1];
        String agAdmnRateId = agAdmnRate.Id;
        
        MARSAgencyController.updateTheParentToApproved(assId);
        MARSAgencyController.updateTheParentToExpired(assId, 'test');
        MARSAgencyController.updateTheParentToApproved(aseId);
        MARSAgencyController.updateTheParentToExpired(aseId, 'test');
        MARSAgencyController.updateTheParentToApproved(agNonSupId);
        MARSAgencyController.updateTheParentToExpired(agNonSupId, 'test');
        MARSAgencyController.updateTheParentToApproved(agRateAgrId);
        MARSAgencyController.updateTheParentToExpired(agRateAgrId, 'test');
        MARSAgencyController.updateTheParentToApproved(agAdmnRateId);
        MARSAgencyController.updateTheParentToExpired(agAdmnRateId, 'test');
    }
}