codepkg/objects/Amendment_Request__c.object
<CustomObject>
    <fields>
        <fullName>FDSR__c</fullName>
        <description>PW/DSR/PJ/PL Number  version</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>PW/DSR/PJ/PL</inlineHelpText>
        <label>Project Version (PW/DSR/PJ/PL)</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project to which the Amendment is requested.</description>
        <inlineHelpText>Project to which the Amendment is requested.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Amendment Requests</relationshipLabel>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SupplementNumber__c</fullName>
        <description>Sequential numbering system related to FEMA Obligations for a given Incident.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Sequential numbering system related to FEMA Obligations for a given Incident.</inlineHelpText>
        <label>Supplement Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Amendment Request</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Amendment Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Federal_Project_Award_W_O_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Federal Project Award - Total Federal Retention on Project</description>
        <inlineHelpText>Federal Project Award - Total Federal Retention on Project</inlineHelpText>
        <label>Federal Project Award W/O Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Federal_Project_Award__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Federal Amount awarded to the Project.</description>
        <inlineHelpText>This is the Total Amount of money FEMA has awarded for this Project.</inlineHelpText>
        <label>Federal Project Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Federal_Retention__c</fullName>
        <description>The Percent Amount withheld by CalOES as retention on Federal Funds. The standard is 0%.</description>
        <inlineHelpText>The Percent Amount withheld by CalOES as retention on Federal Funds. The standard is 0%. If this is a Large Project &lt; 100% complete, Project Funds will be paid on a reimbursement basis with 10% retention.</inlineHelpText>
        <label>Federal Retention %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Latest_Project_Version__c</fullName>
        <description>The latest version of Project Number, driven from the Latest Amendment available on the Project.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The latest version of Project Number, driven from the Latest Amendment available on the Project.</inlineHelpText>
        <label>Latest Project Version</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latest_Supplement_Number__c</fullName>
        <description>The supplement Number of the Latest Amendment available on the Project.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The supplement Number of the Latest Amendment available on the Project.</inlineHelpText>
        <label>Latest Supplement Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <description>The Federal State Assigned Project Number - FDSR or PA State Project Number.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Project Identifer (PW/DSR/PJ/PL)</inlineHelpText>
        <label>Project (PW/DSR/PJ/PL)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Project_Award_W_O_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Project Award - Total State Retention on Project</description>
        <inlineHelpText>State Project Award - Total State Retention on Project</inlineHelpText>
        <label>State Project Award W/O Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Project_Award__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total State Amount awarded to the Project.</description>
        <inlineHelpText>This is the portion of Total Project Award that the State will award to the Subrecipient.</inlineHelpText>
        <label>State Project Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Retention__c</fullName>
        <description>The State retention percent on reimbursable funds of a project in the obligation/repayment phases. Standard is 10%.</description>
        <inlineHelpText>The State retention percent on reimbursable funds of a project in the obligation/repayment phases. Standard is 10%.</inlineHelpText>
        <label>State Retention %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Supplement_Number__c</fullName>
        <description>The PA State Project Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This is the FEMA Amendment, Bundle, or Package number. Sequential numbering system related to FEMA Obligations for a given incident.</inlineHelpText>
        <label>Supplement Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Federal_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Federal Retention.[ Federal Project Amount * Federal Retention% ]</description>
        <inlineHelpText>Total Federal Retention.[ Federal Project Amount * Federal Retention% ]</inlineHelpText>
        <label>Total Federal Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_State_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;Total State Retention.
[ State Project Amount * State Retention% ]&quot;</description>
        <inlineHelpText>&quot;Total State Retention.
[ State Project Amount * State Retention% ]&quot;</inlineHelpText>
        <label>Total State Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/REAL_UpdateLatProjVerAndSuppNumJob.cls
/***********************************************************************************************************************************
* Class Name   : REAL_UpdateAwardRecordNewFieldsBatch
* Description  : This batch job is created to update the Total Individual Retentions and Amount Except Retention, Latest Project Version
 *                  and Latest Supplement Number field of Project record.
* Author       : Ricky
* Created On   : 20/07/2020
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Ricky              20/07/2020       Initial Implementation
**************************************************************************************************************************************/

public with sharing class REAL_UpdateLatProjVerAndSuppNumJob implements Database.Batchable<SObject>, Schedulable {
    private final String query;

    public REAL_UpdateLatProjVerAndSuppNumJob(String query) {
        this.query = query;
    }

    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new REAL_UpdateLatProjVerAndSuppNumJob(query));
    }

    // Database.Batchable methods
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Project__c> projectRecordList = (List<Project__c>) scope;
        for (Project__c project : projectRecordList) {
            Decimal federalProjectAmount = project.Federal_Project_Award__c == null ? 0.00 : project.Federal_Project_Award__c;
            Decimal stateProjectAmount = project.State_Project_Award__c == null ? 0.00 : project.State_Project_Award__c;
            Decimal federalRetention = project.Federal_Retention__c == null ? 0.00 : project.Federal_Retention__c;
            Decimal stateRetention = project.State_Retention__c == null ? 0.00 : project.State_Retention__c;

            project.Total_Federal_Retention__c = ((federalProjectAmount * federalRetention)/100)?.setScale(2,system.RoundingMode.DOWN);
            project.Total_State_Retention__c = ((stateProjectAmount * stateRetention)/100)?.setScale(2,system.RoundingMode.DOWN);
            project.Federal_Project_Award_W_O_Retention__c = (federalProjectAmount - project.Total_Federal_Retention__c)?.setScale(2,system.RoundingMode.DOWN);
            project.State_Project_Award_W_O_Retention__c = (stateProjectAmount - project.Total_State_Retention__c)?.setScale(2,system.RoundingMode.DOWN);

            if (project?.Amendment_Requests__r?.size() == 1) {
                project.Latest_Project_Version__c = project?.Amendment_Requests__r[0].FDSR__c == null ? null : project?.Amendment_Requests__r[0].FDSR__c;
                project.Latest_Supplement_Number__c = project?.Amendment_Requests__r[0].SupplementNumber__c == null ? null : project?.Amendment_Requests__r[0].SupplementNumber__c;
            }
            else {
                project.Latest_Project_Version__c = project.Project_Number__c == null ? null : project.Project_Number__c;
                project.Latest_Supplement_Number__c = project.Supplement_Number__c == null ? null : project.Supplement_Number__c;
            }
        }
        update projectRecordList;
    }

    public void finish(Database.BatchableContext bc) {
    }
}