codepkg/objects/Amendment_Request__c.object
<CustomObject>
    <fields>
        <fullName>FDSR__c</fullName>
        <description>PW/DSR/PJ/PL Number  version</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>PW/DSR/PJ/PL</inlineHelpText>
        <label>Project Version (PW/DSR/PJ/PL)</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEMA_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The &quot;FEMA Cost Share&quot; to be Amended for this Project.</description>
        <inlineHelpText>The &quot;FEMA Cost Share&quot; to be Amended for this Project.</inlineHelpText>
        <label>FEMA Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project to which the Amendment is requested.</description>
        <inlineHelpText>Project to which the Amendment is requested.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Amendment Requests</relationshipLabel>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;State Cost Share&quot; percentage to Amended for this Project.</description>
        <inlineHelpText>&quot;State Cost Share&quot; percentage to Amended for this Project.</inlineHelpText>
        <label>State Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Amendment Request</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Amendment Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Amendment_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Amendment Request due to which this Award is created.</description>
        <inlineHelpText>Amendment Request due to which this Award is created.</inlineHelpText>
        <label>Amendment Request</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Amendment_Request__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Amendment_Request__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AmountObligated__c</fullName>
        <description>Amount Obligated for the Award (Total Project Award of the Project).</description>
        <inlineHelpText>Amount Obligated for the Award (Total Project Award of the Project).</inlineHelpText>
        <label>Amount Obligated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FDSR__c</fullName>
        <description>PW/DSR/PJ/PL Number version.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>PW/DSR/PJ/PL</inlineHelpText>
        <label>Project Version (PW/DSR/PJ/PL)</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEMA_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;FEMA Share %&quot; of the Project.</description>
        <inlineHelpText>&quot;FEMA Share %&quot; of the Project.</inlineHelpText>
        <label>FEMA Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Federal_Project_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;Federal Project Amount&quot; for this Award as per &quot;New Obigated Amount&quot;.</description>
        <inlineHelpText>&quot;Federal Project Amount&quot; for this Award as per &quot;New Obigated Amount&quot;.</inlineHelpText>
        <label>Federal Project Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Federal_Retention_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Federal Retention% of the Project.</description>
        <inlineHelpText>Federal Retention% of the Project.</inlineHelpText>
        <label>Federal Retention%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Federal_Retention__c</fullName>
        <description>Federal Retention [Federal Supplement Amount * Federal Retention]</description>
        <inlineHelpText>Federal Retention [Federal Supplement Amount * Federal Retention]</inlineHelpText>
        <label>Supplement Federal Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Federal_Supplement_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;Federal Supplement Amount&quot; added to the Project from the current Award&apos;s Amendment.</description>
        <inlineHelpText>&quot;Federal Supplement Amount&quot; added to the Project from the current Award&apos;s Amendment.</inlineHelpText>
        <label>Federal Supplement Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project for which this Award is created.</description>
        <inlineHelpText>Project for which this Award is created.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State_Admin_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;State Admin Amount&quot; for this Award as per &quot;New Obligated Amount&quot;.</description>
        <inlineHelpText>&quot;State Admin Amount&quot; for this Award as per &quot;New Obligated Amount&quot;.</inlineHelpText>
        <label>State Admin Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Admin_Supplement_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;State Admin Supplement Amount&quot; added to the Project from the current Award&apos;s Amendment.</description>
        <inlineHelpText>&quot;State Admin Supplement Amount&quot; added to the Project from the current Award&apos;s Amendment.</inlineHelpText>
        <label>State Admin Supplement Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Admin__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Admin% of the Project.</description>
        <inlineHelpText>State Admin% of the Project.</inlineHelpText>
        <label>State Admin%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>State_Project_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;State Project Amount&quot; for this Award as per &quot;New Obigated Amount&quot;.</description>
        <inlineHelpText>&quot;State Project Amount&quot; for this Award as per &quot;New Obigated Amount&quot;.</inlineHelpText>
        <label>State Project Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Retention_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Retention% of the Project.</description>
        <inlineHelpText>State Retention% of the Project.</inlineHelpText>
        <label>State Retention%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>State_Retention__c</fullName>
        <description>State Retention [ State Supplement  Amount * State Retention ]</description>
        <inlineHelpText>State Retention [ State Supplement  Amount * State Retention ]</inlineHelpText>
        <label>Supplement State Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;State Share %&quot; of the Project.</description>
        <inlineHelpText>&quot;State Share %&quot; of the Project.</inlineHelpText>
        <label>State Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>State_Supplement_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;State Supplement Amount&quot; added to the Project from the current Award&apos;s Amendment.</description>
        <inlineHelpText>&quot;State Supplement Amount&quot; added to the Project from the current Award&apos;s Amendment.</inlineHelpText>
        <label>State Supplement Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Supplement_Award__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of Money Awarded in &quot;Additional Funding&quot; Amendment if the Award is crated due to Amendment or else Initial Award Amount from Project.</description>
        <inlineHelpText>Amount of Money Awarded in &quot;Additional Funding&quot; Amendment if the Award is crated due to Amendment or else Initial Award Amount from Project.</inlineHelpText>
        <label>Supplement Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Supplement_Number__c</fullName>
        <description>Supplement Number provided by FEMA.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Sequential Numbering system related to FEMA Obligations for a given Incident.</inlineHelpText>
        <label>Supplement Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Award</label>
    <nameField>
        <displayFormat>AW-{000000}</displayFormat>
        <label>Award Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>FEMA_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The FEMA Cost Share for this Project. The values are inherited from the Program Cost Share.</description>
        <inlineHelpText>Percentage of the Project Amount ($) that will be paid by FEMA.  Equal to the Federal Share ($) divided by the Project Amount ($).</inlineHelpText>
        <label>FEMA Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Federal_Retention__c</fullName>
        <description>The Percent Amount withheld by CalOES as retention on Federal Funds. The standard is 0%.</description>
        <inlineHelpText>The Percent Amount withheld by CalOES as retention on Federal Funds. The standard is 0%. If this is a Large Project &lt; 100% complete, Project Funds will be paid on a reimbursement basis with 10% retention.</inlineHelpText>
        <label>Federal Retention %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <description>The Federal State Assigned Project Number - FDSR or PA State Project Number.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Project Identifer (PW/DSR/PJ/PL)</inlineHelpText>
        <label>Project (PW/DSR/PJ/PL)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateAdmin__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Admin share of State Share%.</description>
        <inlineHelpText>State Admin share of the State Cost Share.</inlineHelpText>
        <label>State Admin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>State_Retention__c</fullName>
        <description>The State retention percent on reimbursable funds of a project in the obligation/repayment phases. Standard is 10%.</description>
        <inlineHelpText>The State retention percent on reimbursable funds of a project in the obligation/repayment phases. Standard is 10%.</inlineHelpText>
        <label>State Retention %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>State_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Share Cost Component only applies to Non Disaster Grants or PA Projects</description>
        <inlineHelpText>Percentage of the Project Amount ($) that was not covered by FEMA that will be paid out by Cal OES as CDAA funds.</inlineHelpText>
        <label>State Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Supplement_Number__c</fullName>
        <description>The PA State Project Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This is the FEMA Amendment, Bundle, or Package number. Sequential numbering system related to FEMA Obligations for a given incident.</inlineHelpText>
        <label>Supplement Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/REAL_UpdateAwardRecordNewFieldsBatch.cls
/***********************************************************************************************************************************
* Class Name   : REAL_UpdateAwardRecordNewFieldsBatch
* Description  : This batch job is created to update the Award record new fields which are created for Docu Gen requirements.
* Author       : Ricky
* Created On   : 17/07/2020
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Ricky              17/07/2020       Initial Implementation
**************************************************************************************************************************************/

public with sharing class REAL_UpdateAwardRecordNewFieldsBatch implements Database.Batchable<SObject>, Schedulable {
    private final String query;

    public REAL_UpdateAwardRecordNewFieldsBatch(String query) {
        this.query = query;
    }

    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new REAL_UpdateAwardRecordNewFieldsBatch(query));
    }

    // Database.Batchable methods
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Project__c> projectWithRelatedAwardList = (List<Project__c>) scope;
        List<Award__c> awardToUpdateList = new List<Award__c>();

        for (Project__c  projectRecordToProcess : projectWithRelatedAwardList) {
            Award__c updatedAwardRecord = new Award__c();

            for (Award__c awardToProcess : projectRecordToProcess.Awards__r) {

                awardToProcess.State_Admin__c = projectRecordToProcess.StateAdmin__c == null ? 0.00 : projectRecordToProcess.StateAdmin__c;
                awardToProcess.Federal_Retention_Share__c = projectRecordToProcess.Federal_Retention__c == null ? 0.00 : projectRecordToProcess.Federal_Retention__c;
                awardToProcess.State_Retention_Share__c = projectRecordToProcess.State_Retention__c == null ? 0.00 : projectRecordToProcess.State_Retention__c;

                Decimal femaShare = awardToProcess.FEMA_Share__c == null ? 0.00 : awardToProcess.FEMA_Share__c;
                Decimal stateShare = awardToProcess.State_Share__c == null ? 0.00 : awardToProcess.State_Share__c;
                Decimal supplementAmount = awardToProcess.Supplement_Award__c == null ? 0.00 : awardToProcess.Supplement_Award__c;
                Decimal newObligatedAmount = awardToProcess.AmountObligated__c == null ? 0.00 : awardToProcess.AmountObligated__c;

                if (awardToProcess.Amendment_Request__c == null) {
                    awardToProcess.Supplement_Number__c = projectRecordToProcess.Supplement_Number__c == null ? null : projectRecordToProcess.Supplement_Number__c;
                    awardToProcess.Federal_Project_Amount__c = ((newObligatedAmount * femaShare)/100)?.setScale(2,system.RoundingMode.DOWN);
                    awardToProcess.State_Project_Amount__c = ((newObligatedAmount * stateShare)/100)?.setScale(2,system.RoundingMode.DOWN);
                    awardToProcess.State_Admin_Amount__c = ((awardToProcess.State_Project_Amount__c * awardToProcess.State_Admin__c)/100)?.setScale(2,system.RoundingMode.DOWN);
                    awardToProcess.Federal_Supplement_Amount__c = awardToProcess.Federal_Project_Amount__c;
                    awardToProcess.State_Supplement_Amount__c = awardToProcess.State_Project_Amount__c;
                    awardToProcess.State_Admin_Supplement_Amount__c = awardToProcess.State_Admin_Amount__c;
                    awardToProcess.FDSR__c = projectRecordToProcess.Project_Number__c == null ? null : projectRecordToProcess.Project_Number__c;
                    awardToProcess.Supplement_Award__c = awardToProcess.AmountObligated__c == null ? 0.00 : awardToProcess.AmountObligated__c;
                    awardToProcess.Previous_Amount_Obligated__c = 0;

                    updatedAwardRecord.Federal_Project_Amount__c = awardToProcess.Federal_Project_Amount__c == null ? 0.00 : awardToProcess.Federal_Project_Amount__c;
                    updatedAwardRecord.State_Project_Amount__c = awardToProcess.State_Project_Amount__c == null ? 0.00 : awardToProcess.State_Project_Amount__c;
                    updatedAwardRecord.State_Admin_Amount__c = awardToProcess.State_Admin_Amount__c == null ? 0.00 : awardToProcess.State_Admin_Amount__c;
                }
                else if (awardToProcess.Amendment_Request__c != null) {
                    awardToProcess.Supplement_Number__c = awardToProcess.Amendment_Request__r.SupplementNumber__c == null ? null : awardToProcess.Amendment_Request__r.SupplementNumber__c;
                    awardToProcess.Federal_Project_Amount__c = ((newObligatedAmount * femaShare)/100)?.setScale(2,system.RoundingMode.DOWN);
                    awardToProcess.State_Project_Amount__c = ((newObligatedAmount * stateShare)/100)?.setScale(2,system.RoundingMode.DOWN);
                    awardToProcess.State_Admin_Amount__c = ((awardToProcess.State_Project_Amount__c * awardToProcess.State_Admin__c)/100)?.setScale(2,system.RoundingMode.DOWN);
                    awardToProcess.Federal_Supplement_Amount__c = (awardToProcess.Federal_Project_Amount__c - updatedAwardRecord.Federal_Project_Amount__c)?.setScale(2,system.RoundingMode.DOWN);
                    awardToProcess.State_Supplement_Amount__c = (awardToProcess.State_Project_Amount__c - updatedAwardRecord.State_Project_Amount__c)?.setScale(2,system.RoundingMode.DOWN);
                    awardToProcess.State_Admin_Supplement_Amount__c = (awardToProcess.State_Admin_Amount__c - updatedAwardRecord.State_Admin_Amount__c)?.setScale(2,system.RoundingMode.DOWN);
                    awardToProcess.FDSR__c = awardToProcess.Amendment_Request__r.FDSR__c == null ? null : awardToProcess.Amendment_Request__r.FDSR__c;

                    updatedAwardRecord.Federal_Project_Amount__c = awardToProcess.Federal_Project_Amount__c == null ? 0.00 : awardToProcess.Federal_Project_Amount__c;
                    updatedAwardRecord.State_Project_Amount__c = awardToProcess.State_Project_Amount__c == null ? 0.00 : awardToProcess.State_Project_Amount__c;
                    updatedAwardRecord.State_Admin_Amount__c = awardToProcess.State_Admin_Amount__c == null ? 0.00 : awardToProcess.State_Admin_Amount__c;
                }

                /** Updating the Previous Obligated Amount fields. */
                awardToProcess.Previous_Amount_Obligated__c = (newObligatedAmount
                        - supplementAmount)?.setScale(2,system.RoundingMode.DOWN);
                awardToProcess.Previous_Federal_Amount_Obligated__c = (awardToProcess.Federal_Project_Amount__c
                        - awardToProcess.Federal_Supplement_Amount__c)?.setScale(2,system.RoundingMode.DOWN);
                awardToProcess.Previous_State_Amount_Obligated__c = (awardToProcess.State_Project_Amount__c
                        - awardToProcess.State_Supplement_Amount__c)?.setScale(2,system.RoundingMode.DOWN);
                awardToProcess.Previous_State_Admin_Amount_Obligated__c = (awardToProcess.State_Admin_Amount__c
                        - awardToProcess.State_Admin_Supplement_Amount__c)?.setScale(2,system.RoundingMode.DOWN);

                awardToProcess.Total_Obligated_Amount__c = (awardToProcess.Federal_Project_Amount__c + awardToProcess.State_Project_Amount__c
                        + awardToProcess.State_Admin_Amount__c)?.setScale(2,system.RoundingMode.DOWN);
                awardToProcess.Total_Obligated_Supplement_Amount__c = (awardToProcess.Federal_Supplement_Amount__c + awardToProcess.State_Supplement_Amount__c
                        + awardToProcess.State_Admin_Supplement_Amount__c)?.setScale(2,system.RoundingMode.DOWN);

                awardToProcess.Federal_Retention__c = ((awardToProcess.Federal_Supplement_Amount__c
                        * awardToProcess.Federal_Retention_Share__c)/100)?.setScale(2,system.RoundingMode.DOWN);
                awardToProcess.State_Retention__c = ((awardToProcess.State_Supplement_Amount__c
                        * awardToProcess.State_Retention_Share__c)/100)?.setScale(2,system.RoundingMode.DOWN);

                awardToProcess.Federal_Amount_Available__c = (awardToProcess.Federal_Supplement_Amount__c
                        - awardToProcess.Federal_Retention__c)?.setScale(2,system.RoundingMode.DOWN);
                awardToProcess.State_Amount_Available__c = (awardToProcess.State_Supplement_Amount__c
                        - awardToProcess.State_Retention__c)?.setScale(2,system.RoundingMode.DOWN);

                awardToProcess.Sum_of_State_and_Federal__c = (awardToProcess.Federal_Supplement_Amount__c
                        + awardToProcess.State_Supplement_Amount__c)?.setScale(2,system.RoundingMode.DOWN);
                awardToProcess.Sum_of_State_and_Admin_Supplement__c = (awardToProcess.State_Supplement_Amount__c
                        + awardToProcess.State_Admin_Supplement_Amount__c)?.setScale(2,system.RoundingMode.DOWN);

                awardToProcess.Sum_of_State_and_Federal_to_Date__c = (awardToProcess.Federal_Project_Amount__c
                        + awardToProcess.State_Project_Amount__c)?.setScale(2,system.RoundingMode.DOWN);
                awardToProcess.Sum_of_State_and_Admin_to_Date__c = (awardToProcess.State_Project_Amount__c
                        + awardToProcess.State_Admin_Amount__c)?.setScale(2,system.RoundingMode.DOWN);
                awardToUpdateList.add(awardToProcess);
            }
        }
        if (awardToUpdateList?.size() > 0) {
            update awardToUpdateList;
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}