codepkg/objects/Announcement__mdt.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Announcement</label>
    <pluralLabel>Announcements</pluralLabel>
</CustomObject>

codepkg/objects/Community_Application__c.object
<CustomObject>
    <fields>
        <fullName>App_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>APP URL(Relative)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Logo Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Show_on_Portal__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPrivateApp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Its to specify which are private app and need access  internal</description>
        <inlineHelpText>Its to specify which are private app and need access  internal</inlineHelpText>
        <label>Is Private App?</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Community_Application_to_User__c.object
<CustomObject>
    <fields>
        <fullName>Community_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Application</label>
        <referenceTo>Community_Application__c</referenceTo>
        <relationshipLabel>Community Application to Users</relationshipLabel>
        <relationshipName>Community_Application_to_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Community_Application_to_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Application to User</label>
    <nameField>
        <displayFormat>CAU-{00000000}</displayFormat>
        <label>Community Application to User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Application to Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/User_Preference__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Term_Acceptance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Term Acceptance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term_Accepted_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Term Accepted Date</label>
        <type>DateTime</type>
    </fields>
    <label>User Preference</label>
</CustomObject>

codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Community_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Application</label>
        <referenceTo>Community_Application__c</referenceTo>
        <relationshipLabel>Community Registration</relationshipLabel>
        <relationshipName>CommunityRegistration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Tribal</fullName>
                </value>
                <value>
                    <fullName>Special District</fullName>
                </value>
                <value>
                    <fullName>Courts</fullName>
                </value>
                <value>
                    <fullName>Fire Agency</fullName>
                </value>
                <value>
                    <fullName>MARS Paying Entity</fullName>
                </value>
                <value>
                    <fullName>Federal Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CommunityHomePageCtrl.cls
/***********************************************************************************************************************************
* Class Name   : CommunityHomePageCtrl
* Description  : This class to get the data for Community Home Page 
* Author       : Pankaj
* Created On   : 07/08/2020
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj            07/08/2020       Initial Implementation
**************************************************************************************************************************************/

public without sharing class CommunityHomePageCtrl {

    
    /***********************************************
    * Method Name : isTermsPolicyAccepted
    * Author : Dayal
    * Inputs : -
    * Description: this method check the user is accepted terms ploicy or not
    *********************************************/
    public static Boolean isTermsPolicyAccepted(){        
        String userId = UserInfo.getUserId();  
        User_Preference__c userPreference = User_Preference__c.getInstance(userID);
        if(userPreference != null && userPreference.Term_Acceptance__c == true) {
            return true;
        }
       return false;
    }

    /***********************************************
    * Method Name : accepteTermsAndPloicy
    * Author : Dayal
    * Inputs : -
    * Description: it click the accept terms policy if user click on accept button
    *********************************************/
    @AuraEnabled
    public static Boolean accepteTermsAndPolicy(){
        Boolean isAccepted = false;
        try{
            String userId = UserInfo.getUserId();
            User_Preference__c userPreference = new User_Preference__c();
            userPreference.SetupOwnerId = userId;
            userPreference.Term_Accepted_Date__c = DateTime.now();
            userPreference.Term_Acceptance__c = true;
            upsert userPreference;
            isAccepted = true;
        }catch(Exception e){
            throw new AuraHandledException('Terms and policy not accpted');
        }  
        return  isAccepted;  
   }

    /***********************************************
    * Method Name : getAllApplications
    * Author : Pankaj
    * Inputs : -
    * Description: This method return map of all applications with apps, announcements and contact details.
    *********************************************/
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getAllApplications() {
        Map<String, Object> returnMap = new Map<String, Object>();
        List<Id> communityAppIds = new List<Id>();    
        List<Community_Application_to_User__c> communityAppIdLst = [SELECT Community_Application__r.Id 
                                            FROM Community_Application_to_User__c WHERE User__c =: UserInfo.getUserId()];
        for(Community_Application_to_User__c commAppUser: communityAppIdLst){
                communityAppIds.add(commAppUser.Community_Application__r.Id);
        }                                    
        // Set<Id> resultIds = (new Map<Id,SObject>(communityAppIdLst)).keySet();   
                                     
        List<Community_Application__c> communityApplications = [
                SELECT
                        Id,
                        Description__c,
                        Display_Name__c,
                        isActive__c,
                        Name,
                        isPrivateApp__c,
                        App_URL__c,
                        Logo_Name__c,
                    (   SELECT Id FROM Community_Application_to_Users__r
                            WHERE User__c=:UserInfo.getUserId() AND isActive__c=TRUE ),
                    (   SELECT Community_Application__r.Name, Id, Name, RecordTypeId, Status__c FROM CommunityRegistration__r
                            where CreatedById =: UserInfo.getUserId() And Status__c =: PHOS_Constants.APPROVAL_STATUS_APP_REQUESTED )
                FROM Community_Application__c WHERE isActive__c = TRUE AND Show_on_Portal__c = TRUE AND (isPrivateApp__c = false OR Id IN :communityAppIds) ORDER BY Sequence__c ASC ];
        System.debug('Apps: '+communityApplications);
        returnMap.put('Apps', communityApplications);
        returnMap.put('UserId',UserInfo.getUserId());
        returnMap.put('Announcements',getAnnouncements());
        returnMap.put('ContactDetails',getUserDetails());
        returnMap.put('isTermsPolicyAccepted',isTermsPolicyAccepted());
        return returnMap;
    }

    /***********************************************
    * Method Name : getAnnouncements
    * Author : Pankaj
    * Inputs : -
    * Description: This method return an announcement meatadata.
    *********************************************/
    private static List<Announcement__mdt> getAnnouncements(){
        List<Announcement__mdt> announcements = [select Title__c,Description__c,Image__c,Sequence__c from Announcement__mdt where IsActive__c = true Order By Sequence__c];
        return announcements;
    }

    /***********************************************
    * Method Name : getUserDetails
    * Author : Pankaj
    * Inputs : -
    * Description: This method return contact details.
    *********************************************/
    private static Contact getUserDetails(){
        String userId = UserInfo.getUserId();
        User userRec = [SELECT Id,ContactId from User where Id =:userId];
        Contact contactRec = [SELECT FirstName,LastName,Email,Phone,Account.Name,Account.Entity_Type__c FROM Contact WHERE Id =: userRec.ContactId];
        return contactRec;
    }

     /***********************************************
    * Method Name : paAppAccesCheck
    * Author : Pankaj
    * Inputs : -
    * Description: This method to check for .
    *********************************************/
    private static Boolean isPAAppAccessible(){
        Boolean hasPAAppAccess;
        String userId = UserInfo.getUserId();
       Community_Application_to_User__c commAppUser = [SELECT Id, Community_Application__c, Community_Application__r.Name
                                                        FROM  Community_Application_to_User__c 
                                                        WHERE User__r.Id =:userId and Community_Application__r.Name = 'PA']; 
        if(commAppUser == null){
            hasPAAppAccess = false;
        }else{
            hasPAAppAccess = true;
        }
        return hasPAAppAccess;
    }
}