codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>OES Review</fullName>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>The Document&apos;s Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Document&apos;s Name</inlineHelpText>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Site</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Document Stage</description>
        <inlineHelpText>The Document Stage</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Project Sites</relationshipLabel>
        <relationshipName>Project_Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Site</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Project Site   Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Request_For_Information__c.object
<CustomObject>
    <fields>
        <fullName>Analyst_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Analyst Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Request For Informations</relationshipLabel>
        <relationshipName>Request_For_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFI_Deadline__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>RFI Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFI_Type__c</fullName>
        <label>RFI Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OES BCA</fullName>
                </value>
                <value>
                    <fullName>OES Programmatic</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP</fullName>
                </value>
                <value>
                    <fullName>FEMA OES Programmatic</fullName>
                </value>
                <value>
                    <fullName>FEMA OES EHP</fullName>
                </value>
                <value>
                    <fullName>CWMP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RFI_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Sent to Subapplicant</fullName>
                </value>
                <value>
                    <fullName>Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted</fullName>
                </value>
                <value>
                    <fullName>Response Accepted</fullName>
                </value>
                <value>
                    <fullName>Response Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted to Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA EHP RFI</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA Programmatic RFI</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted by Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>RFI Requested</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Withdrawal</fullName>
                </value>
                <value>
                    <fullName>Submitted to HMA Analyst</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to HMA Analyst</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subapplicant_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Subapplicant Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Request For Information</label>
    <nameField>
        <displayFormat>RFI-{00000}</displayFormat>
        <label>Request For Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HMA_Utility.cls
public without sharing class HMA_Utility {
   
    /** 
     **************** Parameters **************************
     * Map<Id, Set<Id>> SObjectIdToUserIds : Object Record Id to set of User or Group Ids
     * String shareObjectName : Object Share Api Name like Application__share
     * String strAccessLevel : Access level like Read or Edit
     * String strRowCause : Record Sharing Reason Ex: for Application__c - Schema.Application__share.RowCause.Manual
     */
    public static Boolean shareCustomObjectRecordsWithUser(Map<Id, Set<Id>> SObjectIdToUserIds, String shareObjectName, String strAccessLevel, String strRowCause) {
        List<SObject> lstObjects = new List<SObject>();
        if(SObjectIdToUserIds.size() == 0 && String.isEmpty(shareObjectName) && !shareObjectName.contains('__share')) return false;
        SObjectType objectType = Schema.getGlobalDescribe().get(shareObjectName);
        for(Id sObjId : SObjectIdToUserIds.keySet()) {
            for(Id userId : SObjectIdToUserIds.get(sObjId)) {
                SObject shareRecord = objectType.newsObject();
                shareRecord.put('ParentId', sObjId);
                shareRecord.put('UserOrGroupId', userId);
                shareRecord.put('AccessLevel', strAccessLevel);
                shareRecord.put('RowCause', strRowCause);
                lstObjects.add(shareRecord);
            }
        }
        if(!lstObjects.isEmpty()) {
            insert lstObjects;
            
            return true;
        }   
        return false;
    }
    /**
     * Method used to get Application related RFIs
     * Set<String> appIds : Application Ids
     * Set<String> RFITypes : RFI Types
     * Set<String> status : RFI Status
     * String strRowCause : Record Sharing Reason Ex: for Application__c - Schema.Application__share.RowCause.Manual
    */
    public static List<Request_For_Information__c> getApplicationRFIs(Set<String> appIds, Set<String> RFITypes, Set<String> status){
        //Request_For_Information__c[] rfiList = [SELECT Id, Analyst_Comment__c, Subapplicant_Comment__c, RFI_Deadline__c, Name, Application__c from Request_For_Information__c WHERE Id IN: RFIIds AND RFI_Type__c IN: RFITypes AND Status__c IN: status];
        String query = 'SELECT Id, Name, Analyst_Comment__c, Subapplicant_Comment__c, RFI_Deadline__c, Application__c from Request_For_Information__c WHERE Application__c IN: appIds ';
                    if(RFITypes.size() > 0){
                        query += ' AND RFI_Type__c IN: RFITypes ';
                    }
                    if(status.size() > 0){
                        query += ' AND Status__c IN: status';
                    }
        return Database.query(query);
    }

    public static SObject convertSIdToSObject(String sobjectName ,Id sId) {
        SObject app = (SObject) (Type.forName('Schema.'+sobjectName).newInstance());
        app.Id = sId;
        return app;
    }
    

    /** This method is used for share Document records related to Application With Responsible Representative, Requestor, Contributor */
    public static void shareApplicationRelatedDocumentsWithSpecificUser(Map<Id, Set<Id>> applicationIdToUserIds) {
        Map<Id, Set<Id>> documentIdToUserIdsMap = new Map<Id, Set<Id>>();
        List<Document__c> docRecords = [SELECT Id, Application__c, Document_Name__c  FROM Document__c WHERE Application__c IN: applicationIdToUserIds.keySet()];
        System.debug('docRecords------------'+ docRecords);
        for(Document__c doc : docRecords) {
            if(documentIdToUserIdsMap.get(doc.Id) == null) {
                documentIdToUserIdsMap.put(doc.Id, new Set<Id>());
            }
            documentIdToUserIdsMap.get(doc.Id).addAll(applicationIdToUserIds.get(doc.Application__c));
        }
        System.debug('documentIdToUserIdsMap-App-----------'+ documentIdToUserIdsMap);
        if(documentIdToUserIdsMap.size() > 0) {
            Boolean isRecordShared = shareCustomObjectRecordsWithUser(documentIdToUserIdsMap, 'Document__share', 'Edit', Schema.Document__share.RowCause.Manual);
            if(isRecordShared) {
                System.debug('Document records of Application are shared Successfully.');
            }
        }
    }

    /** This method is used for share Document records related to Project Site With Responsible Representative, Requestor, Contributor */
    public static void shareProjectSiteRelatedDocumentsWithSpecificUser(Map<Id, Set<Id>> applicationIdToUserIds) {
        Map<Id, Set<Id>> projectSiteToUserIds = new Map<Id, Set<Id>>();
        Map<Id, Set<Id>> documentIdToUserIdsMap = new Map<Id, Set<Id>>();

        List<Project_Site__c> projectSites = [SELECT Id, Application__c FROM Project_Site__c WHERE Application__c IN: applicationIdToUserIds.keySet()];
        System.debug('projectSites------------'+ projectSites);
        for(Project_Site__c proSite : projectSites) {
            if(projectSiteToUserIds.get(proSite.Id) == null) {
                projectSiteToUserIds.put(proSite.Id, new Set<Id>());
            }
            projectSiteToUserIds.get(proSite.Id).addAll(applicationIdToUserIds.get(proSite.Application__c));
        }
        System.debug('projectSiteToUserIds-PS-----------'+ projectSiteToUserIds);
        List<Document__c> docRecords = [SELECT Id, Application__c, Project_Site__c, Document_Name__c  FROM Document__c WHERE Project_Site__c IN: projectSiteToUserIds.keySet()];
        System.debug('docRecords-PS-----------'+ docRecords);
        for(Document__c doc : docRecords) {
            if(documentIdToUserIdsMap.get(doc.Id) == null) {
                documentIdToUserIdsMap.put(doc.Id, new Set<Id>());
            }
            documentIdToUserIdsMap.get(doc.Id).addAll(projectSiteToUserIds.get(doc.Project_Site__c));
        }
        System.debug('documentIdToUserIdsMap-PS-----------'+ documentIdToUserIdsMap);
        if(documentIdToUserIdsMap.size() > 0) {
            Boolean isRecordShared = shareCustomObjectRecordsWithUser(documentIdToUserIdsMap, 'Document__share', 'Edit', Schema.Document__share.RowCause.Manual);
            if(isRecordShared) {
                System.debug('Document records of Project Site are shared Successfully.');
            }
        }
    }
}