codepkg/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Application_Extension__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Extensions</relationshipLabel>
        <relationshipName>Application_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Extension</label>
    <nameField>
        <displayFormat>AE-{00000}</displayFormat>
        <label>Application Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Application_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Extension</label>
        <referenceTo>Application_Extension__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Site</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Application_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Extension</label>
        <referenceTo>Application_Extension__c</referenceTo>
        <relationshipLabel>Project Sites</relationshipLabel>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Project Sites</relationshipLabel>
        <relationshipName>Project_Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Site</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Project Site   Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Request_For_Information__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Request For Informations</relationshipLabel>
        <relationshipName>Request_For_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request For Information</label>
    <nameField>
        <displayFormat>RFI-{00000}</displayFormat>
        <label>Request For Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HMA_UtilityTest.cls
@isTest
public with sharing class HMA_UtilityTest {
    @isTest
    public static void testShareCustomObjectRecordsWithUser() {
        User u = HMA_TestHelper.getPortalUserHMA(true);
        Application__c app = HMA_TestHelper.getApplication(true, '','', '');
        Map<Id, Set<Id>> sObjectIdtoUserIdsMap = new Map<Id, Set<Id>>();
        sObjectIdtoUserIdsMap.put(app.Id, new Set<Id>{u.Id});
        Test.startTest();
        Boolean shared = HMA_Utility.shareCustomObjectRecordsWithUser(sObjectIdtoUserIdsMap, 'Application__share', 'Edit', 'Manual');
        System.assert(shared == true || shared == false);
        Test.stopTest();
    }

    @isTest
    public static void testGetApplicationRFIs() {
        Application__c app = HMA_TestHelper.getApplication(true, '', '', '');
        Request_For_Information__c rfi = HMA_TestHelper.getRFI(true, app.Id, 2, 'OES BCA');
        Set<String> appIds = new Set<String>{String.valueOf(app.Id)};
        Set<String> rfiTypes = new Set<String>{'OES BCA'};
        Set<String> statuses = new Set<String>{'Draft'};
        Test.startTest();
        List<Request_For_Information__c> rfis = HMA_Utility.getApplicationRFIs(appIds, rfiTypes, statuses);
        System.assert(rfis.size() > 0);
        Test.stopTest();
    }

    // @isTest
    // public static void testGetContactIdtoUserIdMap() {
    //     User u = HMA_TestHelper.getPortalUserHMA(true);
    //     Test.startTest();
    //     Map<Id, Id> returnMap = HMA_Utility.getContactIdtoUserIdMap(new Set<Id>{String.valueOf(u.contactId)});
    //     System.assert(returnMap.size() > 0);
    //     Test.stopTest();
    // }

    @isTest
    public static void testConvertSIdToSObject() {
        Application__c app = HMA_TestHelper.getApplication(true, '','', '');
        Test.startTest();
        SObject sobj = HMA_Utility.convertSIdToSObject('Application__c', app.Id);
        System.assert(sobj != null);
        Test.stopTest();
    }

    @isTest
    public static void testShareApplicationRelatedDocumentsWithSpecificUser() {
        Map<Id, Set<Id>> paramMap = new Map<Id, Set<Id>>();
        Application__c app = HMA_TestHelper.getApplication(true, '', '', '');
        User u = HMA_TestHelper.getPortalUserHMA(true);
        paramMap.put(app.Id, new Set<Id>{u.Id});
        HMA_TestHelper.createCustomDocumentRecord(app.Id);
        Test.startTest();
        HMA_Utility.shareApplicationRelatedDocumentsWithSpecificUser(paramMap);
        Test.stopTest();
    }

    @isTest
    public static void testShareProjectSiteRelatedDocumentsWithSpecificUser() {
        Map<Id, Set<Id>> paramMap = new Map<Id, Set<Id>>();
        Application__c app = HMA_TestHelper.getApplication(true, '', '', '');
        Application_Extension__c appExt = HMA_TestHelper.getApplicationExension(true, app.Id);
        User u = HMA_TestHelper.getPortalUserHMA(true);
        Project_Site__c ps = HMA_TestHelper.getProjectSite(true, app.Id, appExt.Id);
        Document__c doc = HMA_TestHelper.createCustomDocumentRecord(app.Id);
        doc.Project_Site__c = ps.Id;
        update doc;
        paramMap.put(app.Id, new Set<Id>{u.Id});
        Test.startTest();
        HMA_Utility.shareProjectSiteRelatedDocumentsWithSpecificUser(paramMap);
        Test.stopTest();
    }
}