codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <inlineHelpText>Planning activities include developing a new Hazard Mitigation Plan or updating a current plan.</inlineHelpText>
        <label>Subapplication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Planning-related</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Advance Assistance</fullName>
                </value>
                <value>
                    <fullName>5% Initiative</fullName>
                </value>
                <value>
                    <fullName>Flood Hazard Mitigation Planning</fullName>
                </value>
                <value>
                    <fullName>Project Scoping</fullName>
                </value>
                <value>
                    <fullName>Community Flood Mitigation Project</fullName>
                </value>
                <value>
                    <fullName>Individual Flood Mitigation Project</fullName>
                </value>
                <value>
                    <fullName>Capability and Capacity Building (C&amp;CB)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HMAApplicationTriggerHandler.cls
public with sharing class HMAApplicationTriggerHandler extends TriggerHandler implements TriggerInterface {
    //private ApplicationValidationRuleHandler validationRuleHandler;
    public HMAApplicationTriggerHandler() {
        
    }

    public override void beforeTrigger() {
        
        try{
           
        } catch(Exception e) {
            throw new CustomExceptionController.NoApplicationTriggerException(e);
        }
        
    }

    public override void beforeInsert() {
        for(Application__c app : (List<Application__c>) Trigger.New) {
            
        }
        
    } 
    public override void afterInsert() {
        if(Trigger.newMap.keySet().size() > 0) {
            ApplicationHelper.processToCreateWSAndWSLI(Trigger.newMap.keySet());
        }
    } 

    public override void afterUpdate() {
        Set<Id> appIds = new Set<Id>();
        for(Application__c app : (List<Application__c>) Trigger.New) {
            if(shouldExecute(app)) {
                Application__c oldApp = (Application__c) trigger.oldMap.get(app.Id);
                Application__c newApp = (Application__c) trigger.newMap.get(app.Id);
                if(oldApp.Application_Type__c != newApp.Application_Type__c) {
                    appIds.add(app.Id);
                }
            }
        }
        if(appIds.size() > 0) {
            //ApplicationHelper.processToCreateWSAndWSLI(appIds);  //-------Commented Create Work Schedule and Work Schedule Line Item call after Update Application 
        }        
    }
}