codepkg/objects/Application_Contact__c.object
<CustomObject>
    <description>This object is the junction between Home Hardening Application(HH Application) and Contact object.</description>
    <fields>
        <fullName>Annual_Income__c</fullName>
        <label>Annual Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HH_Application__c</fullName>
        <description>Lookup to Home Hardening Application(HH Application) object in order to capture the number of Applications for each Contact.</description>
        <inlineHelpText>Lookup to Home Hardening Application(HH Application) object in order to capture the number of Applications for each Contact.</inlineHelpText>
        <label>HH Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>Application Contacts</relationshipLabel>
        <relationshipName>Application_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Head_of_Household__c</fullName>
        <label>Head of Household?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Homeowner__c</fullName>
        <label>Relationship to Homeowner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Application-Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HHCustomRelatedListCtrl.cls
/**
 * Created by StackNexus Admin on 07-09-2021.
 */

public without sharing class HHCustomRelatedListCtrl {
    @AuraEnabled(cacheable=true)
    //Get Application_Contact__c data related to HH_Application__c record
    public static Map<String, Object> getRecordInfo(String masterRecordId, String filter, String refresh){
        Map<String, Object> resultMap = new Map<String, Object>();
        String query ='Select Id,Name,First_Name__c,Last_Name__c,toLabel(Relationship_to_Homeowner__c), toLabel(Head_of_Household__c), HH_Application__c,Annual_Income__c,Date_of_Birth__c From Application_Contact__c where HH_Application__c ='+'\''+masterRecordId+'\''+' AND '+filter;
        System.debug('Query--- '+query);
        List<Application_Contact__c> getApplicationContactList = Database.query(query);
        resultMap.put('applicationContacts',getApplicationContactList);
        return resultMap;
    }
}