codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <inlineHelpText>Planning activities include developing a new Hazard Mitigation Plan or updating a current plan.</inlineHelpText>
        <label>Subapplication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Planning-related</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Advance Assistance</fullName>
                </value>
                <value>
                    <fullName>5% Initiative</fullName>
                </value>
                <value>
                    <fullName>Flood Hazard Mitigation Planning</fullName>
                </value>
                <value>
                    <fullName>Project Scoping</fullName>
                </value>
                <value>
                    <fullName>Community Flood Mitigation Project</fullName>
                </value>
                <value>
                    <fullName>Individual Flood Mitigation Project</fullName>
                </value>
                <value>
                    <fullName>Capability and Capacity Building (C&amp;CB)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OES_Analyst_Brief_Summary__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OES Analyst Brief Summary</label>
        <length>800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Acquisition Demo Relocation is the purchase of properties voluntarily to remove structure(s) from natural hazards (flood/landslide/avalanche.) Structures must be demolished or relocated outside hazards.</inlineHelpText>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Plan</fullName>
                </value>
                <value>
                    <fullName>Plan Update</fullName>
                </value>
                <value>
                    <fullName>Planning-Related Activities</fullName>
                </value>
                <value>
                    <fullName>Acquisition Demo-Relocation</fullName>
                </value>
                <value>
                    <fullName>Drainage/Flood Control</fullName>
                </value>
                <value>
                    <fullName>Elevation-Floodproofing</fullName>
                </value>
                <value>
                    <fullName>Safe Room/Shelter</fullName>
                </value>
                <value>
                    <fullName>Seismic Retrofitting</fullName>
                </value>
                <value>
                    <fullName>Wildfire &amp; Vegetation Management</fullName>
                </value>
                <value>
                    <fullName>Generator(s)/Other Power Source(s)</fullName>
                </value>
                <value>
                    <fullName>Mitigation Reconstruction</fullName>
                </value>
                <value>
                    <fullName>Tsunami Vertical Evacuation</fullName>
                </value>
                <value>
                    <fullName>Advance Assistance</fullName>
                </value>
                <value>
                    <fullName>Post-Disaster Code Enforcement</fullName>
                </value>
                <value>
                    <fullName>Public Awareness and Education</fullName>
                </value>
                <value>
                    <fullName>Early Warning Systems</fullName>
                </value>
                <value>
                    <fullName>Hazard Identification or Mapping</fullName>
                </value>
                <value>
                    <fullName>GIS for Mitigation</fullName>
                </value>
                <value>
                    <fullName>New Techniques/Methods</fullName>
                </value>
                <value>
                    <fullName>Project Scoping</fullName>
                </value>
                <value>
                    <fullName>Nature-Based Solutions/Green Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Planning-New Plan</fullName>
                </value>
                <value>
                    <fullName>Partnerships</fullName>
                </value>
                <value>
                    <fullName>Building Code</fullName>
                </value>
                <value>
                    <fullName>Planning-Plan Update</fullName>
                </value>
                <value>
                    <fullName>Utility and Infrastructure Protection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>OES Review</fullName>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>HMGP</fullName>
        <active>true</active>
        <label>HMGP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Pre_Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <inlineHelpText>Planning - Activities include developing a new hazard mitigation plan or updating a current mitigation plan.</inlineHelpText>
        <label>Subapplication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Planning-related</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Advance Assistance</fullName>
                </value>
                <value>
                    <fullName>5% Initiative</fullName>
                </value>
                <value>
                    <fullName>Flood Hazard Mitigation Planning</fullName>
                </value>
                <value>
                    <fullName>Project Scoping</fullName>
                </value>
                <value>
                    <fullName>Community Flood Mitigation Project</fullName>
                </value>
                <value>
                    <fullName>Individual Flood Mitigation Project</fullName>
                </value>
                <value>
                    <fullName>Capability and Capacity Building (C&amp;CB)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Acquisition Demo-Relocation - Purchase of properties on a voluntary basis in order to remove structure(s) from natural hazards (flood/landslide/avalanche). Structures must be demolished or relocated outside hazard.</inlineHelpText>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New Plan</fullName>
                </value>
                <value>
                    <fullName>Plan Update</fullName>
                </value>
                <value>
                    <fullName>Planning-Related Activities</fullName>
                </value>
                <value>
                    <fullName>Acquisition Demo-Relocation</fullName>
                </value>
                <value>
                    <fullName>Drainage/Flood Control</fullName>
                </value>
                <value>
                    <fullName>Elevation-Floodproofing</fullName>
                </value>
                <value>
                    <fullName>Safe Room/Shelter</fullName>
                </value>
                <value>
                    <fullName>Seismic Retrofitting</fullName>
                </value>
                <value>
                    <fullName>Wildfire &amp; Vegetation Management</fullName>
                </value>
                <value>
                    <fullName>Generator(s)/Other Power Source(s)</fullName>
                </value>
                <value>
                    <fullName>Mitigation Reconstruction</fullName>
                </value>
                <value>
                    <fullName>Tsunami Vertical Evacuation</fullName>
                </value>
                <value>
                    <fullName>Advance Assistance</fullName>
                </value>
                <value>
                    <fullName>Post-Disaster Code Enforcement</fullName>
                </value>
                <value>
                    <fullName>Public Awareness and Education</fullName>
                </value>
                <value>
                    <fullName>Early Warning Systems</fullName>
                </value>
                <value>
                    <fullName>Hazard Identification or Mapping</fullName>
                </value>
                <value>
                    <fullName>GIS for Mitigation</fullName>
                </value>
                <value>
                    <fullName>New Techniques/Methods</fullName>
                </value>
                <value>
                    <fullName>Project Scoping</fullName>
                </value>
                <value>
                    <fullName>Nature-Based Solutions/Green Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Planning-New Plan</fullName>
                </value>
                <value>
                    <fullName>Partnerships</fullName>
                </value>
                <value>
                    <fullName>Building Code</fullName>
                </value>
                <value>
                    <fullName>Planning-Plan Update</fullName>
                </value>
                <value>
                    <fullName>Utility and Infrastructure Protection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
                <value>
                    <fullName>Analyst Review</fullName>
                </value>
                <value>
                    <fullName>Request for Information</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Manager Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <recordTypes>
        <fullName>HMGP</fullName>
        <active>true</active>
        <description>For HMGP NOI Requests</description>
        <label>HMGP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HMA_ApplicationTriggerHandler.cls
public with sharing class HMA_ApplicationTriggerHandler extends TriggerHelper {
    //private ApplicationValidationRuleHandler validationRuleHandler;
    Set<String> preAppIds = new Set<String>();
    public HMA_ApplicationTriggerHandler() {
        
    }

    public override void processBeforeInsert() {
        
    } 
    public override void processAfterInsert() {
        //TODO: Add HMGP record type check
        Map<Id, String> appIdToAppProjectType = new Map<Id, String>();
        Map<Id, String> appIdToSubApplicationTypeMap = new Map<Id, String>();
        Map<Id, Application__c> preAppIdToApplicationMap = new Map<iD, Application__c>();
        Map<Id, Application__c> applicationIdToApplicationMap = new Map<iD, Application__c>();
        
        if(Trigger.newMap.keySet().size() > 0) {
            HMA_ApplicationHelper.processToCreateWSAndWSLI(Trigger.newMap.keySet());
            //HMA_ApplicationHelper.createProjectBudgetProjectCost(Trigger.newMap.keySet());
        }
        for(Application__c app : (List<Application__c>) Trigger.New) {
            if(app.Pre_Application__c != null) {
                preAppIdToApplicationMap.put(app.Pre_Application__c, app); 
            }
            
            appIdToAppProjectType.put(app.Id, app.Project_Type__c);
            appIdToSubApplicationTypeMap.put(app.Id, app.Application_Type__c);
            applicationIdToApplicationMap.put(app.Id, app);
            preAppIds.add(app.Pre_Application__c);
        }
        if(appIdToAppProjectType.size() > 0) {
            HMA_ApplicationHelper.createApplicationExtension(appIdToAppProjectType, appIdToSubApplicationTypeMap);
        }
        createDocumentsForApplicationRecords();
        /** Creating Application Contact Role */
        if(preAppIdToApplicationMap.size() > 0) {
            HMA_ApplicationHelper.checkACRoleAndCreateContactRoleForApplication(preAppIdToApplicationMap);
        }       
        

        /** This method is used for check User is present or not for Contact of AccountContactRole
         * for User check is Community Application User present or not, if not create it and if present update it
         * For User Share Application records with specified user
         * For Contact Create Community Application User records
         */
        HMA_ApplicationHelper.checkUserAndCreateCommunityApplicationUser(Trigger.newMap.keySet());
        
        /** Send Email to Contact Role(Responsible Representative and Requestor) */
        //HMA_ApplicationHelper.prepareForSubApplicationApprovalEmail(applicationIdToApplicationMap);
    }

    private void createDocumentsForApplicationRecords(){
        /*To create application Record related documents*/
        Map<String, List<Application__c>> filterClauseToApplicationMap = new Map<String, List<Application__c>>();
        /*Key="Application" is default value and filter clause to get Application related documents from Program Document Object*/
        filterClauseToApplicationMap.put('Application', new List<Application__c>());
        filterClauseToApplicationMap.get('Application').addAll((List<Application__c>)Trigger.new);
        /*It will create configured doc for application and share with community user*/
        HMA_ApplicationHelper.createDocumentsByFilterClause(filterClauseToApplicationMap, HMA_CONSTANTS.PROGRAM_DOC_PARENT_OBJECT_APPLICATION);
    }
    public override void processBeforeUpdate() {
        List<Application__c> femaApplications = new List<Application__c>();
        for(Application__c newApp : (List<Application__c>) Trigger.New) {
             /**Validate some fields when user changed Application status to FEMA Review */
             if(newApp.Status__c.equals(HMA_CONSTANTS.APPLICATION_STATUS_FEMA_REVIEW)) {
                femaApplications.add(newApp);
            }
        }
        /**Validate some fields when user changed Application status to FEMA Review */
        if(femaApplications.size() > 0) {
            HMA_ApplicationHelper.validateAppWhenStatusIsFEMAReview(femaApplications);
        }
    } 
    public override void processAfterUpdate() {
        Map<Id, Application__c> applicationIdToApplicationMap = new Map<Id, Application__c>();
        //Set for getting the FEMA Review applications
        Set<Id> statusFEMAReviewAppIds = new Set<Id>();
        for(Application__c app : (List<Application__c>) Trigger.New) {
                Application__c oldApp = (Application__c) trigger.oldMap.get(app.Id);
                Application__c newApp = (Application__c) trigger.newMap.get(app.Id);
                /**
                 * If application OES Analyst Brief Summary is changed 
                 * */
                if(oldApp.OES_Analyst_Brief_Summary__c != newApp.OES_Analyst_Brief_Summary__c) {
                    applicationIdToApplicationMap.put(app.Id, App);                    
                }

                /**
                 * If application status is changed to FEMA Review and Status is changed to FEMA Decision
                 * Fema Review to fema decision no invitation required 
                 * */
                if(oldApp.Status__c != HMA_CONSTANTS.APPLICATION_STATUS_FEMA_REVIEW && newApp.Status__c.equals(HMA_CONSTANTS.APPLICATION_STATUS_FEMA_REVIEW)) {
                            statusFEMAReviewAppIds.add(newApp.Id);
                }
        }
        /**
         * If any applications have status as FEMA Review then check AccountContactJunction for them and process them accordingly
         */
        if(statusFEMAReviewAppIds.size() > 0) {
            HMA_ApplicationHelper.processApplicationsForFEMA(statusFEMAReviewAppIds);
        }
        if(applicationIdToApplicationMap.size() > 0) {
            HMA_ApplicationHelper.updateScoringChecklistOESBriefSummary(applicationIdToApplicationMap);
        }
    }

}