codepkg/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Application_Extension__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Extensions</relationshipLabel>
        <relationshipName>Application_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase_1_Project_Costs__c</fullName>
        <label>Phase 1 Project Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phase_2_Project_Costs__c</fullName>
        <label>Phase 2 Project Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Project_Cost__c</fullName>
        <label>Total Project Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Application Extension</label>
    <nameField>
        <displayFormat>AE-{00000}</displayFormat>
        <label>Application Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Project_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Application_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Extension</label>
        <referenceTo>Application_Extension__c</referenceTo>
        <relationshipLabel>Project Budgets</relationshipLabel>
        <relationshipName>Project_Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Project Budgets</relationshipLabel>
        <relationshipName>Project_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Budget</label>
    <nameField>
        <displayFormat>PB-{00000}</displayFormat>
        <label>Project Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Project_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Project_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Budget</label>
        <referenceTo>Project_Budget__c</referenceTo>
        <relationshipLabel>Project Costs</relationshipLabel>
        <relationshipName>Project_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Site</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Project Costs</relationshipLabel>
        <relationshipName>Project_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Cost</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Project_Cost_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Estimate_Total__c</fullName>
        <description>Used in Management Cost Budget Breakdown as an Amount</description>
        <label>Cost Estimate Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Type__c</fullName>
        <label>Cost Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public Outreach</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Permitting</fullName>
                </value>
                <value>
                    <fullName>Title Search / Title Insurance</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                </value>
                <value>
                    <fullName>Duplication of Benefits analysis</fullName>
                </value>
                <value>
                    <fullName>Acquisition of Properties/Structures (Market Value - Pre or Post Disaster Valuation)</fullName>
                </value>
                <value>
                    <fullName>Closing Costs</fullName>
                </value>
                <value>
                    <fullName>Project Management</fullName>
                </value>
                <value>
                    <fullName>Demolition/Site Restoration/Landfill Tipping Fees/Utility Removal</fullName>
                </value>
                <value>
                    <fullName>Asbestos Testing/Abatement</fullName>
                </value>
                <value>
                    <fullName>Lead Based Paint Testing/Remediation</fullName>
                </value>
                <value>
                    <fullName>EHP Review / Coordination</fullName>
                </value>
                <value>
                    <fullName>Acquisition of Property (Land Only)</fullName>
                </value>
                <value>
                    <fullName>Jacking and Moving Structure</fullName>
                </value>
                <value>
                    <fullName>Dissembling and Reassembling Appurtenances (Porches, Decks, Awnings, Ramps)</fullName>
                </value>
                <value>
                    <fullName>Site Preparation (foundation, water, sewer, utility hookup)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phase 1</fullName>
                </value>
                <value>
                    <fullName>Phase 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Cost__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Cost</label>
        <referenceTo>Project_Cost__c</referenceTo>
        <relationshipLabel>Project Cost Line Items</relationshipLabel>
        <relationshipName>Project_Cost_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Cost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Measure__c</fullName>
        <label>Unit Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                </value>
                <value>
                    <fullName>Mile</fullName>
                </value>
                <value>
                    <fullName>Hour</fullName>
                </value>
                <value>
                    <fullName>Ton</fullName>
                </value>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Cubic Foot</fullName>
                </value>
                <value>
                    <fullName>Cubic Yard</fullName>
                </value>
                <value>
                    <fullName>Day</fullName>
                </value>
                <value>
                    <fullName>Linear Foot</fullName>
                </value>
                <value>
                    <fullName>Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Million Board Feet</fullName>
                </value>
                <value>
                    <fullName>Number Of Seats</fullName>
                </value>
                <value>
                    <fullName>Square Foot</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Square Yard</fullName>
                </value>
                <value>
                    <fullName>Square Yard Per Inch</fullName>
                </value>
                <value>
                    <fullName>Foot</fullName>
                </value>
                <value>
                    <fullName>Inch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Quantity__c</fullName>
        <label>Unit Quantity</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Cost Line Item</label>
    <nameField>
        <displayFormat>PCLI-{00000}</displayFormat>
        <label>Project Cost Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Cost Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Application_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Extension</label>
        <referenceTo>Application_Extension__c</referenceTo>
        <relationshipLabel>Project Sites</relationshipLabel>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Project Sites</relationshipLabel>
        <relationshipName>Project_Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Site</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Project Site   Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/HMA_PCLITriggerHandlerTest.cls
@isTest
public with sharing class HMA_PCLITriggerHandlerTest {
    @isTest
    public static void testTriggerScenarios() {
        Application__c app = HMA_TestHelper.getApplication(true, '', '', '');
        HMA_TestHelper.createCustomDocumentRecord(app.Id);
        Application_Extension__c appExt = HMA_TestHelper.getApplicationExension(false, app.Id);
        appExt.Total_Project_Cost__c = 0;
        appExt.Phase_1_Project_Costs__c = 0;
        appExt.Phase_2_Project_Costs__c = 0;
        insert appExt;
        Project_Site__c ps = HMA_TestHelper.getProjectSite(true, app.Id, appExt.Id);
        Project_Budget__c pb = HMA_TestHelper.getProjectBudget(true, app.Id, appExt.Id);
        Project_Cost__c pcb = HMA_TestHelper.getProjectCost(true, pb.Id);
        Project_Cost__c pcs = HMA_TestHelper.getProjectCostwithProjectSiteRecordType(true, ps.Id);
        Test.startTest();
            Project_Cost_Line_Item__c pcli1 = HMA_TestHelper.getProjectCostLineItem(false, pcb.Id);
            pcli1.Cost_Estimate_Total__c = 100;
            pcli1.Phase__c = 'Phase 1';
            pcli1.Cost_Type__c = 'Survey';
            pcli1.Item_Name__c = 'test';
            pcli1.Unit_Quantity__c = 2;
            pcli1.Unit_Measure__c = 'Each';
            pcli1.Unit_Cost__c = 50;
            Project_Cost_Line_Item__c pcli2 = HMA_TestHelper.getProjectCostLineItem(false, pcb.Id);
            pcli2.Cost_Estimate_Total__c = 100;
            pcli2.Phase__c = 'Phase 2';
            pcli2.Cost_Type__c = 'Survey';
            pcli2.Item_Name__c = 'test';
            pcli2.Unit_Quantity__c = 2;
            pcli2.Unit_Measure__c = 'Each';
            pcli2.Unit_Cost__c = 50;
            List<Project_Cost_Line_Item__c> pclis =  new List<Project_Cost_Line_Item__c>();
            pclis.add(pcli1);
            pclis.add(pcli2);
            insert pclis;
            for(Project_Cost_Line_Item__c pcli : pclis) {
                pcli.Cost_Estimate_Total__c = 200;
            }
            update pclis;
            for(Project_Cost_Line_Item__c pcli : pclis) {
                if(pcli.Phase__c == 'Phase 1') {
                    pcli.Cost_Estimate_Total__c = 210;
                    pcli.Phase__c = 'Phase 2';
                }
            }
            update pclis;
            for(Project_Cost_Line_Item__c pcli : pclis) {
                if(pcli.Phase__c == 'Phase 2') {
                    pcli.Cost_Estimate_Total__c = 220;
                    pcli.Phase__c = 'Phase 1';
                }
            }
            update pclis;
            for(Project_Cost_Line_Item__c pcli : pclis) {
                if(pcli.Phase__c == 'Phase 1') {
                    pcli.Phase__c = 'Phase 2';
                }
            }
            update pclis;
            for(Project_Cost_Line_Item__c pcli : pclis) {
                if(pcli.Phase__c == 'Phase 2') {
                    pcli.Phase__c = 'Phase 1';
                }
            }
            update pclis;
            for(Project_Cost_Line_Item__c pcli : pclis) {
                pcli.Cost_Estimate_Total__c = 400;
            }
            update pclis; 
            for(Project_Cost_Line_Item__c pcli : pclis) {
                pcli.Cost_Estimate_Total__c = 180;
            }
            update pclis;
            for(Project_Cost_Line_Item__c pcli : pclis) {
                if(pcli.Phase__c == 'Phase 1') {
                    pcli.Cost_Estimate_Total__c = 150;
                    pcli.Phase__c = 'Phase 2';
                }
            }
            update pclis;
            for(Project_Cost_Line_Item__c pcli : pclis) {
                if(pcli.Phase__c == 'Phase 2') {
                    pcli.Cost_Estimate_Total__c = 100;
                    pcli.Phase__c = 'Phase 1';
                }
            }
            update pclis;
            delete pclis;
        Test.stopTest();
    }

    @isTest
    public static void testTriggerScenariosSites() {
        Application__c app = HMA_TestHelper.getApplication(true, '', '', '');
        HMA_TestHelper.createCustomDocumentRecord(app.Id);
        Application_Extension__c appExt = HMA_TestHelper.getApplicationExension(false, app.Id);
        appExt.Total_Project_Cost__c = 0;
        appExt.Phase_1_Project_Costs__c = 0;
        appExt.Phase_2_Project_Costs__c = 0;
        insert appExt;
        Project_Site__c ps = HMA_TestHelper.getProjectSite(true, app.Id, appExt.Id);
        Project_Budget__c pb = HMA_TestHelper.getProjectBudget(true, app.Id, appExt.Id);
        Project_Cost__c pcb = HMA_TestHelper.getProjectCost(true, pb.Id);
        Project_Cost__c pcs = HMA_TestHelper.getProjectCostwithProjectSiteRecordType(true, ps.Id);
        Test.startTest();
            List<Project_Cost_Line_Item__c> pcliSites = new List<Project_Cost_Line_Item__c>();
            Project_Cost_Line_Item__c pcliSite1 = HMA_TestHelper.getProjectCostLineItem(false, pcs.Id);
            pcliSite1.Phase__c = 'Phase 1';
            pcliSites.add(pcliSite1);
            Project_Cost_Line_Item__c pcliSite2 = HMA_TestHelper.getProjectCostLineItem(false, pcs.Id);
            pcliSite2.Phase__c = 'Phase 2';
            pcliSites.add(pcliSite2);
            insert pcliSites; 
            for(Project_Cost_Line_Item__c pcli : pcliSites) {
                if(pcli.Phase__c == 'Phase 1') {
                    pcli.Cost_Estimate_Total__c = 210;
                    pcli.Phase__c = 'Phase 2';
                }
            }
            update pcliSites;
            for(Project_Cost_Line_Item__c pcli : pcliSites) {
                if(pcli.Phase__c == 'Phase 2') {
                    pcli.Cost_Estimate_Total__c = 220;
                    pcli.Phase__c = 'Phase 1';
                }
            }
            update pcliSites;
            for(Project_Cost_Line_Item__c pcli : pcliSites) {
                if(pcli.Phase__c == 'Phase 1') {
                    pcli.Phase__c = 'Phase 2';
                }
            }
            update pcliSites;
            for(Project_Cost_Line_Item__c pcli : pcliSites) {
                if(pcli.Phase__c == 'Phase 2') {
                    pcli.Phase__c = 'Phase 1';
                }
            }
            update pcliSites;
            for(Project_Cost_Line_Item__c pcli : pcliSites) {
                pcli.Cost_Estimate_Total__c = 400;
            }
            update pcliSites; 
            for(Project_Cost_Line_Item__c pcli : pcliSites) {
                pcli.Cost_Estimate_Total__c = 180;
            }
            update pcliSites;
            for(Project_Cost_Line_Item__c pcli : pcliSites) {
                if(pcli.Phase__c == 'Phase 1') {
                    pcli.Cost_Estimate_Total__c = 150;
                    pcli.Phase__c = 'Phase 2';
                }
            }
            update pcliSites;
            for(Project_Cost_Line_Item__c pcli : pcliSites) {
                if(pcli.Phase__c == 'Phase 2') {
                    pcli.Cost_Estimate_Total__c = 100;
                    pcli.Phase__c = 'Phase 1';
                }
            }
            update pcliSites;
            delete pcliSites;
        Test.stopTest();
    }
}