codepkg/objects/Application_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>Bypass_Trigger_Execution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable trigger for entire application</description>
        <label>Bypass Trigger Execution</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class_to_Execute__c</fullName>
        <description>Name of the class which to be execute</description>
        <label>Class to Execute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Select All in this project only If functionality is required for all the projects.</description>
        <label>Project</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cal_OES_Public_Health_Ordering_System</fullName>
                    <default>true</default>
                    <label>Cal_OES_Public_Health_Ordering_System</label>
                </value>
                <value>
                    <fullName>Cal_OES_Donation_Intake_Portal</fullName>
                </value>
                <value>
                    <fullName>CalOES_HMA</fullName>
                </value>
                <value>
                    <fullName>Cal_OES_Support</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Config</label>
    <pluralLabel>Application Configs</pluralLabel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/SObject__mdt.object
<CustomObject>
    <fields>
        <fullName>Applicable_Trigger_Handlers__c</fullName>
        <description>All the trigger handlers that will be created on the object are entered here as semicolon separated value</description>
        <inlineHelpText>All the trigger handlers that will be created on the object are entered here as semicolon separated value</inlineHelpText>
        <label>Applicable Trigger Handlers</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bypass_Trigger_Execution__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Trigger Execution</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ObjectApiName__c</fullName>
        <label>ObjectApiName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skip_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to bypass validation rules for particular sobject.</description>
        <label>Skip Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <label>SObject</label>
    <pluralLabel>SObjects</pluralLabel>
</CustomObject>

codepkg/objects/Trigger_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>Criteria_Field_API_Name__c</fullName>
        <label>Criteria Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Name__c</fullName>
        <label>Criteria Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Record Type</fullName>
                    <default>true</default>
                    <label>Record Type</label>
                </value>
                <value>
                    <fullName>Object Type</fullName>
                </value>
                <value>
                    <fullName>User Profile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Criteria_Operator__c</fullName>
        <label>Criteria Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>==</fullName>
                    <default>true</default>
                    <label>==</label>
                </value>
                <value>
                    <fullName>!=</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Criteria_Value__c</fullName>
        <label>Criteria Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SObject__c</fullName>
        <label>SObject</label>
        <referenceTo>SObject__mdt</referenceTo>
        <relationshipLabel>Trigger Configs</relationshipLabel>
        <relationshipName>Trigger_Configs</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Trigger Config</label>
    <pluralLabel>Trigger Configs</pluralLabel>
</CustomObject>

codepkg/objects/Validation_Rule_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Error message to be displayed.</description>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SObject__c</fullName>
        <label>SObject</label>
        <referenceTo>SObject__mdt</referenceTo>
        <relationshipLabel>Validation Rule Configs</relationshipLabel>
        <relationshipName>Validation_Rule_Configs</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Validation Rule Config</label>
    <pluralLabel>Validation Rule Configs</pluralLabel>
</CustomObject>

codepkg/classes/MetadataUtility.cls
//get user app name and fetch metadata 
public inherited sharing class MetadataUtility extends TriggerHandler {
    public static List<Trigger_Config__mdt> triggerConfigs;
    
    public MetadataUtility() {
        
    }

    //static initialization 
    {
        triggerConfigs = new List<Trigger_Config__mdt>();
    }

    //Fetch all the metadata Types related to trigger Configuration and SObject Config
    public static Map<String, Object> fetchAllMetadataTypes(String sobjectName) {
        Map<String, Object> returnMap = new Map<String, Object>();
        Object sobjectConfigs = [SELECT ObjectAPIName__c, Bypass_Trigger_Execution__c,
                                        Applicable_Trigger_Handlers__c,Skip_Validation_Rules__c 
                                    FROM SObject__mdt 
                                    WHERE ObjectAPIName__c = :sobjectName LIMIT 1];
        List<Object> triggerConfigs = [SELECT Criteria_Name__c,Criteria_Operator__c,
                                        Criteria_Field_API_Name__c,
                                        Criteria_Value__c,Id,
                                        Is_Active__c,Label
                                    FROM Trigger_Config__mdt 
                                    WHERE SObject__r.ObjectApiName__c = :sobjectName];
        List<Object> validationRuleConfigs = [SELECT Label, Is_Active__c, SObject__c, Error_Message__c
                                                FROM Validation_Rule_Config__mdt
                                                WHERE SObject__r.ObjectAPIName__c = :sobjectName AND Is_Active__c = true];
        returnMap.put('SobjectConfig', sobjectConfigs);
        returnMap.put('ValidationRuleConfigs', validationRuleConfigs);
        returnMap.put('TriggerConfigs', triggerConfigs);
        return returnMap;
    }

    //get current app name for logged in user
    public static String getCurrentAppName() {
        UserAppInfo userApp = [SELECT Id, AppDefinitionId
                                        FROM UserAppInfo WHERE UserId = :UserInfo.getUserId()  ORDER BY CreatedDate DESC LIMIT 1];
        String appName = [SELECT DurableId, Label, DeveloperName FROM AppDefinition
                                            Where DurableId = :userApp.AppDefinitionId LIMIT 1].DeveloperName;
        return appName;
    }

    //get validation rule for sobject
    public static List<Validation_Rule_Config__mdt> getValidationRules(String sobjectName) {
        return [SELECT Label, Is_Active__c, SObject__c FROM Validation_Rule_Config__mdt WHERE SObject__r.ObjectAPIName__c = :sobjectName];
    }

    //Get the application Specific metadata type configuration data 
    public static List<Application_Config__mdt> fetchApplicationConfig() {
        List<Application_Config__mdt> applicationConfigMdtList = [SELECT Id, Bypass_Trigger_Execution__c,
                                                                    Project__c, Sequence__c,Class_to_Execute__c
                                                                    FROM Application_Config__mdt
                                                                    WHERE Bypass_Trigger_Execution__c = false
                                                                    ORDER BY Sequence__c];
        return applicationConfigMdtList;
    }

    
}