codepkg/objects/Application_Contact__c.object
<CustomObject>
    <description>This object is the junction between Home Hardening Application(HH Application) and Contact object.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Application-Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Community_Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Permission_Set_Developer_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>App Permission Set Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>App_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>APP URL(Relative)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Approval_Class__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>User Approval Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <inlineHelpText>For which user this app is applicable?</inlineHelpText>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FEMA</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Homeowner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Document Stage</description>
        <inlineHelpText>The Document Stage</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Applicant/Homeowner Email Address</description>
        <formula>Applicant__r.Email</formula>
        <inlineHelpText>Applicant/Homeowner Email Address</inlineHelpText>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Community_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Application</label>
        <referenceTo>Community_Application__c</referenceTo>
        <relationshipLabel>Community Registration</relationshipLabel>
        <relationshipName>CommunityRegistration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>FEMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <recordTypes>
        <fullName>HMA</fullName>
        <active>true</active>
        <label>HMA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HH_TestHelper.cls
@isTest(seeAllData=false)
public without sharing class HH_TestHelper {


    public static User createPortalUser () {
        Account acc = new Account (
            Name = 'Portal Account'
        );  
        insert acc;
        Contact con = new Contact (
            AccountId = acc.id,
            FirstName = 'FirstName',
            LastName = 'LastName'
        );
        insert con;
        Profile p = [select Id,name from Profile where Name = 'CalOES Portal User' limit 1];
        User newUser = new User(
            profileId = p.id,
            username = 'PortalUser@gmail.com',
            email = 'pb@ff.com',
            emailencodingkey = 'UTF-8',
            localesidkey = 'en_US',
            languagelocalekey = 'en_US',
            timezonesidkey = 'America/Los_Angeles',
            alias='JamesS',
            lastname='Smith',
            IsActive = true,
            contactId = con.id
        );
        insert newUser;     
        return newUser;
    }
    
    public static User createCaloesPortalUser (String uniqueEmail) {
        Account a = getAccount(true);
        Contact con = new Contact (
            AccountId = a.id,
            FirstName = 'John',
            LastName = 'Smith',
            Email = uniqueEmail
        );
        insert con;
        Profile p = [select Id,name from Profile where Name =:HH_CONSTANTS.CALOES_Portal_Profile_Name limit 1];
        User newUser = new User(
            profileId = p.id,
            username = uniqueEmail,
            email = uniqueEmail,
            emailencodingkey = 'UTF-8',
            localesidkey = 'en_US',
            languagelocalekey = 'en_US',
            timezonesidkey = 'America/Los_Angeles',
            alias='John',
            lastname='Smith',
            IsActive = true,
            contactId = con.id
        );
        insert newUser;     
        return newUser;
    }

    

    public static User createCaloesUser() {
        Profile p = [select Id,name from Profile where Name =:HH_CONSTANTS.CALOES_Internal_Profile_Name limit 1];
        User internalUser = new User(
            profileId = p.id,
            username = 'caloes@xyz.com',
            email = 'caloes@xyz.com',
            emailencodingkey = 'UTF-8',
            localesidkey = 'en_US',
            languagelocalekey = 'en_US',
            timezonesidkey = 'America/Los_Angeles',
            alias='JSmith',
            firstname='Jason',
            lastname='Smith',
            IsActive = true
        ); 
        insert internalUser;  
        PermissionSet permissionSet =  [SELECT Id,Name FROM PermissionSet WHERE Name =: HH_CONSTANTS.HH_PermissionSet_CalOESUser_APIName LIMIT 1];
        insert new PermissionSetAssignment(AssigneeId = internalUser.id, PermissionSetId = permissionSet.Id); 
        return internalUser;
    }
    
    
    
    
    public static Community_Application__c getCommunityApplication(boolean create){
        Community_Application__c newCommunityApplication = new Community_Application__c();
        newCommunityApplication.App_Permission_Set_Developer_Name__c = 'HH_Community_Homeowner_User';
        //newCommunityApplication.User_Approval_Class__c = 'PHOS_UserServiceAppHandler';
        //newCommunityApplication.App_URL__c = 'https://uat-caloes.cs33.force.com/hma ';
       // newCommunityApplication.Display_Name__c = 'Hazard Mitigation - NOI Requests Portal  ';
        newCommunityApplication.isActive__c = true;
        newCommunityApplication.Name = 'HH Community Homeowner';
        if(create)
            insert newCommunityApplication;
        return newCommunityApplication;
    }
    
     public static User_Registration__c getUserRegistration(boolean create){
        Account newAccount = HH_TestHelper.getAccount(create);
        User_Registration__c   newUserRegistration = new User_Registration__c();
       
        newUserRegistration.First_Name__c = 'testFirstName';
        newUserRegistration.Last_Name__c = 'testLastName';
        newUserRegistration.Status__c = 'Pending for Approval';
        newUserRegistration.Email__c = 'test@gmail.com';
        newUserRegistration.User_Type__c = 'Community';
        
        if(create)
            insert newUserRegistration;
        return newUserRegistration;
    }


    public static Contact getContact(boolean create){
        Account account = getAccount(create);
        Contact contact = new Contact(Firstname='FirstName',
                                    Lastname='LastName',
                                    Email='email@gmail.com',
                                    Phone = '9652314586',	
                                    AccountId = account.Id);
        if(create)
        insert contact;
        return contact;
    }

    public static Account getAccount(boolean create){
        Account account = new Account(Name = 'HOUSEHOLD-312vg3',AccountSource = 'web',AnnualRevenue = 1800000,Description = 'A bank account is a financial account maintained by a bank or other financial institution in which the financial transactions between the bank and a customer are recorded',
                              NumberOfEmployees = 15,Industry = 'banking',Phone = '8569321475',Rating = 'Warm');
        if(create)
        insert account;
        return account;
    }
    /*public static Document__c getDocument(){
        Document__c doc = new Document__c(Document_Type__c='',Document_Name__c='Test');
        insert doc;
        ContentVersion conVer = new ContentVersion();
        conVer.ContentLocation = 'S'; // S specify this document is in SF, use E for external files
        conVer.PathOnClient = 'ionicLogo.csv'; // The files name, extension is very important here which will help the file in preview.
        conVer.Title = 'Accounts '; // Display name of the files
        conVer.VersionData = EncodingUtil.base64Decode(''); // converting your binary string to Blog
        insert conVer;

        // First get the content document Id from ContentVersion
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;

        //Create ContentDocumentLink
        ContentDocumentLink cDe = new ContentDocumentLink();
        cDe.ContentDocumentId = conDoc;
        cDe.LinkedEntityId = doc.Id; // you can use objectId,GroupId etc
        cDe.ShareType = 'I'; // Inferred permission, checkout description of ContentDocumentLink object for more details
        cDe.Visibility = 'AllUsers';
        insert cDe;
        return doc;
    }*/

    public static HH_Application__c getApplication (Boolean addApplicationContact,Boolean create) {
        HH_Application__c application = new HH_Application__c();
        if(create) {
            insert application;
        }
        Contact c1 = HH_TestHelper.getContact(false);
        c1.FirstName = 'Jerry';
        c1.LastName = 'Jason';
        insert c1;
        Application_Contact__c ac = new Application_Contact__c();
        ac.HH_Application__c = application.Id;
        ac.Contact__c = c1.Id;
        ac.Head_of_Household__c = 'Yes';
        if(create && addApplicationContact) {
            insert ac;
        }
        return application;
    }

    
}