codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Disaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Disaster</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subapplicant_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subapplicant Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Application_Extension__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Extensions</relationshipLabel>
        <relationshipName>Application_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Extension</label>
    <nameField>
        <displayFormat>AE-{00000}</displayFormat>
        <label>Application Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Application_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Extension</label>
        <referenceTo>Application_Extension__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocuSign_Envelope_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DocuSign Envelope Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Working Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Responsible Representative</fullName>
                </value>
                <value>
                    <fullName>Match Commitment</fullName>
                </value>
                <value>
                    <fullName>Maintenance Commitment</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic Analyst</fullName>
                </value>
                <value>
                    <fullName>Authorized Agent</fullName>
                    <isActive>false</isActive>
                    <label>Authorized Agent</label>
                </value>
                <value>
                    <fullName>Requestor</fullName>
                    <isActive>false</isActive>
                    <label>Requestor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Signature_Status__c</fullName>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent For Signature</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HMGP_SendDocuSignToResponsibleRepCtrl.cls
public without sharing class HMGP_SendDocuSignToResponsibleRepCtrl implements PageTableActionsInterface{
    public Map<String, Object> executeAction(String parentId, String rowId) {
        Map<String, Object> returnMap = new Map<String, Object>();
        returnMap.put('isSuccess', false);
        try{
            //Application__c app = [SELECT Id, Subapplicant_Entity__c, Disaster__c from Application__c WHERE Id=:String.escapeSingleQuotes(parentId)];
            Application_Extension__c appExt = [SELECT Id, Application__c, Application__r.Subapplicant_Entity__c, Application__r.Disaster__c from Application_Extension__c WHERE Id=:String.escapeSingleQuotes(parentId)];
            Contact_Role__c contactRole = [SELECT Id, Contact__c, Role__c from Contact_Role__c WHERE Id=:String.escapeSingleQuotes(rowId)];
            if(appExt != null && appExt.Application__r.Subapplicant_Entity__c != null && appExt.Application__r.Disaster__c != null && contactRole != null && contactRole.Contact__c != null){
                List<Id> recordIds = new List<Id>();
                String templateIdMaintenanceCommitment = KeyValueHelper.getTextValue('Docusign_Maintenance_Commitment_TempId');
                if(contactRole.Role__c.contains('Maintenance Commitment')){
                    recordIds = new List<Id> {parentId, appExt.Application__c, appExt.Application__r.Subapplicant_Entity__c, appExt.Application__r.Disaster__c, contactRole.Contact__c};
                }else if(contactRole.Role__c.contains('Match Commitment')){
                    recordIds = new List<Id> {parentId, appExt.Application__c, appExt.Application__r.Subapplicant_Entity__c, contactRole.Contact__c};
                    templateIdMaintenanceCommitment = KeyValueHelper.getTextValue('Docusign_Match_Commitment_TempId');
                }
                //List<Id> recordIds = new List<Id> {parentId, app.Subapplicant_Entity__c, app.Disaster__c, contactRole.Contact__c};
                DocuSignIntegrationCtrl docusignObject = new DocuSignIntegrationCtrl(templateIdMaintenanceCommitment, contactRole.Contact__c, recordIds);
                String envelopeId = docusignObject.docuSignEnvelopeGenerator();
                if(String.isNotEmpty(envelopeId)){
                    update new Contact_Role__c(Id=contactRole.Id, Signature_Status__c ='Sent For Signature', DocuSign_Envelope_Id__c = envelopeId);
                }
                returnMap.put('isSuccess', true);
            }
        }catch(Exception e){
            returnMap.put('errorMsg', e.getMessage());
        }
        return returnMap;
    }
}