codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <inlineHelpText>Planning activities include developing a new Hazard Mitigation Plan or updating a current plan.</inlineHelpText>
        <label>Subapplication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Planning-related</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Advance Assistance</fullName>
                </value>
                <value>
                    <fullName>5% Initiative</fullName>
                </value>
                <value>
                    <fullName>Flood Hazard Mitigation Planning</fullName>
                </value>
                <value>
                    <fullName>Project Scoping</fullName>
                </value>
                <value>
                    <fullName>Community Flood Mitigation Project</fullName>
                </value>
                <value>
                    <fullName>Individual Flood Mitigation Project</fullName>
                </value>
                <value>
                    <fullName>Capability and Capacity Building (C&amp;CB)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_this_project_phased__c</fullName>
        <inlineHelpText>Is this project phased?</inlineHelpText>
        <label>Is this project phased?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subapplicant_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subapplicant Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Work_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Work Schedules</relationshipLabel>
        <relationshipName>Work_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Work Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Work_Schedule_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_Months__c</fullName>
        <label>Duration (Months)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phase 1</fullName>
                </value>
                <value>
                    <fullName>Phase 2</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Task Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Schedule__c</fullName>
        <label>Work Schedule</label>
        <referenceTo>Work_Schedule__c</referenceTo>
        <relationshipLabel>Work Schedules Line Items</relationshipLabel>
        <relationshipName>Work_Schedules_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Schedule Line Item</label>
    <nameField>
        <displayFormat>WSLI-{000000}</displayFormat>
        <label>Work Schedule Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedules Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/ApplicationHelper.cls
public with sharing class ApplicationHelper {
    public static void processToCreateWSAndWSLI(Set<Id> appIds) {
        try {
            //Map<String, Set<Id>> paramMap = new Map<String, Set<Id>>();
            Set<Id> appIdsOfPlanning = new Set<Id>();
            Set<Id> appIdsOfPhasedNo = new Set<Id>();
            Set<Id> appIdsOfPhasedYes = new Set<Id>();
            if(appIds.size() > 0) {
                List<Application__c> appDetailList = [SELECT Id, 
                                                                Application_Type__c, 
                                                                Subapplicant_Entity__c,
                                                                Subapplicant_Entity__r.Is_this_project_phased__c,
                                                                (SELECT Id FROM Work_Schedules__r)
                                                                FROM Application__c WHERE Id IN: appIds];
    
                for(Application__c app : appDetailList) {
                    if(app.Application_Type__c == HMA_CONSTANTS.APPLICATION_SUBAPPLICATION_TYPE_PLANNING) {
                        appIdsOfPlanning.add(app.Id);
                    } else if(checkSubApplicationType(app.Application_Type__c) && app.Subapplicant_Entity__r.Is_this_project_phased__c == 'No') {
                        appIdsOfPhasedNo.add(app.Id);
                    } else if(checkSubApplicationType(app.Application_Type__c) && app.Subapplicant_Entity__r.Is_this_project_phased__c == 'Yes') {
                        appIdsOfPhasedYes.add(app.Id);
                    }
                }

                if(appIdsOfPlanning.size() > 0) {
                    ApplicationHelper.deleteWorkSchedules(appIdsOfPlanning);
                    ApplicationHelper.createWorkSchedules(new Map<String,Set<Id>>{'appIdsOfPlanning' => appIdsOfPlanning});
                }
                if(appIdsOfPhasedNo.size() > 0) {
                    ApplicationHelper.deleteWorkSchedules(appIdsOfPhasedNo);
                    ApplicationHelper.createWorkSchedules(new Map<String,Set<Id>>{'appIdsOfPhasedNo' => appIdsOfPhasedNo});
                }
                if(appIdsOfPhasedYes.size() > 0) {
                    ApplicationHelper.deleteWorkSchedules(appIdsOfPhasedYes);
                    ApplicationHelper.createWorkSchedules(new Map<String,Set<Id>>{'appIdsOfPhasedYes' => appIdsOfPhasedYes});
                }
            }
        } catch (Exception e) {
            System.debug('error_processToCreateWSAndWSLI: ' + e);
            throw new AuraHandledException(e.getMessage());
        }               
    }
    
    public static void createWorkSchedules(Map<String,Set<Id>> paramMap) {
        Set<Id> WSIds = new Set<Id>();
        List<Work_Schedule__c> workSchedules = new List<Work_Schedule__c>();
        for(Id appId : paramMap.values()[0]) {
            Work_Schedule__c ws = new Work_Schedule__c(Application__c = appId);
            workSchedules.add(ws);
        }        
        insert workSchedules;
        for(Work_Schedule__c workS : workSchedules) {
            WSIds.add(workS.Id);
        }
        if(paramMap.keySet().contains('appIdsOfPlanning')) {
            ApplicationHelper.createWorkScheduleLineItems(WSIds);
            ApplicationHelper.createCloseoutWorkScheduleLineItems(WSIds);
        } else if(paramMap.keySet().contains('appIdsOfPhasedNo')) {
            ApplicationHelper.createCloseoutWorkScheduleLineItems(WSIds);
        } else if(paramMap.keySet().contains('appIdsOfPhasedYes')) {
            ApplicationHelper.createPhaseWorkScheduleLineItems(WSIds);
            ApplicationHelper.createCloseoutWorkScheduleLineItems(WSIds);
        }
    }


    public static void createWorkScheduleLineItems(Set<Id> WSIds) {
        try {
            List<Work_Schedule_Line_Item__c> WSLIList = new List<Work_Schedule_Line_Item__c>();
            List<String> phasePicklistValues = new List<String>();
            phasePicklistValues.add(HMA_CONSTANTS.WSLI_PHASE_THE_PLANNING_PROCESS);
            phasePicklistValues.add(HMA_CONSTANTS.WSLI_PHASE_HAZARD_IDENTIFICATION);
            phasePicklistValues.add(HMA_CONSTANTS.WSLI_PHASE_RISK_ASSESSMENT);
            phasePicklistValues.add(HMA_CONSTANTS.WSLI_PHASE_MITIGATION_STRATEGY);
            phasePicklistValues.add(HMA_CONSTANTS.WSLI_PHASE_PLAN_PREPARATION);
            phasePicklistValues.add(HMA_CONSTANTS.WSLI_PHASE_PLAN_DRAFTING);
            phasePicklistValues.add(HMA_CONSTANTS.WSLI_PHASE_PUBLIC_OUTREACH_MEETINGS_PUBLICHEARINGS);
            phasePicklistValues.add(HMA_CONSTANTS.WSLI_PHASE_PLAN_ADOPTION);

            for(Id WSId : WSIds) {
                for(String phaseValue : phasePicklistValues) {                        
                    Work_Schedule_Line_Item__c wsli = new Work_Schedule_Line_Item__c(Work_Schedule__c = WSId, Phase__c = phaseValue);
                    WSLIList.add(wsli);
                }
            }            
            insert WSLIList;
            
        } catch (Exception e) {
            System.debug('error: ' + e);
        }
    }
    public static void createPhaseWorkScheduleLineItems(Set<Id> WSIds) {
        List<Work_Schedule_Line_Item__c> WSLIList = new List<Work_Schedule_Line_Item__c>();
        for(Id WSId : WSIds) {
            Work_Schedule_Line_Item__c wsliPhase1 = new Work_Schedule_Line_Item__c(Work_Schedule__c = WSId, Phase__c = HMA_CONSTANTS.WSLI_PHASE_PHASE1);
            Work_Schedule_Line_Item__c wsliPhase2 = new Work_Schedule_Line_Item__c(Work_Schedule__c = WSId, Phase__c = HMA_CONSTANTS.WSLI_PHASE_PHASE2);
            WSLIList.add(wsliPhase1);
            WSLIList.add(wsliPhase2);
        }
        insert WSLIList;
    }
    public static void createCloseoutWorkScheduleLineItems(Set<Id> WSIds) {
        List<Work_Schedule_Line_Item__c> WSLIList = new List<Work_Schedule_Line_Item__c>();
        for(Id WSId : WSIds) {
            Work_Schedule_Line_Item__c wsli = new Work_Schedule_Line_Item__c(Work_Schedule__c = WSId, Phase__c = 'Closeout', Task_Name__c = 'Closeout', Description__c = 'Project Closeout line item', Duration_Months__c = '3');
            WSLIList.add(wsli);
        }
        insert WSLIList;
    }

    
    public static void deleteWorkSchedules(Set<Id> appIds) {
        try {
            List<Work_Schedule__c> wsList = new List<Work_Schedule__c>();
            wsList = [SELECT Id FROM Work_Schedule__c WHERE Application__c IN: appIds];
            if(wsList.size() > 0) {
                delete wsList;
            }            
            //delete[SELECT Id FROM Work_Schedule__c WHERE Application__c IN: appIds];
        } catch (Exception e) {
            System.debug('error: ' + e);
        }
    }
    private static Boolean checkSubApplicationType(String subApplicationType) {
        return (subApplicationType == HMA_CONSTANTS.APPLICATION_SUBAPPLICATION_TYPE_PROJECT || 
                subApplicationType == HMA_CONSTANTS.APPLICATION_SUBAPPLICATION_TYPE_5INITIATIVE || 
                subApplicationType == HMA_CONSTANTS.APPLICATION_SUBAPPLICATION_TYPE_PLANNING_RELATED) ? true : false;
    }
}