codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Acquisition Demo Relocation is the purchase of properties voluntarily to remove structure(s) from natural hazards (flood/landslide/avalanche.) Structures must be demolished or relocated outside hazards.</inlineHelpText>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Plan</fullName>
                </value>
                <value>
                    <fullName>Plan Update</fullName>
                </value>
                <value>
                    <fullName>Planning-Related Activities</fullName>
                </value>
                <value>
                    <fullName>Acquisition Demo-Relocation</fullName>
                </value>
                <value>
                    <fullName>Drainage/Flood Control</fullName>
                </value>
                <value>
                    <fullName>Elevation-Floodproofing</fullName>
                </value>
                <value>
                    <fullName>Safe Room/Shelter</fullName>
                </value>
                <value>
                    <fullName>Seismic Retrofitting</fullName>
                </value>
                <value>
                    <fullName>Wildfire &amp; Vegetation Management</fullName>
                </value>
                <value>
                    <fullName>Generator(s)/Other Power Source(s)</fullName>
                </value>
                <value>
                    <fullName>Mitigation Reconstruction</fullName>
                </value>
                <value>
                    <fullName>Tsunami Vertical Evacuation</fullName>
                </value>
                <value>
                    <fullName>Advance Assistance</fullName>
                </value>
                <value>
                    <fullName>Post-Disaster Code Enforcement</fullName>
                </value>
                <value>
                    <fullName>Public Awareness and Education</fullName>
                </value>
                <value>
                    <fullName>Early Warning Systems</fullName>
                </value>
                <value>
                    <fullName>Hazard Identification or Mapping</fullName>
                </value>
                <value>
                    <fullName>GIS for Mitigation</fullName>
                </value>
                <value>
                    <fullName>New Techniques/Methods</fullName>
                </value>
                <value>
                    <fullName>Project Scoping</fullName>
                </value>
                <value>
                    <fullName>Nature-Based Solutions/Green Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Planning-New Plan</fullName>
                </value>
                <value>
                    <fullName>Partnerships</fullName>
                </value>
                <value>
                    <fullName>Building Code</fullName>
                </value>
                <value>
                    <fullName>Planning-Plan Update</fullName>
                </value>
                <value>
                    <fullName>Utility and Infrastructure Protection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending OES Review</fullName>
                </value>
                <value>
                    <fullName>Analyst Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Analyst Review Complete</fullName>
                </value>
                <value>
                    <fullName>OES RFI In Progress</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>OES Subapplication Review Complete</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Selected for Submission to FEMA</fullName>
                </value>
                <value>
                    <fullName>Not Selected - Pending Future Consideration</fullName>
                </value>
                <value>
                    <fullName>Submitted to FEMA</fullName>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Pending</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Review Pending</fullName>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>By Subapplicant after funds are obligated</fullName>
                </value>
                <value>
                    <fullName>By Subapplicant with no funds obligated</fullName>
                </value>
                <value>
                    <fullName>By OES</fullName>
                </value>
                <value>
                    <fullName>Waitlist Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>OES Review</fullName>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Program_Document__c.object
<CustomObject>
    <label>Program Document</label>
    <nameField>
        <displayFormat>PDM-{00000}</displayFormat>
        <label>Program Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HMA_ApplicationTriggerHandlerTest.cls
@isTest 
public with sharing class HMA_ApplicationTriggerHandlerTest {
    @isTest 
    public static void testTriggerMethod() {
        test.startTest();
        Application__c applicationProjectYes = HMA_TestHelper.getApplication(true, '', '', 'Yes');
        test.stopTest();
    }
    @isTest 
    public static void testTriggerMethod1() {
        test.startTest();
        //Program_Document__c proDoc = HMA_TestHelper.getProgramDocument(true, 'Work Schedule', 'Work Schedule');
        Application__c applicationAANo = HMA_TestHelper.getApplication(true, 'Advance Assistance', 'Acquisition Demo-Relocation', 'No');
        applicationAANo.Project_Type__c = 'Elevation-Floodproofing';
        update applicationAANo;
        test.stopTest();
    }
    @isTest 
    public static void testTriggerMethod2() {
        test.startTest();
        Application__c applicationplanning = HMA_TestHelper.getApplication(true, 'Planning', 'New Plan', 'Yes');
        test.stopTest();
    }

    //This method tests the application update scenario for FEMA Review status for application.
    /*@isTest
    public static void testUpdateApplicationScenario() {
        User user = HMA_TestHelper.getUser(false);
        //HMA_TestHelper.assignPermissionSet(user, 'HMA_Analyst_User');
        Application__c app = HMA_TestHelper.getApplication(false, '', '', '');
        Contact contact = HMA_TestHelper.getPortalContact(true);
        app.Status__c = 'Draft';
        app.Status_Reason__c = 'In Progress';
        insert app;
        Test.startTest();
        Account acc = HMA_TestHelper.getAccount(false);
        acc.Name = 'FEMA Account';
        insert acc;
        Contact_Role__c contactRole = HMA_TestHelper.getContactRoleForSpecificApplication(true, app, contact.Id, 'FEMA EHP Analyst');
        app.Status__c = 'FEMA Review';
        app.Status_Reason__c = 'Submitted to FEMA';
        update app;
        System.assert(app.Status__c == 'FEMA Review');
        Test.stopTest();
    }*/
}