codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Application_Extension__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Extensions</relationshipLabel>
        <relationshipName>Application_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Extension</label>
    <nameField>
        <displayFormat>AE-{00000}</displayFormat>
        <label>Application Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Application_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Extension</label>
        <referenceTo>Application_Extension__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Working Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Responsible Representative</fullName>
                </value>
                <value>
                    <fullName>Match Commitment</fullName>
                </value>
                <value>
                    <fullName>Maintenance Commitment</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic Analyst</fullName>
                </value>
                <value>
                    <fullName>Authorized Agent</fullName>
                    <isActive>false</isActive>
                    <label>Authorized Agent</label>
                </value>
                <value>
                    <fullName>Requestor</fullName>
                    <isActive>false</isActive>
                    <label>Requestor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Pre_Application__c.object
<CustomObject>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pre-Applications</relationshipLabel>
        <relationshipName>Pre_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Work_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Work Schedules</relationshipLabel>
        <relationshipName>Work_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Work Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Work_Schedule_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_Months__c</fullName>
        <label>Duration (Months)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Task Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Schedule__c</fullName>
        <label>Work Schedule</label>
        <referenceTo>Work_Schedule__c</referenceTo>
        <relationshipLabel>Work Schedules Line Items</relationshipLabel>
        <relationshipName>Work_Schedules_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Schedule Line Item</label>
    <nameField>
        <displayFormat>WSLI-{000000}</displayFormat>
        <label>Work Schedule Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedules Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/PageTableControllerTest.cls
@isTest
public without sharing class PageTableControllerTest {
    @isTest public static void testGetTableRecordDetails() {
        Map<String, Object> returnMap = new Map<String, Object>();
        List<String> tableColumnNames = new List<String>();
        tableColumnNames.add('Task_Name__c');
        tableColumnNames.add('Description__c');
        tableColumnNames.add('Start_Month__c');
        tableColumnNames.add('Duration_Months__c');

        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        Work_Schedule__c ws = HMA_TestHelper.getWorkSchedule(true, newApplication.Id);
        Work_Schedule_Line_Item__c wsli = HMA_TestHelper.getWorkScheduleLineItem(true, ws.Id);
        String whereClause = 'Work_Schedule__r.Application__c=\'' + newApplication.Id+'\'  AND Work_Schedule__c= \'{parentRecordId}\'' ;
        String getParentRecordQuery = 'SELECT Id from Work_Schedule__c WHERE Application__c = \''+ newApplication.Id +'\' LIMIT 1';

        returnMap = PageTableController.getTableRecordDetails(tableColumnNames, 'Work_Schedule_Line_Item__c', '1', whereClause, getParentRecordQuery);
        System.assert(returnMap.size() > 0);
    }

    @isTest public static void testUpdateObjectDetails() {
        List<Work_Schedule_Line_Item__c> wsliList = new List<Work_Schedule_Line_Item__c>();

        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        Work_Schedule__c ws = HMA_TestHelper.getWorkSchedule(true, newApplication.Id);
        Work_Schedule_Line_Item__c wsli = HMA_TestHelper.getWorkScheduleLineItem(true, ws.Id);
        wsliList.add(wsli);
        Boolean isUpdateObject = PageTableController.updateObjectDetails(wsliList);
        System.assert(isUpdateObject == true);
    }
    @isTest public static void testUpdateObjectDetails1() {
        List<Work_Schedule_Line_Item__c> wsliList = new List<Work_Schedule_Line_Item__c>();
        Boolean isUpdateObject = PageTableController.updateObjectDetails(wsliList);
        System.assert(isUpdateObject == false);
    }
    @isTest public static void testDeleteTableRowRecord() {
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        Work_Schedule__c ws = HMA_TestHelper.getWorkSchedule(true, newApplication.Id);
        Work_Schedule_Line_Item__c wsli = HMA_TestHelper.getWorkScheduleLineItem(true, ws.Id);

        PageTableController.deleteTableRowRecord(wsli.Id);
    }

    /**Test method for Send For Signature logic */
    @isTest public static void testExecuteTableAction() {
        Map<String, Object> returnMap = new Map<String, Object>();
        Application__c newApplication = HMA_TestHelper.getApplication(true, '', '', '');
        Application_Extension__c aapEx = HMA_TestHelper.getApplicationExension(true, newApplication.Id);
        Pre_Application__c PreApplication = [Select Id, Requestor__c from Pre_Application__c WHERE Id =: newApplication.Pre_Application__c LIMIT 1];
        Contact_Role__c conRole = HMA_TestHelper.getContactRole(false);
        conRole.Application__c = newApplication.Id;
        conRole.Contact__c = PreApplication.Requestor__c;
        conRole.Role__c = 'Match Commitment';
        insert conRole;

        returnMap = PageTableController.executeTableAction(aapEx.Id, conRole.Id, 'HMGP_SendDocuSignToResponsibleRepCtrl');
        System.assert(returnMap.size() > 0);
    }
}