codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Project_Plan_Duration_in_Months__c</fullName>
        <inlineHelpText>Indicate the number of months it will take for this mitigation action to be implemented. Cannot exceed 36 months (33 months implementation plus 3 months for closeout)</inlineHelpText>
        <label>Project / Plan Duration (in Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Work_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Work Schedules</relationshipLabel>
        <relationshipName>Work_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Plan_Duration_In_Months__c</fullName>
        <defaultValue>00</defaultValue>
        <label>Project / Plan Duration (In Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Work Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Work_Schedule_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Duration_Months__c</fullName>
        <label>Duration (Months)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Schedule__c</fullName>
        <label>Work Schedule</label>
        <referenceTo>Work_Schedule__c</referenceTo>
        <relationshipLabel>Work Schedules Line Items</relationshipLabel>
        <relationshipName>Work_Schedules_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Schedule Line Item</label>
    <nameField>
        <displayFormat>WSLI-{000000}</displayFormat>
        <label>Work Schedule Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedules Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/HMA_WorkScheduleLineItemTriggerHandler.cls
public without sharing class HMA_WorkScheduleLineItemTriggerHandler extends TriggerHandler implements TriggerInterface {
    public HMA_WorkScheduleLineItemTriggerHandler() {

    }
    public override void beforeTrigger() {
    }

    public override void beforeInsert() {
        
    } 
    public override void afterInsert() {
        Set<Id> workScheduleIds = new Set<Id>();
        for(Work_Schedule_Line_Item__c wsli : (List<Work_Schedule_Line_Item__c>) Trigger.New) {  
            if(String.isNotEmpty(wsli.Work_Schedule__c)) {
                workScheduleIds.add(wsli.Work_Schedule__c);
            }            
        }
        System.debug('workScheduleIds : '+ workScheduleIds);
        if(workScheduleIds.size() > 0) {
            HMA_WorkScheduleLineItemTriggerHandler.calculateWorkSchedulePlanDuration(workScheduleIds);       
        }
    }
    public override void beforeUpdate() {
        
    } 
    public override void afterUpdate() {
        Set<Id> workScheduleIds = new Set<Id>();
        for(Work_Schedule_Line_Item__c wsli : (List<Work_Schedule_Line_Item__c>) Trigger.New) {  
            if(String.isNotEmpty(wsli.Work_Schedule__c)) {
                workScheduleIds.add(wsli.Work_Schedule__c);
            }            
        }
        System.debug('workScheduleIds : '+ workScheduleIds);
        if(workScheduleIds.size() > 0) {
            HMA_WorkScheduleLineItemTriggerHandler.calculateWorkSchedulePlanDuration(workScheduleIds);       
        }
    }

    public static void calculateWorkSchedulePlanDuration(Set<Id> workScheduleIds) {
        Map<Id, List<Work_Schedule_Line_Item__c>> wsIdToWsliMap = new Map<Id, List<Work_Schedule_Line_Item__c>>();
        Map<Id, Integer> wsIdToTotalDurationMap = new Map<Id, Integer>();
        List<Work_Schedule__c> wsToUpdate = new List<Work_Schedule__c>();

        List<Work_Schedule_Line_Item__c>  relatedWsli = [SELECT Id, Work_Schedule__c, Start_Month__c, Duration_Months__c FROM Work_Schedule_Line_Item__c WHERE Work_Schedule__c IN: workScheduleIds];
        System.debug('relatedWsli : ' + relatedWsli);
        for(Work_Schedule_Line_Item__c wsliRec : relatedWsli) {
            if(wsIdToWsliMap.get(wsliRec.Work_Schedule__c) == null) {
                wsIdToWsliMap.put(wsliRec.Work_Schedule__c, new List<Work_Schedule_Line_Item__c>());
            }
            wsIdToWsliMap.get(wsliRec.Work_Schedule__c).add(wsliRec);
        }
        for(Id wsId : wsIdToWsliMap.keySet()) {
            List<Work_Schedule_Line_Item__c> wsliList = wsIdToWsliMap.get(wsId);
            Integer maxSum = 0;
            for(Work_Schedule_Line_Item__c wsli : wsliList) {
                System.debug('wsli : ' + wsli);
                Integer sum = HMA_WorkScheduleLineItemTriggerHandler.getIntegerFromString(wsli.Start_Month__c) + HMA_WorkScheduleLineItemTriggerHandler.getIntegerFromString(wsli.Duration_Months__c);
                if(sum > maxSum) {
                    maxSum = sum;
                }
            }
            maxSum = maxSum + 3;       // Adding Closeout Row Duration Values & Closeout Duration is fixed
            wsIdToTotalDurationMap.put(wsId, maxSum);
        }
        System.debug('wsIdToTotalDurationMap : ' + wsIdToTotalDurationMap);
        List<Work_Schedule__c> wsList = [SELECT Id, Application__c, Project_Plan_Duration_In_Months__c FROM Work_Schedule__c WHERE Id IN: wsIdToTotalDurationMap.keySet()];
        for(Work_Schedule__c ws : wsList) {
            ws.Project_Plan_Duration_In_Months__c = wsIdToTotalDurationMap.get(ws.Id);
            wsToUpdate.add(ws);
        }
        update wsToUpdate;
    }
    public static Integer getIntegerFromString(String value) {
        if(String.isNotEmpty(value)) {
            return Integer.valueOf(value);
        } else {
            return 0;
        }
    }
}