codepkg/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending OES Review</fullName>
                </value>
                <value>
                    <fullName>Analyst Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Analyst Review Complete</fullName>
                </value>
                <value>
                    <fullName>OES RFI In Progress</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>OES Subapplication Review Complete</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Selected for Submission to FEMA</fullName>
                </value>
                <value>
                    <fullName>Not Selected - Pending Future Consideration</fullName>
                </value>
                <value>
                    <fullName>Submitted to FEMA</fullName>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Pending</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Review Pending</fullName>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>By Subapplicant after funds are obligated</fullName>
                </value>
                <value>
                    <fullName>By Subapplicant with no funds obligated</fullName>
                </value>
                <value>
                    <fullName>By OES</fullName>
                </value>
                <value>
                    <fullName>Waitlist Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>OES Review</fullName>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HMA_FEMAAppDetailsCtrlTest.cls
@isTest
public with sharing class HMA_FEMAAppDetailsCtrlTest {
    @isTest
    public static void testSaveApplication() {
        Application__c app = HMA_TestHelper.getApplication(false, '', '', '');
        app.Status__c = 'FEMA Review';
        app.Status_Reason__c = 'Submitted to FEMA';
        insert app;
        Test.startTest();
        Map<String, Object> returnMap = HMA_FEMAApplicationDetailsCtrl.saveApplication(JSON.serialize(app));
        System.assert(returnMap.size()>0);
        Test.stopTest();
    }

    @isTest
    public static void testGetCurrentUserContactRole() {
        User user = HMA_TestHelper.getPortalUserHMA(false);
        Application__c app = HMA_TestHelper.getApplication(true, '', '', '');
        Contact contact = HMA_TestHelper.getPortalContact(true);
        user.ContactId = contact.Id;
        user.IsActive = true;
        insert user;
        System.debug('User in FEma---'+user.Id);
        Id uId = user.Id;
        String userStringId = String.valueOf(uId);
        System.debug('User in FEma String---'+userStringId);
        Contact_Role__c contactRole = HMA_TestHelper.getContactRoleForSpecificApplication(true, app, contact.Id, 'Responsible Representative');
        System.runAs(user) {
            Test.startTest();
            Map<String, Object> returnMap = HMA_FEMAApplicationDetailsCtrl.getCurrentUserContactRole(app.Id);
            System.assert(returnMap.size() > 0);
            Test.stopTest();
        }
}
}