codepkg/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project for which this Award is created.</description>
        <inlineHelpText>Project for which this Award is created.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <displayFormat>AW-{000000}</displayFormat>
        <label>Award Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Funding_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <formula>IF(  Program_Name__r.Name   = &quot;PA - Federal&quot;  || Program_Name__r.Name  = &quot;PA - FMAG&quot;, Incident_Name__r.Declaration_Number__c, 
IF(Program_Name__r.Name = &quot;CDAA (State Funding)&quot;, Incident_Name__r.State_Declaration_Number__c, &quot;&quot;)
)</formula>
        <label>Declaration Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Incident / Disaster Name</description>
        <inlineHelpText>The Incident Name related to this Funding Opportunity</inlineHelpText>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The record owner. Should be a Programs Profile or Role</description>
        <inlineHelpText>The Staff Member who owns the record</inlineHelpText>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program that issued with this Funding Opportunity</description>
        <inlineHelpText>Program Name for the funding Opportunity ( Ex: PA-Federal, HMGP etc.).</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>What is the Stage of this Funding Opportunity.</description>
        <inlineHelpText>Status of Funding Opportunity ( Ex: Draft, Pending, Approved etc.).</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Disaster Grant / Funding Opportunity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disaster Grants / Funding Opps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Federal Incident Declaration Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Incident Declaration Number. DR number if a Major Disaster, CDAA Number if CDAA-Only, etc.</inlineHelpText>
        <label>Declaration Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Federal_Small_Project_Threshold__c</fullName>
        <description>The Federal Small Project Threshold Amount</description>
        <inlineHelpText>The Federal Small Project Threshold Amount</inlineHelpText>
        <label>Federal Small Project Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Financial Closeout - FPU In Progress</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout FPU - Closed</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - In Review</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - Awaiting FEMA Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Small_Project_Threshold__c</fullName>
        <description>The State Small Project Threshold Amount</description>
        <inlineHelpText>The State Small Project Threshold Amount</inlineHelpText>
        <label>State Small Project Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>Funding_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To compare Funding Opportunity of Service Location / Encumbrance.
Used for Look up filter configuration.</description>
        <inlineHelpText>To compare Funding Opportunity of Service Location / Encumbrance.
Used for Look up filter configuration.</inlineHelpText>
        <label>Disaster Grant/FO</label>
        <referenceTo>Funding_Opportunity__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project for which this Payment is Requested?</description>
        <inlineHelpText>Project for which this Payment is Requested?</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of Payment Request</description>
        <inlineHelpText>Stage of Payment Request</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Reviewed - Needs Information</fullName>
                </value>
                <value>
                    <fullName>Payment Processing</fullName>
                </value>
                <value>
                    <fullName>Returned Project Payment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Parent Program</description>
        <inlineHelpText>If the Program you are adding is not one of the Programs in this list, please select the parent Program from this list.</inlineHelpText>
        <label>Parent Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Related Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>DUNS_Expiration_Date__c</fullName>
        <description>DUNS Expiration Date of Obligating Sub Recipient.</description>
        <formula>Obligating_Sub_Recipient__r.DUNS_Expiration_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date when the DUNS registration expires on SAM.gov</inlineHelpText>
        <label>SAM Registration Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Declaration Number of the Incident.</description>
        <formula>Incident_Name__r.Declaration_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Declaration Number assigned to a Disaster/Incident.</inlineHelpText>
        <label>Declaration Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Funding Opportunity Name</description>
        <inlineHelpText>Specific Funding Opportunity for the Grant (Program+Incident+Declaration Number).</inlineHelpText>
        <label>Disaster Grant/FO</label>
        <referenceTo>Funding_Opportunity__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The name of the Incident</description>
        <inlineHelpText>Disaster/Incident for which the project is related. Not all projects will have an associated Incident.</inlineHelpText>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Name, Derives from Disaster Grant/FO.</description>
        <inlineHelpText>The grant program from which the Project originates. This field is used for reporting.</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Transmittal__c.object
<CustomObject>
    <description>To store the Transmittal of Payment request.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project of the Payment Request.</description>
        <inlineHelpText>Project of the Payment Request.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Transmittals</relationshipLabel>
        <relationshipName>Transmittals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transmittal</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transmittal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transmittals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/ALS_TransmittalPreviewCtrlTest.cls
/**
 * Created by StackNexus Admin on 11-01-2021.
 */
@IsTest
public with sharing class ALS_TransmittalPreviewCtrlTest {
@IsTest
    public static void testTransmittalPreviewMethod()
{
    Date startDate = system.today()+1;
    Date EndDate = system.today()+10;
    Profile pf= [Select Id from profile where Name='System Administrator'];
    String orgId=UserInfo.getOrganizationId();
    String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
    Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000));
    String uniqueName=orgId+dateString+RandomId;
    User uu=new User(firstname = 'ABC',
            lastName = 'XYZ',
            email = uniqueName + '@test' + orgId + '.org',
            Username = uniqueName + '@test' + orgId + '.org',
            EmailEncodingKey = 'ISO-8859-1',
            Alias = uniqueName.substring(18, 23),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            ProfileId = pf.Id
    );
    insert uu;
    Program__c prP = new Program__c(Name='Test Program Parent');
    insert prP;
    Program__c pr3 = new Program__c(Name='Test Program update', Parent_Program__c=prP.Id);
    insert pr3;
    Incident__c inc = new Incident__c(Name = 'Test Incident FP',Declaration_Number__c = '4456',State_Small_Project_Threshold__c=200,Federal_Small_Project_Threshold__c=200);
    insert inc;
    Funding_Opportunity__c fp2=new Funding_Opportunity__c(Name='Test FP ',Program_Name__c=pr3.Id,Incident_Name__c=inc.Id, Owner__c=uu.Id);
    insert fp2;
    Account account =new Account(DUNS__c = '1234',Sub_Recipient_FIPS__c='1234',Email_Address__c='test@gmail.com',Name ='Test Account' ,Entity_Type__c=ALS_CONSTANTS.Account_EntityType_City,DUNS_Expiration_Date__c =EndDate,FFATAExpirationDate__c =EndDate);
    insert account;
    Project__c project =new Project__c(Funding_Opportunity_Name__c=fp2.Id,Stage__c=ALS_CONSTANTS.Project_Stage_ActivePayment,Start_Date__c = startDate,End_Date__c= EndDate,Total_Project_Award__c=1000,State_Share__c=10,FEMA_Share__c =80,FundingSource__c=ALS_CONSTANTS.Project_FundingSource_FederalAndState,Obligating_Sub_Recipient__c=account.Id);
    insert project;
    Award__c award =new Award__c(Project__c=project.Id,Status__c=ALS_CONSTANTS.Award_Status_Active);
    insert award;
    Payment_Request__c paymentRequest =new  Payment_Request__c(Project__c=project.Id,PaymentType__c =ALS_CONSTANTS.PR_PaymentType_Reimbursement,ReimbursementStartDate__c = startDate,ReimbursementEndDate__c = EndDate);
    insert paymentRequest;
    Transmittal__c transmittal =new Transmittal__c(PaymentRequest__c=paymentRequest.Id);
    insert transmittal;

    Test.startTest();
        ALS_TransmittalPreviewController.getDetails(transmittal.Id);
    Test.stopTest();

}

}