codepkg/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project for which this Award is created.</description>
        <inlineHelpText>Project for which this Award is created.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <displayFormat>AW-{000000}</displayFormat>
        <label>Award Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Funding_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <formula>IF(  Program_Name__r.Name   = &quot;PA - Federal&quot;  || Program_Name__r.Name  = &quot;PA - FMAG&quot;, Incident_Name__r.Declaration_Number__c, 
IF(Program_Name__r.Name = &quot;CDAA (State Funding)&quot;, Incident_Name__r.State_Declaration_Number__c, &quot;&quot;)
)</formula>
        <label>Declaration Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Incident / Disaster Name</description>
        <inlineHelpText>The Incident Name related to this Funding Opportunity</inlineHelpText>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The record owner. Should be a Programs Profile or Role</description>
        <inlineHelpText>The Staff Member who owns the record</inlineHelpText>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program that issued with this Funding Opportunity</description>
        <inlineHelpText>Program Name for the funding Opportunity ( Ex: PA-Federal, HMGP etc.).</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Disaster Grant / Funding Opportunity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disaster Grants / Funding Opps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Federal Incident Declaration Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Incident Declaration Number. DR number if a Major Disaster, CDAA Number if CDAA-Only, etc.</inlineHelpText>
        <label>Declaration Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>Funding_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To compare Funding Opportunity of Service Location / Encumbrance.
Used for Look up filter configuration.</description>
        <inlineHelpText>To compare Funding Opportunity of Service Location / Encumbrance.
Used for Look up filter configuration.</inlineHelpText>
        <label>Disaster Grant/FO</label>
        <referenceTo>Funding_Opportunity__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project for which this Payment is Requested?</description>
        <inlineHelpText>Project for which this Payment is Requested?</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Parent Program</description>
        <inlineHelpText>If the Program you are adding is not one of the Programs in this list, please select the parent Program from this list.</inlineHelpText>
        <label>Parent Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Related Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Program_Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Category__c</fullName>
        <label>Document Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Obligating</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Request</fullName>
                </value>
                <value>
                    <fullName>Supplement</fullName>
                </value>
                <value>
                    <fullName>Property Owner ID</fullName>
                </value>
                <value>
                    <fullName>Proof of Ownership</fullName>
                </value>
                <value>
                    <fullName>Proof of Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Creation_Method__c</fullName>
        <label>Document Creation Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manually Uploaded</fullName>
                </value>
                <value>
                    <fullName>System Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Format__c</fullName>
        <label>Document  Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.pdf</fullName>
                    <label>PDF</label>
                </value>
                <value>
                    <fullName>.docx</fullName>
                    <label>Word</label>
                </value>
                <value>
                    <fullName>.zip</fullName>
                    <isActive>false</isActive>
                    <label>.zip</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <description>Object on which  Document is to be created.</description>
        <inlineHelpText>Object on which  Document is to be created.</inlineHelpText>
        <label>Parent Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>HH Application</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                    <isActive>false</isActive>
                    <label>Application</label>
                </value>
                <value>
                    <fullName>Application Extensions</fullName>
                    <isActive>false</isActive>
                    <label>Application Extensions</label>
                </value>
                <value>
                    <fullName>Project Site</fullName>
                    <isActive>false</isActive>
                    <label>Project Site</label>
                </value>
                <value>
                    <fullName>Work Schedule</fullName>
                    <isActive>false</isActive>
                    <label>Work Schedule</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Documents</relationshipLabel>
        <relationshipName>Program_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Document_Filter_Clause__c</fullName>
        <description>Filter clause to create project document. Document will get created only after matching condition.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Provide filter clause. You can generate filter clause from workbench.</inlineHelpText>
        <label>Project Document Filter Clause</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Program Document</label>
    <nameField>
        <displayFormat>PDM-{00000}</displayFormat>
        <label>Program Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Declaration Number of the Incident.</description>
        <formula>Incident_Name__r.Declaration_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Declaration Number assigned to a Disaster/Incident.</inlineHelpText>
        <label>Declaration Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Funding Opportunity Name</description>
        <inlineHelpText>Specific Funding Opportunity for the Grant (Program+Incident+Declaration Number).</inlineHelpText>
        <label>Disaster Grant/FO</label>
        <referenceTo>Funding_Opportunity__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The name of the Incident</description>
        <inlineHelpText>Disaster/Incident for which the project is related. Not all projects will have an associated Incident.</inlineHelpText>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Name, Derives from Disaster Grant/FO.</description>
        <inlineHelpText>The grant program from which the Project originates. This field is used for reporting.</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CreatePaymentRequestDocumentTest.cls
/**
 * Created by StackNexus Admin on 12-01-2021.
 */
@IsTest
public with sharing class CreatePaymentRequestDocumentTest {
    @IsTest
    public static void testCreatePaymentRequestDocumentMenthod() {
        set<Id> prIds = new set<Id>();
        Date startDate = system.today()+1;
        Date EndDate = system.today()+10;
        Profile pf = [Select Id from profile where Name = 'System Administrator'];
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ', '').replace(':', '').replace('-', '') ;
        Integer RandomId = Integer.valueOf(Math.rint(Math.random() * 1000000));
        String uniqueName = orgId + dateString + RandomId;
        User uu = new User(firstname = 'ABC',
                lastName = 'XYZ',
                email = uniqueName + '@test' + orgId + '.org',
                Username = uniqueName + '@test' + orgId + '.org',
                EmailEncodingKey = 'ISO-8859-1',
                Alias = uniqueName.substring(18, 23),
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                ProfileId = pf.Id
        );
        insert uu;
        Program__c prP = new Program__c(Name = 'Test Program Parent');
        insert prP;
        Program__c prC = new Program__c(Name = 'Test Program Child', Parent_Program__c = prP.Id);
        insert prC;
        Program__c prC1 = new Program__c(Name = 'Test Program Child1', Parent_Program__c = prP.Id);
        insert prC1;
        Program_Document__c pgd2 = new Program_Document__c(Parent_Object__c = 'Payment Request', Document_Name__c = 'Test Program Document', Document_Category__c = ALS_CONSTANTS.PDocument_DocumentCategory_Obligating, Document_Creation_Method__c = ALS_CONSTANTS.PDocument_DocumentCreationMethod_ManuallyUploaded, Document_Format__c = ALS_CONSTANTS.PDocument_DocumentFormat_PDF, Program__c = prC.Id, Project_Document_Filter_Clause__c = 'Id != null');
        insert pgd2;
        Program_Document__c pgd3 = new Program_Document__c(Parent_Object__c = 'Payment Request', Document_Name__c = 'Test Program Document', Document_Category__c = ALS_CONSTANTS.PDocument_DocumentCategory_Obligating, Document_Creation_Method__c = ALS_CONSTANTS.PDocument_DocumentCreationMethod_ManuallyUploaded, Document_Format__c = ALS_CONSTANTS.PDocument_DocumentFormat_PDF, Program__c = prC.Id);
        insert pgd3;
        Incident__c inc = new Incident__c(Name = 'Test Incident FP', Declaration_Number__c = '4407');
        insert inc;
        Account account = new Account(Name = 'Test Account', Entity_Type__c = ALS_CONSTANTS.Account_EntityType_City);
        insert account;
        Funding_Opportunity__c fp1 = new Funding_Opportunity__c(Name = 'Test FP ', Program_Name__c = prC.Id, Incident_Name__c = inc.Id, Owner__c = uu.Id);
        insert fp1;
        Project__c newProj = new Project__c(Program_Name__c = prC1.Id, Funding_Opportunity_Name__c = fp1.Id, Stage__c = ALS_CONSTANTS.Project_Stage_Closeout, Obligating_Sub_Recipient__c = account.Id, Start_Date__c = startDate, End_Date__c =EndDate, FundingSource__c = ALS_CONSTANTS.Project_FundingSource_FederalAndState, State_Share__c = 20, FEMA_Share__c = 70);
        insert newProj;
        Award__c award = new Award__c(Project__c = newProj.Id);
        insert award;
        Payment_Request__c payRequest = new Payment_Request__c(Award__c = award.Id, Project__c = newProj.Id, ExpenditurestoDate__c = 2000);
        insert payRequest;
        prIds.add(payRequest.Id);
        CreateProjectDocumentPlatformEvent projDoc = new CreateProjectDocumentPlatformEvent();

        Test.startTest();
        projDoc.handle(prIds);
        Test.stopTest();
    }
}