codepkg/objects/CFAA__c.object
<CustomObject>
    <fields>
        <fullName>END_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>CFAA Rate Letter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CFAA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CFAA Rate Letter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/F42__c.object
<CustomObject>
    <description>This object stores the actual f-42 submission data. This and related child objects will be used for generating Invoices</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>1 AGENCY NAME</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>F-42</relationshipLabel>
        <relationshipName>F_42</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DF_Dispatch_From_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>END DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DF_OLD_INCIDENT_REQUEST__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OLD INCIDENT REQUEST#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DF_OLD_INCIDENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLD INCIDENT</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>F-42s (OLD INCIDENT)</relationshipLabel>
        <relationshipName>F_42s1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DI_COMMITTED_TO_INCIDENT_FORMULA__c</fullName>
        <formula>TEXT(DI_Committed_to_Incident_Date__c) + &apos; &apos;+ DI_Committed_to_Incident_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>COMMITTED TO INCIDENT</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DI_Committed_to_Incident_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>COMMITTED TO INCIDENT DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_Committed_to_Incident_Time__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>COMMITTED TO INCIDENT TIME</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DI_Mobilization_Center_Preposition__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MOBILIZATION CENTER / PREPOSITION</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Dispatch_To_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>START DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DT_NEW_INCIDENT_REQUEST__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>NEW INCIDENT REQUEST#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_NEW_INCIDENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NEW INCIDENT</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>F-42s (NEW INCIDENT)</relationshipLabel>
        <relationshipName>F_42s2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_APPARATUS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>APPARATUS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_CDF_OES_VEHICLE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CDF/OES VEHICLE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_FEMA_CODES__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>FEMA CODES</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_LICENSE_NUMBER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>LICENSE NUMBER</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F42_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>F42 Entry</label>
        <referenceTo>F42_Entry__c</referenceTo>
        <relationshipLabel>F-42</relationshipLabel>
        <relationshipName>F_42</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <formula>Incident__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>INCIDENT NAME (formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Order__c</fullName>
        <formula>Incident__r.Order_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>3. INCIDENT ORDER#</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Request_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>4. INCIDENT REQUEST NUMBER</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>INCIDENT NAME</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>F-42s</relationshipLabel>
        <relationshipName>F_42s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OH_ICS_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ICS Title Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OH_OTHER_ICS_TITLE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OTHER ICS TITLE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OH_OVERHEAD_TYPE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OVERHEAD TYPE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PA_CALOESREP_DATE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PA_Cal_OES_REPRESENTATIVE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cal OES REPRESENTATIVE (if assigned)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PA_DATE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PA_ICS_POSITION_TITLE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ICS POSITION / TITLE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PA_OTHER_POSITION_TITLE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OTHER POSITION / TITLE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PA_OTHER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OTHER</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RA_AGENCY_NAME__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>AGENCY NAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SN_LOSS_DAMAGE_CLAIM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>15. LOSS/DAMAGE CLAIM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SN_SUPPLY_NUMBER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>16. SUPPLY NUMBER</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_BEGINNING_ODODMETER__c</fullName>
        <label>BEGINNING ODODMETER</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SV_ENDING_ODOMETER__c</fullName>
        <label>ENDING ODOMETER</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SV_LICENSE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>LICENSE#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CALOES REVIEW</fullName>
                </value>
                <value>
                    <fullName>AGENCY REVIEW</fullName>
                </value>
                <value>
                    <fullName>APPROVED</fullName>
                </value>
                <value>
                    <fullName>DOCUMENTATION ONLY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strike_Team__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>2 STRIKE TEAM / TASK FORCE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>F-42</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>F-42 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>F-42s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/F42_Entry__c.object
<CustomObject>
    <description>This object is used to track all F42 Entries into the system. This object captures the entry data made by portal users on the UI. Once submitted this record will span into multiple f42 records and f42 line items that will then be used for invoice generation.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>F42 Entries</relationshipLabel>
        <relationshipName>F42_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>F42 Entries</relationshipLabel>
        <relationshipName>F42_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Online Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Offline Draft</fullName>
                </value>
                <value>
                    <fullName>Caloes Review</fullName>
                </value>
                <value>
                    <fullName>Disregarded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>F42 Entry</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>F42 Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>F42 Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/FEMA_Code__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FEMA Code</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FEMA Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_GenerateInvoiceHelper.cls
/***********************************************************************************************************************************
* Class Name   : MARS_GenerateInvoiceHelper
* Description  : This class for Generate Invoice
* Author       : Chandrabhan
* Created On   : 05/05/2021
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Chandrabhan          05/05/2021      Initial Implementation
**************************************************************************************************************************************/


public without sharing class MARS_GenerateInvoiceHelper {
    /***********************************************
    * Method Name : generateInvoice
    * Author : Pankaj
    * Inputs : List<List<String>> ids
    * Description: This method 
    *********************************************/
    @InvocableMethod(label='Generate Invoice' description='Generate Invoice From F-42s')
    public static void generateInvoice(List<List<String>> ids) {//List<List<F42__c>> ids
        System.debug('F42_RecordIdList===>'+ids);
        System.debug('F42_RecordIdList[]===>'+ids[0]);
        System.debug('Length===>'+ids[0].get(0));
        List<F42__c> f42List = [SELECT Name,Account__c, Account__r.Name,Incident__c, Incident__r.Name, Status__c,SN_LOSS_DAMAGE_CLAIM__c,SN_SUPPLY_NUMBER__c,Strike_Team__c,Incident_Order__c,Incident_Request_Number__c,RA_AGENCY_NAME__c,
                                ER_APPARATUS__c,SV_BEGINNING_ODODMETER__c,PA_Cal_OES_REPRESENTATIVE__c,ER_CDF_OES_VEHICLE__c,DI_COMMITTED_TO_INCIDENT_FORMULA__c,DI_Committed_to_Incident_Date__c,DI_Committed_to_Incident_Time__c,
                                PA_CALOESREP_DATE__c,PA_DATE__c,DF_Dispatch_From_End_Date__c,DT_Dispatch_To_Start_Date__c,SV_ENDING_ODOMETER__c,F42_Entry__c,ER_FEMA_CODES__c,
                                PA_ICS_POSITION_TITLE__c,OH_ICS_Title__c,Incident_Name__c,ER_LICENSE_NUMBER__c,SV_LICENSE__c,DI_Mobilization_Center_Preposition__c,DT_NEW_INCIDENT__c,DT_NEW_INCIDENT_REQUEST__c,DF_OLD_INCIDENT__c,DF_OLD_INCIDENT_REQUEST__c,
                                PA_OTHER__c,OH_OTHER_ICS_TITLE__c,PA_OTHER_POSITION_TITLE__c,OH_OVERHEAD_TYPE__c,PA_PAYING_AGENCY__c,PA_PRINTED_NAME__c,DI_REDISPATCHED__c,DI_Redispatched_Date__c,DI_Redispatched_Time__c,DI_REPORTING_LOCATION__c
                                ,DI_RETURN_FROM_INCIDENT__c,DI_Return_from_Incident_Date__c,DI_Return_from_Incident_Time__c,SV_TOTAL_MILES__c,SV_TYPE__c,ER_TYPE__c,ER_UNIT__c,SV_VEHICLE_OWNERSHIP__c,RA_YOUR_NAME__c,
                                RA_YOUR_PHONE__c,RA_YOUR_TITLE__c  FROM F42__c WHERE Id=:ids[0]];
        System.debug('f42List===>'+f42List);
        Set<Id> f42EntryIdSet = new Set<Id>();  
        for(F42__c frecord : f42List){
            f42EntryIdSet.add(frecord.F42_Entry__c);
        }                      
        List<F42_Entry__c> f42EntryList = [SELECT Name,Account__c, Account__r.Name,Incident__c, Incident__r.Name,JSON__c, Offline_JSON__c,Source__c, Status__c  from F42_Entry__c WHERE  Id=:f42EntryIdSet];
        System.debug('f42EntryList===>'+f42EntryList);
        List<FEMA_Code_LineItem__c> fEMACodeLintItemList =[SELECT Id,Name, Equipment__c, HP__c, Current_Rate__c FROM FEMA_Code_LineItem__c WHERE FEMA_Code__r.Status__c = 'Active'];
        System.debug('fEMACodeLintItemList===>'+fEMACodeLintItemList);
        List<CFAA_Line_Items__c> cFAALineItemList=[SELECT Id, Personnel_Role__c, Straight_Time_Rate__c, Order_No__c,
                                                    CFAA__r.Start_Date__c, CFAA__r.END_Date__c,CFAA__c FROM CFAA_Line_Items__c WHERE CFAA__c != null AND CFAA__r.Start_Date__c <= today AND CFAA__r.END_Date__c >= today AND RecordType.Name = 'Personnel Base Rate' ORDER BY Order_No__c ASC];
        System.debug('cFAALineItemList===>'+cFAALineItemList);
       /* PageReference pr = new PageReference('/apex/GenerateInvoice');
        Blob content = pr.getContent();

        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = content;
        cv.IsMajorVersion = true;
        Insert cv;
         
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
         
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = 'a0D35000001OVxuEAG';//record.Incident__c;//
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;*/
    }

    
}