codepkg/objects/CFAA__c.object
<CustomObject>
    <fields>
        <fullName>CFAA_Processed_for_Salary_Surveys__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates that after the creation of new CFAA records, batch job is run to make sure copies of Salary Survey records are created and new CFAA rates are applied</description>
        <label>CFAA Processed for Salary Surveys</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Admin_Rate__c</fullName>
        <label>Default Admin Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>END_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>CFAA Rate Letter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CFAA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CFAA Rate Letter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/CFAA_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>CFAA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CFAA</label>
        <referenceTo>CFAA__c</referenceTo>
        <relationshipLabel>CFAA Line Items</relationshipLabel>
        <relationshipName>CFAA_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Emergency_Apparatus_Type__c</fullName>
        <label>Emergency Apparatus Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type I</fullName>
                </value>
                <value>
                    <fullName>Type II</fullName>
                </value>
                <value>
                    <fullName>Type III</fullName>
                </value>
                <value>
                    <fullName>Type IV - VII</fullName>
                </value>
                <value>
                    <fullName>Water Tender Tactical I</fullName>
                </value>
                <value>
                    <fullName>Water Tender Tactical II</fullName>
                </value>
                <value>
                    <fullName>Type IV – VII</fullName>
                    <isActive>false</isActive>
                    <label>Type IV – VII</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Overhead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Overhead ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Role__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Other Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Over_Time_Rate__c</fullName>
        <label>Over Time Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personnel_Role__c</fullName>
        <label>Personnel Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chief</fullName>
                </value>
                <value>
                    <fullName>Deputy Chief</fullName>
                </value>
                <value>
                    <fullName>Division Chief</fullName>
                </value>
                <value>
                    <fullName>Assistant Chief</fullName>
                </value>
                <value>
                    <fullName>Battalion Chief</fullName>
                </value>
                <value>
                    <fullName>Co. Officer/Capt./Lt.</fullName>
                </value>
                <value>
                    <fullName>App. Officer/Eng</fullName>
                </value>
                <value>
                    <fullName>Firefighter/FF-PMedic</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Straight_Time_Rate__c</fullName>
        <label>Straight Time Rate</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Support_Equipment_Type__c</fullName>
        <label>Support Equipment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sedan</fullName>
                </value>
                <value>
                    <fullName>Pick-Up (1/2 Ton)</fullName>
                </value>
                <value>
                    <fullName>Van</fullName>
                </value>
                <value>
                    <fullName>SUV</fullName>
                </value>
                <value>
                    <fullName>Other (3/4 Ton &amp; Above)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personnel Base Rates</fullName>
                </value>
                <value>
                    <fullName>Support Equipment Rates</fullName>
                </value>
                <value>
                    <fullName>Emergency Apparatus Rates</fullName>
                </value>
                <value>
                    <fullName>Privately Owned Vehicle (POV) Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Mile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CFAA Line Item</label>
    <nameField>
        <label>CFAA Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CFAA Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_Process_CFAA_Ctrl.cls
public with sharing class MARS_Process_CFAA_Ctrl {

    @AuraEnabled
    public static string checkEndDate(string currentCFAAId){
        try {
            list<CFAA__c> existingCFAA = [SELECT Id, Name, Default_Admin_Rate__c, Start_Date__c, END_Date__c,
                                            CFAA_Processed_for_Salary_Surveys__c
                                            FROM CFAA__c WHERE Id=: currentCFAAId LIMIT 1];
            if(existingCFAA[0].End_Date__c == null){
                return 'Please put the end date for the current CFAA before cloning a new one.';
            }

            return '';
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string cloneCFAA(date newStartDate, string currentCFAAId){
        try {
            CFAA__c newCFAA = new CFAA__c();
            list<CFAA_Line_Items__c> newCFAAlineItems = new list<CFAA_Line_Items__c>();

            list<CFAA__c> existingCFAA = [SELECT Id, Name,Default_Admin_Rate__c,Start_Date__c,END_Date__c,
                                            CFAA_Processed_for_Salary_Surveys__c
                                            FROM CFAA__c WHERE Id=: currentCFAAId LIMIT 1];

            newCFAA = existingCFAA[0].clone(false, false, false, false);
            newCFAA.Start_Date__c = newStartDate;
            newCFAA.ENd_Date__c = null;
            newCFAA.CFAA_Processed_for_Salary_Surveys__c = false;
            newCFAA.Name = 'CFAA beginning from '+newStartDate;

            insert newCFAA;

            list<CFAA_Line_Items__c> lineItems = [SELECT Id,CFAA__c,Emergency_Apparatus_Type__c,Is_Overhead__c,Order_No__c,Other_Role__c,
                                                    Over_Time_Rate__c, Personnel_Role__c, RecordTypeId, Straight_Time_Rate__c, Support_Equipment_Type__c,
                                                    Type__c, Unit_of_Measure__c 
                                                 FROM CFAA_Line_Items__c 
                                                 WHERE CFAA__c = :currentCFAAId];
            
            CFAA_Line_Items__c  lineItem;
            for(CFAA_Line_Items__c li: lineItems){
                lineItem = new CFAA_Line_Items__c();
                lineItem = li.clone(false, false, false, false);
                lineItem.CFAA__c = newCFAA.Id;
                newCFAAlineItems.add(lineItem);
            }

            insert newCFAAlineItems;

            return newCFAA.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }



    //This is for cloning salary survey line items
    @AuraEnabled
    public static string validateCFAAForSalarySurveys(string currentCFAAId){
        try {
            CFAA__c currentCFAA = [SELECT Id, Name, Default_Admin_Rate__c, Start_Date__c, END_Date__c,
                                            CFAA_Processed_for_Salary_Surveys__c
                                            FROM CFAA__c WHERE Id=: currentCFAAId LIMIT 1];
            
            if(currentCFAA.CFAA_Processed_for_Salary_Surveys__c){
                return 'This CFAA is already processed for Salary Surveys. Re-processing will create duplicate entries';
            }

            list<CFAA__c> noEndDateCFAA = [SELECT Id, Name, Default_Admin_Rate__c, Start_Date__c, END_Date__c,
                                            CFAA_Processed_for_Salary_Surveys__c
                                            FROM CFAA__c WHERE Id !=: currentCFAAId
                                            AND  END_Date__c = null
                                            LIMIT 1];
            
            if(!noEndDateCFAA.isEmpty()){
                return 'There is a CFAA record with Salesforce Id: '+noEndDateCFAA[0].Id+ ' that does not have end date. Please put end date to the CFAA before processing this for cloning salary surveys';
            }

            list<CFAA__c> overlapCFAA = [SELECT Id FROM CFAA__c WHERE 
                                            Id !=: currentCFAAId AND
                                            End_Date__c >= :currentCFAA.Start_Date__c 
                                            LIMIT 1];

            if(!overlapCFAA.isEmpty()){
                return 'Current CFAA record start date is overlapping with an existing CFAA record with Salesforce Id: '+overlapCFAA[0].Id+'. Please put correct the start date of the current CFAA before proceeding with cloning salary surveys';
            }


            return '';

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string ProceedCloneSalarySurvey(string currentCFAAId){
        try {
            MARS_CFAAProcessing_Batch b = new MARS_CFAAProcessing_Batch();
            b.CFAArecId = currentCFAAId;
            Database.executeBatch(b,10);

            return 'Batch job to clone the salary survey records started in the backend. You will receive an email once the process is complete';

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}