codepkg/objects/Closeout_Request__c.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Closeout Requests</relationshipLabel>
        <relationshipName>Closeout_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Date__c</fullName>
        <description>This date would capture the Closeout Request Initiation Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending SR Claim</fullName>
                </value>
                <value>
                    <fullName>Closeout Request Finalized</fullName>
                </value>
                <value>
                    <fullName>Closeout on Hold</fullName>
                </value>
                <value>
                    <fullName>Closeout in Progress</fullName>
                </value>
                <value>
                    <fullName>Closeout Complete</fullName>
                </value>
                <value>
                    <fullName>Closeout Requested</fullName>
                    <isActive>false</isActive>
                    <label>Closeout Requested</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subrecipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subrecipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Closeout Requests</relationshipLabel>
        <relationshipName>Closeout_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Closeout Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Closeout Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Closeout Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/classes/PACRPortalUserMessageController_Test.cls
/*************************************************************************************
* Class Name   : PACRPortalUserMessageController_Test
* Description  : used to test controller
* Author       : Dayal
* Created On   : 17/11/2021
* Modification Log:  
* -----------------------------------------------------------------------
* Developer             Date             Description 
* -----------------------------------------------------------------------
* Dayal               17/11/2021     Initial Implementation
**************************************************************************************/
@isTest
public with sharing class PACRPortalUserMessageController_Test {
    
/***********************************************************************************************************************************
    * Method  Name   : closeoutCloseoutinProgress
    * Description    :used to test the closeout request message
    * Author         : Dayal
    * Created On   : 30/08/2021
    * Modification Log:  
 * --------------------------------------------------------------------------------------------------------------------------------------*/
  
    @isTest 
    public static void closeoutCloseoutinProgress() {        
    Incident__c incident = PA_TestHelper.getIncident(true);
    //Account Subrecipent create
    Account account = PA_TestHelper.getAccountSubrecipent(true);


    // closeout requested  Created ;    
    Closeout_Request__c closeoutRequest = new Closeout_Request__c();      
    closeoutRequest.Request_Date__c = System.today();
    closeoutRequest.Subrecipient__c = account.Id;
    closeoutRequest.Incident__c = incident.Id;
    closeoutRequest.Status__c = 'Closeout in Progress';
      
    upsert closeoutRequest;

    //PACRPortalUserMessageController.getMessage(closeoutRequest.Id);
    PACloseoutPoratalMessageController.getMessage(closeoutRequest.Id);
    
              
    }   
    
    /***********************************************************************************************************************************
    * Method  Name   : closeoutPendingSRClaim
    * Description    :used to test the closeout request message
    * Author         : Dayal
    * Created On   : 30/08/2021
    * Modification Log:  
 * --------------------------------------------------------------------------------------------------------------------------------------*/
  
        @isTest 
        public static void closeoutPendingSRClaim() {        
        Incident__c incident = PA_TestHelper.getIncident(true);
        //Account Subrecipent create
        Account account = PA_TestHelper.getAccountSubrecipent(true);

        // closeout requested  Created ;    
        Closeout_Request__c closeoutRequest1 = new Closeout_Request__c();      
        closeoutRequest1.Request_Date__c = System.today();
        closeoutRequest1.Subrecipient__c = account.Id;
        closeoutRequest1.Incident__c = incident.Id;
        closeoutRequest1.Status__c = 'Pending SR Claim';
            
        upsert closeoutRequest1;
        //PACRPortalUserMessageController.getMessage(closeoutRequest1.Id);
        PACloseoutPoratalMessageController.getMessage(closeoutRequest1.Id);       
                
    }   

    /***********************************************************************************************************************************
    * Method  Name   : closeoutCloseoutRequestFinalized
    * Description    :used to test the closeout request message
    * Author         : Dayal
    * Created On   : 30/08/2021
    * Modification Log:  
   * --------------------------------------------------------------------------------------------------------------------------------------*/
  
    @isTest 
    public static void closeoutCloseoutRequestFinalized() {        
    Incident__c incident = PA_TestHelper.getIncident(true);
    //Account Subrecipent create
    Account account = PA_TestHelper.getAccountSubrecipent(true);

   
    // closeout requested  Created ;    
    Closeout_Request__c closeoutRequest2 = new Closeout_Request__c();      
    closeoutRequest2.Request_Date__c = System.today();
    closeoutRequest2.Subrecipient__c = account.Id;
    closeoutRequest2.Incident__c = incident.Id;
    closeoutRequest2.Status__c = 'Closeout Request Finalized';
        
    upsert closeoutRequest2;
    PACloseoutPoratalMessageController.getMessage(closeoutRequest2.Id);
            
  }   

}