codepkg/objects/Closeout_Task__c.object
<CustomObject>
    <label>Closeout Task</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Closeout Task</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Closeout Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Closeout_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closeout Task</label>
        <referenceTo>Closeout_Task__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Uploaded__c</fullName>
        <description>The Date the document was uploaded into Salesforce.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Date the document was uploaded into Salesforce.</inlineHelpText>
        <label>Date Uploaded</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>The Document&apos;s Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Document&apos;s Name</inlineHelpText>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>The Document Type</description>
        <inlineHelpText>The Document Type</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Obligating</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>De Obligation</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Request</fullName>
                </value>
                <value>
                    <fullName>Supplement</fullName>
                </value>
                <value>
                    <fullName>miscellaneous</fullName>
                    <label>Miscellaneous</label>
                </value>
                <value>
                    <fullName>FIR</fullName>
                </value>
                <value>
                    <fullName>Signed FIR</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                </value>
                <value>
                    <fullName>FGAS Report</fullName>
                </value>
                <value>
                    <fullName>Property Owner ID</fullName>
                </value>
                <value>
                    <fullName>Proof of Ownership</fullName>
                </value>
                <value>
                    <fullName>Proof of Rental</fullName>
                </value>
                <value>
                    <fullName>Home Assessment Report</fullName>
                </value>
                <value>
                    <fullName>Environmental Checklist</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Homeowner Paper Application</fullName>
                </value>
                <value>
                    <fullName>Homeowner Appeal Form</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Punch List</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Requested</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Received</fullName>
                </value>
                <value>
                    <fullName>Executed Tri-Party Agreement</fullName>
                </value>
                <value>
                    <fullName>BCA Technical Review Memo</fullName>
                    <isActive>false</isActive>
                    <label>BCA Technical Review Memo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_File_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Original File Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project Name</description>
        <inlineHelpText>The Project Name</inlineHelpText>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Closeout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Closeout</label>
        <referenceTo>Project_Closeout__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project for which this Payment is Requested?</description>
        <inlineHelpText>Project for which this Payment is Requested?</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>CloseOut_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CloseOut Task</label>
        <referenceTo>Closeout_Task__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project_Closeout__c.object
<CustomObject>
    <fields>
        <fullName>Closeout_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closeout Task</label>
        <referenceTo>Closeout_Task__c</referenceTo>
        <relationshipLabel>Project Closeouts</relationshipLabel>
        <relationshipName>CloseOuts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Closeout</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Closeout</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Closeouts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/ContentDocumentLinkTriggerHelper.cls
/***********************************************************************************************************************************
* Class Name   : ContentDocumentLinkTriggerHelper
* Description  : This class for sharing notes to community user
* Author       : Pankaj
* Created On   : 05/15/2020
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj             05/15/2020       Initial Implementation
**************************************************************************************************************************************/

public without sharing class ContentDocumentLinkTriggerHelper extends TriggerHelper { 

    /***********************************************
    * Method Name : processBeforeInsert
    * Author : Pankaj
    * Inputs : -
    * Description: This method set default sharing to public read only. so that notes created by Internal users should be visible to community users
    *********************************************/
    public override void processBeforeInsert() {
        // set default sharing to public read only. so that notes created by Internal users should be visible to community users
        for(ContentDocumentLink cont : (List<ContentDocumentLink>)Trigger.new) {
            cont.Visibility = 'AllUsers';
        }
    }

    public override void processAfterInsert() {
        if(System.isFuture() == false && System.isQueueable() == false && System.isBatch() == false
                && System.isScheduled() == false) {
            processDocGenAssociation();
        }
    }

    private void processDocGenAssociation() {
        List<ContentDocumentLink> contDocLinkList = (List<ContentDocumentLink>)Trigger.new;
        /* 
        String docGenSalesforceUserId = KeyValueHelper.getTextValue('DocGenAdminUserId');
        if(Id.valueOf(docGenSalesforceUserId) != UserInfo.getUserId()) return;
        */

        linkingDocumentToContentDocumentLinksForDocGen(contDocLinkList);
    }

    public void linkingDocumentToContentDocumentLinksForDocGen(List<ContentDocumentLink> contentDocLinkList){
        List<ContentDocumentLink> updateDocList = new List<ContentDocumentLink>();
        Set<Id> contDocIds = new Set<Id>();
        List<String> docNameList = new List<String>();
        List<String> recIdVal = new List<String>();
        List<sObject> sobjResultVal;
        String docGenRecId;
        String docGenRecAPIName;

        if(contentDocLinkList.size() > 0){
            Id recIdValSingle;
            for(ContentDocumentLink contDocLink: contentDocLinkList){
                contDocIds.add(contDocLink.ContentDocumentId);
                recIdVal.add(contDocLink.LinkedEntityId);
                String linkedEntityId = contDocLink.LinkedEntityId;
                if(linkedEntityId.startsWith('005') == false) {
                    recIdValSingle = Id.valueOf(recIdVal[0]);
                }
            }

            if(recIdValSingle != null) {
                String objectName = recIdValSingle.getSObjectType().getDescribe().getName();
                docGenRecId = recIdValSingle;
                docGenRecAPIName = objectName;
                if(recIdValSingle != null && (docGenRecAPIName == 'Project__c' || docGenRecAPIName == 'Closeout_Task__c'
                        || docGenRecAPIName == 'Project_Closeout__c' || docGenRecAPIName == 'Payment_Request__c')){
                   sobjResultVal =  Database.query('SELECT Id,Name FROM ' + objectName + ' WHERE Id = :recIdValSingle Limit 1');
                }
            }
            
        }
       
        if(sobjResultVal != null && sobjResultVal.size() > 0){
            List<ContentVersion> contentVersionList = [SELECT Id, ContentDocumentId, Description, Title,
                                                    Document_Type__c, FileType
                                                    FROM  ContentVersion 
                                                    WHERE ContentDocumentId IN: contDocIds ];
            if(contentVersionList.size() > 0) {
                for(ContentVersion contVersionVal: contentVersionList) {
                    for(ContentDocumentLink contDocLink: contentDocLinkList) {
                        String docTitle =   contVersionVal.Title;
                        //doc gen Files
                        DateTime todayDate = Datetime.now();
                        String formattedTodaysDate = '_'+ todayDate.format('yyyy-MM-dd');
                        if(docTitle.contains(String.valueOf(sobjResultVal[0].get('Name')) )) {
                            docTitle = docTitle.replace('_'+String.valueOf(sobjResultVal[0].get('Name')), '');
                            docTitle = docTitle.replace(formattedTodaysDate, '');
                            docNameList.add(docTitle);
                        } else if(docTitle.contains( formattedTodaysDate )) {
                            docTitle = docTitle.replace(formattedTodaysDate, '');
                            docNameList.add(docTitle);
                        } else {
                            docNameList.add(docTitle);
                        }
                        
                    }
                }
            }
            
            String additionalFilterClause = '';
            if(docGenRecAPIName == 'Project__c') {
                additionalFilterClause = ' and ProjectId__c=:docGenRecId';
            } else if(docGenRecAPIName == 'Closeout_Task__c') {
                additionalFilterClause = ' and Closeout_Task__c=:docGenRecId';
            } else if(docGenRecAPIName == 'Project_Closeout__c') {
                additionalFilterClause = ' and Project_Closeout__c=:docGenRecId';
            } else if(docGenRecAPIName == 'Payment_Request__c') {
                additionalFilterClause = ' and PaymentRequest__c=:docGenRecId';
            }

            //***********************
            //String query = 'SELECT Id, Document_Name__c, Original_File_Name__c, Document_Type__c, Name,CreatedById FROM Document__c WHERE  Original_File_Name__c IN:docNameList and Date_Uploaded__c = NULL';
            String query = 'SELECT Id, Document_Name__c, Original_File_Name__c, Document_Type__c, Name,CreatedById, ProjectId__c, PaymentRequest__c, Closeout_Task__c, Project_Closeout__c FROM Document__c WHERE  Original_File_Name__c IN:docNameList and Date_Uploaded__c = NULL';
            //***********************
            query += additionalFilterClause;
            List<Document__c> docValList = Database.query(query);
            if(docValList.size() == 0){
                return ;
            }
            Id newVal = contentDocLinkList[0].ContentDocumentId;
            Id sobjIdVal = (Id) sobjResultVal[0].get('Id');
            List<ContentDocumentLink> contentDCLinkList = [SELECT Id, ContentDocumentId, LinkedEntityId
                                                            FROM ContentDocumentLink
                                                            WHERE ContentDocumentId =:newVal and LinkedEntityId=:sobjIdVal];
            //check if document record have already file attached. In that case create new version for same document record.
            List<Id> docsIds = new List<Id>();
            for (Document__c document : docValList) {
                docsIds.add(document.Id);
            }
                    List<ContentDocumentLink> contentDocumentLinksForDocuments = [
                            SELECT ContentDocumentId, LinkedEntityId
                            FROM ContentDocumentLink
                            WHERE LinkedEntityId In:docsIds
                    ];
            Map<Id, Id> docWithContentDocId = new Map<Id, Id>();
            for (ContentDocumentLink contentDocumentLink : contentDocumentLinksForDocuments) {
                docWithContentDocId.put(contentDocumentLink.LinkedEntityId, contentDocumentLink.ContentDocumentId);
            }
            
            //******************* 
            //Set<Id> documentIdToUploadedDoc = new Set<Id>();
            Map<String, String> documentIdToLinkedObjectMap = new  Map<String, String>();
            //******************* 
                for(Document__c docVal : docValList) {
                    docVal.Date_Uploaded__c = System.today();
                    for(ContentDocumentLink cdLink : contentDCLinkList){
                        ContentDocumentLink newCdl = cdLink.clone();
                        newCdl.LinkedEntityId = docVal.Id;
                        updateDocList.add(newCdl);
                        // get list of documents for which we have to create new versions for existing document
                        if(docWithContentDocId.get(docVal.Id) != null) {
                            //***************************
                            //documentIdToUploadedDoc.add(docVal.Id);
                            if(docGenRecAPIName == 'Project__c') {
                                documentIdToLinkedObjectMap.put(docVal.Id, docVal.ProjectId__c);
                            } else if(docGenRecAPIName == 'Closeout_Task__c') {
                                documentIdToLinkedObjectMap.put(docVal.Id, docVal.Closeout_Task__c);
                            } else if(docGenRecAPIName == 'Project_Closeout__c') {
                                documentIdToLinkedObjectMap.put(docVal.Id, docVal.Project_Closeout__c);
                        }else if (docGenRecAPIName == 'Payment_Request__c') {
                            documentIdToLinkedObjectMap.put(docVal.Id, docVal.PaymentRequest__c);
                            }
                            //***************************
                        }
                    }
                }
            TriggerHelper.skipTrigger = true;
            System.debug('updateDocList ....===>'+updateDocList);
            System.debug('docValList ....===>'+docValList);
            upsert updateDocList;
            upsert docValList;
            TriggerHelper.skipTrigger = false;
            if(documentIdToLinkedObjectMap.size() > 0) {
                System.enqueueJob(new UpdateDocumentVersion(documentIdToLinkedObjectMap));
            }
        }
    }

    public class UpdateDocumentVersion implements Queueable {
        Map<String, String> documentIdToLinkedObjectMap;
        public UpdateDocumentVersion(Map<String, String> documentIdToLinkedObjectMap) {
            this.documentIdToLinkedObjectMap = documentIdToLinkedObjectMap;
        }
        public void execute(QueueableContext context) {
            system.debug('#UpdateDocumentVersion In Action...');
            system.debug('#documentIdToLinkedObjectMap :'+documentIdToLinkedObjectMap);
            for (String docId : documentIdToLinkedObjectMap.keySet()) {
                ALS_DocumentUpload_Ctrl.saveFileDetails(docId, null, documentIdToLinkedObjectMap.get(docId));
            }
        }
    }



}