codepkg/objects/Closeout_Task__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Assignment</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>FIR in Progress</fullName>
                </value>
                <value>
                    <fullName>OES Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Workflow</fullName>
                </value>
                <value>
                    <fullName>PA Correspondence</fullName>
                </value>
                <value>
                    <fullName>Cost Share</fullName>
                </value>
                <value>
                    <fullName>Transmittals</fullName>
                </value>
                <value>
                    <fullName>FPU Workflow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closeout Task</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Closeout Task</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Closeout Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/PA_ReadyForAssignmentCloseoutTaskCtrl.cls
/**
* Class Name   : PA_ReadyForAssignmentCloseoutTaskCtrl
* Description  : This class used  to change the status of the closeout task
* Author       : Dayal
* Created On   : 23/06/2021
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Dayal             23/06/2021       Initial Implementation
 */

public without sharing class PA_ReadyForAssignmentCloseoutTaskCtrl {

    /***********************************************************************************************
    * Method  Name   : getCloseOutTaskDetails
    * Description    : This method is used to update the closeout task staus 
    * Return         : -
    * Inputs         : String closeOutTaskId
    * Author         : Dayal
    * Created On     : 26/05/2021
    * Modification Log:  
    * -----------------------------------------------------------------------------------------------*/
   
    @AuraEnabled
    public static void getCloseOutTaskDetails(String closeOutTaskId){

            Closeout_Task__c closeoutTask = new Closeout_Task__c();
            closeoutTask.Id = closeOutTaskId;
            closeoutTask.Status__c = 'Pending Assignment';
            update closeoutTask;
        

    }

}