codepkg/objects/Closeout_Request__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending SR Claim</fullName>
                </value>
                <value>
                    <fullName>Closeout Request Finalized</fullName>
                </value>
                <value>
                    <fullName>Closeout on Hold</fullName>
                </value>
                <value>
                    <fullName>Closeout in Progress</fullName>
                </value>
                <value>
                    <fullName>Closeout Complete</fullName>
                </value>
                <value>
                    <fullName>Closeout Requested</fullName>
                    <isActive>false</isActive>
                    <label>Closeout Requested</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closeout Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Closeout Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Closeout Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Key_Value_Store__mdt.object
<CustomObject>
    <fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Key Value Store</label>
    <pluralLabel>Key Value Stores</pluralLabel>
</CustomObject>

codepkg/classes/PACloseoutPoratalMessageController.cls
public without sharing class PACloseoutPoratalMessageController {
    /***********************************************************************************************
    * Method  Name   : getMessage
    * Description    : 
    * Return         : 
    * Inputs         : 
    * Author       : Digamber
    * Created On   : 01/11/2021
    * Modification Log:  
    * -----------------------------------------------------------------------------------------------*/
    @AuraEnabled(Cacheable=true)
    public static Map<String, Object> getMessage(String recordId) {
        Map<String, Object> result = new Map<String, Object>();
        result.put('msg', '');
        result.put('isMsgVisible', false);            
        
        Closeout_Request__c closeoutRequest = [SELECT Id, Name, Status__c FROM Closeout_Request__c WHERE Id =:recordId];
        Key_Value_Store__mdt closeoutTextInProcess = Key_Value_Store__mdt.getInstance('CloseoutTextInProcess');
        Key_Value_Store__mdt closeoutTextOnHold = Key_Value_Store__mdt.getInstance('CloseoutTextOnHold');
        Key_Value_Store__mdt closeoutTextComplete = Key_Value_Store__mdt.getInstance('CloseoutTextComplete');
        Key_Value_Store__mdt closeoutTextPendingClaim = Key_Value_Store__mdt.getInstance('CloseoutTextPendingClaim');

        if(closeoutTextInProcess.Text_Value__c.contains(closeoutRequest.Status__c)){
            result.put('msg', System.Label.CloseoutTextInProcess);
            result.put('isMsgVisible', true);  
        }
        else if(closeoutTextOnHold.Text_Value__c.contains(closeoutRequest.Status__c)){
            result.put('msg', System.Label.CloseoutTextOnHold);
            result.put('isMsgVisible', true);  
        }
        else if(closeoutTextComplete.Text_Value__c.contains(closeoutRequest.Status__c)){
            result.put('msg', System.Label.CloseoutTextComplete);
            result.put('isMsgVisible', true);  
        }
        else if(CloseoutTextPendingClaim.Text_Value__c.contains(closeoutRequest.Status__c)){
            result.put('msg', System.Label.CloseoutTextPendingClaim);
            result.put('isMsgVisible', true);  
        }
        return result;
    }

}