codepkg/objects/Community_Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Permission_Set_Developer_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>App Permission Set Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Application</label>
        <referenceTo>Community_Application__c</referenceTo>
        <relationshipLabel>Community Applications</relationshipLabel>
        <relationshipName>Parent_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Approval_Class__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>User Approval Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <inlineHelpText>For which user this app is applicable?</inlineHelpText>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FEMA</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Homeowner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Community_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Application</label>
        <referenceTo>Community_Application__c</referenceTo>
        <relationshipLabel>Community Registration</relationshipLabel>
        <relationshipName>CommunityRegistration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Registrations</relationshipLabel>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alameda, County of</fullName>
                </value>
                <value>
                    <fullName>Alpine, County of</fullName>
                </value>
                <value>
                    <fullName>Amador, County of</fullName>
                </value>
                <value>
                    <fullName>Butte, County of</fullName>
                </value>
                <value>
                    <fullName>Calaveras, County of</fullName>
                </value>
                <value>
                    <fullName>Colusa, County of</fullName>
                </value>
                <value>
                    <fullName>Contra Costa, County of</fullName>
                </value>
                <value>
                    <fullName>Del Norte, County of</fullName>
                </value>
                <value>
                    <fullName>El Dorado, County of</fullName>
                </value>
                <value>
                    <fullName>Fresno, County of</fullName>
                </value>
                <value>
                    <fullName>Glenn, County of</fullName>
                </value>
                <value>
                    <fullName>Humboldt, County of</fullName>
                </value>
                <value>
                    <fullName>Imperial, County of</fullName>
                </value>
                <value>
                    <fullName>Inyo, County of</fullName>
                </value>
                <value>
                    <fullName>Kern, County of</fullName>
                </value>
                <value>
                    <fullName>Kings, County of</fullName>
                </value>
                <value>
                    <fullName>Lake, County of</fullName>
                </value>
                <value>
                    <fullName>Lassen, County of</fullName>
                </value>
                <value>
                    <fullName>Los Angeles, County of</fullName>
                </value>
                <value>
                    <fullName>Madera, County of</fullName>
                </value>
                <value>
                    <fullName>Marin, County of</fullName>
                </value>
                <value>
                    <fullName>Mariposa, County of</fullName>
                </value>
                <value>
                    <fullName>Mendocino, County of</fullName>
                </value>
                <value>
                    <fullName>Merced, County of</fullName>
                </value>
                <value>
                    <fullName>Modoc, County of</fullName>
                </value>
                <value>
                    <fullName>Mono, County of</fullName>
                </value>
                <value>
                    <fullName>Monterey, County of</fullName>
                </value>
                <value>
                    <fullName>Napa, County of</fullName>
                </value>
                <value>
                    <fullName>Nevada, County of</fullName>
                </value>
                <value>
                    <fullName>Orange, County of</fullName>
                </value>
                <value>
                    <fullName>Shasta, County of</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Unique_Household_Number__c</fullName>
        <description>Unique Household Number generated for the Account When the very first member has registered to HH_Community.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique Household Number generated for the Account When the very first member has registered to HH_Community.</inlineHelpText>
        <label>Unique Household Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>FEMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HH_UserServiceAppHandlerTest.cls
@isTest(seeAllData=true)
public class HH_UserServiceAppHandlerTest {

    @isTest 
    public static void testHandleApprove() {
        List<User_Registration__c> userRegistrationsList = new List<User_Registration__c>();
        Community_Application__c parentCommunity = new Community_Application__c();
       // parentCommunity.App_Permission_Set_Developer_Name__c = 'HH_Community_Homeowner_User';
        parentCommunity.Display_Name__c = 'California Wildfire Mitigation Program ';
        parentCommunity.isActive__c = true;
        parentCommunity.User_Approval_Class__c='HH_UserServiceAppHandler';
        parentCommunity.Name = HH_CONSTANTS.HH_Parent_Community_Application_Name;
        parentCommunity.User_Type__c = 'Community'; 
        insert parentCommunity;
        
        Community_Application__c newCommunityApp = new Community_Application__c();
        newCommunityApp.App_Permission_Set_Developer_Name__c = 'HH_Community_Homeowner_User';
        newCommunityApp.Display_Name__c = 'HH Community Homeowner ';
        newCommunityApp.isActive__c = true;
        newCommunityApp.Parent__c = parentCommunity.Id;
		newCommunityApp.User_Type__c = 'Community';        
        newCommunityApp.Name = 'HH Community Homeowner ';
        insert newCommunityApp;
        
        Community_Application__c newCommunityAppFema = new Community_Application__c();
        newCommunityAppFema.App_Permission_Set_Developer_Name__c = 'HH_Community_FEMA_User';
        newCommunityAppFema.Display_Name__c = 'HH Community FEMA';
        newCommunityAppFema.isActive__c = true;
        newCommunityAppFema.Parent__c = parentCommunity.Id;
		newCommunityAppFema.User_Type__c = 'FEMA';        
        newCommunityAppFema.Name = 'HH Community FEMA';
        insert newCommunityAppFema;
        
        Account newAccount = HH_TestHelper.getAccount(true);
        Contact cont = new Contact(Firstname='FirstName',Lastname='LastName', Email='email1213@gmail.com',Phone = '9652314586',AccountId = newAccount.Id, Entity_Change_Requested__c=true);
        insert cont;
        Contact cont2 = new Contact(Firstname='FirstName',Lastname='LastName', Email='email1213534@gmail.com',Phone = '9652314586',AccountId = newAccount.Id, Entity_Change_Requested__c=true);
        insert cont2;
        User_Registration__c   newUserRegistration = HH_TestHelper.getUserRegistration(false);
        newUserRegistration.RecordTypeId = Schema.SObjectType.User_Registration__c.getRecordTypeInfosByDeveloperName().get(System.Label.HH_RecordType_API_Name_HH_Registration).getRecordTypeId();
        newUserRegistration.Community_Application__c = newCommunityApp.Id;
        newUserRegistration.Contact_Name__c = cont.Id;
        newUserRegistration.Email__c = 'email1213@gmail.com';
        newUserRegistration.Unique_Household_Number__c = '12376';
        newUserRegistration.County__c='Shasta, County of';
        newUserRegistration.User__c = UserInfo.getUserId();
        insert newUserRegistration;
        userRegistrationsList.add(newUserRegistration);
        
        User_Registration__c   newUserRegistrationFema = HH_TestHelper.getUserRegistration(false);
        newUserRegistrationFema.RecordTypeId = Schema.SObjectType.User_Registration__c.getRecordTypeInfosByDeveloperName().get(System.Label.HH_RecordType_API_Name_HH_Registration).getRecordTypeId();
        newUserRegistrationFema.Community_Application__c = newCommunityApp.Id;
        newUserRegistrationFema.Contact_Name__c = cont2.Id;
        newUserRegistrationFema.Email__c = 'email1213@gmail.com';
        newUserRegistrationFema.Unique_Household_Number__c = '12376';
        //newUserRegistration.County__c='Shasta, County of';
        newUserRegistrationFema.User_Type__c = HH_CONSTANTS.UserRegistration_UserType_FEMA;
        newUserRegistrationFema.User__c = UserInfo.getUserId();
        insert newUserRegistrationFema;
        userRegistrationsList.add(newUserRegistrationFema);

        Test.startTest();
        HH_UserServiceAppHandler UserServiceAppHandler = new HH_UserServiceAppHandler();
        UserServiceAppHandler.handleApprove(userRegistrationsList);
        UserServiceAppHandler.handleReject(userRegistrationsList);

        Test.stopTest();
    }
    
   /* @isTest 
    public static void testInsertMembers() {
        
        List<User> User = new List<User>();
       
        User newUser = HH_TestHelper.createPortalUser();
        
        

        Test.startTest();
        HH_UserServiceAppHandler.insertMembers(newUser.Name);
       // System.assertEquals(newUserReg.Id, newUserReg.Id);
        Test.stopTest();
    }*/
}