codepkg/objects/Community_Application__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Community_Application_to_User__c.object
<CustomObject>
    <fields>
        <fullName>Community_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Application</label>
        <referenceTo>Community_Application__c</referenceTo>
        <relationshipLabel>Community Application to Users</relationshipLabel>
        <relationshipName>Community_Application_to_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Community Application to Users</relationshipLabel>
        <relationshipName>Community_Application_to_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Community_Application_to_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Application to User</label>
    <nameField>
        <displayFormat>CAU-{00000000}</displayFormat>
        <label>Community Application to User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Application to Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/CommunityAppToUserTriggerHelperTest.cls
@isTest(seeAllData=false)
public class CommunityAppToUserTriggerHelperTest {
    @isTest public static void testCommunityAppToUser() {
        test.startTest();
        Contact newContact = PHOS_TestHelper.getContact(true);
        User poratlUser = PHOS_TestHelper.getPortalUser(false);
        poratlUser.ContactId = newContact.Id;
        insert poratlUser;
        Community_Application__c comApp = PHOS_TestHelper.getCommunityApplication(true);
        Community_Application_to_User__c comAppToUSer = new Community_Application_to_User__c();
        comAppToUSer.Community_Application__c = null;
        comAppToUSer.Contact__c = newContact.Id;
        comAppToUSer.User__c = poratlUser.Id;
        insert comAppToUSer;
        comAppToUSer.isActive__c = false;
        update comAppToUSer;
        delete comAppToUSer;
        test.stopTest();
    }
}