codepkg/objects/Community_Application__c.object
<CustomObject>
    <label>Community Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>City_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Entity_Type__c</field>
                <operation>equals</operation>
                <value>City</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations (City)</relationshipLabel>
        <relationshipName>User_Registrations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Application</label>
        <referenceTo>Community_Application__c</referenceTo>
        <relationshipLabel>Community Registration</relationshipLabel>
        <relationshipName>CommunityRegistration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alameda, County of</fullName>
                </value>
                <value>
                    <fullName>Alpine, County of</fullName>
                </value>
                <value>
                    <fullName>Amador, County of</fullName>
                </value>
                <value>
                    <fullName>Butte, County of</fullName>
                </value>
                <value>
                    <fullName>Calaveras, County of</fullName>
                </value>
                <value>
                    <fullName>Colusa, County of</fullName>
                </value>
                <value>
                    <fullName>Contra Costa, County of</fullName>
                </value>
                <value>
                    <fullName>Del Norte, County of</fullName>
                </value>
                <value>
                    <fullName>El Dorado, County of</fullName>
                </value>
                <value>
                    <fullName>Fresno, County of</fullName>
                </value>
                <value>
                    <fullName>Glenn, County of</fullName>
                </value>
                <value>
                    <fullName>Humboldt, County of</fullName>
                </value>
                <value>
                    <fullName>Imperial, County of</fullName>
                </value>
                <value>
                    <fullName>Inyo, County of</fullName>
                </value>
                <value>
                    <fullName>Kern, County of</fullName>
                </value>
                <value>
                    <fullName>Kings, County of</fullName>
                </value>
                <value>
                    <fullName>Lake, County of</fullName>
                </value>
                <value>
                    <fullName>Lassen, County of</fullName>
                </value>
                <value>
                    <fullName>Los Angeles, County of</fullName>
                </value>
                <value>
                    <fullName>Madera, County of</fullName>
                </value>
                <value>
                    <fullName>Marin, County of</fullName>
                </value>
                <value>
                    <fullName>Mariposa, County of</fullName>
                </value>
                <value>
                    <fullName>Mendocino, County of</fullName>
                </value>
                <value>
                    <fullName>Merced, County of</fullName>
                </value>
                <value>
                    <fullName>Modoc, County of</fullName>
                </value>
                <value>
                    <fullName>Mono, County of</fullName>
                </value>
                <value>
                    <fullName>Monterey, County of</fullName>
                </value>
                <value>
                    <fullName>Napa, County of</fullName>
                </value>
                <value>
                    <fullName>Nevada, County of</fullName>
                </value>
                <value>
                    <fullName>Orange, County of</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Courts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Courts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Courts</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations (Courts)</relationshipLabel>
        <relationshipName>User_Registrations4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Tribal</fullName>
                </value>
                <value>
                    <fullName>Special District</fullName>
                </value>
                <value>
                    <fullName>Courts</fullName>
                </value>
                <value>
                    <fullName>Fire Agency</fullName>
                </value>
                <value>
                    <fullName>MARS Paying Entity</fullName>
                </value>
                <value>
                    <fullName>Federal Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Facility Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations (Facility)</relationshipLabel>
        <relationshipName>User_Registrations5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Federal_Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Federal Tax ID #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Government_Entity_Type__c</fullName>
        <label>Non-Government Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Health Care Facility</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Non_Governmental_Entity__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Non-Governmental Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>32</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request Denied</fullName>
                </value>
                <value>
                    <fullName>Entity Change Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special District</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Special District</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations (Special District)</relationshipLabel>
        <relationshipName>User_Registrations3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>State Agency</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations</relationshipLabel>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tribal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tribal</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Tribal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations (Tribal)</relationshipLabel>
        <relationshipName>User_Registrations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <recordTypes>
        <fullName>PHOS</fullName>
        <active>true</active>
        <label>PHOS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Registration</fullName>
        <active>true</active>
        <label>Registration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CommunityAppPHOSRegistrationCtrl.cls
/***********************************************************************************************************************************
* Class Name   : CommunityAppPHOSRegistrationCtrl
* Description  : An apex page controller that supports self registration of users in communities that allow self registration
* Author       : Pankaj
* Created On   : 07/09/2020
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj            07/09/2020       Initial Implementation
**************************************************************************************************************************************/

public without sharing class CommunityAppPHOSRegistrationCtrl {

    /***********************************************
    * Method Name : processPHOSRequest
    * Author : Pankaj
    * Inputs : String userRegistrationStr
    * Description: This method process the PHOS App Request.
    *********************************************/
    @AuraEnabled
    public static void processPHOSRequest(String userRegistrationStr) {

        User_Registration__c userRegistration = (User_Registration__c) JSON.deserialize(userRegistrationStr, User_Registration__c.class);
        system.debug('userRegistration----'+userRegistration);

        User_Registration__c newUserReg = [ SELECT City__c,Community_Application__c,
                                            County__c,Courts__c,Email__c,Entity_Type__c,Facility_Name__c,Facility__c,
                                            Federal_Tax_ID__c, First_Name__c,Last_Name__c,
                                            Non_Governmental_Entity__c,Non_Government_Entity_Type__c,
                                            Password__c,Phone__c,Special_District__c,State_Agency__c,
                                            State__c,Status__c,Street_Address__c,Token__c,Tribal__c,City_Name__c,
                                            Zip_Postal_Code__c,User__c FROM User_Registration__c
                                            WHERE User__c =: UserInfo.getUserId() and Email__c =: UserInfo.getUserEmail()
                                            ORDER BY CreatedDate DESC LIMIT 1];
        String newUserRegistration = JSON.serialize(newUserReg);
        //newUserRegistration = newUserRegistration.replace('Id','----');
        User_Registration__c userReg = (User_Registration__c) JSON.deserialize(newUserRegistration, User_Registration__c.class);
        userReg.Status__c = 'App Requested';
        // remove id from existing record of User Registration
        userReg.Id = null;
        userReg.Community_Application__c = userRegistration.Community_Application__c;
        userReg.RecordTypeId = Schema.SObjectType.User_Registration__c.getRecordTypeInfosByDeveloperName().get('PHOS').getRecordTypeId();
        insert userReg;
        updateOwner(userReg.Id);
        PHOS_UserInfoEmail userInfoObject = new PHOS_UserInfoEmail(userReg.Id);
        System.enqueueJob(userInfoObject);
        //sendEmailInformationForPHOSAppRequest(userReg.Id);
        //System.assertEquals('34', '4444');
    }

    /***********************************************
    * Method Name : processPHOSRequestForRejection
    * Author : Pankaj
    * Inputs : String userRegistrationStr
    * Description: This method process the PHOS App Request for Rejection.
    *********************************************/
    @AuraEnabled
    public static void processPHOSRequestForRejection(String userRegistrationStr) {
        User userRec =  ApexUtils.getCurrentUserDetails();
        User_Registration__c userRegistration = (User_Registration__c) JSON.deserialize(userRegistrationStr, User_Registration__c.class);
        system.debug('userRegistration----'+userRegistration);
        userRegistration.Status__c = 'App Requested';
        // remove id from existing record of User Registration
        userRegistration.Community_Application__c = userRegistration.Community_Application__c;
        userRegistration.RecordTypeId = Schema.SObjectType.User_Registration__c.getRecordTypeInfosByDeveloperName().get('PHOS').getRecordTypeId();
        userRegistration.First_Name__c = userRec.FirstName;
        userRegistration.Last_Name__c = userRec.LastName;
        userRegistration.Email__c = userRec.Email;
        userRegistration.User__c = userRec.Id;
        userRegistration.Rejection_Reason__c = 'Entity Change Required';
        insert userRegistration;
        UserService.createCommunityStandardUser(new List<User_Registration__c>{userRegistration});
        updateOwner(userRegistration.Id);
        PHOS_UserInfoEmail userInfoObject = new PHOS_UserInfoEmail(userRegistration.Id);
        System.enqueueJob(userInfoObject);
    }

    /***********************************************
    * Method Name : updateOwner
    * Author : Pankaj
    * Inputs : String recordId
    * Description: This method update the record owner.
    *********************************************/
    public static void updateOwner(String recordId){
        User_Registration__c userReg = [SELECT Id,County__c,Non_Governmental_Entity__c,State_Agency__c,Entity_Type__c FROM User_Registration__c WHERE Id =: recordId];
        //String comment = 'Record for approval';

        List<Group> queues = new List<Group>();
        User user = [SELECT Id,Account.Parent.Queue_Name__c FROM User WHERE Id=:UserInfo.getUserId()];

        queues = [SELECT Id FROM Group WHERE DeveloperName=:user.Account.Parent.Queue_Name__c AND Type='Queue'];
        if(queues.size() == 0) return;

        User_Registration__c updateUserReg = new User_Registration__c(Id = userReg.Id, OwnerId = queues.get(0).Id);
        update updateUserReg;
    }

    /***********************************************
    * Method Name : getUserDetails
    * Author : Pankaj
    * Inputs : -
    * Description: This method return map of Contact details.
    *********************************************/
    @AuraEnabled
    public static Map<String,Object> getUserDetails(){
        Map<String,Object> returnMap = new Map<String,Object>();
        String userId = UserInfo.getUserId();
        User userRec = [SELECT Id,ContactId from User where Id =:userId];
        Contact contactRec = [SELECT FirstName,LastName,Email,Phone,Account.Name,Account.Parent.Name,Account.Entity_Type__c,Entity_Change_Requested__c FROM Contact WHERE Id =: userRec.ContactId];
        returnMap.put('ContactDetails',contactRec);
        return returnMap;
    }



    /***********************************************
    * Method Name : formatPlainBody
    * Author : Pankaj
    * Inputs : String plainBody
    * Description: This method return mail plain body, replace \n to <br/>.
    *********************************************/
    private static String formatPlainBody(String plainBody) {
        if (String.isEmpty(plainBody)) return '';
        return plainBody.replace('\n', '<br/>');
    }

    /***********************************************************************************************************************************
    * Class Name   : PHOS_UserInfoEmail
    * Description  : Inner class for send email to Queue members when user send PHOS App Request.
    * Author       : Pankaj
    * Created On   : 07/09/2020
    * Modification Log:  
    * --------------------------------------------------------------------------------------------------------------------------------------
    * Developer             Date             Description 
    * ---------------------------------------------------------------------------------------------------------------------------------------
    * Pankaj            07/09/2020       Initial Implementation
    **************************************************************************************************************************************/

    private class PHOS_UserInfoEmail implements Queueable {
        private String recordId;
        public  PHOS_UserInfoEmail(String recordId)
        {
            this.recordId = recordId;
        }
        public void execute(QueueableContext context) {
            System.debug('Line=111'+recordId);
            User_Registration__c userReg = [SELECT Id,OwnerId FROM User_Registration__c WHERE Id =: recordId];
            List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();
            List<Group> queues = new List<Group>();
            List<String> ccAddresses = new List<String>();
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            EmailTemplate et=[SELECT Id FROM EmailTemplate WHERE developerName = 'PHOS_User_Registration_Request'];
            List<User> userList = [SELECT Id,Email FROM User WHERE Id IN (SELECT UserOrGroupId  FROM GroupMember WHERE Group.Type='Queue' AND GroupId=:userReg.OwnerId) AND IsActive=true];
            System.debug('Line 119'+userList);
            if(userList.size() == 0) return;
            for (User userRecord : userList) {
                if(userRecord.Email != null)
                 ccAddresses.add(userRecord.Email);
            }
            Messaging.SingleEmailMessage singleEmail = Messaging.renderStoredEmailTemplate(et.Id, null, recordId);
            mail.htmlBody=String.isNotEmpty(singleEmail.htmlBody) ? singleEmail.htmlBody : formatPlainBody(singleEmail.plainTextBody);
            mail.subject = singleEmail.subject;
            mail.setWhatId(userReg.Id);
            mail.setSaveAsActivity(true);
            mail.setCcAddresses(ccAddresses);
            mails.add(mail);
            System.debug('Line 132'+mail);
            Messaging.sendEmail(mails);
        }
    }

}