codepkg/objects/Community_Application__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Community_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Application</label>
        <referenceTo>Community_Application__c</referenceTo>
        <relationshipLabel>Community Registration</relationshipLabel>
        <relationshipName>CommunityRegistration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Tribal</fullName>
                </value>
                <value>
                    <fullName>Special District</fullName>
                </value>
                <value>
                    <fullName>Courts</fullName>
                </value>
                <value>
                    <fullName>Fire Agency</fullName>
                </value>
                <value>
                    <fullName>MARS Paying Entity</fullName>
                </value>
                <value>
                    <fullName>Federal Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>32</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <recordTypes>
        <fullName>HMA</fullName>
        <active>true</active>
        <label>HMA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CommunitySetPasswordCtrlTest.cls
@IsTest
public class CommunitySetPasswordCtrlTest {

    @TestSetup
    static void makeData() {
        User_Registration__c userReg = PHOS_TestHelper.getUserRegistration(true);
        String record = JSON.serialize(userReg);
        //CommunityRegistrationCtrl.createUserRegistration(record);
        User_Registration__c userRec = [Select Id, Email__c, Entity_Type__c, Token__c, User__c from User_Registration__c where Email__c =: userReg.Email__c];

        Community_Application__c communityApp = new Community_Application__c(Name = 'HMA',
                isActive__c = true);
        insert communityApp;
    }

    @IsTest
    static void checktokenEmpty() {
        User_Registration__c userRec = [Select Id, Email__c, Entity_Type__c, Token__c, User__c from User_Registration__c];
        userRec.Token__c = '';
        Test.startTest();
        try {
            communitySetPasswordCtrl.setPassword(userRec.Token__c, 'test@1234');
            System.debug('------password------->' + userRec.Password__c);
        }
        catch(Exception ex) {
             system.assertNotEquals(null,ex.getMessage());
            //System.assertEquals('Token empty', ex.getMessage());
            System.debug('------------->' + ex.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    static void checkInvalidtoken() {
        User_Registration__c userRec = [Select Id, Email__c, Entity_Type__c, Token__c, User__c from User_Registration__c];
        userRec.Token__c = 'kC3FY6RC7mdiQSL7r5drp2F8fvnSQp3D';
        Test.startTest();
        try {
            communitySetPasswordCtrl.setPassword(userRec.Token__c, 'test@1234');
            System.debug('------password------->' + userRec.Password__c);
        }
        catch(Exception ex) {
            system.assertNotEquals(null,ex.getMessage());
            //System.assertEquals('Invalid token', ex.getMessage());
            System.debug('------------->' + ex.getMessage());
        }
        Test.stopTest();
    }
 
     @IsTest
    static void checkCreatedUserVerification() {
        User_Registration__c userReg = PHOS_TestHelper.getUserRegistration(false);
 		userReg.Status__c = 'Verification Pending';
        userReg.Token__c = 'kC3FY6RC7mdiQSL7r5drp2F8fvnSQp3D';
        String password = 'test@1234567';
        userReg.Password__c = password;
        userReg.User__c = UserInfo.getUserId();
        insert userReg;
        User_Registration__c userRec = [Select Id, Email__c, Entity_Type__c, Token__c, User__c from User_Registration__c where Token__c =: userReg.Token__c limit 1];
        Test.startTest();
        try {
            communitySetPasswordCtrl.setPassword(userRec.Token__c, password);
        }
        catch(Exception ex) {
            System.debug('------------->' + ex.getMessage());
        }
        Test.stopTest();
    }

     @IsTest
    static void checkPasswordReset() {
        User_Registration__c userReg = PHOS_TestHelper.getUserRegistration(false);
 		userReg.Status__c = 'Password Reset';
        userReg.Token__c = 'kC3FY6RC7mdiQSL7r5drp2F8fvnSQp3D';
        String password = 'test@1234567';
        userReg.Password__c = password;
        userReg.Email__c = 'test23432@gmail.com';
        userReg.User__c = UserInfo.getUserId();
        insert userReg;
        User_Registration__c userRec = [Select Id, Email__c, Entity_Type__c, Token__c, User__c from User_Registration__c where Token__c =: userReg.Token__c limit 1];
        Test.startTest();
        try {
            communitySetPasswordCtrl.setPassword(userRec.Token__c, password);
        }
        catch(Exception ex) {
            System.debug('------------->' + ex.getMessage());
        }
        Test.stopTest();
    }

}