codepkg/objects/Community_Application__c.object
<CustomObject>
    <label>Community Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Community_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Application</label>
        <referenceTo>Community_Application__c</referenceTo>
        <relationshipLabel>Community Registration</relationshipLabel>
        <relationshipName>CommunityRegistration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alameda, County of</fullName>
                </value>
                <value>
                    <fullName>Alpine, County of</fullName>
                </value>
                <value>
                    <fullName>Amador, County of</fullName>
                </value>
                <value>
                    <fullName>Butte, County of</fullName>
                </value>
                <value>
                    <fullName>Calaveras, County of</fullName>
                </value>
                <value>
                    <fullName>Colusa, County of</fullName>
                </value>
                <value>
                    <fullName>Contra Costa, County of</fullName>
                </value>
                <value>
                    <fullName>Del Norte, County of</fullName>
                </value>
                <value>
                    <fullName>El Dorado, County of</fullName>
                </value>
                <value>
                    <fullName>Fresno, County of</fullName>
                </value>
                <value>
                    <fullName>Glenn, County of</fullName>
                </value>
                <value>
                    <fullName>Humboldt, County of</fullName>
                </value>
                <value>
                    <fullName>Imperial, County of</fullName>
                </value>
                <value>
                    <fullName>Inyo, County of</fullName>
                </value>
                <value>
                    <fullName>Kern, County of</fullName>
                </value>
                <value>
                    <fullName>Kings, County of</fullName>
                </value>
                <value>
                    <fullName>Lake, County of</fullName>
                </value>
                <value>
                    <fullName>Lassen, County of</fullName>
                </value>
                <value>
                    <fullName>Los Angeles, County of</fullName>
                </value>
                <value>
                    <fullName>Madera, County of</fullName>
                </value>
                <value>
                    <fullName>Marin, County of</fullName>
                </value>
                <value>
                    <fullName>Mariposa, County of</fullName>
                </value>
                <value>
                    <fullName>Mendocino, County of</fullName>
                </value>
                <value>
                    <fullName>Merced, County of</fullName>
                </value>
                <value>
                    <fullName>Modoc, County of</fullName>
                </value>
                <value>
                    <fullName>Mono, County of</fullName>
                </value>
                <value>
                    <fullName>Monterey, County of</fullName>
                </value>
                <value>
                    <fullName>Napa, County of</fullName>
                </value>
                <value>
                    <fullName>Nevada, County of</fullName>
                </value>
                <value>
                    <fullName>Orange, County of</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Tribal</fullName>
                </value>
                <value>
                    <fullName>Special District</fullName>
                </value>
                <value>
                    <fullName>Courts</fullName>
                </value>
                <value>
                    <fullName>Fire Agency</fullName>
                </value>
                <value>
                    <fullName>MARS Paying Entity</fullName>
                </value>
                <value>
                    <fullName>Federal Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Governmental_Entity__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Non-Governmental Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>State Agency</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations</relationshipLabel>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <recordTypes>
        <fullName>PHOS</fullName>
        <active>true</active>
        <label>PHOS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CommunityAppPHOSRegistrationCtrlTest.cls
@isTest(seeAllData=false)
public without sharing class CommunityAppPHOSRegistrationCtrlTest {
    public static Contact getPortalContact(boolean create) {
        Account acc = PHOS_TestHelper.getAccount(create);
        Contact portalContact = new Contact();
        portalContact.Firstname='FirstNameportal';
        portalContact.Lastname='LastNameportal';
        portalContact.Email='email@portal.com';
        portalContact.Phone ='923-875-1274';
        portalContact.AccountId = acc.Id;

        if(create)
            insert portalContact;
        return portalContact;
    }

    public static User getPortalUser(boolean create) {

        //**** First give call to getPortalContact() methos and provide ContactId to PortalUser

        Profile profile = [select Id,name from Profile where Name like 'PHOS Customer Community Plus Login User' limit 1];
        UserRole userRole = [Select Id, Name from UserRole where Name like 'Region 1 Customer User' limit 1];
        system.debug('profile-----------'+profile);
        Contact con = getPortalContact(create);
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        String uniqueName = orgId + dateString;
        User portalUser = new User(
                Username = uniqueName+'@acme.com',
                //ContactId = contact.Id,
                ProfileId = profile.Id,
                Alias = 'test123',
                Email = 'email@portal.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'McTesty',
                CommunityNickname = 'test12345',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                ContactId = con.Id
                //IsActive = true,
                //UserRoleId = userRole.Id
        );

        if(create)
            insert portalUser;
        return portalUser;
    }

    public static User_Registration__c getUserRegistration(boolean create){
        Account newAccount = PHOS_TestHelper.getAccount(create);
        User_Registration__c   newUserRegistration = new User_Registration__c();
        //newUserRegistration.Community_Application__c = Community_Application__c.Id;
        newUserRegistration.County__c = 'Alameda';
        newUserRegistration.First_Name__c = 'testFirstName';
        newUserRegistration.Last_Name__c = 'testLastName';
        newUserRegistration.Status__c = 'Pending for Approval';
        newUserRegistration.Email__c = 'email@portal.com';
        newUserRegistration.Non_Governmental_Entity__c = 'test';
        //newUserRegistration.State_Agency__c = newAccount.Id;
        newUserRegistration.Entity_Type__c = 'State Agency';

        if(create)
            insert newUserRegistration;
        return newUserRegistration;
    }
    /*@isTest public static void testProcessPHOSRequest(){

        Account acc = PHOS_TestHelper.getParentAccount(true);
        Contact con = getPortalContact(false);
        con.AccountId = acc.Id;
        insert con; 
       // User u =[SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];  
        User u = [SELECT Id FROM User WHERE ID =: UserInfo.getUserId()]; 
        User usr = getPortalUser(false);
        usr.ContactId = con.Id;
        usr.IsActive = true;
        insert usr;
        Group g1;
        System.runAs(u) {  
             g1 = new Group(Name='testQ', type='Queue');
            insert g1;   
            QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'User_Registration__c');
            insert q1;
            GroupMember member = new GroupMember();
            member.UserOrGroupId = usr.Id;
            member.GroupId = g1.Id;
            insert member;
        }
        System.runAs(usr) {  
            Test.startTest();
                User_Registration__c newUserRegistration = getUserRegistration(false);
                newUserRegistration.User__c = usr.Id;
                newUserRegistration.OwnerId = g1.Id;
                newUserRegistration.Email__c = 'email'+UserServiceTest.generateRandomString(8)+'@portal.com';
                insert newUserRegistration;
                newUserRegistration.Id = null;
                String userRegistrationStr = JSON.serialize(newUserRegistration);
                
                CommunityAppPHOSRegistrationCtrl.processPHOSRequest(userRegistrationStr);
                CommunityAppPHOSRegistrationCtrl.processPHOSRequestForRejection(userRegistrationStr);
            Test.stopTest();
        }
    }

     @isTest public static void testProcessUserRegApprovalRequest(){
         Account newAccount = new Account();
         newAccount.Name = 'NewTest1'+system.now()+Math.random();
         newAccount.BillingStreet='rse';
         newAccount.BillingCountry='USA1';
         newAccount.type = 'Customer';
         newAccount.BillingState='NY';
         newAccount.Queue_Name__c = 'test232';
         newAccount.BillingPostalCode='3421545';
         newAccount.Phone='5445342134';
         newAccount.Website='https://www.google.com';
         insert newAccount;
         Contact newContact = PHOS_TestHelper.getContact(false);
         newContact.AccountId = newAccount.Id;
         insert newContact;
         User portalUser = PHOS_TestHelper.getPortalUser(false);
         portalUser.ContactId = newContact.Id;
         //portalUser.AccountId = newContact.AccountId;
         insert portalUser;
         System.runAs(portalUser) {
             Account newAccount1 = PHOS_TestHelper.getAccount(true);
             Account acc = [SELECT Id,Name,Parent.Queue_Name__c FROM Account WHERE Id=: newContact.AccountId LIMIT 1];
             User_Registration__c newUserRegistration = PHOS_TestHelper.getUserRegistration(false);
             insert newUserRegistration;
             String recordId = String.valueOf(newUserRegistration.Id);

             test.startTest();
             //CommunityAppPHOSRegistrationCtrl.processUserRegApprovalRequest(recordId);
             test.stopTest();
         }
     }*/

    @isTest public static void testProcessPHOSRequestForRejection(){

        /*Account acc = PHOS_TestHelper.getParentAccount(true);
        Contact con = PHOS_TestHelper.getPortalContact(false);
        con.AccountId = acc.Id;
        insert con;
        User u = PHOS_TestHelper.getPortalUser(false);
        u.ContactId = con.Id;
        insert u;
        System.runAs(u) {
            User_Registration__c newUserRegistration = getUserRegistration(false);
            //insert newUserRegistration;
            String userRegistrationStr = JSON.serialize(newUserRegistration);
            test.startTest();
            CommunityAppPHOSRegistrationCtrl.processPHOSRequestForRejection(userRegistrationStr);
            test.stopTest();
        }*/
    }

    @isTest public static void testUpdateOwner(){

        Account acc = PHOS_TestHelper.getParentAccount(true);
        Contact con = PHOS_TestHelper.getPortalContact(false);
        con.AccountId = acc.Id;
        insert con;
        User u = PHOS_TestHelper.getPortalUser(false);
        u.ContactId = con.Id;
        insert u;
        System.runAs(u) {
            User_Registration__c newUserRegistration = PHOS_TestHelper.getUserRegistration(false);
            insert newUserRegistration;
            test.startTest();
            CommunityAppPHOSRegistrationCtrl.updateOwner(newUserRegistration.Id);
            CommunityAppPHOSRegistrationCtrl.getUserDetails();
            test.stopTest();
        }
    }
}