codepkg/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>Pre_Application__c</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Working Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Responsible Representative</fullName>
                </value>
                <value>
                    <fullName>Match Commitment</fullName>
                </value>
                <value>
                    <fullName>Maintenance Commitment</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA Viewer</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic Analyst</fullName>
                </value>
                <value>
                    <fullName>Authorized Agent</fullName>
                    <isActive>false</isActive>
                    <label>Authorized Agent</label>
                </value>
                <value>
                    <fullName>Requestor</fullName>
                    <isActive>false</isActive>
                    <label>Requestor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Pre_Application__c.object
<CustomObject>
    <fields>
        <fullName>Activity_TitleName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The project/plan title must include the subapplicant name and subapplication type or project type. Do not use abbreviations in the title. For example, Marin County Marin Center Exhibit Hall - Seismic Retrofit Project, City of Los Angeles Stormwater Analys</inlineHelpText>
        <label>Project / Plan Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Federal_Request_Share__c</fullName>
        <inlineHelpText>Financial responsibility of federal government.</inlineHelpText>
        <label>Federal Request Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>First_Name_of_Person_Completing_NOI__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name of Person Completing NOI</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_of_Person_Completing_NOI__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name of Person Completing NOI</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>For example, DR4407-PJ0001</inlineHelpText>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsible_Representative_Name__c</fullName>
        <formula>Responsible_Representative__r.FirstName + &apos; &apos; + Responsible_Representative__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Responsible Representative Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsible_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pre-Applications (Responsible Representative)</relationshipLabel>
        <relationshipName>Pre_Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NOI Approved</fullName>
                </value>
                <value>
                    <fullName>Approved for Future Consideration</fullName>
                </value>
                <value>
                    <fullName>Ineligible Sub-applicant</fullName>
                </value>
                <value>
                    <fullName>Ineligible Activity</fullName>
                </value>
                <value>
                    <fullName>Ineligible Sub-applicant &amp; Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
                <value>
                    <fullName>Analyst Review</fullName>
                </value>
                <value>
                    <fullName>Request for Information</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Manager Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <recordTypes>
        <fullName>BRIC</fullName>
        <active>true</active>
        <description>Used for BRIC NOI Forms</description>
        <label>BRIC</label>
    </recordTypes>
    <recordTypes>
        <fullName>FMA</fullName>
        <active>true</active>
        <description>Used for FMA NOI Forms</description>
        <label>FMA</label>
    </recordTypes>
    <recordTypes>
        <fullName>HMGP</fullName>
        <active>true</active>
        <description>For HMGP NOI Requests</description>
        <label>HMGP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HMANOI_StatusEmail.cls
/***********************************************************************************************************************************
* Class Name   : HMANOI_StatusEmail
* Description  : This class for send HMA NOI Status Email
* Author       : Pankaj
* Created On   : 07/12/2020
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj               07/12/2020       Initial Implementation
**************************************************************************************************************************************/

public class HMANOI_StatusEmail {

    /***********************************************
    * Method Name : getSendEmailInfo
    * Author : Pankaj
    * Inputs : List<Id> recIds
    * Description: This method send email info with status approved/rejected
    *********************************************/
    @InvocableMethod(Label = 'Pre-Application Send Email'  Description = 'Send Email For Status Approved/Rejected')
    public static void getSendEmailInfo(List<Id> recIds){
        List<String> toAddresses = new List<String>();
        List<String> ccAddresses = new List<String>();
        List<Pre_Application__c> preAppRecInfo = [Select Id, 
                                                        RecordType.Name, 
                                                        CreatedById, 
                                                        CreatedBy.Email, 
                                                        Status__c, 
                                                        Status_Reason__c, 
                                                        Project_Number__c, 
                                                        First_Name_of_Person_Completing_NOI__c, 
                                                        Last_Name_of_Person_Completing_NOI__c, 
                                                        Activity_TitleName__c, 
                                                        Federal_Request_Share__c,
                                                        Responsible_Representative__c,
                                                        Responsible_Representative_Name__c,
                                                        (SELECT Id, Contact__r.Email from Contact_Roles__r WHERE Role__c includes('Primary Contact','Responsible Representative'))
                                                        from Pre_Application__c Where Id IN :recIds];
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        for(Pre_Application__c preAppRec : preAppRecInfo){
            String toAddress = preAppRec.CreatedBy.Email;
            toAddresses.add(toAddress);
            if(preAppRec.Contact_Roles__r.size() > 0 && preAppRec.RecordType.Name == 'HMGP'){
                for(Contact_Role__c role : preAppRec.Contact_Roles__r) {
                    if(String.isNotEmpty(role.Contact__r.Email)) {
                        toAddresses.add(role.Contact__r.Email);
                    } 
                }
            }
            if(preAppRec.Status__c == 'Approved' && preAppRec.Status_Reason__c == 'NOI Approved' && preAppRec.RecordType.Name == 'HMGP'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'HMA_Status_Approved_NOI_Approved', 'HMA_From_Email_Addresses');
            } 
            if(preAppRec.Status__c == 'Approved' && preAppRec.Status_Reason__c == 'Approved For Future Consideration' && preAppRec.RecordType.Name == 'HMGP'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'HMA_Status_Approved_Approved_For_Future_Consideration', 'HMA_From_Email_Addresses');
            }
            if(preAppRec.Status__c == 'Rejected' && preAppRec.Status_Reason__c =='Ineligible Activity' && preAppRec.RecordType.Name == 'HMGP'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'HMA_Status_Rejected_Ineligible_Activity', 'HMA_From_Email_Addresses');
            } 
            if(preAppRec.Status__c == 'Rejected' && preAppRec.Status_Reason__c == 'Ineligible Sub-applicant' && preAppRec.RecordType.Name == 'HMGP'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'HMA_Status_Rejected_Ineligible_Subapplicant', 'HMA_From_Email_Addresses');
            } 
            if(preAppRec.Status__c == 'Rejected' && preAppRec.Status_Reason__c == 'Ineligible Sub-applicant & Activity' && preAppRec.RecordType.Name == 'HMGP'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'HMA_Status_Rejected_Ineligible_Subapplicant_And_Activity', 'HMA_From_Email_Addresses');
            }

            if(preAppRec.Status__c == 'Approved' && preAppRec.Status_Reason__c == 'NOI Approved' && preAppRec.RecordType.Name == 'BRIC'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'BRIC_Status_Approved_NOI_Approved', 'HMA_From_Email_Addresses');
            }
            if(preAppRec.Status__c == 'Rejected' && preAppRec.Status_Reason__c =='Ineligible Activity' && preAppRec.RecordType.Name == 'BRIC'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'BRIC_Status_Rejected_Ineligible_Activity', 'HMA_From_Email_Addresses');
            } 
            if(preAppRec.Status__c == 'Rejected' && preAppRec.Status_Reason__c == 'Ineligible Sub-applicant' && preAppRec.RecordType.Name == 'BRIC'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'BRIC_Status_Rejected_Ineligible_Subapplicant', 'HMA_From_Email_Addresses');
            } 
            if(preAppRec.Status__c == 'Rejected' && preAppRec.Status_Reason__c == 'Ineligible Sub-applicant & Activity' && preAppRec.RecordType.Name == 'BRIC'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'BRIC_Status_Rejected_Ineligible_Subapplicant_And_Activity', 'HMA_From_Email_Addresses');
            } 

            if(preAppRec.Status__c == 'Approved' && preAppRec.Status_Reason__c == 'NOI Approved' && preAppRec.RecordType.Name == 'FMA'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'FMA_Status_Approved_NOI_Approved', 'HMA_From_Email_Addresses');
            }
            if(preAppRec.Status__c == 'Rejected' && preAppRec.Status_Reason__c =='Ineligible Activity' && preAppRec.RecordType.Name == 'FMA'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'FMA_Status_Rejected_Ineligible_Activity', 'HMA_From_Email_Addresses');
            } 
            if(preAppRec.Status__c == 'Rejected' && preAppRec.Status_Reason__c == 'Ineligible Sub-applicant' && preAppRec.RecordType.Name == 'FMA'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'FMA_Status_Rejected_Ineligible_Subapplicant', 'HMA_From_Email_Addresses');
            } 
            if(preAppRec.Status__c == 'Rejected' && preAppRec.Status_Reason__c == 'Ineligible Sub-applicant & Activity' && preAppRec.RecordType.Name == 'FMA'){
                mails = EmailHelper.sendEmail(new List<SObject>{preAppRec}, toAddresses, ccAddresses, 'FMA_Status_Rejected_Ineligible_Subapplicant_And_Activity', 'HMA_From_Email_Addresses');
            } 
        }
        Messaging.sendEmail(mails);
    }
    public static List<String> getContactRoleEmail(List<Id> preApplicationIds) {
        List<String> emails = new List<String>();
        List<Contact_Role__c > conRoles = [SELECT Id, Contact__c, Contact__r.Email, Pre_Application__c, Pre_Application__r.Status__c FROM Contact_Role__c  WHERE Pre_Application__c IN: preApplicationIds AND Role__c includes('Responsible Representative')];
        for(Contact_Role__c role : conRoles) {
            if(String.isNotEmpty(role.Contact__r.Email)) {
                emails.add(role.Contact__r.Email);
            }                
        }
        return emails;
    }
}