codepkg/objects/County_Config__mdt.object
<CustomObject>
    <description>This metadata is created to configure the public groups with respect to county and application</description>
    <fields>
        <fullName>Public_Group_API_Name__c</fullName>
        <description>API name of public group</description>
        <inlineHelpText>API name of public group</inlineHelpText>
        <label>Public Group API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>County Config</label>
    <pluralLabel>County Configs</pluralLabel>
</CustomObject>

codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <description>Date it was passed &amp; approved by the governing body</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date it was passed &amp; approved by the governing body</inlineHelpText>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Of_Fiscal_Year_End__c</fullName>
        <description>Date Of Fiscal Year End</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date Of Fiscal Year End</inlineHelpText>
        <label>Date Of Fiscal Year End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Of_Signature__c</fullName>
        <description>Date Of Signature</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date Of Signature</inlineHelpText>
        <label>Date Of Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpirationDate__c</fullName>
        <description>Document Expiration Date</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Document Expiration Date</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Global_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Global Document is used for All Projects related to Incident / SubRecipient</description>
        <label>Global Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HH_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to HH Application Object, in order to upload the Documents for Home Hardening Application.</description>
        <inlineHelpText>Lookup to HH Application Object, in order to upload the Documents for Home Hardening Application.</inlineHelpText>
        <label>HH Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Letter_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Letter Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Document Stage</description>
        <inlineHelpText>The Document Stage</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>HH_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>County of Property</description>
        <inlineHelpText>County of Property</inlineHelpText>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Shasta</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                    <isActive>false</isActive>
                    <label>Los Angeles</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the application</description>
        <inlineHelpText>Stage of the application</inlineHelpText>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Community Review</fullName>
                </value>
                <value>
                    <fullName>Community Decision</fullName>
                </value>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Decision</fullName>
                </value>
                <value>
                    <fullName>CalOES Review</fullName>
                    <label>Cal OES Review</label>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                    <label>Cal OES Decision</label>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Approved- Converted</fullName>
                    <label>Approved - Converted</label>
                </value>
                <value>
                    <fullName>Rejected - Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/DocumentTriggerHelper.cls
/**
 * Created by Ricky 0n 20/11/2020....
 */
public with sharing class DocumentTriggerHelper extends TriggerHelper{
    public override void processAfterInsert(){
        shareDocumentWithCommunityAndCalOES();
    }
    public override void processBeforeUpdate() {
        preventChangingDocumentStatus();
        clearGlobalDocumentsRelatedClonedDates();
    }
    //To prevent changing of Document "Stage" to "Uploaded", until a file is uploaded in it...
    private void preventChangingDocumentStatus() {
        Map<Id, Document__c> idToDocumentMap = new Map<Id, Document__c>();
        for(Document__c doc : (List<Document__c>) Trigger.new) //Iterating Trigger.new of Document Trigger...
        {
            Document__c oldDocRecord = (Document__c )(Trigger.oldMap.get(doc.Id)); //Fetching Old record from Trigger.oldMap collection....
            if((oldDocRecord.Stage__c != doc.Stage__c) && doc.Stage__c == ALS_CONSTANTS.Document_Stage_Uploaded) //Condition to check if the stage is changed to Uploaded...
            {
                idToDocumentMap.put(doc.Id, doc); //Collecting the Document record into a Mao collection.....
            }
        }
        if (idToDocumentMap.size() > 0) { //Checking for null pointer for Exception...
            //Collecting all the contentDocumentLink which has been created for this current Document record...
            Map<Id, Document__c> lstContDocLink = new Map<Id, Document__c>([SELECT Id, Name, (SELECT Id,LinkedEntityId,ContentDocumentId FROM ContentDocumentLinks) FROM Document__c WHERE Id IN : idToDocumentMap.keySet()]);

            for(Document__c docToProcess : idToDocumentMap.values()) { //Iterating the Document map...
                List<ContentDocumentLink> contentDocLinks = lstContDocLink.get(docToProcess.Id).ContentDocumentLinks; //Fetching the ContentDocumentLick for the Document...
                if(contentDocLinks.isEmpty()) //To check if there is any ContentDocumentLink available, if not then prevent changing stage to Uploaded..
                {
                    docToProcess.addError('Please upload the file to mark the Stage as Uploaded.'); //Displaying the error...
                }
            }
        }
    }
    private void clearGlobalDocumentsRelatedClonedDates() {
        for(Document__c doc : (List<Document__c>) Trigger.new) //Iterating Trigger.new of Document Trigger.
        {
            Document__c oldDocRecord = (Document__c )(Trigger.oldMap.get(doc.Id)); //Fetching Old record from Trigger.oldMap collection.
            if(doc.Global_Document__c == false && oldDocRecord.Global_Document__c == true ){
                doc.ExpirationDate__c = null;
                doc.Date_Of_Signature__c = null;
                doc.Date_Of_Fiscal_Year_End__c = null;
                doc.Approval_Date__c = null;
                doc.Letter_Date__c = null;
            }
        }
    }
//    private void  shareDocumentWithCommunityAndCalOES(){
//        List<Id> hhAppId = new List<Id>();
//        List<Document__c> docList = new List<Document__c>();
//        for(Document__c doc : (List<Document__c>) Trigger.new) //Iterating Trigger.new of Document Trigger.
//        {
//            if(doc.hh_Application__c !=null){
//                hhAppId.add(doc.hh_Application__c);
//                docList.add(doc);
//            }
//        }
//        if(hhAppId.size()>0){
//            Map<Id,HH_Application__c> hhApplicationsIdToHHProcess = new Map<Id,HH_Application__c>([SELECT Id,County__c,stage__c,(SELECT Id,HH_Application__c from Documents__r) from HH_Application__c WHERE  Id IN :hhAppId AND stage__c !='draft']);
//            Map<String,Group> groupNameToGroupMap = new Map<String, Group>();
//
//            if(hhApplicationsIdToHHProcess.size()>0){
//                List<County_Config__mdt> CountyConfig = County_Config__mdt.getall().values();//Get Records from Global Document Configuration Metadata
//                Map<String,County_Config__mdt> labelToCountyMp = new Map<String, County_Config__mdt>();
//                for(County_Config__mdt cc:CountyConfig){
//                    labelToCountyMp.put(cc.label,cc);
//                }
//
//                Set<String> groupsAPINames = new Set<String>();
//                for(HH_Application__c hhApplication: hhApplicationsIdToHHProcess.values()) {
//                        groupsAPINames.add(labelToCountyMp?.get(hhApplication?.County__c)?.Public_Group_API_Name__c);
//                        groupsAPINames.add(HH_CONSTANTS.HH_CalOESInternal_User_Group_APIName);
//                }
//                List<Group> groups = [SELECT Id FROM Group WHERE DeveloperName IN :groupsAPINames AND Type != 'Queue'];
//                if(groups?.size() >0){
//                    for (Group gp : groups) {
//                        groupNameToGroupMap.put(gp.DeveloperName, gp);
//                    }
//                }
//
//                List<Document__Share> dShares = new List<Document__Share>();
//                for(HH_Application__c hhApplication: hhApplicationsIdToHHProcess.values()) {
//                    for (Document__c docs : hhApplication.Documents__r) {
//                        Document__Share dShare = new Document__Share(ParentId = docs.Id, UserOrGroupId = groupNameToGroupMap.get(labelToCountyMp?.get(hhApplication?.County__c)?.Public_Group_API_Name__c).Id, AccessLevel = 'Edit', RowCause = Document__Share.RowCause.HH_Document__c);
//                        dShares.add(dShare);
//                        if(hhApplication.county__c !=null){
//                            Document__Share dShare1 = new Document__Share(ParentId = docs.Id, UserOrGroupId = groupNameToGroupMap.get(HH_CONSTANTS.HH_CalOESInternal_User_Group_APIName).Id, AccessLevel = 'Edit', RowCause = Document__Share.RowCause.HH_Document__c);
//                            dShares.add(dShare1);
//                        }
//                    }
//                }
//                if(dShares.size() >0){
//                    new SystemContextProvider().insertDocumentShares(dShares);
//                }
//            }
//        }
//    }
private void  shareDocumentWithCommunityAndCalOES() {
    List<Document__c> docListToProcess = new List<Document__c>();
    for(Document__c doc : (List<Document__c>) Trigger.new) //Iterating Trigger.new of Document Trigger.
        {
            if(doc.hh_Application__c !=null){
                docListToProcess.add(doc);
            }
        }
    if(docListToProcess.size() >0) {
        shareHHDocuments(docListToProcess);
    }
}

public void shareHHDocuments(List<Document__c> docs) {
    new SystemContextProvider().shareHHDocuments(docs);
}



public  without sharing class SystemContextProvider {

    public void shareHHDocuments(List<Document__c> docs) {
        System.debug('share Documents: '+docs);
        List<String> applicationIds = new List<String>();
        for(Document__c doc : docs) {
            if(doc.HH_Application__c != null) {
                applicationIds.add(doc.HH_Application__c);
            }
        }
        Map<Id,HH_Application__c> appMap = new Map<Id,HH_Application__c> ([SELECT Id,County__c,Applicant__c FROM HH_Application__c WHERE
                                                                      Id IN: applicationIds AND Stage__c !=: HH_CONSTANTS.HHApplication_Stage_Draft
                                                                      AND (Status__c != null OR Status__c !=:HH_CONSTANTS.HHApplication_Status_New)]);
        System.debug('appMaps: '+appMap);
        if (appMap.size()==0) {
            return ;
        }
        List<String> applicantIds = new List<String>();
        List<String> counties = new List<String>();
        for(HH_Application__c app : appMap.values()) {
            applicantIds.add(app.Applicant__c);
            counties.add(app.County__c);
        }
        List<User> users = [SELECT Id,ContactId FROM User WHERE ContactId IN: applicantIds];
        Map<String,String> applicantMap = new Map<String,String>();
        for (User user : users) {
            applicantMap.put(user.ContactId, user.Id);
        }
        List<County_Config__mdt> countyConfigs = [SELECT Id,Label,Public_Group_API_Name__c FROM County_Config__mdt WHERE Label IN:counties];
        Map<String,String> grpAPIToLabelMap = new Map<String,String>();
        for (County_Config__mdt countyConfig : countyConfigs) {
            grpAPIToLabelMap.put(countyConfig.Public_Group_API_Name__c, countyConfig.Label);
        }
        grpAPIToLabelMap.put(HH_CONSTANTS.HH_CalOESInternal_User_Group_APIName, 'CalOES');
        grpAPIToLabelMap.put(HH_CONSTANTS.HH_FEMA_User_Group_APIName,'FEMA');
        List<Group> groups = [SELECT Id,DeveloperName FROM Group WHERE DeveloperName IN :grpAPIToLabelMap.keySet() AND Type != 'Queue'];
        Map<String,String> groupLabelToIdMap = new Map<String,String>();
        for( Group group1 : groups) {
            String identifierName = grpAPIToLabelMap.get(group1.DeveloperName);
            if(identifierName != null) {
                groupLabelToIdMap.put(identifierName,group1.Id);
            }
        }
        System.debug('groupLabelToIdMap: '+ groupLabelToIdMap);
        List<Document__Share> dShares = new List<Document__Share>();
        for (Document__c doc : docs) {
            HH_Application__c app = appMap.get(doc.HH_Application__c);
            String femaGroupId = groupLabelToIdMap.get('FEMA');
            String caloesGroupId = groupLabelToIdMap.get('CalOES');
            String countyGroupId = groupLabelToIdMap.get(app.County__c);
            String userId = applicantMap.get(app.Applicant__c);
            //caloes internal user
            if(caloesGroupId != null) {
                Document__Share dShare = new Document__Share(ParentId=doc.Id, UserOrGroupId=caloesGroupId, AccessLevel='Edit', RowCause = Document__Share.RowCause.HH_Document__c);
                dShares.add(dShare);
            }
            //community user
            if(countyGroupId != null) {
                Document__Share dShare = new Document__Share(ParentId=doc.Id, UserOrGroupId=countyGroupId, AccessLevel='Edit', RowCause = Document__Share.RowCause.HH_Document__c);
                dShares.add(dShare);
            }
            //Homeowner
            if(userId != null) {
                Document__Share dShare = new Document__Share(ParentId=doc.Id, UserOrGroupId=userId, AccessLevel='Edit', RowCause = Document__Share.RowCause.HH_Document__c);
                dShares.add(dShare);
            }
            //fema
            if(femaGroupId != null ) {
                Document__Share dShare = new Document__Share(ParentId=doc.Id, UserOrGroupId=femaGroupId, AccessLevel='Edit', RowCause = Document__Share.RowCause.HH_Document__c);
                dShares.add(dShare);
            }
        }
        System.debug('doc shares: '+dshares);
        if(dShares.size() > 0) {
            insert dShares;
        }
    }

   }

   
}