codepkg/objects/County_Config__mdt.object
<CustomObject>
    <description>This metadata is created to configure the public groups with respect to county and application</description>
    <fields>
        <fullName>Queue_API_Name__c</fullName>
        <description>API name of the Queue.</description>
        <inlineHelpText>API name of the Queue.</inlineHelpText>
        <label>County Manager Queue API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>County Config</label>
    <pluralLabel>County Configs</pluralLabel>
</CustomObject>

codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Application_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CWMP_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>County of Property</description>
        <inlineHelpText>County of Property</inlineHelpText>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Shasta</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                    <isActive>false</isActive>
                    <label>Los Angeles</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the application</description>
        <inlineHelpText>Stage of the application</inlineHelpText>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Community Review</fullName>
                </value>
                <value>
                    <fullName>Community Decision</fullName>
                </value>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Decision</fullName>
                </value>
                <value>
                    <fullName>CalOES Review</fullName>
                    <label>Cal OES Review</label>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                    <label>Cal OES Decision</label>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Approved- Converted</fullName>
                    <label>Approved - Converted</label>
                </value>
                <value>
                    <fullName>Rejected - Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HH_UpdateApplicationLeadCtrl.cls
/***********************************************************************************************************************************
* Class Name   : HH_UpdateApplicationLeadCtrl
* Description  : This Controller class is used in hhApplicationLead LWC component.
* Author       : Shantanu
* Created On   : 17/11/2021
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Shantanu             17/11/2021       Initial Implementation
**************************************************************************************************************************************/

public without sharing class HH_UpdateApplicationLeadCtrl {


    @AuraEnabled
    public static Map<String,Object>  getQueueName(String applicationId) {
        Map<String,Object> returnMap = new Map<String,Object>();
        List<HH_Application__c> apps = [SELECT Id,County__c,Application_Lead__c,Stage__c,Status__c FROM HH_Application__c WHERE Id=:applicationId];
        String countyQueueAPIName = getCountyQueueAPIName();
        if(countyQueueAPIName == null && apps.get(0).County__c != null) {
            List<County_Config__mdt> countyconfigs = [SELECT Id,Queue_API_Name__c FROM County_Config__mdt WHERE Label =: apps.get(0).County__c];
            if(countyconfigs.size() > 0 ) {
                returnMap.put('queueName', countyconfigs.get(0).Queue_API_Name__c);
            }
        } else {
            returnMap.put('queueName', countyQueueAPIName);
        }
       
        returnMap.put('applicationLeadId', apps.get(0).Application_Lead__c);
        returnMap.put('showComponent', true);
        return returnMap;
    }

    private static String getCountyQueueAPIName() {
        List<GroupMember> members = [SELECT Id,GroupId,Group.DeveloperName FROM GroupMember WHERE UserOrGroupId =:UserInfo.getUserId() AND Group.Type = 'Queue'];
        if(members.size() > 0 ) {
            System.debug('members: '+members.get(0).Group.DeveloperName);
            List<County_Config__mdt> countyconfigs = [SELECT Id,Queue_API_Name__c FROM County_Config__mdt WHERE Queue_API_Name__c =: members.get(0).Group.DeveloperName];
            System.debug('countyconfigs: '+countyconfigs);
            if(countyconfigs.size() > 0 && countyconfigs.get(0).Queue_API_Name__c != null) {
                return countyconfigs.get(0).Queue_API_Name__c;
            }
        }
        return null;
    }


   public static List<LookupSearchResult> getSearchResults(String searchTerm, String queueName) {
        return null;
   }

   @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> apexSearchFacility(String searchTerm,String queueName) {
        
        searchTerm = searchTerm.replace(' ','%');
        String query = 'select id,name from user where id in (select userorgroupid from groupmember where group.DeveloperName = \''+queueName+'\')';
        if(String.isNotEmpty(searchTerm)) {
            query += ' AND (Name like\'%' + searchTerm + '%\'' ;
        }
        system.debug('query===='+query);
        List<User> users = Database.query(query);
        List<LookupSearchResult> results = searchUsers(users, true);
        System.debug('results---' + results);
        return results;
    }
    
    /***********************************************
    * Method Name : searchAccount
    * Author : Shantanu
    * Inputs : List<User> users, Boolean showSubtitle
    * Description: This method return list of LookupSearchResult from Accounts with Entity Type Health Care Facility
    *********************************************/
    private static List<LookupSearchResult> searchUsers( List<User> users, Boolean showSubtitle) {

        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        // Extract Accounts & convert them into LookupSearchResult
        String userIcon = 'standard:user';
        for (User user : users) {
            results.add(
                    new LookupSearchResult(
                            user.Id,
                            'User',
                            userIcon,
                            user.Name,
                            null,
                            user
                    )
            );
        }
        // Optionnaly sort all results on title
        results.sort();
        System.debug('results---' + results);
        return results;
    }

    
    @AuraEnabled
    public static void  saveApplicationLead(String userId, String applicationId) {
        HH_Application__c application = new HH_Application__c(Id=applicationId, Application_Lead__c=userId);
        update application;
    }
}