codepkg/objects/Current_Priorities__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Priority_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Priority Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Current Priorities</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Current Priorities Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Current Priorities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/DIP_Current_Priority_DetailCtrlTest.cls
/**
 * Created by Admin on 15-04-2020.
 */


@IsTest
private class DIP_Current_Priority_DetailCtrlTest {
    @IsTest
    static void testBehavior() {
        Test.startTest();

        Current_Priorities__c testItem = new Current_Priorities__c();
        testItem.Priority_Description__c = 'this is a test priority';
        testItem.Is_Active__c = true;
        insert testItem;

        Map<String,Object> resultMap = (Map<String,Object>) DIP_Current_Priority_DetailCtrl.getPriorityItem();

        Current_Priorities__c testItemAnother = (Current_Priorities__c)resultMap.get('PriorityItem');

                System.assert(testItemAnother.Id ==testItem.Id);

        Test.stopTest();
    }
}