codepkg/objects/CWMP_Project__c.object
<CustomObject>
    <description>Project for California wildfire mitigation program</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CWMP Projects</relationshipLabel>
        <relationshipName>CWMP_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CWMP_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CWMP Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>CWMP Projects</relationshipLabel>
        <relationshipName>CWMP_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CWMP Project</label>
    <nameField>
        <displayFormat>CWMPP-{000000}</displayFormat>
        <label>CWMP Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>HH_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessor_Email__c</fullName>
        <description>Assessor&apos;s Email</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Assessor&apos;s Email</inlineHelpText>
        <label>Assessor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>County of Property</description>
        <inlineHelpText>County of Property</inlineHelpText>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Shasta</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                    <isActive>false</isActive>
                    <label>Los Angeles</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the application</description>
        <inlineHelpText>Stage of the application</inlineHelpText>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Community Review</fullName>
                </value>
                <value>
                    <fullName>Community Decision</fullName>
                </value>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Decision</fullName>
                </value>
                <value>
                    <fullName>CalOES Review</fullName>
                    <label>Cal OES Review</label>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                    <label>Cal OES Decision</label>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Approved- Converted</fullName>
                    <label>Approved - Converted</label>
                </value>
                <value>
                    <fullName>Rejected - Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HH_CWMPProjectTriggerHandlerTest.cls
@Istest
public without sharing class HH_CWMPProjectTriggerHandlerTest {
    @IsTest
    public static void testHH_CWMPProjectTriggerHandler() {
        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Contact con = new Contact(AccountId = acc.Id, FirstName = 'FirstName', LastName = 'LastName', Email = 'firstnamelastname3463563@gmail.com', Contact_Type__c = HH_CONSTANTS.HH_Contact_Type_Homeowner);
        insert con;

        HH_Application__c applicationRecord = new HH_Application__c(Applicant__c = con.Id, Stage__c = HH_CONSTANTS.HHApplication_Stage_Draft, Status__c = HH_CONSTANTS.HHApplication_Status_New, County__c = HH_CONSTANTS.HHApplication_County_SanDiego);
        insert applicationRecord;

        CWMP_Project__c projectRecord = new CWMP_Project__c(CWMP_Application__c = applicationRecord.Id);
        insert projectRecord;
        
        projectRecord.Project_Stage__c = '';
        update projectRecord;
        
        projectRecord.Project_Stage__c = HH_CONSTANTS.CWMPProject_Stage_SiteWork;
        update projectRecord;
        
		projectRecord.Project_Stage__c = HH_CONSTANTS.CWMPProject_Stage_PostAssessment;
        update projectRecord;
        
        projectRecord.Project_Stage__c = HH_CONSTANTS.CWMPProject_Stage_ProjectComplete;
        projectRecord.Assessor_Email__c = 'test@gmail.com';
        update projectRecord;
        
        projectRecord.Project_Stage__c = HH_CONSTANTS.CWMPProject_Stage_NewProjectCreated;
        update projectRecord;
    }
}