codepkg/objects/DashBoard_Config__mdt.object
<CustomObject>
    <description>Holds the Description and Id of the Dashboards to be shown on home page</description>
    <fields>
        <fullName>Dashboard_Description__c</fullName>
        <label>Dashboard Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Dashboard_Id__c</fullName>
        <label>Dashboard Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dashboard_Label__c</fullName>
        <description>Name of the Dashboard</description>
        <label>Dashboard Label</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>DashBoard Config</label>
    <pluralLabel>DashBoard Configs</pluralLabel>
</CustomObject>

codepkg/classes/DIP_DashBoard_ListCtrlTest.cls
/**
 * Created by Neha on 10-04-2020.
 */

@IsTest
private class DIP_DashBoard_ListCtrlTest {
    @IsTest
    static void testBehavior() {
        Test.startTest();

        Map<String,List<DashBoard_Config__mdt>> resultMap =(Map<String,List<DashBoard_Config__mdt>>) DIP_DashBoard_ListCtrl.getImportantBoards();
        List<DashBoard_Config__mdt> dashBoardConfigs = [SELECT Id,Label,Dashboard_Description__c,Dashboard_Id__c,Dashboard_Label__c FROM DashBoard_Config__mdt Where is_Active__c=true ORDER BY Dashboard_Label__c];

        System.assert(resultMap.get('dashBoardConfigs').size() == dashBoardConfigs.size());

        Test.stopTest();
    }
}