codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>The Document&apos;s Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Document&apos;s Name</inlineHelpText>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HH_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to HH Application Object, in order to upload the Documents for Home Hardening Application.</description>
        <inlineHelpText>Lookup to HH Application Object, in order to upload the Documents for Home Hardening Application.</inlineHelpText>
        <label>HH Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CustomDocumentCreateEditTest.cls
/**
 * Created by Sushant Patil on 16-06-2021.
 */

@IsTest
private class CustomDocumentCreateEditTest {
    @IsTest
    static void testBehavior() {
        HH_Application__c hhApplication = new HH_Application__c();
        Document__c doc =new Document__c(Document_Name__c ='Test');
        Document__c doc1 =new Document__c(Document_Name__c ='Test');
        insert hhApplication;
        insert doc1;
        String documentDetail =JSON.serialize(doc);
        String documentDetail1 =JSON.serialize(doc1);
        Test.startTest();
        try{
            CustomDocumentCreateEdit.saveDocumentInfo(documentDetail,false);
        }catch(Exception e) {
            System.assert(e.getMessage().contains('Insertion Failed'));
        }
        CustomDocumentCreateEdit.getDocumentInfo(doc1.Id,hhApplication.Id);
        try{
            CustomDocumentCreateEdit.saveDocumentInfo(documentDetail1,true);
        }catch(Exception e) {
            System.assert(e.getMessage().contains('Failed to Update'));
        }

        Test.stopTest();
    }
}