codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Format__c</fullName>
        <label>Document Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.pdf</fullName>
                    <label>PDF</label>
                </value>
                <value>
                    <fullName>.docx</fullName>
                    <label>Word</label>
                </value>
                <value>
                    <fullName>.zip</fullName>
                    <label>ZIP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>The Document&apos;s Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Document&apos;s Name</inlineHelpText>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>The Document Type</description>
        <inlineHelpText>The Document Type</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Obligating</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>De Obligation</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Request</fullName>
                </value>
                <value>
                    <fullName>Supplement</fullName>
                </value>
                <value>
                    <fullName>miscellaneous</fullName>
                    <label>Miscellaneous</label>
                </value>
                <value>
                    <fullName>FIR</fullName>
                </value>
                <value>
                    <fullName>Signed FIR</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                </value>
                <value>
                    <fullName>FGAS Report</fullName>
                </value>
                <value>
                    <fullName>Property Owner ID</fullName>
                </value>
                <value>
                    <fullName>Proof of Ownership</fullName>
                </value>
                <value>
                    <fullName>Proof of Rental</fullName>
                </value>
                <value>
                    <fullName>Home Assessment Report</fullName>
                </value>
                <value>
                    <fullName>Environmental Checklist</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Homeowner Paper Application</fullName>
                </value>
                <value>
                    <fullName>Homeowner Appeal Form</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Punch List</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Requested</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Received</fullName>
                </value>
                <value>
                    <fullName>Executed Tri-Party Agreement</fullName>
                </value>
                <value>
                    <fullName>BCA Technical Review Memo</fullName>
                    <isActive>false</isActive>
                    <label>BCA Technical Review Memo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <label>Is Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                    <default>true</default>
                    <label>Optional</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project Name</description>
        <inlineHelpText>The Project Name</inlineHelpText>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Program_Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Category__c</fullName>
        <label>Document Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Obligating</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Request</fullName>
                </value>
                <value>
                    <fullName>Supplement</fullName>
                </value>
                <value>
                    <fullName>Property Owner ID</fullName>
                </value>
                <value>
                    <fullName>Proof of Ownership</fullName>
                </value>
                <value>
                    <fullName>Proof of Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Format__c</fullName>
        <label>Document  Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.pdf</fullName>
                    <label>PDF</label>
                </value>
                <value>
                    <fullName>.docx</fullName>
                    <label>Word</label>
                </value>
                <value>
                    <fullName>.zip</fullName>
                    <isActive>false</isActive>
                    <label>.zip</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <label>Is Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <description>Object on which  Document is to be created.</description>
        <inlineHelpText>Object on which  Document is to be created.</inlineHelpText>
        <label>Parent Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>HH Application</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                    <isActive>false</isActive>
                    <label>Application</label>
                </value>
                <value>
                    <fullName>Application Extensions</fullName>
                    <isActive>false</isActive>
                    <label>Application Extensions</label>
                </value>
                <value>
                    <fullName>Project Site</fullName>
                    <isActive>false</isActive>
                    <label>Project Site</label>
                </value>
                <value>
                    <fullName>Work Schedule</fullName>
                    <isActive>false</isActive>
                    <label>Work Schedule</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Documents</relationshipLabel>
        <relationshipName>Program_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Document_Filter_Clause__c</fullName>
        <description>Filter clause to create project document. Document will get created only after matching condition.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Provide filter clause. You can generate filter clause from workbench.</inlineHelpText>
        <label>Project Document Filter Clause</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Program Document</label>
    <nameField>
        <displayFormat>PDM-{00000}</displayFormat>
        <label>Program Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Name, Derives from Disaster Grant/FO.</description>
        <inlineHelpText>The grant program from which the Project originates. This field is used for reporting.</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CreateProjectDocumentPlatformEvent.cls
/**
 * Created by Pankaj on 20-11-2020.
 *
 * @description - This class is responsible to add dependant documents to project.
 *                  Document will get copied from Program document.
 *                  todo - change this class to platform event
 */

public without sharing class CreateProjectDocumentPlatformEvent {
    List<Document__c> documentsToInsert = new List<Document__c>();
    Map<Id, Set<Id>> programWithProjectIds = new Map<Id, Set<Id>>();

    public void handle(Set<Id> recordIds) {
        if(recordIds == null || recordIds.size() == 0) return;


        List<Project__c> projects = [SELECT Program_Name__c FROM Project__c WHERE Id IN :recordIds];
        List<String> programIds = new List<String>();

        for (Project__c project : projects) {
            if(programWithProjectIds.get(project.Program_Name__c) == null) {
                programWithProjectIds.put(project.Program_Name__c, new Set<Id>());
            }
            programWithProjectIds.get(project.Program_Name__c).add(project.Id);
            programIds.add(project.Program_Name__c);
        }

        Map<Id, Program__c> programs = new Map<Id, Program__c>( [SELECT Id,
                    (SELECT Id, Project_Document_Filter_Clause__c, Document_Name__c, Is_Required__c, Document_Category__c, Parent_Object__c , Document_Format__c
                        FROM Program_Documents__r where Parent_Object__c=: ALS_CONSTANTS.PDocument_ParentObject_Project)
                    FROM Program__c WHERE Id IN :programIds] );
        for (Program__c program : programs.values()) {
            if(programWithProjectIds.get(program.Id) == null) continue;
            for (Program_Document__c programDocument : program.Program_Documents__r) {
             //   if (programDocument.Parent_Object__c == 'Project') {
                    getDocumentsForProject(programDocument, program);
            //    }
            }
        }
        insert documentsToInsert;

    }

    private void getDocumentsForProject(Program_Document__c programDocument, Program__c program) {
        Set<Id> projectIds = new Set<Id>();
        if (programDocument.Project_Document_Filter_Clause__c == null) {
            projectIds = programWithProjectIds.get(program.Id);
        } else {
            projectIds = programWithProjectIds.get(program.Id);
            List<Project__c> projects2 = Database.query('Select Id From Project__c Where Id In:projectIds AND '
                    + programDocument.Project_Document_Filter_Clause__c);
            projectIds = new Set<Id>();
            for (Project__c project : projects2) {
                projectIds.add(project.Id);
            }
        }
        if(projectIds == null || projectIds.size() == 0) return ;
        
        for(String projectId : projectIds) {
            Document__c docToInsert = new Document__c();
            docToInsert.Document_Format__c = programDocument.Document_Format__c;
            docToInsert.Document_Name__c = programDocument.Document_Name__c;
            docToInsert.Document_Type__c = programDocument.Document_Category__c;//Disaster
            docToInsert.ProjectId__c = projectId;
            docToInsert.Is_Required__c = programDocument.Is_Required__c;
            documentsToInsert.add(docToInsert);
        }
    }

}