codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Creation_Method__c</fullName>
        <description>If the document is created from a Program document then Document Creation Method is System Generated or Manually Uploaded.</description>
        <label>Document Creation Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manually Uploaded</fullName>
                    <default>true</default>
                    <label>Manually Uploaded</label>
                </value>
                <value>
                    <fullName>System Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>The Document&apos;s Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Document&apos;s Name</inlineHelpText>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HH_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to HH Application Object, in order to upload the Documents for Home Hardening Application.</description>
        <inlineHelpText>Lookup to HH Application Object, in order to upload the Documents for Home Hardening Application.</inlineHelpText>
        <label>HH Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <label>Is Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                    <default>true</default>
                    <label>Optional</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Document Stage</description>
        <inlineHelpText>The Document Stage</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For Document Creation</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>HH_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the application</description>
        <inlineHelpText>Stage of the application</inlineHelpText>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Community Review</fullName>
                </value>
                <value>
                    <fullName>Community Decision</fullName>
                </value>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Decision</fullName>
                </value>
                <value>
                    <fullName>CalOES Review</fullName>
                    <label>Cal OES Review</label>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                    <label>Cal OES Decision</label>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Approved- Converted</fullName>
                    <label>Approved - Converted</label>
                </value>
                <value>
                    <fullName>Rejected - Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Master_Label_Program_Name__c</fullName>
        <description>Internal</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This Field is Used in Custom Implementation and must not be changed without informing the Administrator.</inlineHelpText>
        <label>Program Name(Master Label)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The Stage of this program in its lifecycle</description>
        <inlineHelpText>What is the Stage is this Program?</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HHDocumentActionCtrlTest.cls
@isTest
public class HHDocumentActionCtrlTest {
 	@isTest
    public static void test1() {
        	User u = HH_TestHelper.createPortalUser();
        
        	System.runAs(new User(Id=UserInfo.getUserId())) {
            Program__c program = new Program__c();
            program.Name = 'HH Application';
            program.Master_Label_Program_Name__c = 'HH Application';
            insert program;
            
            PermissionSet permissionSet =  [SELECT Id,Name FROM PermissionSet WHERE Name = 'HH_Community_Homeowner_User' LIMIT 1];
            insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = permissionSet.Id);
            Group g1 = new Group(Name='HH_Community_San_Diego_County_Group',Type='Regular');
            insert g1;
            Group g2 = new Group(Name='HH_San_Diego_County_Community_Reviewer',Email='test@gmail.com', type='Queue');
            insert g2;
            QueuesObject q1 = new QueueSObject(QueueID = g2.id, SobjectType = 'HH_Application__c');
            insert q1;
            }
        System.debug('Homeowner: '+u);
        HH_Application__c application = new HH_Application__c();
        application.Stage__c = HH_CONSTANTS.HHApplication_Stage_Draft;
        application.Status__c = HH_CONSTANTS.HHApplication_Status_New;
        insert application;
        Document__c document = new Document__c();
        document.Document_Name__c = 'Test Doc';
        document.Status__c = 'Active';
        document.HH_Application__c = application.Id;
        document.Document_Creation_Method__c = HH_CONSTANTS.Document_CreationMethod_SystemGenerated;
        insert document;
        
        Document__c document1 = new Document__c();
        document1.Document_Name__c = 'Test Doc1';
        document1.Status__c = 'Active';
        document1.Is_Required__c = 'Required';
        document1.HH_Application__c = application.Id;
        insert document1;
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;

        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;

        //Create ContentDocumentLink for Project
        ContentDocumentLink cdl1 = New ContentDocumentLink();
        cdl1.LinkedEntityId = document.Id;
        cdl1.ContentDocumentId = conDocId;
        cdl1.shareType = 'V';
        Insert cdl1;

        document.Stage__c = 'Uploaded';
        Update document;

        HH_Application__c application1 = new HH_Application__c();
        application1.Stage__c = HH_CONSTANTS.HHApplication_Stage_Draft;
        application1.Status__c = HH_CONSTANTS.HHApplication_Status_AppealApprovalResubmit;
        insert application1;
        Document__c document2 = new Document__c();
        document2.Document_Name__c = 'Test Doc';
        document2.Status__c = 'Active';
        document2.HH_Application__c = application1.Id;
        document2.Document_Creation_Method__c = HH_CONSTANTS.Document_CreationMethod_SystemGenerated;
        insert document2;

        Document__c document11 = new Document__c();
        document11.Document_Name__c = 'Test Doc1';
        document11.Status__c = 'Active';
        document11.Is_Required__c = 'Required';
        document11.HH_Application__c = application1.Id;
        insert document11;

        ContentVersion cv1 = new ContentVersion();
        cv1.Title = 'Test Document';
        cv1.PathOnClient = 'TestDocument.pdf';
        cv1.VersionData = Blob.valueOf('Test Content');
        cv1.IsMajorVersion = true;
        Insert cv1;

        //Get Content Documents
        Id conDocId1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv1.Id].ContentDocumentId;

        //Create ContentDocumentLink for Project
        ContentDocumentLink cdl11 = New ContentDocumentLink();
        cdl11.LinkedEntityId = document2.Id;
        cdl11.ContentDocumentId = conDocId1;
        cdl11.shareType = 'V';
        Insert cdl11;

        document2.Stage__c = 'Uploaded';
        Update document2;
        
        HH_DocumentActionCtrl obj = new HH_DocumentActionCtrl();
        List<DocumentUploadCtrl.DocumentMetaInfoWrapper> docWrapperList = new List<DocumentUploadCtrl.DocumentMetaInfoWrapper>();
      	DocumentUploadCtrl.DocumentMetaInfoWrapper testObj = new DocumentUploadCtrl.DocumentMetaInfoWrapper();
        testObj.documentRecord = document2;
        testObj.ContentDocumentLink = cdl1;
        //testObj.ContentVersion = cv;
        docWrapperList.add(testObj);

        String testx;
        	Test.startTest();
        System.debug('Is Active User: '+u.IsActive);
        System.runAs(u) {
       	 	docWrapperList = obj.handleHHApplicationActions(application.Id,docWrapperList);
        }
        	docWrapperList = obj.executeAction(application.Id,docWrapperList);
        	HH_DocumentActionCtrl executeDelete = new HH_DocumentActionCtrl();
            try{
                executeDelete.executeDeleteAction(document.Id,conDocId);
        		executeDelete.executeDeleteAction(document1.Id,conDocId);
                executeDelete.executeDeleteAction(document2.Id,conDocId);
                executeDelete.executeDeleteAction(document11.Id,conDocId);
            }catch(exception e){
                System.assertEquals(System.label.HH_Document_Edit_Delete, e.getMessage());
            }
        try{
            executeDelete.executeEditAction(document.Id);
            executeDelete.executeEditAction(document.Id);
            executeDelete.executeEditAction(document2.Id);
            executeDelete.executeEditAction(document11.Id);
        }Catch(exception e){
            System.assertEquals('Application not editable', e.getMessage());
        }
        	Test.stopTest();
        }
}