codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Creation_Method__c</fullName>
        <description>If the document is created from a Program document then Document Creation Method is System Generated or Manually Uploaded.</description>
        <label>Document Creation Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manually Uploaded</fullName>
                    <default>true</default>
                    <label>Manually Uploaded</label>
                </value>
                <value>
                    <fullName>System Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Format__c</fullName>
        <label>Document Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.pdf</fullName>
                    <label>PDF</label>
                </value>
                <value>
                    <fullName>.docx</fullName>
                    <label>Word</label>
                </value>
                <value>
                    <fullName>.zip</fullName>
                    <label>ZIP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>The Document&apos;s Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Document&apos;s Name</inlineHelpText>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>The Document Type</description>
        <inlineHelpText>The Document Type</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Obligating</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>De Obligation</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Request</fullName>
                </value>
                <value>
                    <fullName>Supplement</fullName>
                </value>
                <value>
                    <fullName>miscellaneous</fullName>
                    <label>Miscellaneous</label>
                </value>
                <value>
                    <fullName>FIR</fullName>
                </value>
                <value>
                    <fullName>Signed FIR</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                </value>
                <value>
                    <fullName>FGAS Report</fullName>
                </value>
                <value>
                    <fullName>Property Owner ID</fullName>
                </value>
                <value>
                    <fullName>Proof of Ownership</fullName>
                </value>
                <value>
                    <fullName>Proof of Rental</fullName>
                </value>
                <value>
                    <fullName>Home Assessment Report</fullName>
                </value>
                <value>
                    <fullName>Environmental Checklist</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Homeowner Paper Application</fullName>
                </value>
                <value>
                    <fullName>Homeowner Appeal Form</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Punch List</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Requested</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Received</fullName>
                </value>
                <value>
                    <fullName>Executed Tri-Party Agreement</fullName>
                </value>
                <value>
                    <fullName>BCA Technical Review Memo</fullName>
                    <isActive>false</isActive>
                    <label>BCA Technical Review Memo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HH_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to HH Application Object, in order to upload the Documents for Home Hardening Application.</description>
        <inlineHelpText>Lookup to HH Application Object, in order to upload the Documents for Home Hardening Application.</inlineHelpText>
        <label>HH Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <label>Is Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                    <default>true</default>
                    <label>Optional</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For Document Creation</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>HH_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Program_Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Category__c</fullName>
        <label>Document Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Obligating</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Request</fullName>
                </value>
                <value>
                    <fullName>Supplement</fullName>
                </value>
                <value>
                    <fullName>Property Owner ID</fullName>
                </value>
                <value>
                    <fullName>Proof of Ownership</fullName>
                </value>
                <value>
                    <fullName>Proof of Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Creation_Method__c</fullName>
        <label>Document Creation Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manually Uploaded</fullName>
                </value>
                <value>
                    <fullName>System Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Format__c</fullName>
        <label>Document  Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.pdf</fullName>
                    <label>PDF</label>
                </value>
                <value>
                    <fullName>.docx</fullName>
                    <label>Word</label>
                </value>
                <value>
                    <fullName>.zip</fullName>
                    <isActive>false</isActive>
                    <label>.zip</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <label>Is Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <description>Object on which  Document is to be created.</description>
        <inlineHelpText>Object on which  Document is to be created.</inlineHelpText>
        <label>Parent Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>HH Application</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                    <isActive>false</isActive>
                    <label>Application</label>
                </value>
                <value>
                    <fullName>Application Extensions</fullName>
                    <isActive>false</isActive>
                    <label>Application Extensions</label>
                </value>
                <value>
                    <fullName>Project Site</fullName>
                    <isActive>false</isActive>
                    <label>Project Site</label>
                </value>
                <value>
                    <fullName>Work Schedule</fullName>
                    <isActive>false</isActive>
                    <label>Work Schedule</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Documents</relationshipLabel>
        <relationshipName>Program_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Document_Filter_Clause__c</fullName>
        <description>Filter clause to create project document. Document will get created only after matching condition.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Provide filter clause. You can generate filter clause from workbench.</inlineHelpText>
        <label>Project Document Filter Clause</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Program Document</label>
    <nameField>
        <displayFormat>PDM-{00000}</displayFormat>
        <label>Program Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HHCreateHHApplicationDocument.cls
/**
 * Created by StackNexus Admin on 24-08-2021.
 */

public without sharing class HHCreateHHApplicationDocument {

    List<Document__c> documentsToInsert = new List<Document__c>(); //To collect the list of Document to Insert...
    Map<Id, Set<Id>> programWithHHApplicationIds = new Map<Id, Set<Id>>(); //To store the Program with the Payment Request Ids which is inserted...
    public void handle(Set<Id> recordIds) {
        if(recordIds == null || recordIds.size() == 0) return;


        List<HH_Application__c> applications = [SELECT Program__c FROM HH_Application__c WHERE Id IN :recordIds];
        List<String> programIds = new List<String>();

        for (HH_Application__c Apps : applications) {
            if(programWithHHApplicationIds.get(Apps.Program__c) == null) {
                programWithHHApplicationIds.put(Apps.Program__c, new Set<Id>());
            }
            programWithHHApplicationIds.get(Apps.Program__c).add(Apps.Id);
            programIds.add(Apps.Program__c);
        }

        Map<Id, Program__c> programs = new Map<Id, Program__c>( [SELECT Id,
        (SELECT Id, Document_Name__c, Is_Required__c, Document_Category__c, Document_Creation_Method__c, Parent_Object__c , Document_Format__c
        FROM Program_Documents__r where Parent_Object__c=: HH_CONSTANTS.HH_Program_Document_ParentObject_Name)
        FROM Program__c WHERE Id IN :programIds] );
        for (Program__c program : programs.values()) {
            if(programWithHHApplicationIds.get(program.Id) == null) continue;
            for (Program_Document__c programDocument : program.Program_Documents__r) {
                getDocumentsForHHApplication(programDocument, program);
            }
        }
        insert documentsToInsert;
    }

    private void getDocumentsForHHApplication(Program_Document__c programDocument,Program__c program) {
        Set<Id> hhApplicationIds = new Set<Id>();
        //if (programDocument.Project_Document_Filter_Clause__c == null) {
            hhApplicationIds = programWithHHApplicationIds.get(program.Id);
        /*} else {
            hhApplicationIds = programWithHHApplicationIds.get(program.Id);
            List<HH_Application__c> App2 = Database.query('Select Id From HH_Application__c Where Id In:hhApplicationIds AND '
                    + programDocument.Project_Document_Filter_Clause__c);
            hhApplicationIds = new Set<Id>();
            for (HH_Application__c App : App2) {
                hhApplicationIds.add(App.Id);
            }
        }*/
        if(hhApplicationIds == null || hhApplicationIds.size() == 0) return ;

        for(String hhAppId : hhApplicationIds) {
            Document__c docToInsert = new Document__c();
            docToInsert.Document_Format__c = programDocument.Document_Format__c;
            docToInsert.Document_Name__c = programDocument.Document_Name__c;
            docToInsert.Document_Type__c = programDocument.Document_Category__c;
            docToInsert.HH_Application__c = hhAppId;
            docToInsert.Document_Creation_Method__c = programDocument.Document_Creation_Method__c;
            docToInsert.Is_Required__c = programDocument.Is_Required__c;
            documentsToInsert.add(docToInsert);
        }
    }
}