codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>The Document&apos;s Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Document&apos;s Name</inlineHelpText>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/DocumentTriggerHelperTest.cls
@isTest
public with sharing class DocumentTriggerHelperTest {
    @isTest public static void testBehaviour() {
        List<Document__c> lstDocs = new list<Document__c>();    
        Document__c doc1 = new Document__c();
            doc1.Document_Name__c = 'Test Document1';
            doc1.Stage__c = ALS_CONSTANTS.Document_Stage_New;
            lstDocs.add(doc1);
        insert lstDocs;
        
        Test.startTest();
                for(Document__c doc : lstDocs){
                    doc.Stage__c = ALS_CONSTANTS.Document_Stage_Uploaded;
                }
                try {
                    update lstDocs;
                }
                catch(Exception e) {
                    System.assert(e.getMessage().contains(System.Label.REAL_Document_UploadStageError));
                }
        Test.stopTest();
    }
}