codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Format__c</fullName>
        <label>Document Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.pdf</fullName>
                    <label>PDF</label>
                </value>
                <value>
                    <fullName>.docx</fullName>
                    <label>Word</label>
                </value>
                <value>
                    <fullName>.zip</fullName>
                    <label>ZIP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>The Document&apos;s Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The Document&apos;s Name</inlineHelpText>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>The Document Type</description>
        <inlineHelpText>The Document Type</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Obligating</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>De Obligation</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Request</fullName>
                </value>
                <value>
                    <fullName>Supplement</fullName>
                </value>
                <value>
                    <fullName>miscellaneous</fullName>
                    <label>Miscellaneous</label>
                </value>
                <value>
                    <fullName>FIR</fullName>
                </value>
                <value>
                    <fullName>Signed FIR</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                </value>
                <value>
                    <fullName>FGAS Report</fullName>
                </value>
                <value>
                    <fullName>Property Owner ID</fullName>
                </value>
                <value>
                    <fullName>Proof of Ownership</fullName>
                </value>
                <value>
                    <fullName>Proof of Rental</fullName>
                </value>
                <value>
                    <fullName>Home Assessment Report</fullName>
                </value>
                <value>
                    <fullName>Environmental Checklist</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Homeowner Paper Application</fullName>
                </value>
                <value>
                    <fullName>Homeowner Appeal Form</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Punch List</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Requested</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Received</fullName>
                </value>
                <value>
                    <fullName>Executed Tri-Party Agreement</fullName>
                </value>
                <value>
                    <fullName>BCA Technical Review Memo</fullName>
                    <isActive>false</isActive>
                    <label>BCA Technical Review Memo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <label>Is Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                    <default>true</default>
                    <label>Optional</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PaymentRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project for which this Payment is Requested?</description>
        <inlineHelpText>Project for which this Payment is Requested?</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Program_Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Category__c</fullName>
        <label>Document Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Obligating</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Request</fullName>
                </value>
                <value>
                    <fullName>Supplement</fullName>
                </value>
                <value>
                    <fullName>Property Owner ID</fullName>
                </value>
                <value>
                    <fullName>Proof of Ownership</fullName>
                </value>
                <value>
                    <fullName>Proof of Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Format__c</fullName>
        <label>Document  Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.pdf</fullName>
                    <label>PDF</label>
                </value>
                <value>
                    <fullName>.docx</fullName>
                    <label>Word</label>
                </value>
                <value>
                    <fullName>.zip</fullName>
                    <isActive>false</isActive>
                    <label>.zip</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <label>Is Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <description>Object on which  Document is to be created.</description>
        <inlineHelpText>Object on which  Document is to be created.</inlineHelpText>
        <label>Parent Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>HH Application</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                    <isActive>false</isActive>
                    <label>Application</label>
                </value>
                <value>
                    <fullName>Application Extensions</fullName>
                    <isActive>false</isActive>
                    <label>Application Extensions</label>
                </value>
                <value>
                    <fullName>Project Site</fullName>
                    <isActive>false</isActive>
                    <label>Project Site</label>
                </value>
                <value>
                    <fullName>Work Schedule</fullName>
                    <isActive>false</isActive>
                    <label>Work Schedule</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Documents</relationshipLabel>
        <relationshipName>Program_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Document_Filter_Clause__c</fullName>
        <description>Filter clause to create project document. Document will get created only after matching condition.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Provide filter clause. You can generate filter clause from workbench.</inlineHelpText>
        <label>Project Document Filter Clause</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Program Document</label>
    <nameField>
        <displayFormat>PDM-{00000}</displayFormat>
        <label>Program Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Name, Derives from Disaster Grant/FO.</description>
        <inlineHelpText>The grant program from which the Project originates. This field is used for reporting.</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CreatePaymentRequestDocument.cls
public without sharing class CreatePaymentRequestDocument {
    List<Document__c> documentsToInsert = new List<Document__c>(); //To collect the list of Document to Insert...
    Map<Id, Set<Id>> programWithPaymentRequestIds = new Map<Id, Set<Id>>(); //To store the Program with the Payment Request Ids which is inserted...
    List <Id> recordIds = new List<Id>();
    //recordIds.add('a0Y35000000noXuEAI');

    public void handle(Set<Id> recordIds) {
        //Fetching all the Payment Requests whose Id are present in recordId collection...
        List<Payment_Request__c> paymentRequests = [SELECT Id ,Project__r.Program_Name__c FROM Payment_Request__c WHERE Id IN :recordIds];
        List<String> programIds = new List<String>();

        //Adding the value to the "programWithPaymentRequestIds" collection.....
        for (Payment_Request__c paymentRequestToProcess : paymentRequests) {
        if(programWithPaymentRequestIds.get(paymentRequestToProcess.Project__r.Program_Name__c) == null) {
        programWithPaymentRequestIds.put(paymentRequestToProcess.Project__r.Program_Name__c, new Set<Id>());
        }
        programWithPaymentRequestIds.get(paymentRequestToProcess.Project__r.Program_Name__c).add(paymentRequestToProcess.Id);
            programIds.add(paymentRequestToProcess.Project__r.Program_Name__c);
        }

        //Selecting the Program and associated Program Documents which is to be created on Payment Request...
        Map<Id, Program__c> programs = new Map<Id, Program__c>( [SELECT Id,
        (SELECT Id, Project_Document_Filter_Clause__c, Document_Name__c,Is_Required__c,  Document_Category__c, Parent_Object__c,Document_Format__c
        FROM Program_Documents__r where Parent_Object__c=: ALS_CONSTANTS.PDocument_ParentObject_PR)
        FROM Program__c WHERE Id IN :programIds] );

        for (Program__c program : programs.values()) {
        if(programWithPaymentRequestIds.get(program.Id) == null) continue;
        for (Program_Document__c programDocument : program.Program_Documents__r) {
            getDocumentsForPaymentRequest(programDocument, program);
        }
        }

        insert documentsToInsert;

    }

    private void getDocumentsForPaymentRequest(Program_Document__c programDocument, Program__c program) {
        Set<Id> paymentRequestIds = new Set<Id>();
        if (programDocument.Project_Document_Filter_Clause__c == null) {
        paymentRequestIds = programWithPaymentRequestIds.get(program.Id);
        }else {
        paymentRequestIds = programWithPaymentRequestIds.get(program.Id);
        List<Payment_Request__c> prList = Database.query('Select Id From Payment_Request__c Where Id In:paymentRequestIds AND '
        + programDocument.Project_Document_Filter_Clause__c);
        paymentRequestIds = new Set<Id>();
        for (Payment_Request__c pr : prList) {
        paymentRequestIds.add(pr.Id);
        }
    }

        if(paymentRequestIds == null || paymentRequestIds.size() == 0) return ;
        //Creating the Document for Payment Request by fetching the data from Program Document.....
        for(String prId : paymentRequestIds) {
            Document__c docToInsert = new Document__c();
            docToInsert.Document_Format__c = programDocument.Document_Format__c;
            docToInsert.Document_Name__c = programDocument.Document_Name__c;
            docToInsert.Document_Type__c = programDocument.Document_Category__c;//Disaster
            docToInsert.PaymentRequest__c = prId;
            docToInsert.Is_Required__c = programDocument.Is_Required__c;
            documentsToInsert.add(docToInsert); //Adding document record to collection to insert...
        }
    }
}