codepkg/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Funding_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <formula>IF(  Program_Name__r.Name   = &quot;PA - Federal&quot;  || Program_Name__r.Name  = &quot;PA - FMAG&quot;, Incident_Name__r.Declaration_Number__c, 
IF(Program_Name__r.Name = &quot;CDAA (State Funding)&quot;, Incident_Name__r.State_Declaration_Number__c, &quot;&quot;)
)</formula>
        <label>Declaration Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Incident / Disaster Name</description>
        <inlineHelpText>The Incident Name related to this Funding Opportunity</inlineHelpText>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The record owner. Should be a Programs Profile or Role</description>
        <inlineHelpText>The Staff Member who owns the record</inlineHelpText>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program that issued with this Funding Opportunity</description>
        <inlineHelpText>Program Name for the funding Opportunity ( Ex: PA-Federal, HMGP etc.).</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>What is the Stage of this Funding Opportunity.</description>
        <inlineHelpText>Status of Funding Opportunity ( Ex: Draft, Pending, Approved etc.).</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Disaster Grant / Funding Opportunity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disaster Grants / Funding Opps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Federal Incident Declaration Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Incident Declaration Number. DR number if a Major Disaster, CDAA Number if CDAA-Only, etc.</inlineHelpText>
        <label>Declaration Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Federal_Small_Project_Threshold__c</fullName>
        <description>The Federal Small Project Threshold Amount</description>
        <inlineHelpText>The Federal Small Project Threshold Amount</inlineHelpText>
        <label>Federal Small Project Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Financial Closeout - FPU In Progress</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout FPU - Closed</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - In Review</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - Awaiting FEMA Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Small_Project_Threshold__c</fullName>
        <description>The State Small Project Threshold Amount</description>
        <inlineHelpText>The State Small Project Threshold Amount</inlineHelpText>
        <label>State Small Project Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Parent Program</description>
        <inlineHelpText>If the Program you are adding is not one of the Programs in this list, please select the parent Program from this list.</inlineHelpText>
        <label>Parent Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Related Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Program_Document__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Documents</relationshipLabel>
        <relationshipName>Program_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Document</label>
    <nameField>
        <displayFormat>PDM-{00000}</displayFormat>
        <label>Program Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>DUNS_Expiration_Date__c</fullName>
        <description>DUNS Expiration Date of Obligating Sub Recipient.</description>
        <formula>Obligating_Sub_Recipient__r.DUNS_Expiration_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date when the DUNS registration expires on SAM.gov</inlineHelpText>
        <label>SAM Registration Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Declaration Number of the Incident.</description>
        <formula>Incident_Name__r.Declaration_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Declaration Number assigned to a Disaster/Incident.</inlineHelpText>
        <label>Declaration Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEMA_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The FEMA Cost Share for this Project. The values are inherited from the Program Cost Share.</description>
        <inlineHelpText>Percentage of the Project Amount ($) that will be paid by FEMA.  Equal to the Federal Share ($) divided by the Project Amount ($).</inlineHelpText>
        <label>FEMA Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FundingSource__c</fullName>
        <description>Funding Source of the Project.</description>
        <inlineHelpText>Select &quot;Federal Only,&quot; &quot;State Only,&quot; or &quot;Federal and State&quot; according to Subrecipient, Incident, and Category eligibility.</inlineHelpText>
        <label>Funding Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Federal and State</fullName>
                </value>
                <value>
                    <fullName>Federal Only</fullName>
                </value>
                <value>
                    <fullName>State Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Funding Opportunity Name</description>
        <inlineHelpText>Specific Funding Opportunity for the Grant (Program+Incident+Declaration Number).</inlineHelpText>
        <label>Disaster Grant/FO</label>
        <referenceTo>Funding_Opportunity__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The name of the Incident</description>
        <inlineHelpText>Disaster/Incident for which the project is related. Not all projects will have an associated Incident.</inlineHelpText>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Name, Derives from Disaster Grant/FO.</description>
        <inlineHelpText>The grant program from which the Project originates. This field is used for reporting.</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Share Cost Component only applies to Non Disaster Grants or PA Projects</description>
        <inlineHelpText>Percentage of the Project Amount ($) that was not covered by FEMA that will be paid out by Cal OES as CDAA funds.</inlineHelpText>
        <label>State Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Project_Award__c</fullName>
        <description>The Total Amount Awarded by FEMA for the cost of the project.</description>
        <inlineHelpText>This is the total cost of the approved Project. Any cost share percentage calculations start from this value.</inlineHelpText>
        <label>Total Project Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/ALS_DocumentUpload_CtrlTest.cls
@isTest(seeAllData=false)
public class ALS_DocumentUpload_CtrlTest {

   @isTest public static void testSaveFileDetails1() {
       Date startDate = system.today()+1;
       Date EndDate = system.today()+10;
       Map<String, Object> returnMap = new Map<String, Object>();
       Map<String, Object> returnMap1 = new Map<String, Object>();
       Profile pf= [Select Id from profile where Name='System Administrator'];
       String orgId=UserInfo.getOrganizationId();
       String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
       Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000));
       String uniqueName=orgId+dateString+RandomId;
       User uu=new User(firstname = 'ABC',
               lastName = 'XYZ',
               email = uniqueName + '@test' + orgId + '.org',
               Username = uniqueName + '@test' + orgId + '.org',
               EmailEncodingKey = 'ISO-8859-1',
               Alias = uniqueName.substring(18, 23),
               TimeZoneSidKey = 'America/Los_Angeles',
               LocaleSidKey = 'en_US',
               LanguageLocaleKey = 'en_US',
               ProfileId = pf.Id
       );
       insert uu;
       Program__c prP = new Program__c(Name='Test Program Parent');
       insert prP;
       Program__c pr3 = new Program__c(Name='Test Program update', Parent_Program__c=prP.Id);
       insert pr3;
       Incident__c inc = new Incident__c(Name = 'Test Incident FP',Declaration_Number__c = '4456',State_Small_Project_Threshold__c=200,Federal_Small_Project_Threshold__c=200);
       insert inc;
       Funding_Opportunity__c fp2=new Funding_Opportunity__c(Name='Test FP ',Program_Name__c=pr3.Id,Incident_Name__c=inc.Id, Owner__c=uu.Id);
       insert fp2;

       Account account=new Account(Sub_Recipient_FIPS__c='1234',Email_Address__c='test@gmail.com',Name ='Test Account' ,Entity_Type__c=ALS_CONSTANTS.Account_EntityType_City,DUNS_Expiration_Date__c =EndDate,FFATAExpirationDate__c =EndDate,DUNS__c = '1234' );
        insert account;
       Project__c newProj =new Project__c(Total_Project_Award__c=1000,State_Share__c=10,FEMA_Share__c =80,FundingSource__c=ALS_CONSTANTS.Project_FundingSource_FederalAndState,Funding_Opportunity_Name__c=fp2.Id,Stage__c=ALS_CONSTANTS.Project_Stage_ActivePayment,Obligating_Sub_Recipient__c=account.Id,Start_Date__c=startDate,End_Date__c=EndDate);
        insert newProj;

        //for Project
        Document__c newDoc1 = new Document__c();
        newDoc1.Document_Type__c = ALS_CONSTANTS.Document_DocumentType_Compliance;
        newDoc1.Document_Name__c = 'testName';
        newDoc1.ProjectId__c =  newProj.Id;
        insert newDoc1;

        Program_Document__c newProDocument = new Program_Document__c();
        newProDocument.Document_Name__c = 'testName';//newDoc1.Document_Name__c;
        insert newProDocument;

        //Create Document
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;

        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;

        //Create ContentDocumentLink for Project
        ContentDocumentLink cdl1 = New ContentDocumentLink();
        cdl1.LinkedEntityId = newDoc1.Id;
        cdl1.ContentDocumentId = conDocId;
        cdl1.shareType = 'V';
        Insert cdl1;

        String documentRecordId = newDoc1.Id;
        String recordId = newProj.Id;

        //Create Document
        ContentVersion cv1 = new ContentVersion();
        cv1.Title = 'Test Document';
        cv1.PathOnClient = 'TestDocument.pdf';
        cv1.VersionData = Blob.valueOf('Test Content');
        cv1.IsMajorVersion = true;
        Insert cv1;

        //Get Content Documents
        Id conDocId1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv1.Id].ContentDocumentId;

        //Create ContentDocumentLink
        ContentDocumentLink cd1 = New ContentDocumentLink();
        cd1.LinkedEntityId = newDoc1.Id;
        cd1.ContentDocumentId = conDocId1;
        cd1.shareType = 'V';
        Insert cd1;

       String documentRecordId1 = newDoc1.Id;
       String recordId1 = account.Id;
        test.startTest();
            returnMap = ALS_DocumentUpload_Ctrl.saveFileDetails(documentRecordId, '', recordId);
            System.assert(returnMap.size()>0);
            returnMap1 = ALS_DocumentUpload_Ctrl.saveFileDetails(documentRecordId, '', recordId);
            System.assert(returnMap1.size()>0);
            try {
               returnMap1 = ALS_DocumentUpload_Ctrl.saveFileDetails(documentRecordId1, '', recordId1);
            }
            catch(Exception e) {
               System.assert(e.getMessage().contains('List has no rows for assignment to SObject'));
            }
        test.stopTest();
   }

}