codepkg/objects/Exception_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Exception Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Stack Trace</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Exception_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/ServiceUtility.cls
public class ServiceUtility {
    
    public static Database.SaveResult logMessage(String className, String methodName, 
                                                 String exceptionMessage, String stackTrace,
                                                 String programName) {
        
        Exception_Log__c exceptionLog = new Exception_Log__c();
        exceptionLog.Type__c = 'Apex Handled Exception';
        exceptionLog.Class_Name__c = className;
        exceptionLog.Method_Name__c = methodName;
        exceptionLog.Message__c = exceptionMessage;
        exceptionLog.Exception_Date__c = Datetime.now();
        exceptionLog.Stack_Trace__c = stackTrace;
        exceptionLog.Program__c = programName;
        exceptionLog.User__c = UserInfo.getUserId();
        
        return Database.insert(exceptionLog, false);
    }

}