codepkg/objects/F42__c.object
<CustomObject>
    <description>This object stores the actual f-42 submission data. This and related child objects will be used for generating Invoices</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>1 AGENCY NAME</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>F-42</relationshipLabel>
        <relationshipName>F_42</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>INCIDENT NAME</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>F-42s</relationshipLabel>
        <relationshipName>F_42s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>F-42s</relationshipLabel>
        <relationshipName>F_42s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CALOES REVIEW</fullName>
                </value>
                <value>
                    <fullName>AGENCY REVIEW</fullName>
                </value>
                <value>
                    <fullName>APPROVED</fullName>
                </value>
                <value>
                    <fullName>DOCUMENTATION ONLY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>F-42</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>F-42 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>F-42s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/F_42_Invoices__c.object
<CustomObject>
    <fields>
        <fullName>F_42__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>F-42</label>
        <referenceTo>F42__c</referenceTo>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>F-42-Expense Claim Invoice</label>
    <nameField>
        <displayFormat>FI-{000000}</displayFormat>
        <label>F-42 Invoicing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F-42 Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Generation In-progress</fullName>
                </value>
                <value>
                    <fullName>Invoice Generated</fullName>
                </value>
                <value>
                    <fullName>Pending For Local Agency Approval</fullName>
                </value>
                <value>
                    <fullName>Local Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Local Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending For Paying Entity Approval</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Paying Entity Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_FlowGenerateInvoiceCtrl_Test.cls
@isTest
private class MARS_FlowGenerateInvoiceCtrl_Test {
    @isTest
    static void flowTaskTest(){
        Account testAccount = MARS_TestHelper.getAccount(true);
        F42__c f42Rec = MARS_TestHelper.getF42(false);
        Incident__c incident = MARS_TestHelper.getIncident(true);
        f42Rec.Incident__c = incident.Id;
        f42Rec.Account__c = testAccount.Id;
        insert f42Rec;
        Invoice__c invoice = new Invoice__c();
        invoice.Account__c = testAccount.Id;
        invoice.Status__c = 'Pending For Local Agency Approval';
        insert invoice;
        /*F_42_Invoices__c child = new F_42_Invoices__c();
        child.F_42__c = f42Rec.Id;
        child.Invoice__c = invoice.Id;
        insert child;*/
        MARS_FlowGenerateInvoiceCtrl plugin = new MARS_FlowGenerateInvoiceCtrl();
        Map<String, Object> inputParams = new Map<String, Object>();
        string invoiceId = invoice.Id;		
        string invtype = 'Regenerate Invoice';
        inputParams.put('InvoiceId', invoiceId);
        inputParams.put('InvoiceType', invtype);
        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        plugin.invoke(request);
        Process.PluginDescribeResult result = plugin.describe();
    }
}