codepkg/objects/F42__c.object
<CustomObject>
    <description>This object stores the actual f-42 submission data. This and related child objects will be used for generating Invoices</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>1 AGENCY NAME</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>F-42</relationshipLabel>
        <relationshipName>F_42</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DI_Committed_to_Incident_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>COMMITTED TO INCIDENT DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_Redispatched_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>REDISPATCHED DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>F42_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>F42 Entry</label>
        <referenceTo>F42_Entry__c</referenceTo>
        <relationshipLabel>F-42</relationshipLabel>
        <relationshipName>F_42</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Request_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>4. INCIDENT REQUEST NUMBER</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>INCIDENT NAME</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>F-42s</relationshipLabel>
        <relationshipName>F_42s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>F-42s</relationshipLabel>
        <relationshipName>F_42s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strike_Team__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>2 STRIKE TEAM / TASK FORCE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>F-42</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>F-42 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>F-42s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/F42_Entry__c.object
<CustomObject>
    <description>This object is used to track all F42 Entries into the system. This object captures the entry data made by portal users on the UI. Once submitted this record will span into multiple f42 records and f42 line items that will then be used for invoice generation.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>F42 Entries</relationshipLabel>
        <relationshipName>F42_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>F42 Entries</relationshipLabel>
        <relationshipName>F42_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>F42 Entry</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>F42 Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>F42 Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/F_42_Invoices__c.object
<CustomObject>
    <fields>
        <fullName>F_42__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>F-42</label>
        <referenceTo>F42__c</referenceTo>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>F-42-Expense Claim Invoice</label>
    <nameField>
        <displayFormat>FI-{000000}</displayFormat>
        <label>F-42 Invoicing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F-42 Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Incident or Disaster</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Description of the Incident or Disaster</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/Mars_InvoiceAllDocumentsTest.cls
@isTest
public class Mars_InvoiceAllDocumentsTest {

    
    @isTest
    static void test() {
        Account acc = new Account();
        acc.Name = 'testAccount';
        insert acc;
        
        Incident__c inci = new Incident__c();
        inci.Name = 'testIncident';
        insert inci;
        
        F42_Entry__c f42EntryRec = new F42_Entry__c();
        f42EntryRec.Name = 'testf42EntryRec';
        f42EntryRec.Account__c = acc.Id;
        insert f42EntryRec;
        
        F42__c f42Rec = new F42__c();
        f42Rec.Account__c = acc.Id;
        f42Rec.Incident__c = inci.Id;
        f42Rec.F42_Entry__c = f42EntryRec.Id;
        f42Rec.Strike_Team__c = 'test team';
        f42Rec.Incident_Request_Number__c = '4321';
        f42Rec.DI_Committed_to_Incident_Date__c = System.today();
        f42Rec.DI_Redispatched_Date__c = System.today() + 10;
        insert f42Rec;
        Incident__c incident = new Incident__c();
        incident.Name = 'testIncident';
        incident.Description__c = 'testIncident';
        insert incident;
        Invoice__c invoice = new Invoice__c();
        invoice.Account__c = acc.Id;
        invoice.Incident__c = incident.Id;
        invoice.Name = 'testInvoice';
        insert invoice;
        
        F_42_Invoices__c child = new F_42_Invoices__c();
        child.F_42__c = f42Rec.Id;
        child.Invoice__c = invoice.Id;
        insert child;
        
        ContentVersion cv1 = new ContentVersion();
        cv1.Title = 'Test Document';
        cv1.PathOnClient = 'TestDocument.pdf';
        cv1.VersionData = Blob.valueOf('Test Content');
        cv1.IsMajorVersion = true;
        Insert cv1;
        
        //Get Content Documents
        Id conDocId1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv1.Id].ContentDocumentId;
        
        //Create ContentDocumentLink 
        ContentDocumentLink cdl1 = New ContentDocumentLink();
        cdl1.LinkedEntityId = f42EntryRec.Id;
        cdl1.ContentDocumentId = conDocId1;
        cdl1.shareType = 'V';
        Insert cdl1;
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = f42Rec.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        
        MARS_Invoice_AllDocuments.getAllRelatedFiles(invoice.Id);
    }
}