codepkg/objects/F42__c.object
<CustomObject>
    <description>This object stores the actual f-42 submission data. This and related child objects will be used for generating Invoices</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>F-42s</relationshipLabel>
        <relationshipName>F_42s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>F-42</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>F-42 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>F-42s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/F_42_Invoices__c.object
<CustomObject>
    <fields>
        <fullName>Expense_Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Claim</label>
        <referenceTo>Reimbursement__c</referenceTo>
        <relationshipLabel>F-42 Invoices</relationshipLabel>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_42__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>F-42</label>
        <referenceTo>F42__c</referenceTo>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>F-42-Expense Claim Invoice</label>
    <nameField>
        <displayFormat>FI-{000000}</displayFormat>
        <label>F-42 Invoicing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F-42 Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Reimbursement__c.object
<CustomObject>
    <fields>
        <fullName>F_42__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>F-42</label>
        <referenceTo>F42__c</referenceTo>
        <relationshipName>Reimbursements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Claim</label>
    <nameField>
        <displayFormat>EC-{00000000}</displayFormat>
        <label>Reimbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_Invoice_AllDocuments.cls
public class MARS_Invoice_AllDocuments {
    
    private static final String DOWNLOAD_URL = '/sfc/servlet.shepherd/version/download/';
    @AuraEnabled
    public static InvoiceDocumentsWrapper getAllRelatedFiles(Id recordId) {
       // Map<string, List<ContentDocumentLink>> mapDoc = new Map<string, List<ContentDocumentLink>>();
        Invoice__c objInvoice = [select id, (select id,F_42__c,F_42__r.Name,Expense_Claim__c,Expense_Claim__r.name,name from F_42_Invoices__r) from Invoice__c where id =:recordId];
        //set<id> setChildIds = new set<id>();
        map<id, string> mapRec = new map<id, string>();
        /*for(F42__c objF42: objInvoice.F_42s__r){
            mapRec.put(objF42.id, objF42.Name);
            setChildIds.add(objF42.id);
        }*/
        for(F_42_Invoices__c objExp: objInvoice.F_42_Invoices__r){
            mapRec.put(objExp.Expense_Claim__c, objExp.Expense_Claim__r.name);
            //setChildIds.add(objExp.Expense_Claim__c);
            //setChildIds
            mapRec.put(objExp.F_42__c, objExp.F_42__r.Name);
        }
        Map<Id, Id> contentIdLinkedIdMap = new Map<Id, Id>();
        for(ContentDocumentLink objCon: [Select id,LinkedEntityId, ContentDocumentId, ContentDocument.title from ContentDocumentLink where LinkedEntityId in :mapRec.keyset() order by ContentDocument.CreatedDate asc]){
           contentIdLinkedIdMap.put(objCon.ContentDocumentId, objCon.LinkedEntityId);
            /* if(mapDoc.containsKey(objCon.LinkedEntityId)){
                List<ContentDocumentLink> lstDoc = new List<ContentDocumentLink>();
                lstDoc = mapDoc.get(objCon.LinkedEntityId);
                lstDoc.add(objCon);
                mapDoc.put(mapRec.get(objCon.LinkedEntityId), lstDoc);}
        
        else{
            mapDoc.put(mapRec.get(objCon.LinkedEntityId), new List<ContentDocumentLink>{objCon});
        }*/
        }
        InvoiceDocumentsWrapper wrapper = new InvoiceDocumentsWrapper();
        Map<String, List<ContentVersion>> mapDoc = new Map<String, List<ContentVersion>>();
        Map<Id, String> contentVersionToObjectId = new Map<Id, String>();
        Map<String, String> allContentVersionURLsMap = new Map<String, String>();
        for (ContentVersion eachContentVersion : [Select Id, Title, ContentDocumentId From ContentVersion Where ContentDocumentId IN: contentIdLinkedIdMap.keySet() and IsLatest = true AND (NOT Title LIKE '%signature%')]) {
            String recName = mapRec.get(contentIdLinkedIdMap.get(eachContentVersion.ContentDocumentId));
            if (mapDoc.containsKey(recName)) {
                mapDoc.get(recName).add(eachContentVersion);
            } else {
                mapDoc.put(recName, new List<ContentVersion>{eachContentVersion});
            }
            if (allContentVersionURLsMap.containsKey(recName)) {
                 allContentVersionURLsMap.put(recName, allContentVersionURLsMap.get(recName) + '/' + eachContentVersion.Id);
            } else {
                allContentVersionURLsMap.put(recName, DOWNLOAD_URL + eachContentVersion.Id);
            }
        }
        wrapper.mapDocs = mapDoc;
        wrapper.allContentVersionURLsMap = allContentVersionURLsMap;
        system.debug('mapDoc: '+mapDoc);
        return wrapper;
    }
    
    public class InvoiceDocumentsWrapper {
        @AuraEnabled
        public  Map<String, List<ContentVersion>> mapDocs {get; set;}
        @AuraEnabled
        public  Map<String, String> allContentVersionURLsMap {get; set;}
        @AuraEnabled
        public Map<Id, String> recordToURLMapping {get; set;}
    }

}