codepkg/objects/F42__c.object
<CustomObject>
    <description>This object stores the actual f-42 submission data. This and related child objects will be used for generating Invoices</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>1 AGENCY NAME</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>F-42</relationshipLabel>
        <relationshipName>F_42</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>INCIDENT NAME</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>F-42s</relationshipLabel>
        <relationshipName>F_42s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>F-42s</relationshipLabel>
        <relationshipName>F_42s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CALOES REVIEW</fullName>
                </value>
                <value>
                    <fullName>AGENCY REVIEW</fullName>
                </value>
                <value>
                    <fullName>APPROVED</fullName>
                </value>
                <value>
                    <fullName>DOCUMENTATION ONLY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>F-42</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>F-42 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>F-42s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Generation In-progress</fullName>
                </value>
                <value>
                    <fullName>Invoice Generated</fullName>
                </value>
                <value>
                    <fullName>Pending For Local Agency Approval</fullName>
                </value>
                <value>
                    <fullName>Local Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Local Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending For Paying Entity Approval</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Paying Entity Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_InvoiceListCtrlTest.cls
@isTest
private class MARS_InvoiceListCtrlTest {
    @isTest
    static void testGetInvoiceList() {
        Account testAccount = MARS_TestHelper.getAccount(true);
        F42__c f42Rec = MARS_TestHelper.getF42(false);
        Incident__c incident = MARS_TestHelper.getIncident(true);
        f42Rec.Incident__c = incident.Id;
        f42Rec.Account__c = testAccount.Id;
        insert f42Rec;
        List<Invoice__c> invoiceList = new List<Invoice__c>();
        Invoice__c invoice1 = new Invoice__c();
        invoice1.Account__c = testAccount.Id;
        invoice1.Status__c = 'Pending For Local Agency Approval';
        invoiceList.add(invoice1); 
        Invoice__c invoice2 = new Invoice__c();
        invoice2.Account__c = testAccount.Id;
        invoice2.Status__c = 'Paid';
        invoiceList.add(invoice2); 
        insert invoiceList;
        test.startTest();
        Map<String, Object> result = MARS_InvoiceListCtrl.getInvoiceList(testAccount.Id);
        System.assert(result.size() > 0);
        test.stopTest();
    }    
    @isTest
    static void testGetInvoiceData() {
        Account testAccount = MARS_TestHelper.getAccount(true);
        F42__c f42Rec = MARS_TestHelper.getF42(false);
        Incident__c incident = MARS_TestHelper.getIncident(true);
        f42Rec.Incident__c = incident.Id;
        f42Rec.Account__c = testAccount.Id;
        insert f42Rec;
        Invoice__c invoice = new Invoice__c();
        invoice.Account__c = testAccount.Id;
        invoice.Status__c = 'Pending For Local Agency Approval';
        insert invoice;
        ContentVersion cv = MARS_TestHelper.getContentVersion();
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = invoice.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        test.startTest();
        Map<String, Object> result = MARS_InvoiceListCtrl.getInvoiceData(invoice.Id);
        System.assert(result.size() > 0);
        Map<String, Object> result1 = MARS_InvoiceListCtrl.getInvoiceDownloadURL(invoice.Id);
        System.assert(result1.size() > 0);
        String result2 = MARS_InvoiceListCtrl.getContentVersionPreview(invoice.Id);
        System.assertNotEquals(result2, null);
        test.stopTest();
    }    
    @isTest
    static void testApproveRejctInvoice() {
        Account testAccount = MARS_TestHelper.getAccount(true);
        F42__c f42Rec = MARS_TestHelper.getF42(false);
        Incident__c incident = MARS_TestHelper.getIncident(true);
        f42Rec.Incident__c = incident.Id;
        f42Rec.Account__c = testAccount.Id;
        insert f42Rec;
        Invoice__c invoice = new Invoice__c();
        invoice.Account__c = testAccount.Id;
        invoice.Status__c = 'Pending For Local Agency Approval';
        insert invoice;
        ContentVersion cv = MARS_TestHelper.getContentVersion();
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = invoice.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        //String pdfUrl = KeyValueHelper.getTextValue('MARS_Community_PDF_Generate_URL');
        //PageReference pr = new PageReference(pdfUrl+invoice.Id);
        //Blob content = pr.getContent();
        //Blob signiture = Blob.valueof('       ');
        //String signStr = JSON.serialize(signiture);
        test.startTest();
        Boolean result = MARS_InvoiceListCtrl.saveSignature(invoice.Id,'Test signature','Manager','Test');
        System.assertNotEquals(false,result);
        Boolean result1 = MARS_InvoiceListCtrl.approveInvoice(invoice.Id);
        System.assertNotEquals(result1, false);
        Boolean result2 = MARS_InvoiceListCtrl.rejectInvoice(invoice.Id,'Invoice is Rejected');
        System.assertNotEquals(false,result2);
        test.stopTest();
    }    
}