codepkg/objects/F_42_Invoices__c.object
<CustomObject>
    <fields>
        <fullName>Expense_Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Claim</label>
        <referenceTo>Reimbursement__c</referenceTo>
        <relationshipLabel>F-42 Invoices</relationshipLabel>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_42__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>F-42</label>
        <referenceTo>F42__c</referenceTo>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>F_42_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>F-42-Expense Claim Invoice</label>
    <nameField>
        <displayFormat>FI-{000000}</displayFormat>
        <label>F-42 Invoicing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F-42 Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Funding_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Funding Rules</relationshipLabel>
        <relationshipName>Funding_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Rule</label>
        <referenceTo>Funding_Rule__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_FlowGenerateInvoiceCtrl.cls
/**
 * Created by Chandrabhan on 28-06-2021.
 */

public without sharing class MARS_FlowGenerateInvoiceCtrl implements Process.Plugin {
    public Process.PluginDescribeResult describe() {
        Process.PluginDescribeResult result = new Process.PluginDescribeResult();
        result.Name = 'Generate Invoice';
        result.Tag = 'MARS_FlowGenerateInvoiceCtrl Classes';
        result.inputParameters = new List<Process.PluginDescribeResult.InputParameter> {
                new Process.PluginDescribeResult.InputParameter('InvoiceId',
                        Process.PluginDescribeResult.ParameterType.STRING, true),
                new Process.PluginDescribeResult.InputParameter('InvoiceType',
                        Process.PluginDescribeResult.ParameterType.STRING, true)

        };
        result.outputParameters = new List<Process.PluginDescribeResult.OutputParameter> {
            new Process.PluginDescribeResult.OutputParameter('NewInvoiceId', 
                Process.PluginDescribeResult.ParameterType.STRING)
        };    
        return result;
    }

    public Process.PluginResult invoke(Process.PluginRequest request) {
        Map<String,Object> result = new Map<String,Object>();
        String invoiceId = (String) request.inputParameters.get('InvoiceId');
        String invoiceType = (String) request.inputParameters.get('InvoiceType');
        List<String> invoiceIds = new List<String>();
        List<String> f42Ids = new List<String>();
        List<String> expenseClaims = new List<String>();  
        List<Invoice__c> invoiceList = [SELECT Account__c,Incident__c,Funding_Rule__c FROM Invoice__c WHERE Id =: invoiceId];
        List<F_42_Invoices__c> f42List =  [SELECT Id, F_42__c, Expense_Claim__c FROM F_42_Invoices__c WHERE Invoice__c =: invoiceId];
        if(invoiceList.size() > 0  && f42List.size() > 0) {
            for(F_42_Invoices__c f42Record : f42List) {
                if(f42Record.F_42__c != null) {
                    f42Ids.add(f42Record.F_42__c);
                } else if(f42Record.Expense_Claim__c != null) {
                    expenseClaims.add(f42Record.Expense_Claim__c);
                }
         }
        invoiceIds = MARSInvoiceHelper.createInvoiceStaging(invoiceList[0].Incident__c, invoiceList[0].Account__c, f42Ids, invoiceList[0].Funding_Rule__c, invoiceId, invoiceType, expenseClaims);
        result.put('NewInvoiceId',invoiceIds.get(0));
    }
        return new Process.PluginResult(result);
    }
}