codepkg/objects/FEMA_Code__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FEMA Code</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FEMA Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/FEMA_Code_LineItem__c.object
<CustomObject>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <label>Current Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FEMA_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FEMA Code</label>
        <referenceTo>FEMA_Code__c</referenceTo>
        <relationshipLabel>FEMA Schedule of Equipment</relationshipLabel>
        <relationshipName>FEMA_Schedule_of_Equipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FEMA Schedule of Equipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEMA Schedule of Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_FEMALineItemTriggerHelper_Test.cls
@isTest
private class MARS_FEMALineItemTriggerHelper_Test {
    @isTest
    static void testUpate(){
		FEMA_Code__c  femaRecord = new FEMA_Code__c();
        femaRecord.Effective_Date__c  = DateTime.Now().AddDays(-3).date();
        femaRecord.Status__c = 'Active';
        insert femaRecord;
        FEMA_Code_LineItem__c femalineItem = new FEMA_Code_LineItem__c();
        femalineItem.Current_Rate__c = 24.75;
        femalineItem.Name = '8089';
        femalineItem.FEMA_Code__c = femaRecord.Id;
        insert femalineItem;
        femalineItem.Current_Rate__c =30.75;
        update femalineItem;
    } 
}