codepkg/objects/Funding_Source__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Please link each funding source to the corresponding account. This will ensure Paying entities to have their own community and approve invoices</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Generation In-progress</fullName>
                </value>
                <value>
                    <fullName>Invoice Generated</fullName>
                </value>
                <value>
                    <fullName>Pending For Local Agency Approval</fullName>
                </value>
                <value>
                    <fullName>Local Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Local Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending For Paying Entity Approval</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Paying Entity Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Date_Of_Payment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Of Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Source</label>
        <referenceTo>Funding_Source__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Percent__c</fullName>
        <label>Invoice %</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid_Amount__c</fullName>
        <label>Paid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_PayingEntity_InvoiceResearch_Ctrl.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-14-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-14-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public without sharing class MARS_PayingEntity_InvoiceResearch_Ctrl {
   
    @AuraEnabled
    public static list<Invoice_Payment__c> getInvoicePayments(string agencyId, string incidentId, Date startDate, Date endDate){
        try {
            string accountId =  [Select Id, Contact.AccountId From User Where Id =: UserInfo.getUserId()].Contact.AccountId;
            string query = 'SELECT Id, Status__c, Invoice__c, Invoice_Percent__c, Invoice_Amount__c, ';
            query += ' Paid_Amount__c, Invoice__r.Invoice_Number__c, Invoice__r.Name, ';
            query += ' Invoice__r.Incident__r.Name, Invoice__r.Account__r.Name, Date_Of_Payment__c, CreatedDate ';
            query += ' FROM Invoice_Payment__c ';
            query += ' WHERE Status__c IN (\'Paid\', \'Partially Paid\') ';
            query += ' AND Funding_Source__r.Account__c = :accountId '; 

            if(string.isNotBlank(incidentId)){
                query+= ' AND Invoice__r.Incident__c =: incidentId ';
            }
            if(string.isNotBlank(agencyId)){
                query+= ' AND Invoice__r.Account__c =:agencyId ';
            }
            if(startDate != null && endDate != null){
                query += ' AND Date_Of_Payment__c >=:startDate AND Date_Of_Payment__c <=: endDate ';
            }

            query+= ' order by Date_Of_Payment__c desc LIMIT 500';
            system.debug('Query******** '+query);
            return Database.query(query);

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }



}