codepkg/objects/Funding_Source__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Please link each funding source to the corresponding account. This will ensure Paying entities to have their own community and approve invoices</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Incident or Disaster</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Description of the Incident or Disaster</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Invocies</relationshipLabel>
        <relationshipName>Invocies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Generation In-progress</fullName>
                </value>
                <value>
                    <fullName>Invoice Generated</fullName>
                </value>
                <value>
                    <fullName>Pending For Local Agency Approval</fullName>
                </value>
                <value>
                    <fullName>Local Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Local Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending For Paying Entity Approval</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Paying Entity Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Source</label>
        <referenceTo>Funding_Source__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Percent__c</fullName>
        <label>Invoice %</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MARS_PayingEntityInvoiceListCtrl_Test.cls
@isTest
private class MARS_PayingEntityInvoiceListCtrl_Test {
    
    @testSetup
    static void createInvoice(){
        Account acc = new Account();
        acc.Name = 'test';
        acc.MACS_ID__c = '1234321';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'test contact';
        insert con;
        
        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='CalOES Portal User'].id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@aqqqqp11rio.com';   
        user.CommunityNickname = 'testssjjsUser123';
        user.Alias = 't1';
        user.Email = 'no1122qq@eaaaamail.com';
        user.IsActive = true;
        user.ContactId = con.Id;
        insert user;
        
        Incident__c incident = new Incident__c();
        incident.Name = 'testIncident';
        incident.Description__c = 'testIncident';
        insert incident;
        
        Invoice__c invoice = new Invoice__c();
        invoice.Account__c = acc.Id;
        invoice.Incident__c = incident.Id;
        invoice.Name = 'testInvoice';
        insert invoice;
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = invoice.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        
        Funding_Source__c fundingSource = new Funding_Source__c();
        fundingSource.Account__c = acc.Id;
        fundingSource.Name = 'testFundingSource';
        insert fundingSource;
        
        Invoice_Payment__c invoicePayment = new Invoice_Payment__c();
        invoicePayment.Invoice__c = invoice.Id;
        invoicePayment.Funding_Source__c = fundingSource.Id;
        invoicePayment.Invoice_Percent__c = 50.0;
        invoicePayment.Invoice_Amount__c = 23900.04;
        invoicePayment.Status__c = 'Pending';
        insert invoicePayment;
    }
    
    @IsTest
    static void test(){
        Account acc = [SELECT Id FROM Account WHERE Name = 'test' LIMIT 1];
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'test contact' LIMIT 1];
        User u = [SELECT Id FROM User WHERE FirstName = 'first' LIMIT 1];
        Invoice__c inv = [SELECT Id FROM Invoice__c WHERE Account__c = :acc.Id LIMIT 1];
        inv.Status__c = 'Pending For Paying Entity Approval';
        update inv;
        Invoice_Payment__c invPayment = [SELECT Id, Name FROM Invoice_Payment__c WHERE Invoice__c = :inv.Id LIMIT 1];
        invPayment.Status__c = 'Pending';
        update invPayment;
        
        System.runAs(u){
            MARS_PayingEntityInvoiceListCtrl.getInvoiceList();
            MARS_PayingEntityInvoiceListCtrl.getInvoiceData(inv.Id);
            MARS_PayingEntityInvoiceListCtrl.getInvoiceListByFilter('', 'testIncident', '1234321');   
            MARS_PayingEntityInvoiceListCtrl.approvePaymentInvoice(invPayment.Id, '10000', System.today(), 'test');
            MARS_PayingEntityInvoiceListCtrl.rejectPaymentInvoice(invPayment.Id, 'test');
            MARS_PayingEntityInvoiceListCtrl.rejectInvoice(inv.Id, 'test');
            
        }
        MARS_PayingEntityInvoiceListCtrl.approveInvoice(inv.Id, 'test', 'testing');
        MARS_PayingEntityInvoiceListCtrl.saveSignature(inv.Id, 'test');
    } 
}