codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>HH_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CWMP_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessed_Value_of_the_Property__c</fullName>
        <description>What is the current assessed value of the property?</description>
        <inlineHelpText>What is the current assessed value of the property?</inlineHelpText>
        <label>Assessed Value of the Property?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Assessor_Email__c</fullName>
        <description>Assessor&apos;s Email</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Assessor&apos;s Email</inlineHelpText>
        <label>Assessor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Income_Bracket__c</fullName>
        <description>What area median income bracket does the Homeowner&apos;s household fall into?</description>
        <inlineHelpText>What area median income bracket does the Homeowner&apos;s household fall into?</inlineHelpText>
        <label>Homeowner&apos;s Income Bracket</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Less than 80%</fullName>
                </value>
                <value>
                    <fullName>80% through 120%</fullName>
                </value>
                <value>
                    <fullName>Above 120% to 200%</fullName>
                </value>
                <value>
                    <fullName>Greater than 200%</fullName>
                </value>
                <value>
                    <fullName>120-200% AMI</fullName>
                    <isActive>false</isActive>
                    <label>120-200% AMI</label>
                </value>
                <value>
                    <fullName>&lt; 120% AMI</fullName>
                    <isActive>false</isActive>
                    <label>&lt; 120% AMI</label>
                </value>
                <value>
                    <fullName>&lt; 80%</fullName>
                    <isActive>false</isActive>
                    <label>&lt; 80%</label>
                </value>
                <value>
                    <fullName>&gt; 200% AMI</fullName>
                    <isActive>false</isActive>
                    <label>&gt; 200% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_the_property_in_the_floodplain__c</fullName>
        <description>Is property in the 100-yr floodplain?</description>
        <inlineHelpText>Is property in the 100-yr floodplain?</inlineHelpText>
        <label>Is property in the 100-yr floodplain?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the application</description>
        <inlineHelpText>Stage of the application</inlineHelpText>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Community Review</fullName>
                </value>
                <value>
                    <fullName>Community Decision</fullName>
                </value>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Decision</fullName>
                </value>
                <value>
                    <fullName>CalOES Review</fullName>
                    <label>Cal OES Review</label>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                    <label>Cal OES Decision</label>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Approved- Converted</fullName>
                    <label>Approved - Converted</label>
                </value>
                <value>
                    <fullName>Rejected - Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Parcel_Number__c</fullName>
        <description>Tax Parcel Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Tax Parcel Number</inlineHelpText>
        <label>Tax Parcel #</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Request_For_Information__c.object
<CustomObject>
    <fields>
        <fullName>CWMP_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CWMP Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>Request For Information</relationshipLabel>
        <relationshipName>Request_For_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RFI_Deadline__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>RFI Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RFI_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Sent to Subapplicant</fullName>
                </value>
                <value>
                    <fullName>Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted</fullName>
                </value>
                <value>
                    <fullName>Response Accepted</fullName>
                </value>
                <value>
                    <fullName>Response Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted to Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA EHP RFI</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA Programmatic RFI</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted by Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>RFI Requested</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Withdrawal</fullName>
                </value>
                <value>
                    <fullName>Submitted to HMA Analyst</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to HMA Analyst</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request For Information</label>
    <nameField>
        <displayFormat>RFI-{00000}</displayFormat>
        <label>Request For Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Information</pluralLabel>
    <recordTypes>
        <fullName>CWMP</fullName>
        <active>true</active>
        <description>Record Type for CWMP RFI</description>
        <label>CWMP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HH_CustomRelatedListRFICtrlTest.cls
@IsTest(SeeAllData=true)
private  class HH_CustomRelatedListRFICtrlTest {
    @IsTest
    public static void test1() {
        Id homownerId = null;
        Id communityUserId = null;
        System.runAs(new User(Id=UserInfo.getUserId())) {
            User homeowner = HH_TestHelper.createCaloesPortalUser('homeowner@xyz.com');
            homownerId = homeowner.Id;
            User communityUser = HH_TestHelper.createCaloesPortalUser('community@xyz.com');
            communityUserId = communityUser.Id;
        }
        User caloesInternalUser = HH_TestHelper.createCaloesUser();
        PermissionSet permissionSet =  [SELECT Id,Name FROM PermissionSet WHERE Name =: HH_CONSTANTS.HH_PermissionSet_HomeOwner_APIName LIMIT 1];
        insert new PermissionSetAssignment(AssigneeId = homownerId, PermissionSetId = permissionSet.Id);
        PermissionSet permissionSet2 =  [SELECT Id,Name FROM PermissionSet WHERE Name =: HH_CONSTANTS.HH_PermissionSet_CommunityUser_APIName LIMIT 1];
        insert new PermissionSetAssignment(AssigneeId = communityUserId, PermissionSetId = permissionSet2.Id);
        Id applicationId = null;
        Test.startTest(); 
        System.runAs(new User(Id=communityUserId)) {
            User u = [SELECT Id,ContactId FROM User WHERE Id=:communityUserId];
            Contact c = [SELECT Id,Email FROM Contact WHERE Id=:u.ContactId];
            c.Preferred_Language__c = 'English';
            update c;
            HH_Application__c application = new HH_Application__c();
            application.Stage__c = HH_CONSTANTS.HHApplication_Stage_Draft;
            application.Assessor_Email__c = 'ashjkhasf@gmail.com';
            application.Tax_Parcel_Number__c = '234234';
            application.Is_the_property_in_the_floodplain__c = 'No';
            application.Applicant__c = c.Id;
            insert application;
            applicationId = application.Id;
            application.Stage__c = HH_CONSTANTS.HHApplication_Stage_CommunityReview;
            application.Status__c = HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo;
            application.Assessed_Value_of_the_Property__c = 1234;
            application.Income_Bracket__c = '< 120% AMI';
            application.Tax_Parcel_Number__c = '123434';
            application.Is_the_property_in_the_floodplain__c = HH_CONSTANTS.PickList_Yes;
            application.Application_Lead__c = u.Id;
            update application;
            Request_For_Information__c req = new Request_For_Information__c();
            HH_Application__c app = [SELECT Id,Applicant__r.Preferred_Language__c FROM HH_Application__c WHERE Id=:application.Id];
            System.debug('app: '+ app);
            req.RecordTypeId = ApexUtils.getRecordTypeIdbyName('Request_For_Information__c','CWMP');
            req.Status__c = 'RFI Requested';
            req.Description__c = 'Description';
            req.RFI_Deadline__c = system.today();
            req.CWMP_Application__c = application.Id;
            insert req;
            System.debug('RFI Created..');
            HH_CustomRelatedListRFICtrl.getRFIRecords(application.Id);
        }

        System.runAs(new User(Id=homownerId)) {
            HH_CustomRelatedListRFICtrl.getRFIRecords(applicationId);
        }
        System.runAs(caloesInternalUser) {
            HH_CustomRelatedListRFICtrl.getRFIRecords(applicationId);
        }
        System.runAs(new User(Id=UserInfo.getUserId())) {
            HH_CustomRelatedListRFICtrl.getRFIRecords(applicationId);
        }
        Test.stopTest();
    }

    
}