codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Application_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CWMP_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessed_Value_of_the_Property__c</fullName>
        <description>What is the current assessed value of the property?</description>
        <inlineHelpText>What is the current assessed value of the property?</inlineHelpText>
        <label>Assessed Value of the Property?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Assessor_Email__c</fullName>
        <description>Assessor&apos;s Email</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Assessor&apos;s Email</inlineHelpText>
        <label>Assessor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Income_Bracket__c</fullName>
        <description>What area median income bracket does the Homeowner&apos;s household fall into?</description>
        <inlineHelpText>What area median income bracket does the Homeowner&apos;s household fall into?</inlineHelpText>
        <label>Homeowner&apos;s Income Bracket</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Less than 80%</fullName>
                </value>
                <value>
                    <fullName>80% through 120%</fullName>
                </value>
                <value>
                    <fullName>Above 120% to 200%</fullName>
                </value>
                <value>
                    <fullName>Greater than 200%</fullName>
                </value>
                <value>
                    <fullName>120-200% AMI</fullName>
                    <isActive>false</isActive>
                    <label>120-200% AMI</label>
                </value>
                <value>
                    <fullName>&lt; 120% AMI</fullName>
                    <isActive>false</isActive>
                    <label>&lt; 120% AMI</label>
                </value>
                <value>
                    <fullName>&lt; 80%</fullName>
                    <isActive>false</isActive>
                    <label>&lt; 80%</label>
                </value>
                <value>
                    <fullName>&gt; 200% AMI</fullName>
                    <isActive>false</isActive>
                    <label>&gt; 200% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_the_property_in_the_floodplain__c</fullName>
        <description>Is property in the 100-yr floodplain?</description>
        <inlineHelpText>Is property in the 100-yr floodplain?</inlineHelpText>
        <label>Is property in the 100-yr floodplain?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the application</description>
        <inlineHelpText>Stage of the application</inlineHelpText>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Community Review</fullName>
                </value>
                <value>
                    <fullName>Community Decision</fullName>
                </value>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Decision</fullName>
                </value>
                <value>
                    <fullName>CalOES Review</fullName>
                    <label>Cal OES Review</label>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                    <label>Cal OES Decision</label>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Approved- Converted</fullName>
                    <label>Approved - Converted</label>
                </value>
                <value>
                    <fullName>Rejected - Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Parcel_Number__c</fullName>
        <description>Tax Parcel Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Tax Parcel Number</inlineHelpText>
        <label>Tax Parcel #</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HH_EditRequestCtrlTest.cls
@isTest
public class HH_EditRequestCtrlTest {
    @TestSetup
    public static void createAppLead () {
        System.runAs(new User(Id=UserInfo.getUserId())) {
            User communityUserObj = HH_TestHelper.createCaloesPortalUser('community+1@xyz.com');
            PermissionSet permissionSet2 =  [SELECT Id,Name FROM PermissionSet WHERE Name =: HH_CONSTANTS.HH_PermissionSet_CommunityUser_APIName LIMIT 1];
            insert new PermissionSetAssignment(AssigneeId = communityUserObj.Id, PermissionSetId = permissionSet2.Id);
        }
    }
 	@isTest
    public static void testGetInitData() {
        Map<String,Object> result = new Map<String,Object>();
        User u = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1];
        System.runAs(u) {
            HH_Application__c application = new HH_Application__c();
 			application.Stage__c = HH_CONSTANTS.HHApplication_Stage_Assessment;
        	application.Status__c = HH_CONSTANTS.HHApplication_Status_AssessmentComplete;
        	application.Assessor_Email__c = 'ashjkhasf@gmail.com';
        	application.Tax_Parcel_Number__c = '234234';
        	application.Is_the_property_in_the_floodplain__c = 'No';
            application.Income_Bracket__c = 'Less than 80%';
            application.Assessed_Value_of_the_Property__c = 1000.00;
            application.Application_Lead__c = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1].Id;
            insert application;
            Test.startTest();
             result = HH_EditRequestCtrl.getInitData(application.Id);
             System.assert(result != null);
             Test.stopTest();
    	}
    }
    @isTest
    public static void testGetInitData1() {
        Map<String,Object> result = new Map<String,Object>();
        User u = HH_TestHelper.createPortalUser();
        System.runAs(new User(Id=UserInfo.getUserId())) {
            PermissionSet permissionSet =  [SELECT Id,Name FROM PermissionSet WHERE Name =: HH_CONSTANTS.HH_PermissionSet_HomeOwner_APIName LIMIT 1];
            insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = permissionSet.Id);
        }
        System.runAs(u) {
            HH_Application__c application = new HH_Application__c();
 			application.Stage__c = HH_CONSTANTS.HHApplication_Stage_Draft;
        	application.Status__c = HH_CONSTANTS.HHApplication_Status_AppealApprovalResubmit;
        	application.Assessor_Email__c = 'ashjkhasf@gmail.com';
        	application.Tax_Parcel_Number__c = '234234';
        	application.Is_the_property_in_the_floodplain__c = 'No';
            application.Income_Bracket__c = 'Less than 80%';
            application.Assessed_Value_of_the_Property__c = 1000.00;
            //application.Application_Lead__c = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1].Id;
            insert application;
            Test.startTest();
             result = HH_EditRequestCtrl.getInitData(application.Id);
             System.assert(result != null);
             Test.stopTest();
    	}
    }
    @isTest
    public static void testGetInitData2() {
        Map<String,Object> result = new Map<String,Object>();
        User u = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1];

        System.runAs(u) {
            HH_Application__c application = new HH_Application__c();
 			application.Stage__c = HH_CONSTANTS.HHApplication_Stage_CommunityReview;
        	application.Status__c = HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo;
        	application.Assessor_Email__c = 'ashjkhasf@gmail.com';
        	application.Tax_Parcel_Number__c = '234234';
        	application.Is_the_property_in_the_floodplain__c = 'No';
            application.Income_Bracket__c = 'Less than 80%';
            application.Assessed_Value_of_the_Property__c = 1000.00;
            application.Application_Lead__c = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1].Id;
            insert application;
            Test.startTest();
             result = HH_EditRequestCtrl.getInitData(application.Id);
             System.assert(result != null);
             Test.stopTest();
    	}
    }
    @isTest
    public static void testGetInitData3() {
        	Map<String,Object> result = new Map<String,Object>();
        	User u = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1];
           System.runAs(u) {
                HH_Application__c application = new HH_Application__c();
                application.Stage__c = HH_CONSTANTS.HHApplication_Stage_Assessment;
                application.Status__c = HH_CONSTANTS.HHApplication_Status_AssessmentPending;
                application.Assessor_Email__c = 'ashjkhasf@gmail.com';
                application.Tax_Parcel_Number__c = '234234';
                application.Is_the_property_in_the_floodplain__c = 'No';
               application.Income_Bracket__c = 'Less than 80%';
               application.Assessed_Value_of_the_Property__c = 1000.00;
               application.Application_Lead__c = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1].Id;
                insert application;
                Test.startTest();
                 HH_EditRequestCtrl.isApplicationEditable(application.Id);
                 //System.assert(result != null);
                 Test.stopTest();
           }
    }
    @isTest
    public static void testGetInitData4() {
        	Map<String,Object> result = new Map<String,Object>();
         	Profile p = [select Id,name from Profile where Name = 'CalOES Internal User' limit 1];
        	User u = new User(profileId = p.id,username = 'internalUser@123@gmail.com',email = 'internal@ff.com',emailencodingkey = 'UTF-8',localesidkey = 'en_US',languagelocalekey = 'en_US',timezonesidkey = 'America/Los_Angeles',alias='JamesweS',lastname='weSmith');
        	insert u;   
        	System.runAs(new User(Id=UserInfo.getUserId())) {
            PermissionSet permissionSet =  [SELECT Id,Name FROM PermissionSet WHERE Name =: HH_CONSTANTS.HH_PermissionSet_CalOESUser_APIName LIMIT 1];
            insert new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = permissionSet.Id);
        	}
           System.runAs(u) {
                HH_Application__c application = new HH_Application__c();
                application.Stage__c = HH_CONSTANTS.HHApplication_Stage_Assessment;
                application.Status__c = HH_CONSTANTS.HHApplication_Status_AssessmentPending;
                application.Assessor_Email__c = 'ashjkhasf@gmail.com';
                application.Tax_Parcel_Number__c = '234234';
                application.Is_the_property_in_the_floodplain__c = 'No';
                application.Income_Bracket__c = 'Less than 80%';
                application.Assessed_Value_of_the_Property__c = 1000.00;
               application.Application_Lead__c = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1].Id;
                insert application;
                Test.startTest();
                 HH_EditRequestCtrl.isApplicationEditable(application.Id);
                 //System.assert(result != null);
                 Test.stopTest();
           }
    }
     @isTest
    public static void testGetInitData5() {
        	Map<String,Object> result = new Map<String,Object>();
         	Profile p = [select Id,name from Profile where Name = 'CalOES Internal User' limit 1];
        	User u = new User(profileId = p.id,username = 'internalUser@123@gmail.com',email = 'internal@ff.com',emailencodingkey = 'UTF-8',localesidkey = 'en_US',languagelocalekey = 'en_US',timezonesidkey = 'America/Los_Angeles',alias='JamesweS',lastname='weSmith');
        	insert u;   
        	System.runAs(new User(Id=UserInfo.getUserId())) {
            PermissionSet permissionSet =  [SELECT Id,Name FROM PermissionSet WHERE Name =: HH_CONSTANTS.HH_PermissionSet_CalOESUser_APIName LIMIT 1];
            insert new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = permissionSet.Id);
        	}
           System.runAs(u) {
                HH_Application__c application = new HH_Application__c();
                application.Stage__c = HH_CONSTANTS.HHApplication_Stage_Assessment;
                application.Status__c = HH_CONSTANTS.HHApplication_Status_AssessmentComplete;
                application.Assessor_Email__c = 'ashjkhasf@gmail.com';
                application.Tax_Parcel_Number__c = '234234';
                application.Is_the_property_in_the_floodplain__c = 'No';
                application.Income_Bracket__c = 'Less than 80%';
                application.Assessed_Value_of_the_Property__c = 1000.00;
               application.Application_Lead__c = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1].Id;
                insert application;
                Test.startTest();
                 HH_EditRequestCtrl.isApplicationEditable(application.Id);
                 //System.assert(result != null);
                 Test.stopTest();
           }
    }

    @isTest
    public static void testGetInitData6() {
        	Map<String,Object> result = new Map<String,Object>();
         	Profile p = [select Id,name from Profile where Name = 'CalOES Internal User' limit 1];
        	User u = new User(profileId = p.id,username = 'internalUser@123@gmail.com',email = 'internal@ff.com',emailencodingkey = 'UTF-8',localesidkey = 'en_US',languagelocalekey = 'en_US',timezonesidkey = 'America/Los_Angeles',alias='JamesweS',lastname='weSmith');
        	insert u;   
        	System.runAs(new User(Id=UserInfo.getUserId())) {
            PermissionSet permissionSet =  [SELECT Id,Name FROM PermissionSet WHERE Name =: HH_CONSTANTS.HH_PermissionSet_CalOESUser_APIName LIMIT 1];
            insert new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = permissionSet.Id);
        	}
           System.runAs(u) {
                HH_Application__c application = new HH_Application__c();
                application.Stage__c = HH_CONSTANTS.HHApplication_Stage_OESReview;
                application.Status__c = HH_CONSTANTS.HHApplication_Status_OESOpenRFI;
                application.Assessor_Email__c = 'ashjkhasf@gmail.com';
                application.Tax_Parcel_Number__c = '234234';
                application.Is_the_property_in_the_floodplain__c = 'No';
                application.Income_Bracket__c = 'Less than 80%';
                application.Assessed_Value_of_the_Property__c = 1000.00;
               application.Application_Lead__c = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1].Id;
                insert application;
                Test.startTest();
                 HH_EditRequestCtrl.isApplicationEditable(application.Id);
                 //System.assert(result != null);
                 Test.stopTest();
           }
    }
    
     @isTest
    public static void testGetInitData7() {
        	Map<String,Object> result = new Map<String,Object>();
         	Profile p = [select Id,name from Profile where Name = 'CalOES Internal User' limit 1];
        	User u = new User(profileId = p.id,username = 'internalUser@123@gmail.com',email = 'internal@ff.com',emailencodingkey = 'UTF-8',localesidkey = 'en_US',languagelocalekey = 'en_US',timezonesidkey = 'America/Los_Angeles',alias='JamesweS',lastname='weSmith');
        	insert u;   
        	System.runAs(new User(Id=UserInfo.getUserId())) {
            PermissionSet permissionSet =  [SELECT Id,Name FROM PermissionSet WHERE Name =: HH_CONSTANTS.HH_PermissionSet_CalOESUser_APIName LIMIT 1];
            insert new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = permissionSet.Id);
        	}
           System.runAs(u) {
                HH_Application__c application = new HH_Application__c();
                application.Stage__c = HH_CONSTANTS.HHApplication_Stage_CommunityReview;
                application.Status__c = HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo;
                application.Assessor_Email__c = 'ashjkhasf@gmail.com';
                application.Tax_Parcel_Number__c = '234234';
                application.Is_the_property_in_the_floodplain__c = 'No';
                application.Income_Bracket__c = 'Less than 80%';
                application.Assessed_Value_of_the_Property__c = 1000.00;
               application.Application_Lead__c = [SELECT Id from User WHERE Username = 'community+1@xyz.com' AND email = 'community+1@xyz.com' limit 1].Id;
                insert application;
                Test.startTest();
                 HH_EditRequestCtrl.isApplicationEditable(application.Id);
                 //System.assert(result != null);
                 Test.stopTest();
           }
    }


}