codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the application</description>
        <inlineHelpText>Stage of the application</inlineHelpText>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Community Review</fullName>
                </value>
                <value>
                    <fullName>Community Decision</fullName>
                </value>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Decision</fullName>
                </value>
                <value>
                    <fullName>CalOES Review</fullName>
                    <label>Cal OES Review</label>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                    <label>Cal OES Decision</label>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Approved- Converted</fullName>
                    <label>Approved - Converted</label>
                </value>
                <value>
                    <fullName>Rejected - Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Request_For_Information__c.object
<CustomObject>
    <fields>
        <fullName>CWMP_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CWMP Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>Request For Information</relationshipLabel>
        <relationshipName>Request_For_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cal_OES_Comment__c</fullName>
        <description>Comment for RFI by Cal OES User.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cal OES Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Community_Comment__c</fullName>
        <description>Comment for RFI by Community.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FEMA_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>FEMA Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Homeowner_Comment__c</fullName>
        <description>Comment for RFI by Homeowner User.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Homeowner Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RFI_Deadline__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>RFI Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFI_Type__c</fullName>
        <label>RFI Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OES BCA</fullName>
                </value>
                <value>
                    <fullName>OES Programmatic</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP</fullName>
                </value>
                <value>
                    <fullName>FEMA OES Programmatic</fullName>
                </value>
                <value>
                    <fullName>FEMA OES EHP</fullName>
                </value>
                <value>
                    <fullName>CWMP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RFI_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Sent to Subapplicant</fullName>
                </value>
                <value>
                    <fullName>Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted</fullName>
                </value>
                <value>
                    <fullName>Response Accepted</fullName>
                </value>
                <value>
                    <fullName>Response Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted to Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA EHP RFI</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA Programmatic RFI</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted by Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>RFI Requested</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Withdrawal</fullName>
                </value>
                <value>
                    <fullName>Submitted to HMA Analyst</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to HMA Analyst</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request For Information</label>
    <nameField>
        <displayFormat>RFI-{00000}</displayFormat>
        <label>Request For Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Information</pluralLabel>
    <recordTypes>
        <fullName>CWMP</fullName>
        <active>true</active>
        <description>Record Type for CWMP RFI</description>
        <label>CWMP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HH_RFICustomRecordFormCtrl.cls
public with sharing class HH_RFICustomRecordFormCtrl {


     /***********************************************
   * Method Name : getInitDetails
   * Author : Shantanu
   * Inputs : String parentRecordId(CWMP Application),String recordId, String userId, String mode(View/Edit)
   * Description: This get Required Details to showcase RFI Record.
   *********************************************/
    @AuraEnabled 
    public static Map<String,Object> getInitDetails(String parentRecordId,String recordId, String userId, String mode) {
        Map<String,Object> result = new Map<String,Object>();
        System.debug('ParentRecordId: '+parentRecordId);
        System.debug('recordId: '+recordId);
        System.debug('UserId: '+userId);
        String cwmpRecordTypeId = Schema.SObjectType.Request_For_Information__c
                                .getRecordTypeInfosByName()
                                .get(HH_CONSTANTS.Rfi_CWMPRecordType_APIName)
                                .getRecordTypeId();
        if(recordId != null) {
            Request_For_Information__c rfi = [SELECT Id, RecordType.Name, RecordTypeId, Name, RFI_Deadline__c,Status__c,RFI_Type__c,Description__c,
                                                Cal_OES_Comment__c,Community_Comment__c,FEMA_Comments__c,
                                                Homeowner_Comment__c, CWMP_Application__c,CWMP_Application__r.Name
                                                 FROM Request_For_Information__c WHERE Id =:recordId];
            
            result.put('rfi',rfi);
            result.put('applicationId',rfi.CWMP_Application__c);
            parentRecordId = rfi.CWMP_Application__c;
        } else {
            Request_For_Information__c rfi = new Request_For_Information__c();
            rfi.RecordTypeId = cwmpRecordTypeId;
            rfi.RFI_Type__c = HH_CONSTANTS.Rfi_RFIType_CWMP;
            rfi.CWMP_Application__c = parentRecordId;
            result.put('rfi',rfi);
        }
        List<HH_Application__c> apps = [SELECT Id,Name,Stage__c,Status__c FROM HH_Application__c WHERE Id =:parentRecordId];
        System.debug('apps: '+apps);
        if(apps.size() == 0) {
            throw new CustomException('No CWMP Application found with Id '+parentRecordId);
        }
        HH_Application__c app = apps.get(0);
        if (!isHomeowner() &&  mode != 'View' && !isRFIEditable(app)) {
            throw new CustomException(System.Label.HH_RFICreationPreventionError);
        }
        result.put('isHomeowner',isHomeowner());
        result.put('applicationName', apps.get(0).Name);
        return result;
    }


     /***********************************************
   * Method Name : upsertRFI
   * Author : Shantanu
   * Inputs : String rfiJSON, String parentRecordId(CWMP Application)
   * Description: This create/update RFI.
   *********************************************/
    @AuraEnabled 
    public static Map<String,Object>  upsertRFI(String rfiJSON, String parentRecordId) {
        Map<String,Object> result = new Map<String,Object>();
        Request_For_Information__c rfi = (Request_For_Information__c)JSON.deserialize(rfiJSON, Request_For_Information__c.class);
        String cwmpRecordTypeId = Schema.SObjectType.Request_For_Information__c
                                .getRecordTypeInfosByName()
                                .get(HH_CONSTANTS.Rfi_CWMPRecordType_APIName)
                                .getRecordTypeId();
        rfi.CWMP_Application__c = parentRecordId;
        rfi.RFI_Type__c = HH_CONSTANTS.Rfi_RFIType_CWMP;
        upsert rfi;
        result.put('rfi', rfi);
        return result;
    }

    @AuraEnabled
    public static void isEditable(String applicationId) {
        HH_Application__c app = [SELECT Id,Status__c, Stage__c FROM HH_Application__c WHERE Id =:applicationId];
        if (!isRFIEditable(app)) {
            throw new CustomException(System.Label.HH_RFICreationPreventionError);
        }
    }

      /***********************************************
   * Method Name : isRFIEditable
   * Author : Shantanu
   * Inputs : HH_Application__c app
   * Description: Check if RFI is Editable for FEMA,Community and Caloes User
   *********************************************/
    private static Boolean isRFIEditable(HH_Application__c app) {
        List<User> userRecords = [SELECT Id, Name, Profile.Name, AccountId, ContactId,
            (SELECT Id, PermissionSet.Name FROM PermissionSetAssignments)
            FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
        if(userRecords.size() > 0) {
            if(userRecords[0]?.profile.Name == HH_CONSTANTS.HH_System_Admin_Profile_Name) {
                return true;
            }
            for(PermissionSetAssignment currentUserPermission: userRecords[0].PermissionSetAssignments) {
                if(currentUserPermission.PermissionSet.Name == HH_CONSTANTS.HH_PermissionSet_CommunityUser_APIName) {
                    if ((app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityReview
                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo)
                    || (app?.Stage__c == HH_CONSTANTS.HHApplication_Stage_Assessment
                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo)) {
                        return true;
                    }
                } else if (currentUserPermission.PermissionSet.Name == HH_CONSTANTS.HH_PermissionSet_CalOESUser_APIName) {
                    if(app?.Stage__c == HH_CONSTANTS.HHApplication_Stage_OESReview
                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_OESOpenRFI) {
                        return true;
                    }
                } else if (currentUserPermission.PermissionSet.Name == HH_CONSTANTS.HH_PermissionSet_FemaUser_APIName) {
                    if(app?.Stage__c == HH_CONSTANTS.HHApplication_Stage_FEMAReview
                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_FEMAReviewOpenRFI) {
                        return true;
                    }
                }
            }
        }
        return false;
   }



   /***********************************************
   * Method Name : isHomeOwner
   * Author : Shantanu
   * Inputs : 
   * Description: This method check current user Permission is Homeowner or not.
   *********************************************/
   private static Boolean isHomeowner() {
    List<PermissionSetAssignment> currentUserPermissionList = [SELECT Id, PermissionSetId, PermissionSet.Name,AssigneeId FROM PermissionSetAssignment WHERE AssigneeId =: UserInfo.getUserId() AND PermissionSet.Name =:HH_CONSTANTS.HH_PermissionSet_HomeOwner_APIName];
    if(currentUserPermissionList.size() > 0) {
        for(PermissionSetAssignment currentUserPermission: currentUserPermissionList) {
            if(currentUserPermission.PermissionSet.Name == HH_CONSTANTS.HH_PermissionSet_HomeOwner_APIName) {
                return true;
            }
        }
    }
    return false;
    }

    /***********************************************
   * Method Name : delete RFI
   * Author : Shantanu
   * Inputs : 
   * Description: This method delete RFI
   *********************************************/
    @AuraEnabled 
    public static void  deleteRFI(String recordId) {
        Request_For_Information__c rfi = new Request_For_Information__c();
        rfi.Id= recordId;
        delete rfi;
    }

    public class CustomException extends Exception{

    }

 }