codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>County__c</fullName>
        <description>County of Property</description>
        <inlineHelpText>County of Property</inlineHelpText>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Shasta</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                    <isActive>false</isActive>
                    <label>Los Angeles</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Request_For_Information__c.object
<CustomObject>
    <fields>
        <fullName>CWMP_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CWMP Application</label>
        <referenceTo>HH_Application__c</referenceTo>
        <relationshipLabel>Request For Information</relationshipLabel>
        <relationshipName>Request_For_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RFI_Deadline__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>RFI Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RFI_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Sent to Subapplicant</fullName>
                </value>
                <value>
                    <fullName>Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted</fullName>
                </value>
                <value>
                    <fullName>Response Accepted</fullName>
                </value>
                <value>
                    <fullName>Response Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted to Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA EHP RFI</fullName>
                </value>
                <value>
                    <fullName>OES Analyst Review FEMA Programmatic RFI</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Requested</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Time Extension Rejected</fullName>
                </value>
                <value>
                    <fullName>Response Submitted by Cal OES Analyst</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA EHP RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Accepted</fullName>
                </value>
                <value>
                    <fullName>FEMA Programmatic RFI Rejected</fullName>
                </value>
                <value>
                    <fullName>RFI Requested</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Withdrawal</fullName>
                </value>
                <value>
                    <fullName>Submitted to HMA Analyst</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to HMA Analyst</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request For Information</label>
    <nameField>
        <displayFormat>RFI-{00000}</displayFormat>
        <label>Request For Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Information</pluralLabel>
    <recordTypes>
        <fullName>CWMP</fullName>
        <active>true</active>
        <description>Record Type for CWMP RFI</description>
        <label>CWMP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HH_CustomRelatedListRFICtrl.cls
public with sharing class HH_CustomRelatedListRFICtrl {
    

     /***********************************************
   * Method Name : getRFIRecords
   * Author : Shantanu
   * Inputs : String applicationId
   * Description: This method will fetch RFI records for provided CWMP Application Id
   *********************************************/
    @AuraEnabled
    public static  Map<String,Object> getRFIRecords(String applicationId){
        Map<String,Object> result = new Map<String,Object>();
        try {
            List<Request_For_Information__c> rfiList = [SELECT Id,Name,toLabel(Status__c)Status__l, Status__c, CWMP_Application__r.County__c,RFI_Deadline__c,Description__c,CreatedDate
                                                 FROM Request_For_Information__c WHERE CWMP_Application__c =:applicationId 
                                                 ORDER BY LastModifiedDate DESC];
            result.put('rfiList', rfiList);
            result.put('rfiListCount', rfiList.size());
            List<User> userRecord = [SELECT Id, Name, Profile.Name, AccountId, ContactId,
            (SELECT Id, PermissionSet.Name FROM PermissionSetAssignments)
            FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
            if(userRecord[0].Profile.Name == HH_CONSTANTS.HH_Profile_SystemAdmin) {
                result.put('isRFICreatable',true);    
            }
            if(userRecord?.size()==1){
                result.put('isExternalUser', userRecord[0].AccountId != null);
                result.put('isRFICreatable',true);
                for(PermissionSetAssignment perSet : userRecord[0].PermissionSetAssignments){
                    if(perSet.PermissionSet.Name == HH_CONSTANTS.HH_PermissionSet_HomeOwner_APIName) {
                        result.put('isRFICreatable',false);
                        result.put('isHomeowner', true);
                        result.put('isCommunityUser', false);
                        result.put('isCaloesUser', false);
                        result.put('isFemaUser', false);
                        break;
                    } else if (perSet.PermissionSet.Name == HH_CONSTANTS.HH_PermissionSet_CommunityUser_APIName) {
                        result.put('isRFICreatable',true);
                        result.put('isHomeowner', false);
                        result.put('isCommunityUser', true);
                        result.put('isCaloesUser', false);
                        result.put('isFemaUser', false);
                        break;
                    } else if (perSet.PermissionSet.Name == HH_CONSTANTS.HH_PermissionSet_CalOESUser_APIName) {
                        result.put('isRFICreatable',false);
                        result.put('isHomeowner', false);
                        result.put('isCommunityUser', false);
                        result.put('isCaloesUser', true);
                        result.put('isFemaUser', false);
                        break;     
                    } else if (perSet.PermissionSet.Name == HH_CONSTANTS.HH_PermissionSet_FemaUser_APIName) {
                        result.put('isRFICreatable',false);
                        result.put('isHomeowner', false);
                        result.put('isCommunityUser', false);
                        result.put('isCaloesUser', false);
                        result.put('isFemaUser', true);
                        break;
                    }
                }
            }
            return result;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}