codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Accessible_by_a_Passenger_Vehicle__c</fullName>
        <description>Is the property currently accessible by a standard passenger vehicle?</description>
        <inlineHelpText>Is the property currently accessible by a standard passenger vehicle?</inlineHelpText>
        <label>Accessible by a Passenger Vehicle?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Any_Other_Names_on_the_Property_Deed__c</fullName>
        <description>Are there any other names on the deed for the property?</description>
        <inlineHelpText>Are there any other names on the deed for the property?</inlineHelpText>
        <label>Any Other Names on the Property Deed?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Anyone_Not_a_Proficient_English_Speaker__c</fullName>
        <description>Is anyone in the household not a proficient English speaker?</description>
        <inlineHelpText>Is anyone in the household not a proficient English speaker?</inlineHelpText>
        <label>Anyone Not a Proficient English Speaker?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>HH_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authority_to_make_updates_to_the_Home__c</fullName>
        <description>Do you have the authority to make any updates to the home, substantial or not?</description>
        <inlineHelpText>Do you have the authority to make any updates to the home, substantial or not?</inlineHelpText>
        <label>Authority to Make Updates to the Home?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Car_Ownership__c</fullName>
        <description>Do the current residents occupying the property own a car?</description>
        <inlineHelpText>Do the current residents occupying the property own a car?</inlineHelpText>
        <label>Car Ownership?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City of property</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>City of property.</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>County of Property</description>
        <inlineHelpText>County of Property</inlineHelpText>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Shasta</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                    <isActive>false</isActive>
                    <label>Los Angeles</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Anyone_65__c</fullName>
        <description>Is anyone in the household age 65 or Older?</description>
        <inlineHelpText>Is anyone in the household age 65 or Older?</inlineHelpText>
        <label>Is Anyone Age 65 or Older?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Anyone_Age_5_and_Under__c</fullName>
        <description>Is anyone in the household age 5 or younger?</description>
        <inlineHelpText>Is anyone in the household age 5 or younger?</inlineHelpText>
        <label>Is Anyone Age 5 or under?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Anyone_has_Disabilities__c</fullName>
        <description>Is anyone in the household a person with disabilities?
Disability Definition: A physical or mental impairment that substantially limits one or more major life activities; a record of such an impairment; or being regarded as having such an impairment. (Regardless if the person is  receiving SSI disability or not.)</description>
        <inlineHelpText>Is anyone in the household a person with disabilities?
Disability Definition: A physical or mental impairment that substantially limits one or more major life activities; a record of such an impairment; or being regarded as having such an impairment. (Regardless if the person is  receiving SSI disability or not.)</inlineHelpText>
        <label>Does Anyone Have a Disability?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_National_Register_of_Historic_Places__c</fullName>
        <description>Is the house you wish to retrofit registered in the National Register of Historic Places?</description>
        <inlineHelpText>Is the house you wish to retrofit registered in the National Register of Historic Places?</inlineHelpText>
        <label>On National Register of Historic Places?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Physical_Address_a_Foreign_Address__c</fullName>
        <description>Is Physical Address a Foreign Address?</description>
        <formula>TEXT(Applicant__r.Is_Physical_Address_a_Foreign_Address__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Is Physical Address a Foreign Address?</inlineHelpText>
        <label>Is Physical Address a Foreign Address?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Stories__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of stories in the structure.</description>
        <inlineHelpText>Number of stories in the structure.</inlineHelpText>
        <label>Number of Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Physical_City__c</fullName>
        <description>Physical City</description>
        <formula>Applicant__r.Physical_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Physical City</inlineHelpText>
        <label>Physical City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Zip_Postal_Code__c</fullName>
        <description>Physical ZIP/Postal Code</description>
        <formula>Applicant__r.Physical_Zip_Postal_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Physical ZIP/Postal Code</inlineHelpText>
        <label>Physical Zip/Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Residence__c</fullName>
        <description>Is the property the homeowner’s primary residence?</description>
        <inlineHelpText>Is the property the homeowner’s primary residence?</inlineHelpText>
        <label>Primary Residence?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Owner__c</fullName>
        <description>Are you the owner of the property?</description>
        <inlineHelpText>Are you the owner of the property?</inlineHelpText>
        <label>Property Owner?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Street_Address__c</fullName>
        <description>Street Address of Property.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Street Address of Property.</inlineHelpText>
        <label>Property Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Structure__c</fullName>
        <description>What type of structure is the property?</description>
        <inlineHelpText>What type of structure is the property?</inlineHelpText>
        <label>Property Structure Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Family Residence Single Story</fullName>
                </value>
                <value>
                    <fullName>Single Family Residence Multi Story</fullName>
                </value>
                <value>
                    <fullName>Multi Family Residence Single Story</fullName>
                </value>
                <value>
                    <fullName>Multi Family Residence Multi Story</fullName>
                </value>
                <value>
                    <fullName>Manufactured or Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Manufactured or Mobile Home; Other</fullName>
                    <isActive>false</isActive>
                    <label>Manufactured or Mobile Home; Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rental_Property__c</fullName>
        <description>Is the property a rental property?</description>
        <inlineHelpText>Is the property a rental property?</inlineHelpText>
        <label>Rental Property?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State of the property</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>State of the property</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Living_Area__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total living area in sq. ft (all floors)</description>
        <inlineHelpText>Total living area in sq. ft (all floors)</inlineHelpText>
        <label>Total Living Area (sq ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_of_Construction__c</fullName>
        <description>Year of Construction of the Property?</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Year of Construction of the Property?</inlineHelpText>
        <label>Year of Construction</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <description>Zip/Postal Code of Property</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Zip/Postal Code of Property</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HH_ApplicationValidationCtrl.cls
public with sharing class HH_ApplicationValidationCtrl {
    
    @AuraEnabled
    public static Map<String,Object> validateApplication(String applicationId) {
        Map<String,Object> result = new Map<String,Object>();
        HH_Application__c app = queryApplication(applicationId);
        result.put('1',validateApplicantInfo(app));
        result.put('2',validateEligibilityInfo(app));
        result.put('3',validatePropertyInfo(app));
        result.put('4',validateApplicationDocmentation(app));
        result.put('5',validateApplicantCertification(app));
        return result;
    }


    public static Boolean validateApplicantInfo(HH_Application__c app) {
        if(app.Applicant__r.FirstName != null && app.Applicant__r.FirstName != null  && app.Applicant__r.Physical_Street__c != null && 
            app.Applicant__r.Physical_City__c != null && app.Applicant__r.Physical_State__c != null &&  
            app.Applicant__r.Physical_Country__c != null && app.Applicant__r.Physical_Zip_Postal_Code__c != null && 
            app.Applicant__r.Phone != null && app.Applicant__r.LastName != null && 
            app.Applicant__r.Is_Physical_Address_a_Foreign_Address__c != null &&  
            app.Applicant__r.Is_Mailing_Address_a_Foreign_Address__c != null && 
            app.Applicant__r.Is_Mailing_Address_Different__c != null &&  
            app.Applicant__r.Preferred_Language__c != null  && 
            app.Applicant__r.MailingStreet != null && app.Applicant__r.MailingCity != null &&
            app.Applicant__r.MailingState != null && app.Applicant__r.MailingCountry != null && 
            app.Applicant__r.MailingPostalCode != null && app.Applicant__r.English_Language_Proficiency__c != null) {
                return true;
        }
        return false;

    }


    public static Boolean validateEligibilityInfo(HH_Application__c app) {
        if(app.Property_Owner__c != null &&  app.Primary_Residence__c != null &&  app.Rental_Property__c != null  && app.Car_Ownership__c != null &&
        app.Is_Anyone_65__c != null &&  app.Is_Anyone_Age_5_and_Under__c != null && app.Anyone_Not_a_Proficient_English_Speaker__c != null &&
          app.Is_Anyone_has_Disabilities__c != null ) {
            return true;
        }
        return false;
    }

    public static Boolean validateApplicationDocmentation(HH_Application__c app) {
        return true;
    }

    public static Boolean validatePropertyInfo(HH_Application__c app) {
        if(app.Property_Structure__c != null &&  app.Property_Street_Address__c != null &&  app.City__c != null  &&
            app.State__c != null && app.Zip_Postal_Code__c != null &&  app.County__c != null &&
            app.Year_of_Construction__c != null &&  app.Authority_to_make_updates_to_the_Home__c != null &&  app.Total_Living_Area__c != null && 
            app.Number_of_Stories__c != null &&  app.Accessible_by_a_Passenger_Vehicle__c != null &&  app.Is_National_Register_of_Historic_Places__c != null &&
            app.Any_Other_Names_on_the_Property_Deed__c != null &&  app.Property_Foreclosed_or_in__c != null &&  app.Property_Liens__c != null && 
            app.Good_Standing_with_a_payment_plan_on_you__c != null  &&  app.Measures_to_Reduce_risks_to_wi__c != null && app.Did_you_receive_wildfire_assistance__c != null) { 
            return true;
        }
        return false;
    }

    public static Boolean validateApplicantCertification(HH_Application__c app) {
        return app.Agreement_Disclosure__c;
    }

    private static HH_Application__c queryApplication(String applicationId) {
        return [SELECT Id, Name, Property_Owner__c, Property_Structure__c, Car_Ownership__c, Currently_Occupied__c,
                Damage_Description__c,Ethnicities_of_Household_Members__c, Is_Anyone_65__c, Is_Anyone_Age_5_and_Under__c,
                Is_Anyone_has_Disabilities__c, Property_Currently_Damaged__c, Rental_Property__c,
                Agreement_Disclosure__c, Primary_Residence__c, Accessible_by_a_Passenger_Vehicle__c, Any_Other_Names_on_the_Property_Deed__c, 
                Anyone_Not_a_Proficient_English_Speaker__c, Assessed_Value_of_the_Property__c, Assistance_to_reduce_yo__c,
                City__c, County__c, Property_Street_Address__c,Did_you_receive_wildfire_assistance__c,
                State__c, Zip_Postal_Code__c, Authority_to_make_updates_to_the_Home__c, Year_of_Construction__c, Total_Living_Area__c,
                Number_of_Stories__c, Is_National_Register_of_Historic_Places__c,
                Property_Foreclosed_or_in__c, Property_Liens__c,Good_Standing_with_a_payment_plan_on_you__c,
                Measures_to_Reduce_risks_to_wi__c, Stage__c, List_of_Measures__c,Program__c,
                Applicant__r.AccountId, Applicant__r.Account.Name, Applicant__r.Account.Account_Name__c, Applicant__r.FirstName,
                Applicant__r.Physical_Street__c,Applicant__r.Physical_City__c,Applicant__r.Physical_State__c, Applicant__r.Physical_Country__c,Applicant__r.Physical_Zip_Postal_Code__c,
                Applicant__r.Email, Applicant__r.Phone,Applicant__r.LastName,
                Applicant__r.Is_Physical_Address_a_Foreign_Address__c, Applicant__r.Is_Mailing_Address_a_Foreign_Address__c,
                Applicant__r.Is_Mailing_Address_Different__c, Applicant__r.Preferred_Language__c, Applicant__r.OtherPhone,
                Applicant__r.MailingStreet,Applicant__r.MailingCity,Applicant__r.MailingState,
                Applicant__r.MailingCountry, Applicant__r.MailingPostalCode,OwnerId,
                Applicant__r.English_Language_Proficiency__c, Applicant__r.MobilePhone, Applicant__r.HomePhone, Unique_Household_Number__c,Household_Members__c 
                FROM HH_Application__c WHERE Id =:applicationId  LIMIT 1];
    }
}