codepkg/objects/HH_Application__c.object
<CustomObject>
    <description>Application Object for Home Hardening Application.</description>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the application</description>
        <inlineHelpText>Stage of the application</inlineHelpText>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Community Review</fullName>
                </value>
                <value>
                    <fullName>Community Decision</fullName>
                </value>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Decision</fullName>
                </value>
                <value>
                    <fullName>CalOES Review</fullName>
                    <label>Cal OES Review</label>
                </value>
                <value>
                    <fullName>OES Decision</fullName>
                    <label>Cal OES Decision</label>
                </value>
                <value>
                    <fullName>FEMA Review</fullName>
                </value>
                <value>
                    <fullName>FEMA Decision</fullName>
                </value>
                <value>
                    <fullName>Approved- Converted</fullName>
                    <label>Approved - Converted</label>
                </value>
                <value>
                    <fullName>Rejected - Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the application</description>
        <inlineHelpText>Status of the application</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Appeal Approval - Resubmit</fullName>
                </value>
                <value>
                    <fullName>Community Review Pending</fullName>
                </value>
                <value>
                    <fullName>Community Review In  Progress</fullName>
                    <label>Community Review In Progress</label>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Pending</fullName>
                </value>
                <value>
                    <fullName>Assessment In progress</fullName>
                </value>
                <value>
                    <fullName>Open Community RFI- Need more Info</fullName>
                    <label>Community RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Assessment Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Cal OES Review</fullName>
                </value>
                <value>
                    <fullName>Rejected - Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Pending Cal OES Review</fullName>
                    <label>Cal OES Review Pending</label>
                </value>
                <value>
                    <fullName>OES Review In Progress</fullName>
                    <label>Cal OES Review In Progress</label>
                </value>
                <value>
                    <fullName>OES RFI- Need more Info</fullName>
                    <label>Cal OES RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for FEMA Review</fullName>
                </value>
                <value>
                    <fullName>Pending FEMA Review</fullName>
                    <label>FEMA Review Pending</label>
                </value>
                <value>
                    <fullName>FEMA Review In Progress</fullName>
                </value>
                <value>
                    <fullName>FEMA RFI- Need more Info</fullName>
                    <label>FEMA RFI Opened - Need More Information</label>
                </value>
                <value>
                    <fullName>Approved for Project Conversion</fullName>
                    <label>FEMA Approved</label>
                </value>
                <value>
                    <fullName>Rejected - Does not meet Criteria</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved  for Project Conversion</fullName>
                    <isActive>false</isActive>
                    <label>Approved  for Project Conversion</label>
                </value>
                <value>
                    <fullName>Community Decision Pending</fullName>
                    <isActive>false</isActive>
                    <label>Community Decision Pending</label>
                </value>
                <value>
                    <fullName>Community Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>Community Review Complete</label>
                </value>
                <value>
                    <fullName>FEMA Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>FEMA Review Complete</label>
                </value>
                <value>
                    <fullName>OES Review Complete</fullName>
                    <isActive>false</isActive>
                    <label>OES Review Complete</label>
                </value>
                <value>
                    <fullName>Pending Community Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Community Review</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CWMP Application</label>
    <nameField>
        <displayFormat>CWMPA-{000000}</displayFormat>
        <label>CWMP Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWMP Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HH_EditRequestCtrl.cls
public without sharing class HH_EditRequestCtrl {
    
    /***********************************************
    * Method Name : getInitData
    * Author : Shantanu
    * Inputs : 1. String appId(HH_Application__c) 
    * Description: This method will determine the when to enable edit button depending 
                    user permission set,
                    Application record stage and status
    *********************************************/
    @AuraEnabled
    public static Map<String, Object> getInitData(String appId) {
        Map<String, Object> returnMap  = new Map<String, Object>();
        try {
            List<User> userRecord = [SELECT Id, Name, Profile.Name, AccountId, ContactId,
            (SELECT Id, PermissionSet.Name FROM PermissionSetAssignments)
            FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
            set<String> prSet = new Set<String>();
            if(userRecord?.size()==1){
                for(PermissionSetAssignment perSet:userRecord[0].PermissionSetAssignments){
                    prSet.add(perSet.PermissionSet.Name);
                }
                if(userRecord[0]?.profile.Name == HH_CONSTANTS.HH_System_Admin_Profile_Name) {
                    returnMap.put('isEdit', true);
                } else {
                    Boolean isEdit;
                    //if (userRecord[0].AccountId != null) {
                        HH_Application__c app = [SELECT Id,Stage__c,Status__c From HH_Application__c WHERE Id=:appId];
                        if(app.Stage__c == HH_CONSTANTS.HHApplication_Stage_Draft
                            && app.Status__c != HH_CONSTANTS.HHApplication_Status_Withdrawn) {
                            isEdit = true;
                        } else if (prSet.contains(HH_CONSTANTS.HH_PermissionSet_HomeOwner_APIName)
                                && app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityReview
                                && app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo) {
                            isEdit = true;
                        } else if(prSet.contains(HH_CONSTANTS.HH_PermissionSet_CommunityUser_APIName)
                                &&((app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityReview
                                        &&(app.Status__c == HH_CONSTANTS.HHApplication_Status_CommunityReviewPending
                                            ||app.Status__c == HH_CONSTANTS.HHApplication_Status_CommunityReviewInProgress
                                            ||app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo))
                                    ||(app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityDecision
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_ApprovedForAssessment)
                                    ||(app.Stage__c == HH_CONSTANTS.HHApplication_Stage_Assessment
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_OESReview
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_OESOpenRFI))) {
                            isEdit = true;
                        }
                    else if(prSet.contains(HH_CONSTANTS.HH_PermissionSet_CalOESUser_APIName)
                                &&((app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityReview
                                        &&(app.Status__c == HH_CONSTANTS.HHApplication_Status_CommunityReviewPending
                                            ||app.Status__c == HH_CONSTANTS.HHApplication_Status_CommunityReviewInProgress
                                            ||app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo))
                                    ||(app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityDecision
                                        && app.Status__c == HH_CONSTANTS.HHApplication_Status_ApprovedForAssessment)
                                    ||(app.Stage__c == HH_CONSTANTS.HHApplication_Stage_Assessment
                                        && app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo)
                                    || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_OESReview
                                        && app.Status__c == HH_CONSTANTS.HHApplication_Status_OESOpenRFI))) {
 
                            isEdit = true;
                    }
                    else {
                        isEdit = false;
                    }

                    /** Post MVP - Sprint 6 - To remove the above and uncomment the below. */
                    /*if (prSet.contains(HH_CONSTANTS.HH_PermissionSet_HomeOwner_APIName)
                            && ((app.Stage__c == HH_CONSTANTS.HHApplication_Stage_Draft 
                                    && app.Status__c != HH_CONSTANTS.HHApplication_Status_Withdrawn)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityReview
                                        && app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo))) {
                        isEdit = true;
                    }
                    else if(prSet.contains(HH_CONSTANTS.HH_PermissionSet_CommunityUser_APIName)
                            && ((app.Stage__c == HH_CONSTANTS.HHApplication_Stage_Draft
                                    && app.Status__c != HH_CONSTANTS.HHApplication_Status_Withdrawn)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityReview
                                    && (app.Status__c == HH_CONSTANTS.HHApplication_Status_CommunityReviewPending
                                        || app.Status__c == HH_CONSTANTS.HHApplication_Status_CommunityReviewInProgress
                                        || app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo))
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityDecision
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_ApprovedForAssessment)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_Assessment
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_OESReview
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_OESOpenRFI)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_FEMAReview
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_FEMAReviewOpenRFI))) {
                        isEdit = true;
                    }
                    else if(prSet.contains(HH_CONSTANTS.HH_PermissionSet_CalOESUser_APIName)
                            && ((app.Stage__c == HH_CONSTANTS.HHApplication_Stage_Draft
                                    && app.Status__c != HH_CONSTANTS.HHApplication_Status_Withdrawn)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityReview
                                    && (app.Status__c == HH_CONSTANTS.HHApplication_Status_CommunityReviewPending
                                        ||app.Status__c == HH_CONSTANTS.HHApplication_Status_CommunityReviewInProgress
                                        ||app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo))
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_CommunityDecision
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_ApprovedForAssessment)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_Assessment
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_OpenRFINeedMoreInfo)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_OESReview
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_OESOpenRFI)
                                || (app.Stage__c == HH_CONSTANTS.HHApplication_Stage_FEMAReview
                                    && app.Status__c == HH_CONSTANTS.HHApplication_Status_FEMAReviewOpenRFI))) {
                        isEdit = true;
                    }
                    else {
                        isEdit = false;
                    }*/

                        returnMap.put('isEdit', isEdit);
                        returnMap.put('recordId',appId);
                        returnMap.put('isExternalUser',userRecord[0].AccountId != null);
                    /*} else {
                        isEdit = false;
                        returnMap.put('isEdit', isEdit);
                        returnMap.put('recordId',appId);
                    }   */
                }
            }
        } catch (Exception e) {
            System.debug('Error : '+e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
        return returnMap;
    }

    public static Boolean isApplicationEditable(String applicationId) {
        
        return (Boolean)getInitData(applicationId).get('isEdit');
    }
}