codepkg/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Incident_Subrecipient_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Sub - Recipient  to which this junction record is related.</description>
        <inlineHelpText>Sub - Recipient  to which this junction record is related.</inlineHelpText>
        <label>Sub Recipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Incident_Subrecipient_Stages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Available_Federal_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Roll Up sum of &quot;Pending Federal Amount Available&quot; of all the Project, which is having the same Incident And Sub Recipient as this Record.</description>
        <inlineHelpText>Roll Up sum of &quot;Pending Federal Amount Available&quot; of all the Project, which is having the same Incident And Sub Recipient as this Record.</inlineHelpText>
        <label>Available Federal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Available_State_Admin_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Roll Up sum of &quot;Pending Admin Amount Available&quot; of all the Project, which is having the same Incident And Sub Recipient as this Record.</description>
        <inlineHelpText>Roll Up sum of &quot;Pending Admin Amount Available&quot; of all the Project, which is having the same Incident And Sub Recipient as this Record.</inlineHelpText>
        <label>Available State Admin Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Available_State_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Roll Up sum of &quot;Pending State Amount Available&quot; of all the Project, which is having the same Incident And Sub Recipient as this Record.</description>
        <inlineHelpText>Roll Up sum of &quot;Pending State Amount Available&quot; of all the Project, which is having the same Incident And Sub Recipient as this Record.</inlineHelpText>
        <label>Available State Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <description>Incident to which this junction is related.</description>
        <inlineHelpText>Incident to which this junction is related.</inlineHelpText>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipName>Incident_sub_recipient_stage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Incident Subrecipient Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Subrecipient Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incident Subrecipient summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>AvailableAdminAmount__c</fullName>
        <description>Total Admin Amount Available for this Project.</description>
        <formula>TotalProjectStateAdminShare__c - AdminAmountDisbursed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Admin Amount Available for this Project.
[ Total Project State Admin Share - Admin Amount Disbursed ]</inlineHelpText>
        <label>Admin Amount Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FederalAmountAvailable__c</fullName>
        <description>Federal Amount available for this Project.</description>
        <formula>Federal_Project_Award__c -  FederalAmountDisbursed__c</formula>
        <inlineHelpText>Federal Amount available for this Project.
[ Total Project Federal Award - Total Federal Amount Disbursed ]</inlineHelpText>
        <label>Federal Amount Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incident_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The name of the Incident</description>
        <inlineHelpText>Disaster/Incident for which the project is related. Not all projects will have an associated Incident.</inlineHelpText>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obligating_Sub_Recipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required because the documents 130 and 130SA creation depends upon Sub-recipient Entity Type.</description>
        <inlineHelpText>The Subrecipient for which the project has been obligated.</inlineHelpText>
        <label>Obligated Sub - Recipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StateAmountAvailable__c</fullName>
        <description>State Amount Available for this Project.</description>
        <formula>State_Project_Award__c -   StateAmountDisbursed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>State Amount Available for this Project.
[ Total Project State Award -  Total State Amount Disbursed ]</inlineHelpText>
        <label>State Amount Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/SummaryJunctionRollupJob.cls
/**
 * Created by StackNexus Admin on 30-03-2021.
 */

public with sharing class SummaryJunctionRollupJob implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    private final String query;

    public SummaryJunctionRollupJob(String query) {
        this.query = query;
    }

    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new SummaryJunctionRollupJob(query));
    }

    public Database.QueryLocator start(Database.batchableContext BC){
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext param1, List<SObject> Scope) {
       List<Incident_Subrecipient_Stage__c> summaryRecordList = (List<Incident_Subrecipient_Stage__c>) Scope;
        /*set<Id> recordId = new set<Id>();
        for(SObject obj : Scope){
            recordId.add(obj.Id);
        }
        List<Incident_Subrecipient_Stage__c> sammaryList =[SELECT Id,Account__c,Incident__c FROM Incident_Subrecipient_Stage__c where Id IN :recordId];*/
        Map<String,AggregateResult> incAccToAggregateResultMap = new Map<String,AggregateResult>();
        Set<Id> accIds =new Set<Id>();
        Set<Id> incIds =new Set<Id>();

        for(Incident_Subrecipient_Stage__c inc : summaryRecordList){
            //String key =(String)inc.Incident__c+(String)inc.Account__c;
            //accIncToSummaryMap.put(key,inc);
            accIds.add(inc.Account__c);
            incIds.add(inc.Incident__c);
        }
        if(accIds.size() > 0 && incIds.size() > 0 ) {
            List<AggregateResult> results = [SELECT Incident_Name__c,Obligating_Sub_Recipient__c ,
                                            SUM(FederalAmountAvailable__c)FederalAmountAvailable,
                                            SUM(StateAmountAvailable__c)StateAmountAvailable,
                                            SUM(AvailableAdminAmount__c)AvailableAdminAmount FROM Project__c
                                            WHERE Incident_Name__c IN : incIds AND
                                            Obligating_Sub_Recipient__c IN : accIds GROUP BY Incident_Name__c,Obligating_Sub_Recipient__c ];

            for (AggregateResult result : results) {
                Id incidentIds = (Id)result.get('Incident_Name__c');
                Id subRecipientId = (Id)result.get('Obligating_Sub_Recipient__c');
                String key = (String)incidentIds + (String)subRecipientId;
                incAccToAggregateResultMap.put(key, result);
            }
            for (Incident_Subrecipient_Stage__c summaryRecord : summaryRecordList) {
                String key =(String)summaryRecord.Incident__c+(String)summaryRecord.Account__c;
                AggregateResult result = (AggregateResult) incAccToAggregateResultMap?.get(key);
                Decimal federalAmountAvailable = (Decimal)result?.get('FederalAmountAvailable') == null ? 0.00 : (Decimal)result?.get('FederalAmountAvailable');
                Decimal stateAmountAvailable = (Decimal)result?.get('StateAmountAvailable') == null ? 0.00 : (Decimal)result?.get('StateAmountAvailable');
                Decimal adminAmountAvailable = (Decimal)result?.get('AvailableAdminAmount') == null ? 0.00 : (Decimal)result?.get('AvailableAdminAmount');

                summaryRecord.Available_State_Admin_Amount__c = adminAmountAvailable == null? 0.00 : adminAmountAvailable;
                summaryRecord.Available_Federal_Amount__c = federalAmountAvailable == null? 0.00 : federalAmountAvailable;
                summaryRecord.Available_State_Amount__c = stateAmountAvailable == null? 0.00 : stateAmountAvailable;
            }
            update summaryRecordList ;

            /*List<Incident_Subrecipient_Stage__c> stageRecordsToUpdate = new List<Incident_Subrecipient_Stage__c>();
            for(AggregateResult aggResult :results){
                Id incidentIds = (Id)aggResult.get('Incident_Name__c');
                Id subRecipientId = (Id)aggResult.get('Obligating_Sub_Recipient__c');
                String key = (String)incidentIds + (String)subRecipientId;
                Incident_Subrecipient_Stage__c stageRecord = accIncToSummaryMap.get(key);
                Decimal federalAmountAvailable = (Decimal)aggResult.get('FederalAmountAvailable');
                Decimal stateAmountAvailable = (Decimal)aggResult.get('StateAmountAvailable');
                Decimal adminAmountAvailable = (Decimal)aggResult.get('AvailableAdminAmount');
                stageRecord.Available_Federal_Amount__c = federalAmountAvailable;
                stageRecord.Available_State_Amount__c = stateAmountAvailable;
                stageRecord.Available_State_Admin_Amount__c = adminAmountAvailable;
                stageRecordsToUpdate.add(stageRecord);
            }
            update stageRecordsToUpdate;*/
        }

    }
    public void finish(Database.BatchableContext BC) {

    }
}