codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Available_for_Application__c</fullName>
        <label>Available for Application</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PHOS</fullName>
                </value>
                <value>
                    <fullName>HMA</fullName>
                </value>
                <value>
                    <fullName>MARS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>The Incident or Emergency Event Type</description>
        <inlineHelpText>Event type (Ex. Fire, Flood, Earthquake etc.).</inlineHelpText>
        <label>Event Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Drought</fullName>
                </value>
                <value>
                    <fullName>Earthquake</fullName>
                </value>
                <value>
                    <fullName>Economic</fullName>
                </value>
                <value>
                    <fullName>Explosion</fullName>
                </value>
                <value>
                    <fullName>Fire</fullName>
                </value>
                <value>
                    <fullName>Flood</fullName>
                </value>
                <value>
                    <fullName>Debris &amp; Mud flows</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Hurricane</fullName>
                </value>
                <value>
                    <fullName>Landslide</fullName>
                </value>
                <value>
                    <fullName>Manmade</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Snow</fullName>
                </value>
                <value>
                    <fullName>Storm</fullName>
                </value>
                <value>
                    <fullName>Tornado</fullName>
                </value>
                <value>
                    <fullName>Tree Mortality</fullName>
                </value>
                <value>
                    <fullName>Tsunami</fullName>
                </value>
                <value>
                    <fullName>Wind</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incident_End_Date__c</fullName>
        <description>Date the Incident Ended</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date the Incident or Event Ended</inlineHelpText>
        <label>Incident End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incident_Start_Date__c</fullName>
        <description>Date the Incident Started or Occurred</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date the Incident Started or Occurred.</inlineHelpText>
        <label>Incident Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Order No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/classes/MARS_Incident_Search_Ctrl.cls
public without sharing class MARS_Incident_Search_Ctrl {



        @AuraEnabled(cacheable=true)
        public static list<Incident__c> getIncidentList(string searchKey) {
            string searchKeyword = '%' + searchKey + '%';
            
           // create Incident__c list to store search result 
           list<Incident__c> incidentListRecord = new list<Incident__c>();
         
           // query Incident__c records
            for(Incident__c conObj : [Select Id, Name, Event_Type__c, isActive__c, Order_No__c, Year__c,
                                       Incident_Start_Date__c, Incident_End_Date__c 
                                       From Incident__c
                                       WHERE Available_for_Application__c   INCLUDES ('MARS') and Name LIKE : searchKeyword ]){
               incidentListRecord.add(conObj);
            }
            
             if(incidentListRecord.size() == 0){
                throw new AuraHandledException('No Record Found..'); 
             }
             
            return incidentListRecord;
        }
        @AuraEnabled(cacheable=true)
        public static list<Incident__c> getIncidentListByNumber(string searchnum) {
            string searchNumber = '%' + searchnum + '%';
            
           // create Incident__c list to store search result 
           list<Incident__c> incidentListRecord = new list<Incident__c>();
         
           // query Incident__c records
            for(Incident__c conObj : [Select Id, Name, Event_Type__c, isActive__c, Order_No__c, Year__c,
                                       Incident_Start_Date__c, Incident_End_Date__c 
                                    From Incident__c
                                WHERE  Available_for_Application__c   INCLUDES ('MARS') and Order_No__c like : searchNumber ]){
               incidentListRecord.add(conObj);
            }
            
             if(incidentListRecord.size() == 0){
                throw new AuraHandledException('No Record Found..'); 
             }
             
            return incidentListRecord;
        }

}