codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Financial Closeout - FPU In Progress</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout FPU - Closed</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - In Review</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - Awaiting FEMA Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Incident_Subrecipient_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Sub - Recipient  to which this junction record is related.</description>
        <inlineHelpText>Sub - Recipient  to which this junction record is related.</inlineHelpText>
        <label>Sub Recipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Incident_Subrecipient_Stages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <description>Incident to which this junction is related.</description>
        <inlineHelpText>Incident to which this junction is related.</inlineHelpText>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipName>Incident_sub_recipient_stage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>This field represents the Stage of the Incident for a particular Sub - Recipient.</description>
        <inlineHelpText>This field represents the Stage of the Incident for a particular Sub - Recipient.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Financial Closeout - FPU In Progress</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout FPU - Closed</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - In Review</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - Awaiting FEMA Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Incident Subrecipient Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Subrecipient Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incident Subrecipient summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/ALS_IncidentSubrecipientJunPreview_Ctrl.cls
/**
 * Created by Sushant on 18-01-2021.
 */

public with sharing class ALS_IncidentSubrecipientJunPreview_Ctrl {
    @AuraEnabled(cacheable=true)
 public static Map<String, Object> getIncidentSubrecipientInfo(String masterRecordId ,String refreshDate){
        Map<String, Object> resultMap = new Map<String, Object>();
        Id masterRecordIdVersion = masterRecordId;
        String masterObjName = masterRecordIdVersion.getSObjectType().getDescribe().getName();
        String FieldName;
        if(masterObjName =='Account'){
            FieldName ='Account__c';
        }else if(masterObjName =='Incident__c'){
            FieldName ='Incident__c';
        }

        String query='Select Name,Id,Account__r.Name, Incident__r.Name, Stage__c From Incident_Subrecipient_Stage__c where '+FieldName+' = '+'\'' + masterRecordId + '\'';
        List<Incident_Subrecipient_Stage__c> getIncidentSubrecipient =Database.query(query);
        resultMap.put('incidentSubrecipient',getIncidentSubrecipient);
        return resultMap;
 }

}