codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Incident or Disaster</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Description of the Incident or Disaster</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Reimbursement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reimbursements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Local Agency Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Incident_Order_Number__c</fullName>
        <formula>Incident__r.Order_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Incident Order Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Request_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Request Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipName>Reimbursements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lodging_Total__c</fullName>
        <label>Lodging Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MACIDs__c</fullName>
        <formula>Account__r.MACS_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MACIDs</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MISC_Total__c</fullName>
        <label>MISC Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Meal_Total__c</fullName>
        <label>Meal Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mutual_Aid_Staff_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Mutual Aid Staff Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Printed_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Printed Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agency Review</fullName>
                </value>
                <value>
                    <fullName>CALOES Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strike_Team__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>STRIKE TEAM / TASK FORCE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Reimbursement_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Unit Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Expense Claim</label>
    <nameField>
        <displayFormat>EC-{00000000}</displayFormat>
        <label>Reimbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Reimbursement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lodging__c</fullName>
        <label>Lodging</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MISC__c</fullName>
        <label>MISC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Meal__c</fullName>
        <label>Meal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reimbursement__c</fullName>
        <label>Reimbursement</label>
        <referenceTo>Reimbursement__c</referenceTo>
        <relationshipLabel>Expense Claim Line Items</relationshipLabel>
        <relationshipName>Reimbursement_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense Claim Line Item</label>
    <nameField>
        <displayFormat>EC-{000000}</displayFormat>
        <label>Reimbursement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Claim Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/Mars_ReimbursementHistoryCtrl.cls
public without sharing class Mars_ReimbursementHistoryCtrl {
    @AuraEnabled
    public static List<Reimbursement__c> getReimbursementHistory(String accountId) {
        return [SELECT Id, Name,Total_Reimbursement_Amount__c,Printed_Name__c,Submission_Date__c,Strike_Team__c,
                Account__r.Name,Incident__r.Name,Comments__c,Status__c,Incident_Order_Number__c,Incident_Request_Number__c,Mutual_Aid_Staff_Comments__c
                FROM Reimbursement__c WHERE Account__c=:accountId ORDER BY CreatedDate DESC NULLS FIRST LIMIT 10];
    } 
    @AuraEnabled
    public static List<Reimbursement_Line_Item__c > getReimbursementLineItems(String reimbursemenId) {
        return [SELECT Id,Date__c, City__c,Meal__c, Lodging__c, MISC__c, Description__c, Amount__c
               FROM Reimbursement_Line_Item__c  WHERE Reimbursement__c=:reimbursemenId];
    }
    @AuraEnabled
    public static Map<String, Object> getData(String reimbursemenId) {
        Map<String, Object> returnMap = new Map<String, Object>();
        String signature='';
        returnMap.put('ReimbursementLineItems', getReimbursementLineItems(reimbursemenId));

        Reimbursement__c reimbursement = [SELECT Id, Name,Total_Reimbursement_Amount__c,Printed_Name__c,Submission_Date__c,Status__c,Approver_Comments__c,
                                            MACIDs__c,Strike_Team__c,Incident_Order_Number__c,Incident_Request_Number__c,Unit_Number__c,Incident__r.Name,Mutual_Aid_Staff_Comments__c,
                                            Comments__c,Meal_Total__c,MISC_Total__c,Lodging_Total__c FROM Reimbursement__c WHERE Id=:reimbursemenId LIMIT 1];
        returnMap.put('Reimbursement', reimbursement);
        returnMap.put('contentVersions', getContentVersions(new List<String>{reimbursemenId}));
        List<ContentVersion> signDco = getSignContentVersions(new List<String>{reimbursemenId});
        if(signDco.size() > 0)
            signature ='/sfc/servlet.shepherd/version/download/'+signDco[0].Id;
        returnMap.put('signature',signature);
        return returnMap;
    }
    private static List<ContentVersion> getContentVersions(List<String> recordIds) {

        Set<Id> contentDocIds = new Set<Id>();
        System.debug('recordIds---' + recordIds);
        // added dynamic query due to weired issue with static query - ContentDocumentLink requires a filter by a single Id on ContentDocumentId or LinkedEntityId using the equals operator or multiple Id's using the IN operator.
        String query = 'SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId in(\'' + String.join(recordIds, '\',\'') + '\')';
        for(ContentDocumentLink contentDocLink : Database.query(query)) {
            contentDocIds.add(contentDocLink.ContentDocumentId);
        }

        system.debug('==contentDocIds==='+contentDocIds);
        return [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
        from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest = true AND Type__c != null order by ContentModifiedDate desc];
    }
    private static List<ContentVersion> getSignContentVersions(List<String> recordIds) {

        Set<Id> contentDocIds = new Set<Id>();
        // added dynamic query due to weired issue with static query - ContentDocumentLink requires a filter by a single Id on ContentDocumentId or LinkedEntityId using the equals operator or multiple Id's using the IN operator.
        String query = 'SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId in(\'' + String.join(recordIds, '\',\'') + '\')';
        for(ContentDocumentLink contentDocLink : Database.query(query)) {
            contentDocIds.add(contentDocLink.ContentDocumentId);
        }

        return [select Id,ContentModifiedDate,ContentModifiedById,Type__c,Title,Owner.Name,ContentDocumentId,FileExtension
        from ContentVersion where ContentDocumentId in:contentDocIds AND IsLatest=true AND Title LIKE 'Signature%' order by ContentModifiedDate desc];
    }
}