codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Eamil_To_Send__c</fullName>
        <description>Put comma separated email ids</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Put comma separated email ids</inlineHelpText>
        <label>Email IDs To Send</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Personnel_Email_IDs__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Personnel Email IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>CASF-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/PHOS_SendEmailRequestFromOtherUserTest.cls
@isTest(seeAllData=false)
public class PHOS_SendEmailRequestFromOtherUserTest {
    @isTest public static void testSendEmail() {
        List<Id> orderIds = new List<Id>();
        Incident__c newIncident = HMA_TestHelper.getIncident(false);
        newIncident.Name = 'COVID-19';
        newIncident.Eamil_To_Send__c = 'test@test.com';
        newIncident.Personnel_Email_IDs__c  = 'test1@test.com';
        insert newIncident;
        Order__c newOrder = PHOS_TestHelper.getOrder(true);
        EmailMessage newEmailMessage = new EmailMessage();
        newEmailMessage.Subject = 'New request submitted by RDMHS/Other User';
        newEmailMessage.ToAddress = 'test@gmail.com';
        newEmailMessage.CcAddress = 'testcc@gmail.com';
        newEmailMessage.RelatedToId = newOrder.Id;
        insert newEmailMessage;

        Order__c orderRec = [SELECT Id,(SELECT Subject, ToAddress, CcAddress, RelatedToId FROM Emails) FROM Order__c LIMIT 1];
        orderIds.add(orderRec.Id);

        Test.startTest();
        PHOS_SendEmail_Request_From_Other_User.sendEmail(orderIds);
        Test.stopTest();
    }
}