codepkg/objects/Incident_Subrecipient_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <description>This field represents the Stage of the Incident for a particular Sub - Recipient.</description>
        <inlineHelpText>This field represents the Stage of the Incident for a particular Sub - Recipient.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Financial Closeout - FPU In Progress</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout FPU - Closed</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - In Review</fullName>
                </value>
                <value>
                    <fullName>Financial Closeout - Awaiting FEMA Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Federal_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is the sum of the &quot;Total Federal Retention&quot; of all the Projects related to this Incident Sub Recipient Summary.</description>
        <inlineHelpText>This field is the sum of the &quot;Total Federal Retention&quot; of all the Projects related to this Incident Sub Recipient Summary.</inlineHelpText>
        <label>Total Federal Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Retention_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is the roll-up sum of &quot;Total Retention to Date&quot; of all the Projects related to this Incident Sub-Recipient Summary record.</description>
        <inlineHelpText>This field is the roll-up sum of &quot;Total Retention to Date&quot; of all the Projects related to this Incident Sub-Recipient Summary record.</inlineHelpText>
        <label>Total Retention To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_State_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is the sum of the &quot;Total State Retention&quot; of all the Projects related to this Incident Sub Recipient Summary.</description>
        <inlineHelpText>This field is the sum of the &quot;Total State Retention&quot; of all the Projects related to this Incident Sub Recipient Summary.</inlineHelpText>
        <label>Total State Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Incident Subrecipient Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Subrecipient Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incident Subrecipient summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The Stage of this program in its lifecycle</description>
        <inlineHelpText>What is the Stage is this Program?</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Federal_Project_Award_W_O_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Federal Project Award - Total Federal Retention on Project</description>
        <inlineHelpText>Federal Project Award - Total Federal Retention on Project</inlineHelpText>
        <label>Federal Project Award W/O Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Federal_Project_Award__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Federal Amount awarded to the Project.</description>
        <inlineHelpText>This is the Total Amount of money FEMA has awarded for this Project.</inlineHelpText>
        <label>Federal Project Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Federal_Retention_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Federal Retention To Date on Project</description>
        <inlineHelpText>Federal Retention To Date on Project</inlineHelpText>
        <label>Federal Retention To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incident_Subrecipient_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look Up to Incident Sub Recipient Summary which is having the same Sub Recipient and same Incident as the Project.</description>
        <inlineHelpText>Links to summary of all Projects within this Incident for this Subrecipient.</inlineHelpText>
        <label>Incident Subrecipient Summary</label>
        <referenceTo>Incident_Subrecipient_Stage__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Admin_Amount_Available__c</fullName>
        <description>Pending Admin Amount Available on the Project.</description>
        <formula>TotalProjectStateAdminShare__c -  Total_Admin_Amount_Approved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pending Admin Amount Available on the Project.
[ Total Project State Admin Share - Total Admin Amount Approved ]</inlineHelpText>
        <label>Pending Admin Amount Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Federal_Amount_Available__c</fullName>
        <description>Pending Federal Amount Available on the Project.</description>
        <formula>Federal_Project_Award__c -  ( Total_Federal_Amount_Approved__c + Federal_Retention_To_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pending Federal Amount Available on the Project.
[ Total Project Federal Award -  (Total Federal Amount Approved + Federal Retention To Date) ]</inlineHelpText>
        <label>Pending Federal Amount Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_State_Amount_Available__c</fullName>
        <description>Pending State Amount Available on the Project.</description>
        <formula>State_Project_Award__c - ( Total_State_Amount_Approved__c + State_Retention_To_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pending State Amount Available on the Project.
[ Total Project State Award - (Total State Amount Approved + State Retention To Date)]</inlineHelpText>
        <label>Pending State Amount Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Name, Derives from Disaster Grant/FO.</description>
        <inlineHelpText>The grant program from which the Project originates. This field is used for reporting.</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The Project Stage.</description>
        <inlineHelpText>The current processing stage of the Project. (e.g. New, Obligated, Compliance Verification, Payment, etc.)</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Obligating</fullName>
                    <label>Obligated</label>
                </value>
                <value>
                    <fullName>Compliance Verification</fullName>
                </value>
                <value>
                    <fullName>Active Payment</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Deobligation</fullName>
                    <isActive>false</isActive>
                    <label>Deobligation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Project_Award_W_O_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Project Award - Total State Retention on Project</description>
        <inlineHelpText>State Project Award - Total State Retention on Project</inlineHelpText>
        <label>State Project Award W/O Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Project_Award__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total State Amount awarded to the Project.</description>
        <inlineHelpText>This is the portion of Total Project Award that the State will award to the Subrecipient.</inlineHelpText>
        <label>State Project Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Retention_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Retention To Date on Project</description>
        <inlineHelpText>State Retention To Date on Project</inlineHelpText>
        <label>State Retention To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalProjectStateAdminShare__c</fullName>
        <description>Project Amount awarded by State Admin.</description>
        <formula>IF( AND( OR(ISPICKVAL( FundingSource__c , &apos;State Only&apos;), ISPICKVAL( FundingSource__c , &apos;Federal and State&apos;)) ,ISPICKVAL(  EligibleforStateAdminShare__c , &apos;Yes&apos;),ISPICKVAL(  PaytoStateAdmin__c , &apos;Yes&apos;)) ,   State_Project_Award__c  * StateAdmin__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is an additional amount the State awards the Subrecipient to help with administrative costs. Admin Share = State Project Award x 0.10, or an additional 10% of the State Project Award</inlineHelpText>
        <label>Total Project State Admin Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Federal_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Federal Retention.[ Federal Project Amount * Federal Retention% ]</description>
        <inlineHelpText>Total Federal Retention.[ Federal Project Amount * Federal Retention% ]</inlineHelpText>
        <label>Total Federal Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Project_Award__c</fullName>
        <description>The Total Amount Awarded by FEMA for the cost of the project.</description>
        <inlineHelpText>This is the total cost of the approved Project. Any cost share percentage calculations start from this value.</inlineHelpText>
        <label>Total Project Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Retention_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Retention To Date on Project</description>
        <inlineHelpText>Total Retention To Date on Project</inlineHelpText>
        <label>Total Retention To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_State_Retention__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;Total State Retention.
[ State Project Amount * State Retention% ]&quot;</description>
        <inlineHelpText>&quot;Total State Retention.
[ State Project Amount * State Retention% ]&quot;</inlineHelpText>
        <label>Total State Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/REAL_UpdateIncSubSummaryRollUpFieldsJob.cls
/***********************************************************************************************************************************
* Class Name   : REAL_UpdateIncSubSummaryRollUpFieldsJob
* Description  : This batch class is created to update the Custom Roll Up fields on Incident Sub Recipient Summary records.
* Author       : Ricky 
* Created On   : 17/07/2020
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Ricky              17/07/2020       Initial Implementation
**************************************************************************************************************************************/

public with sharing class REAL_UpdateIncSubSummaryRollUpFieldsJob  implements Database.Batchable<sObject>, Schedulable {
    private final String query;

    public REAL_UpdateIncSubSummaryRollUpFieldsJob(String query) {
        this.query = query;
    }

    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new REAL_UpdateIncSubSummaryRollUpFieldsJob(query));
    }

    // Database.Batchable methods
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Incident_Subrecipient_Stage__c> summaryList = (List<Incident_Subrecipient_Stage__c>) scope;
        Set<Id> summaryIds = new Set<Id>();
        for (Incident_Subrecipient_Stage__c summary : summaryList) {
            summaryIds.add(summary.Id);
        }
        List<AggregateResult> results = [SELECT Incident_Subrecipient_Summary__c ,
                                                    SUM(Net_Federal_Amount_Available__c)FederalAmountAvailable,
                                                    SUM(Net_State_Amount_Available__c)StateAmountAvailable,
                                                    SUM(Net_Admin_Amount_Available__c)AvailableAdminAmount,
                                                    SUM(Total_Project_Award__c)TotalProjectAward,
                                                    SUM(Federal_Project_Award__c)FederalProjectAward,
                                                    SUM(State_Project_Award__c)StateProjectAward,
                                                    SUM(TotalProjectStateAdminShare__c)StateAdminShare,
                                                    SUM(Federal_Retention_To_Date__c)FederalRetentionToDate,
                                                    SUM(State_Retention_To_Date__c)StateRetentionToDate,
                                                    SUM(Total_Retention_To_Date__c)TotalRetentionToDate,
                                                    SUM(Total_Federal_Retention__c)TotalFederalRetention,
                                                    SUM(Total_State_Retention__c)TotalStateRetention,
                                                    SUM(Federal_Project_Award_W_O_Retention__c)FederalAwardWithRetention,
                                                    SUM(State_Project_Award_W_O_Retention__c)StateAwardWithoutRetention
                                            FROM Project__c
                                            WHERE Incident_Subrecipient_Summary__c IN : summaryIds AND
                                            Stage__c !=: ALS_CONSTANTS.Project_Stage_Withdrawn
                                            GROUP BY Incident_Subrecipient_Summary__c];

        // Fetching the aggregate result for the Project which are of PA programs.
        List<AggregateResult> paResults = [SELECT Incident_Subrecipient_Summary__c, SUM(Federal_Project_Award__c)PaFederalProjectAward,
                                                    SUM(State_Project_Award__c)PaStateProjectAward,
                                                    SUM(TotalProjectStateAdminShare__c)PaAdminProjectAward
                                            FROM Project__c WHERE Incident_Subrecipient_Summary__c IN : summaryIds
                                            AND Stage__c !=: ALS_CONSTANTS.Project_Stage_Withdrawn
                                            AND (Program_Name__r.Parent_Program__r.Master_Label_Program_Name__c =: ALS_CONSTANTS.Program_PA
                                            OR Program_Name__r.Parent_Program__r.Master_Label_Program_Name__c =: ALS_CONSTANTS.Program_PA_StateOnly)
                                            GROUP BY Incident_Subrecipient_Summary__c];
        // Collection to collect the Aggregate result in order of Summary id as key and aggregate result record as value.
        Map<Id, AggregateResult> summaryIdToPaSummaryRecordMap = new Map<Id, AggregateResult>();
        if (paResults?.size() > 0) {
            for (AggregateResult aggResult :paResults) {
                Id summaryId = (Id)aggResult.get('Incident_Subrecipient_Summary__c');
                summaryIdToPaSummaryRecordMap.put(summaryId, aggResult);
            }
        }

        List<Incident_Subrecipient_Stage__c> stageRecordsToUpdate = new List<Incident_Subrecipient_Stage__c>();
        for(AggregateResult aggResult : results) {
            Id summaryId = (Id)aggResult.get('Incident_Subrecipient_Summary__c');
            Incident_Subrecipient_Stage__c stageRecord = new Incident_Subrecipient_Stage__c();
            stageRecord.Id = summaryId;
            Decimal federalAmountAvailable = (Decimal)aggResult?.get('FederalAmountAvailable');
            Decimal stateAmountAvailable = (Decimal)aggResult?.get('StateAmountAvailable');
            Decimal adminAmountAvailable = (Decimal)aggResult?.get('AvailableAdminAmount');

            Decimal totalProjectAward = (Decimal)aggResult?.get('TotalProjectAward');
            Decimal federalProjectAward = (Decimal)aggResult?.get('FederalProjectAward');
            Decimal stateProjectAward = (Decimal)aggResult?.get('StateProjectAward');
            Decimal stateAdminShare = (Decimal)aggResult?.get('StateAdminShare');
            Decimal federalRetentionToDate = (Decimal)aggResult?.get('FederalRetentionToDate');
            Decimal stateRetentionToDate = (Decimal)aggResult?.get('StateRetentionToDate');

            Decimal TotalRetentionToDate = (Decimal)aggResult?.get('TotalRetentionToDate');
            Decimal TotalFederalRetention = (Decimal)aggResult?.get('TotalFederalRetention');
            Decimal TotalStateRetention = (Decimal)aggResult?.get('TotalStateRetention');
            Decimal FederalAwardWithRetention = (Decimal)aggResult?.get('FederalAwardWithRetention');
            Decimal StateAwardWithoutRetention = (Decimal)aggResult?.get('StateAwardWithoutRetention');

            stageRecord.Available_Federal_Amount__c = (federalAmountAvailable == null?0.00:federalAmountAvailable).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Available_State_Amount__c = (stateAmountAvailable == null?0.00:stateAmountAvailable).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Available_State_Admin_Amount__c = (adminAmountAvailable == null?0.00:adminAmountAvailable).setScale(2,system.RoundingMode.DOWN);

            stageRecord.Total_Amount_Obligated__c = (totalProjectAward == null?0.00:totalProjectAward).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Total_Federal_Amount_Obligated__c = (federalProjectAward == null?0.00:federalProjectAward).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Total_State_Amount_Obligated__c = (stateProjectAward == null?0.00:stateProjectAward).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Total_Admin_Amount_Obligated__c = (stateAdminShare == null?0.00:stateAdminShare).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Total_Federal_Retention_to_Date__c = (federalRetentionToDate == null?0.00:federalRetentionToDate).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Total_State_Retention_to_Date__c = (stateRetentionToDate == null?0.00:stateRetentionToDate).setScale(2,system.RoundingMode.DOWN);

            stageRecord.Total_Retention_To_Date__c = (TotalRetentionToDate == null?0.00:TotalRetentionToDate).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Total_Federal_Retention__c = (TotalFederalRetention == null?0.00:TotalFederalRetention).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Total_State_Retention__c = (TotalStateRetention == null?0.00:TotalStateRetention).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Total_Federal_Award_W_O_Retention__c = (FederalAwardWithRetention == null?0.00:FederalAwardWithRetention).setScale(2,system.RoundingMode.DOWN);
            stageRecord.Total_State_Award_W_O_Retention__c = (StateAwardWithoutRetention == null?0.00:StateAwardWithoutRetention).setScale(2,system.RoundingMode.DOWN);

            // Fetching the Aggregate Result for PA Project in order to update PA Roll Ups on Summary record.
            AggregateResult paResult = summaryIdToPaSummaryRecordMap?.get(summaryId);
            // Fetching the values from Aggregate Result record for PA projects...
            Decimal paFederalProjectAward = (Decimal)paResult?.get('PaFederalProjectAward');
            Decimal paStateProjectAward = (Decimal)paResult?.get('PaStateProjectAward');
            Decimal paAdminProjectAward = (Decimal)paResult?.get('PaAdminProjectAward');

            stageRecord.PA_Federal_Amount_Obligated__c = (paFederalProjectAward == null?0.00: paFederalProjectAward).setScale(2,system.RoundingMode.DOWN);
            stageRecord.PA_State_Amount_Obligated__c = (paStateProjectAward == null?0.00: paStateProjectAward).setScale(2,system.RoundingMode.DOWN);
            stageRecord.PA_State_Admin_Amount_Obligated__c = (paAdminProjectAward == null?0.00: paAdminProjectAward).setScale(2,system.RoundingMode.DOWN);

            stageRecordsToUpdate.add(stageRecord);
        }
        if (stageRecordsToUpdate?.size() > 0) {
            update stageRecordsToUpdate;
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}