codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Eamil_To_Send__c</fullName>
        <description>Put comma separated email ids</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Put comma separated email ids</inlineHelpText>
        <label>Email IDs To Send</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Personnel_Email_IDs__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Personnel Email IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Name</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Personnel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Personnel</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>CASF-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/PHOS_SendEmailRequestForIncidentsTest.cls
@isTest(seeAllData=false)
public class PHOS_SendEmailRequestForIncidentsTest {
    @IsTest
    static void testSendEmail(){
        test.StartTest();
        Incident__c newIncident = new Incident__c(Name='COVID-19',Eamil_To_Send__c = 'test@gmail.com',isActive__c =true,
                                                 	Personnel_Email_IDs__c = 'test56@gmail.com');
        insert newIncident;
        List<Id> newOrderList = new List<Id>();
        Order__c newOrder = PHOS_TestHelper.getOrder(false);
        newOrder.Incident__c = newIncident.Id;
        newOrder.Personnel__c = true;
        insert newOrder;
        newOrderList.add(newOrder.Id);
        EmailMessage newEmail = new EmailMessage();
        newEmail.FromAddress = 'test134@gmail.com';
        newEmail.ToAddress = 'test123@gmail.com';
        newEmail.FromName = 'test';
        newEmail.CcAddress = 'test12@gmail.com';
        newEmail.RelatedToId = newOrder.Id;
        newEmail.Subject = 'New request submitted by';
        insert newEmail;
        
        PHOS_SendEmail_Request_For_Incidents.sendEmail(newOrderList);
        test.StopTest();
    }
    @IsTest public static void testFormatPlainBody(){
        Test.startTest();
        PHOS_SendEmail_Request_For_Incidents.formatPlainBody('this is first, email.');                                                            
        Test.stopTest();
    }
}