codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>Federal Incident Declaration Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Incident Declaration Number. DR number if a Major Disaster, CDAA Number if CDAA-Only, etc.</inlineHelpText>
        <label>Declaration Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/objects/Incident_Subrecipient_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Sub - Recipient  to which this junction record is related.</description>
        <inlineHelpText>Sub - Recipient  to which this junction record is related.</inlineHelpText>
        <label>Sub Recipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Incident_Subrecipient_Stages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <description>&quot;Declaration Number&quot; of the Incident.</description>
        <formula>Incident__r.Declaration_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Declaration Number&quot; of the Incident.</inlineHelpText>
        <label>Declaration Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FIPS__c</fullName>
        <description>&quot;FIPS ID&quot; of the Sub Recipient.</description>
        <formula>Account__r.Sub_Recipient_FIPS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;FIPS ID&quot; of the Sub Recipient.</inlineHelpText>
        <label>FIPS</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <description>Incident to which this junction is related.</description>
        <inlineHelpText>Incident to which this junction is related.</inlineHelpText>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipName>Incident_sub_recipient_stage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Incident Subrecipient Summary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Subrecipient Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incident Subrecipient summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Transmittal__c.object
<CustomObject>
    <description>To store the Transmittal of Payment request.</description>
    <label>Transmittal</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transmittal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transmittals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/REAL_IncSubSummaryUtility.cls
/***********************************************************************************************************************************
* Class Name   : REAL_IncSubSummaryUtility
* Description  : Incident Sub Recipient Summary Utility.
* Author       : Ricky
* Created On   : 19/07/2021
* Modification Log :
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Ricky              19/07/2021       Initial Implementation
**************************************************************************************************************************************/

public with sharing class REAL_IncSubSummaryUtility {
    /*********************************************
	* Method Name : updateSummaryName
	* Author : Ricky
	* Inputs : - 1.List<Transmittal__c> transmittalList -
	* Description: This method is used send the Transmittal record for Approval.
	*********************************************/
    public void  updateSummaryName(List<Id> incidentIds, List<Id> subRecipientIds) {
        String query = 'SELECT Id, Name, Account__c, FIPS__c, Incident__c, Declaration_Number__c FROM Incident_Subrecipient_Stage__c';
        if (incidentIds?.size() > 0
                && !(subRecipientIds?.size() > 0)) {
            //String incidentIdString = inClausify(incidentIds);
            //query += 'WHERE Incident__c IN : incidentIdString';
            query += ' WHERE Incident__c IN : incidentIds';
        }
        else if (subRecipientIds?.size() > 0
                && !(incidentIds?.size() > 0)) {
            //String subRecipientIdString = inClausify(subRecipientIds);
            //query += ' WHERE Account__c IN : subRecipientIdString';
            query += ' WHERE Account__c IN : subRecipientIds';
        }
        else if (incidentIds?.size() > 0
                && subRecipientIds?.size() > 0) {
            //String incidentIdString = inClausify(incidentIds);
            //String subRecipientIdString = inClausify(subRecipientIds);
            //query += ' WHERE Account__c IN : subRecipientIdString OR Incident__c IN : incidentIdString';
            query += ' WHERE Account__c IN : subRecipientIds OR Incident__c IN : incidentIds';
        }
        List<Incident_Subrecipient_Stage__c> summaryList = Database.query(query);
        if (summaryList?.size() > 0) {
            for (Incident_Subrecipient_Stage__c summary : summaryList) {
                String summaryName = '';
                if (summary.Declaration_Number__c != null) {
                    summaryName += summary.Declaration_Number__c;
                }
                if (summary.FIPS__c != null
                        && (summaryName != null && summaryName != '')) {
                    summaryName += ('-(' + summary.FIPS__c + ')');
                }
                else if(summary.FIPS__c != null
                        && (summaryName == null || summaryName == '')) {
                    summaryName += summary.FIPS__c;
                }
                summary.Name = summaryName;
            }

            update summaryList;
        }
    }

    /*********************************************
	* Method Name : inClausify
	* Author : Ricky
	* Inputs : - 1. List<Id> ids -
	* Description: This method is used send the Transmittal record for Approval.
	*********************************************/
    public static String inClausify (List<Id> recordIds) {
        String inClause = String.format( '(\'\'{0}\'\')',
                new List<String> { String.join( new List<Id>(recordIds) , '\',\'') });
        return inClause;
    }
}