codepkg/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Available_for_Application__c</fullName>
        <label>Available for Application</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PHOS</fullName>
                </value>
                <value>
                    <fullName>HMA</fullName>
                </value>
                <value>
                    <fullName>MARS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incident_End_Date__c</fullName>
        <description>Date the Incident Ended</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date the Incident or Event Ended</inlineHelpText>
        <label>Incident End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incident_Start_Date__c</fullName>
        <description>Date the Incident Started or Occurred</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date the Incident Started or Occurred.</inlineHelpText>
        <label>Incident Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Order No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

codepkg/classes/MARS_Incident_Search_Ctrl_Test.cls
@isTest
private class MARS_Incident_Search_Ctrl_Test {
	@isTest
    static void getIncidentListTest(){
        Incident__c newIncident = new Incident__c();
        newIncident.Name='test'; 
        newIncident.isActive__c=true; 
        newIncident.Incident_Start_Date__c=System.today(); 
        newIncident.Incident_End_Date__c=System.today().addDays(2);
        newIncident.Available_for_Application__c = 'MARS';
        newIncident.Order_No__c = '12234';
        insert newIncident;
        
        MARS_Incident_Search_Ctrl.getIncidentList('test');
        MARS_Incident_Search_Ctrl.getIncidentListByNumber('12234');
    }

}