codepkg/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Warehouse_Product__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Inventory__c</fullName>
        <label>Remaining Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU_Id__c</fullName>
        <description>SKU ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SKU Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Available_Inventory__c</fullName>
        <label>Total Available Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Warehouse_Code_And_SKU_Id__c</fullName>
        <description>This is external Id field. It is a combination of Warehouse code and SKU Id. It is joined by &quot;_&quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Warehouse Code And SKU Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Warehouse_Code__c</fullName>
        <description>Warehouse Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Warehouse Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to warehouse product.</description>
        <label>Warehouse Product</label>
        <referenceTo>Warehouse_Product__c</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <formula>Warehouse_Product__r.Warehouse__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Warehouse</label>
        <type>Text</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Creator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Creator Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders(Custom) (Creator Contact)</relationshipLabel>
        <relationshipName>Orders_Custom1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Describe Mission/Tasks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>MHOAC Review</fullName>
                </value>
                <value>
                    <fullName>RDMHS Review</fullName>
                </value>
                <value>
                    <fullName>CDPH Resource Request Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>CDPH Resource Analyst Review</fullName>
                </value>
                <value>
                    <fullName>Allocation Review</fullName>
                </value>
                <value>
                    <fullName>Deployment Team</fullName>
                </value>
                <value>
                    <fullName>CDPH Pharmacy Consultant Review</fullName>
                    <label>MAC Group Review</label>
                </value>
                <value>
                    <fullName>Analyst Final Review</fullName>
                </value>
                <value>
                    <fullName>Staffing in Progress</fullName>
                </value>
                <value>
                    <fullName>Unfulfilled - Referred</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled - Referred</fullName>
                </value>
                <value>
                    <fullName>Unfulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Denied</fullName>
                </value>
                <value>
                    <fullName>Fulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>CASF-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fulfilment_Entity_Warehouse__c</fullName>
        <label>Fulfilment Entity / Warehouse</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Filled Locally/Regionally</fullName>
                </value>
                <value>
                    <fullName>Dixon</fullName>
                </value>
                <value>
                    <fullName>CDPH Depot (NEXGEN)</fullName>
                </value>
                <value>
                    <fullName>CDPH West Sacramento (NEXGEN)</fullName>
                </value>
                <value>
                    <fullName>Personnel</fullName>
                </value>
                <value>
                    <fullName>Citrus</fullName>
                </value>
                <value>
                    <fullName>Color</fullName>
                </value>
                <value>
                    <fullName>OES Dixon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Filled__c</fullName>
        <label>Quantity Filled</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Warehouse_Info__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Warehouse SKU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <displayFormat>OP-{00000000}</displayFormat>
        <label>Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Warehouse_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Shipment_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Shipment Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Warehouse Config</label>
    <pluralLabel>Warehouse Configs</pluralLabel>
</CustomObject>

codepkg/objects/Warehouse_Product__c.object
<CustomObject>
    <description>Junction between warehouse and and Product. Mulesoft will send warehouse code and SKU code. We have flow which will populate lookup values based on it.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>check if warehouse Product is active</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_To_Warehouse_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warehouse_Code_And_SKU_Id__c</fullName>
        <description>Format  - WarehouseCode_SKUId</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>It should be concat of Warehouse code and SKU Id joined by -</inlineHelpText>
        <label>Warehouse Code And SKU Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse_Code__c</fullName>
        <description>Warehouse code populate from Mulesoft. Warehouse lookup will be populated from it.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Warehouse Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse_SKU_Id__c</fullName>
        <description>SKU Id from Product</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>SKU Id from Product. Based on it Product lookup will populate</inlineHelpText>
        <label>Warehouse SKU Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Warehouse</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_To_Warehouse_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Warehouse Product</label>
    <nameField>
        <displayFormat>WP-{0000}</displayFormat>
        <label>Warehouse Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warehouse Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/Order_ProductsEditCtrlTest.cls
/**
 * Created by PREM on 31-07-2020.
 */

@isTest
public class Order_ProductsEditCtrlTest {
    @isTest 
    public static void testGetProducts(){
        User newUser = PHOS_TestHelper.getUser(true);
        System.runAs(newUser){
            //Account newAccount = new Account();
            //insert newAccount;
            Map<String,Object> returnMap = new Map<String,Object>();
            Product2 product = PHOS_TestHelper.getProductGoggles(true);
            Test.startTest();
            returnMap = Order_ProductsEditCtrl.getProducts();
            System.assert(returnMap.size()>0);
            Test.stopTest();
        }
    }
    @isTest 
    public static void testGetOrderProductDetails(){
        List<String> fieldAPINameList = new List<String>();
        Map<String,Object> returnMap = new Map<String,Object>();
        Order__c newOrder = PHOS_TestHelper.getOrder(true);


        String orderId = String.valueOf(newOrder.Id);
        fieldAPINameList.add('Description__c');
        String fieldAPINames = JSON.serialize(fieldAPINameList);
        Test.startTest();
        returnMap = Order_ProductsEditCtrl.getOrderProductDetails(orderId, fieldAPINames);
        System.assert(returnMap.size()>0);
        Test.stopTest();
    }

    @isTest 
    public static void testSaveOrderItems(){
        List<User> newUserList = [SELECT Id,Name from User LIMIT 1];
        for(User newUser : newUserList){
            List<UserAppInfo> userAppInfoList =  [SELECT Id, AppDefinitionId FROM UserAppInfo WHERE UserId = :newUser.Id LIMIT 1] ;
            if(!userAppInfoList.isEmpty()){
                System.runAs(newUser){
                    Map<String, Object> paramMap = new Map<String, Object>();
                    List<Order_Product__c> orderItems = new List<Order_Product__c>();
                    Contact newContact = PHOS_TestHelper.getContact(true);
                    Order__c newOrder = PHOS_TestHelper.getOrder(false);
                    newOrder.CreatedById = newUser.Id;
                    newOrder.Requestor__c = newContact.Id;
                    insert newOrder;
                    Product2 product = PHOS_TestHelper.getProductGoggles(true);
                    Order_Product__c newOrderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
                    newOrderItemgoggle.Order__c = newOrder.Id;
                    newOrderItemgoggle.Product__c = product.Id;
                    insert newOrderItemgoggle;
                    orderItems.add(newOrderItemgoggle);
                    paramMap.put('OrderItems', JSON.serialize(orderItems));
                    paramMap.put('Order__c', newOrder.Id);
                    Test.startTest();
                    Map<String, Object> returnMap = Order_ProductsEditCtrl.saveOrderItems(paramMap);
                    system.assert(returnMap.size()>0);
                    Test.stopTest();

                }

            }
            break;
        }

    }

    @isTest 
    public static void testGetFieldDetails(){
        List<Order_ProductsEditCtrl.FieldDetails> returnDetailsList = new List<Order_ProductsEditCtrl.FieldDetails>();
        List<Order_ProductsEditCtrl.FieldDetails> fieldDetailsList = new List<Order_ProductsEditCtrl.FieldDetails>();
        Order_ProductsEditCtrl.FieldDetails fieldDetails = new Order_ProductsEditCtrl.FieldDetails();

        fieldDetails.APIName = 'Name';
        fieldDetails.Label= 'Product Name';
        fieldDetails.fieldType = 'PICKLIST';
        fieldDetails.isRequired = null;
        fieldDetails.isDisabled = null;
        fieldDetails.enablePostSent = null;
        fieldDetails.OnChangeFormula = null;
        fieldDetailsList.add(fieldDetails);
        Product2 newProductMask = PHOS_TestHelper.getProductMask(true);
        string fieldsJSON = JSON.serialize(fieldDetailsList);
        String objectName = JSON.serialize(newProductMask);
        Test.startTest();
        returnDetailsList = Order_ProductsEditCtrl.getFieldDetails(fieldsJSON , 'Product2');
        System.assert(returnDetailsList.size()>0);
        Test.stopTest();
    }
    
    /*@isTest(SeeAllData=true) 
    public static void testSaveOrderItemsnew(){
        Map<String, Object> paramMap = new Map<String, Object>();
        List<Order_Product__c> orderItems = new List<Order_Product__c>();
        //Order_ProductsEditGetAccountTest.getAccountData();
        //system.assert(false,'warehouseAcc--'+warehouseAcc);
        Contact newContact = PHOS_TestHelper.getContact(true);
        Order__c newOrder = PHOS_TestHelper.getOrder(false);
        newOrder.Requestor__c = newContact.Id;
        insert newOrder;
        Product2 product = PHOS_TestHelper.getProductGoggles(true);
        Order_Product__c newOrderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        newOrderItemgoggle.Order__c = newOrder.Id;
        newOrderItemgoggle.Product__c = product.Id;
        newOrderItemgoggle.Fulfilment_Entity_Warehouse__c ='';
        insert newOrderItemgoggle;
        
        Product2 product1 = PHOS_TestHelper.getProductMask(true);
        Order_Product__c newOrderItemMask = PHOS_TestHelper.getOrderItemmask(false);
        newOrderItemMask.Order__c = newOrder.Id;
        newOrderItemMask.Product__c = product1.Id;
        newOrderItemMask.Status__c = 'Sent';
        insert newOrderItemMask;
        orderItems.add(newOrderItemMask);
        
        paramMap.put('OrderItems', JSON.serialize(orderItems));
        paramMap.put('Order__c', newOrder.Id);
        Test.startTest();
        Map<String, Object> returnMap = Order_ProductsEditCtrl.saveOrderItems(paramMap);
        system.assert(returnMap.size()>0);
        Test.stopTest();               
   }*/
    
    @isTest(SeeAllData=true) 
    public static void testSaveOrderItemsFillQty(){
        Map<String, Object> paramMap = new Map<String, Object>();
        List<Order_Product__c> orderItems = new List<Order_Product__c>();
        Warehouse_Config__mdt wareHouseData = [Select Id,Account_Id__c,isActive__c,Send_Email__c,DeveloperName,MasterLabel,Create_Shipment_Order__c
                                                        from Warehouse_Config__mdt where MasterLabel = 'West Sacramento' LIMIT 1];
        
        system.debug('wareHuseData---------'+wareHouseData);
        Account newAccount = [Select Id,Name,Entity_Id__c FROM Account where Id =: wareHouseData.Account_Id__c];
        
        Contact newContact = PHOS_TestHelper.getContact(true);
        User getUser = PHOS_TestHelper.getUser(true);
        Order__c newOrder = PHOS_TestHelper.getOrder(false);
        newOrder.Requestor__c = newContact.Id;
        newOrder.Requestor__c = newContact.id;
        newOrder.CreatedById = getUser.Id;
        newOrder.Creator_Contact__c = newContact.id;
        newOrder.Account__c = newContact.AccountId;
        insert newOrder;
        Product2 product = PHOS_TestHelper.getProductGoggles(true);
        Order_Product__c newOrderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        newOrderItemgoggle.Order__c = newOrder.Id;
        newOrderItemgoggle.Product__c = product.Id;
        newOrderItemgoggle.Fulfilment_Entity_Warehouse__c ='West Sacramento';
        newOrderItemgoggle.Quantity_Filled__c = 5;
        newOrderItemgoggle.Warehouse_Info__c = 'test';
        insert newOrderItemgoggle;
        orderItems.add(newOrderItemgoggle);
        
        Product2 product1 = PHOS_TestHelper.getProductMask(true);
        Order_Product__c newOrderItemMask = PHOS_TestHelper.getOrderItemmask(false);
        newOrderItemMask.Order__c = newOrder.Id;
        newOrderItemMask.Product__c = product1.Id;
        newOrderItemMask.Fulfilment_Entity_Warehouse__c = 'West Sacramento';
        newOrderItemMask.Quantity_Filled__c = 15;
        insert newOrderItemMask;
        orderItems.add(newOrderItemMask);
       
        Warehouse_Product__c warehouseProduct = new Warehouse_Product__c();
        warehouseProduct.Product__c = product.Id;
        warehouseProduct.Warehouse__c = newAccount.Id;
        warehouseProduct.Is_Active__c = true;
        warehouseProduct.Warehouse_SKU_Id__c = newAccount.Entity_Id__c;
        warehouseProduct.Warehouse_Code__c = 'CV24';
        warehouseProduct.Warehouse_SKU_Id__c = 'p-21312';
        warehouseProduct.Warehouse_Code_And_SKU_Id__c = newAccount.Entity_Id__c + 'test';
        insert warehouseProduct;
        
        Inventory__c inventory = new Inventory__c();
        inventory.Warehouse_Product__c = warehouseProduct.Id;
        inventory.Warehouse_Code__c = 'CV12';
        inventory.SKU_Id__c = 'test';
        inventory.Warehouse_Code_And_SKU_Id__c = newAccount.Entity_Id__c + 'test';
        inventory.Remaining_Inventory__c = 1200000;
        inventory.Total_Available_Inventory__c = 1200000;
        insert inventory;
        
        
        paramMap.put('OrderItems', JSON.serialize(orderItems));
        paramMap.put('Order__c', newOrder.Id);
        Test.startTest();
        Map<String, Object> returnMap = Order_ProductsEditCtrl.saveOrderItems(paramMap);
        system.assert(returnMap.size()>0);
        Test.stopTest();               
   }
    
    @isTest(SeeAllData=true) 
    public static void testSaveOrderItemsNoSKU(){
        Map<String, Object> paramMap = new Map<String, Object>();
        List<Order_Product__c> orderItems = new List<Order_Product__c>();
                Warehouse_Config__mdt wareHouseData = [Select Id,Account_Id__c,isActive__c,Send_Email__c,DeveloperName,MasterLabel,Create_Shipment_Order__c
                                                        from Warehouse_Config__mdt where MasterLabel = 'West Sacramento' LIMIT 1];
        
        system.debug('wareHuseData---------'+wareHouseData);
        Account newAccount = [Select Id,Name,Entity_Id__c FROM Account where Id =: wareHouseData.Account_Id__c];
        
        Contact newContact = PHOS_TestHelper.getContact(true);
        User getUser = PHOS_TestHelper.getUser(true);
        Order__c newOrder = PHOS_TestHelper.getOrder(false);
        newOrder.Requestor__c = newContact.Id;
        newOrder.Requestor__c = newContact.id;
        newOrder.CreatedById = getUser.Id;
        newOrder.Creator_Contact__c = newContact.id;
        newOrder.Account__c = newContact.AccountId;
        insert newOrder;

        Product2 product = PHOS_TestHelper.getProductGoggles(true);
        Order_Product__c newOrderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        newOrderItemgoggle.Order__c = newOrder.Id;
        newOrderItemgoggle.Product__c = product.Id;
        newOrderItemgoggle.Fulfilment_Entity_Warehouse__c ='West Sacramento';
        newOrderItemgoggle.Quantity_Filled__c = 15;
        newOrderItemgoggle.Warehouse_Info__c = 'test';
        insert newOrderItemgoggle;
        
        Warehouse_Product__c warehouseProduct = new Warehouse_Product__c();
        warehouseProduct.Product__c = product.Id;
        warehouseProduct.Warehouse__c = newAccount.Id;
        warehouseProduct.Is_Active__c = true;
        warehouseProduct.Warehouse_SKU_Id__c = newAccount.Entity_Id__c;
        warehouseProduct.Warehouse_Code__c = 'CV12';
        warehouseProduct.Warehouse_SKU_Id__c = 'p-21312';
        warehouseProduct.Warehouse_Code_And_SKU_Id__c = newAccount.Entity_Id__c + 'test';
        insert warehouseProduct;

        Inventory__c inventory = new Inventory__c();
        inventory.Warehouse_Product__c = warehouseProduct.Id;
        inventory.Warehouse_Code__c = 'CV12';
        inventory.SKU_Id__c = 'test';
        inventory.Warehouse_Code_And_SKU_Id__c = newAccount.Entity_Id__c + 'test';
        inventory.Remaining_Inventory__c = 1200000;
        inventory.Total_Available_Inventory__c = 1200000;
        insert inventory;
        
        
        orderItems.add(newOrderItemgoggle);
        paramMap.put('OrderItems', JSON.serialize(orderItems));
        paramMap.put('Order__c', newOrder.Id);
        Test.startTest();
        Map<String, Object> returnMap = Order_ProductsEditCtrl.saveOrderItems(paramMap);
        system.assert(returnMap.size()>0);
        Test.stopTest();               
    }
    
   /* @isTest(SeeAllData=true) 
    public static void testSaveOrderItemsNoWarehouse(){
        Map<String, Object> paramMap = new Map<String, Object>();
        List<Order_Product__c> orderItems = new List<Order_Product__c>();
        Contact newContact = PHOS_TestHelper.getContact(true);
        Order__c newOrder = PHOS_TestHelper.getOrder(false);
        newOrder.Requestor__c = newContact.Id;
        insert newOrder;
        Product2 product = PHOS_TestHelper.getProductGoggles(true);
        Order_Product__c newOrderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        newOrderItemgoggle.Order__c = newOrder.Id;
        newOrderItemgoggle.Product__c = product.Id;
        //newOrderItemgoggle.Quantity_Filled__c = 10;
        newOrderItemgoggle.Fulfilment_Entity_Warehouse__c = 'West Sacramento';
        insert newOrderItemgoggle;
        orderItems.add(newOrderItemgoggle);
        Product2 product1 = PHOS_TestHelper.getProductMask(true);
        Order_Product__c newOrderItemMask = PHOS_TestHelper.getOrderItemmask(false);
        newOrderItemMask.Order__c = newOrder.Id;
        newOrderItemMask.Product__c = product1.Id;
        newOrderItemMask.Fulfilment_Entity_Warehouse__c = 'West Sacramento' ;
        insert newOrderItemMask;
        orderItems.add(newOrderItemMask);
        paramMap.put('OrderItems', JSON.serialize(orderItems));
        paramMap.put('Order__c', newOrder.Id);
        Test.startTest();
        Map<String, Object> returnMap = Order_ProductsEditCtrl.saveOrderItems(paramMap);
        system.assert(returnMap.size()>0);
        Test.stopTest();               
    }*/
    
    @isTest(SeeAllData=true) 
    public static void testSaveOrderItemInvLessQty(){
        Map<String, Object> paramMap = new Map<String, Object>();
        List<Order_Product__c> orderItems = new List<Order_Product__c>();
        Warehouse_Config__mdt wareHouseData = [Select Id,Account_Id__c,isActive__c,Send_Email__c,DeveloperName,MasterLabel,Create_Shipment_Order__c
                                                        from Warehouse_Config__mdt where MasterLabel = 'West Sacramento' LIMIT 1];
        
        system.debug('wareHuseData---------'+wareHouseData);
        Account newAccount = [Select Id,Name,Entity_Id__c FROM Account where Id =: wareHouseData.Account_Id__c];
        
        Contact newContact = PHOS_TestHelper.getContact(true);
        User getUser = PHOS_TestHelper.getUser(true);
        Order__c newOrder = PHOS_TestHelper.getOrder(false);
        newOrder.Requestor__c = newContact.Id;
        newOrder.Requestor__c = newContact.id;
        newOrder.CreatedById = getUser.Id;
        newOrder.Creator_Contact__c = newContact.id;
        newOrder.Account__c = newContact.AccountId;
        insert newOrder;
        Product2 product = PHOS_TestHelper.getProductGoggles(true);
        Order_Product__c newOrderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        newOrderItemgoggle.Order__c = newOrder.Id;
        newOrderItemgoggle.Product__c = product.Id;
        newOrderItemgoggle.Unit_Price__c = null;
        newOrderItemgoggle.Fulfilment_Entity_Warehouse__c ='West Sacramento';
        newOrderItemgoggle.Quantity_Filled__c = 1500;
        newOrderItemgoggle.Warehouse_Info__c = 'test';
        insert newOrderItemgoggle;
        orderItems.add(newOrderItemgoggle);
        
        Product2 product1 = PHOS_TestHelper.getProductMask(true);
        Order_Product__c newOrderItemMask = PHOS_TestHelper.getOrderItemmask(false);
        newOrderItemMask.Order__c = newOrder.Id;
        newOrderItemMask.Product__c = product1.Id;
        newOrderItemMask.Fulfilment_Entity_Warehouse__c = PHOS_Constants.FILLED_REGIONALLY_STATUS;
        newOrderItemMask.Quantity_Filled__c = 1200;
        insert newOrderItemMask;
        orderItems.add(newOrderItemMask);
       
        Warehouse_Product__c warehouseProduct = new Warehouse_Product__c();
        warehouseProduct.Product__c = product.Id;
        warehouseProduct.Warehouse__c = newAccount.Id;
        warehouseProduct.Is_Active__c = true;
        warehouseProduct.Warehouse_SKU_Id__c = newAccount.Entity_Id__c;
        warehouseProduct.Warehouse_Code__c = 'CV12';
        warehouseProduct.Warehouse_SKU_Id__c = 'p-21312';
        warehouseProduct.Warehouse_Code_And_SKU_Id__c = newAccount.Entity_Id__c + 'test';
        insert warehouseProduct;
       
        Inventory__c inventory = new Inventory__c();
        inventory.Warehouse_Product__c = warehouseProduct.Id;
        inventory.Warehouse_Code__c = 'CV12';
        inventory.SKU_Id__c = 'test';
        inventory.Warehouse_Code_And_SKU_Id__c = newAccount.Entity_Id__c + 'test';
        inventory.Remaining_Inventory__c = 1000;
        inventory.Total_Available_Inventory__c = 1000;
        insert inventory;
        
        
        paramMap.put('OrderItems', JSON.serialize(orderItems));
        paramMap.put('Order__c', newOrder.Id);
        Test.startTest();
        Map<String, Object> returnMap = Order_ProductsEditCtrl.saveOrderItems(paramMap);
        system.assert(returnMap.size()>0);
        Test.stopTest();               
    }
   
    @isTest(SeeAllData=true) 
    public static void testSaveOrderItemNoInv(){
        Map<String, Object> paramMap = new Map<String, Object>();
        List<Order_Product__c> orderItems = new List<Order_Product__c>();
        Warehouse_Config__mdt wareHouseData = [Select Id,Account_Id__c,isActive__c,Send_Email__c,DeveloperName,MasterLabel,Create_Shipment_Order__c
                                                        from Warehouse_Config__mdt where MasterLabel = 'West Sacramento' LIMIT 1];
        
        system.debug('wareHuseData---------'+wareHouseData);
        Account newAccount = [Select Id,Name,Entity_Id__c FROM Account where Id =: wareHouseData.Account_Id__c];
        
        Contact newContact = PHOS_TestHelper.getContact(true);
        User getUser = PHOS_TestHelper.getUser(true);
        Order__c newOrder = PHOS_TestHelper.getOrder(false);
        newOrder.Requestor__c = newContact.Id;
        newOrder.Requestor__c = newContact.id;
        newOrder.CreatedById = getUser.Id;
        newOrder.Creator_Contact__c = newContact.id;
        newOrder.Account__c = newContact.AccountId;
        insert newOrder;
        Product2 product = PHOS_TestHelper.getProductGoggles(true);
        Order_Product__c newOrderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        newOrderItemgoggle.Order__c = newOrder.Id;
        newOrderItemgoggle.Product__c = product.Id;
        newOrderItemgoggle.Fulfilment_Entity_Warehouse__c ='West Sacramento';
        newOrderItemgoggle.Quantity_Filled__c = 10;
        newOrderItemgoggle.Warehouse_Info__c = 'test123';
        insert newOrderItemgoggle;
        orderItems.add(newOrderItemgoggle);
         
        Product2 product1 = PHOS_TestHelper.getProductMask(true);
        Order_Product__c newOrderItemMask = PHOS_TestHelper.getOrderItemmask(false);
        newOrderItemMask.Order__c = newOrder.Id;
        newOrderItemMask.Product__c = product1.Id;
        newOrderItemMask.Fulfilment_Entity_Warehouse__c ='West Sacramento';
        newOrderItemgoggle.Warehouse_Info__c = '';
        newOrderItemMask.Quantity_Filled__c = 1200;
        insert newOrderItemMask;
        orderItems.add(newOrderItemMask);
        
        
        Warehouse_Product__c warehouseProduct = new Warehouse_Product__c();
        warehouseProduct.Product__c = product.Id;
        warehouseProduct.Warehouse__c = newAccount.Id;
        warehouseProduct.Is_Active__c = true;
        warehouseProduct.Warehouse_SKU_Id__c = newAccount.Entity_Id__c;
        warehouseProduct.Warehouse_Code__c = 'CV12';
        warehouseProduct.Warehouse_SKU_Id__c = 'p-21312';
        warehouseProduct.Warehouse_Code_And_SKU_Id__c = newAccount.Entity_Id__c + 'test';
        insert warehouseProduct;

        Inventory__c inventory = new Inventory__c();
        inventory.Warehouse_Product__c = warehouseProduct.Id;
        inventory.Warehouse_Code__c = 'CV12';
        inventory.SKU_Id__c = 'test';
        inventory.Warehouse_Code_And_SKU_Id__c = newAccount.Entity_Id__c + 'test 1234';
        inventory.Remaining_Inventory__c = 1000;
        inventory.Total_Available_Inventory__c = 1000;
        insert inventory;
        
        
        paramMap.put('OrderItems', JSON.serialize(orderItems));
        paramMap.put('Order__c', newOrder.Id);
        Test.startTest();
        Map<String, Object> returnMap = Order_ProductsEditCtrl.saveOrderItems(paramMap);
        system.assert(returnMap.size()>0);
        Test.stopTest();               
    }

	@isTest 
    public static void testGetFieldTypeTextArea(){
        Schema.DisplayType dt = Schema.DisplayType.TextArea;
		Test.startTest();
        String result = Order_ProductsEditCtrl.getFieldType(dt);
        System.assertNotEquals(result, null);
        Test.stopTest();
    } 
    @isTest 
    public static void testGetFieldTypeCurrency(){
        Schema.DisplayType dt = Schema.DisplayType.Currency;
		Test.startTest();
        String result = Order_ProductsEditCtrl.getFieldType(dt);
        System.assertNotEquals(result, null);
        Test.stopTest();
    } 
    @isTest 
    public static void testGetFieldTypeDouble(){
        Schema.DisplayType dt = Schema.DisplayType.Double;
		Test.startTest();
        String result = Order_ProductsEditCtrl.getFieldType(dt);
        System.assertNotEquals(result, null);
        Test.stopTest();
    } 
    
    @isTest 
    public static void testGetFieldTypeBoolean(){
        Schema.DisplayType dt = Schema.DisplayType.Boolean;
		Test.startTest();
        String result = Order_ProductsEditCtrl.getFieldType(dt);
        System.assertNotEquals(result, null);
        Test.stopTest();
    } 
        
    @isTest 
    public static void testGetFieldTypeDateTime(){
        Schema.DisplayType dt = Schema.DisplayType.DateTime;
		Test.startTest();
        String result = Order_ProductsEditCtrl.getFieldType(dt);
        System.assertNotEquals(result, null);
        Test.stopTest();
    } 
    
    @isTest 
    public static void testGetFieldTypeDate(){
        Schema.DisplayType dt = Schema.DisplayType.Date;
		Test.startTest();
        String result = Order_ProductsEditCtrl.getFieldType(dt);
        System.assertNotEquals(result, null);
        Test.stopTest();
    } 
    @isTest 
    public static void testGetFieldTypePicklist(){
        Schema.DisplayType dt = Schema.DisplayType.PICKLIST;
		Test.startTest();
        String result = Order_ProductsEditCtrl.getFieldType(dt);
        System.assertNotEquals(result, null);
        Test.stopTest();
    } 
    @isTest 
    public static void testGetFieldTypeMultiPicklist(){
        Schema.DisplayType dt = Schema.DisplayType.MultiPicklist;
		Test.startTest();
        String result = Order_ProductsEditCtrl.getFieldType(dt);
        System.assertNotEquals(result, null);
        Test.stopTest();
    } 
    @isTest 
    public static void testGetFieldTypeUnknown(){
        Schema.DisplayType dt = Schema.DisplayType.JSON;
		Test.startTest();
        String result = Order_ProductsEditCtrl.getFieldType(dt);
        System.assertNotEquals(result, null);
        Test.stopTest();
    } 
}