codepkg/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Warehouse_Product__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Inventory__c</fullName>
        <label>Remaining Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU_Id__c</fullName>
        <description>SKU ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SKU Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TX_Number__c</fullName>
        <description>TX Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>TX Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse_Code_And_SKU_Id__c</fullName>
        <description>This is external Id field. It is a combination of Warehouse code and SKU Id. It is joined by &quot;_&quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Warehouse Code And SKU Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Warehouse_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to warehouse product.</description>
        <label>Warehouse Product</label>
        <referenceTo>Warehouse_Product__c</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <formula>Warehouse_Product__r.Warehouse__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Warehouse</label>
        <type>Text</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Warehouse_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Creation_Status__c</fullName>
        <description>Shipment order status</description>
        <label>Creation Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Warehouse Config</label>
    <pluralLabel>Warehouse Configs</pluralLabel>
</CustomObject>

codepkg/objects/Warehouse_Product__c.object
<CustomObject>
    <description>Junction between warehouse and and Product. Mulesoft will send warehouse code and SKU code. We have flow which will populate lookup values based on it.</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_To_Warehouse_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warehouse_Code_And_SKU_Id__c</fullName>
        <description>Format  - WarehouseCode_SKUId</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>It should be concat of Warehouse code and SKU Id joined by -</inlineHelpText>
        <label>Warehouse Code And SKU Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Warehouse</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_To_Warehouse_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Warehouse Product</label>
    <nameField>
        <displayFormat>WP-{0000}</displayFormat>
        <label>Warehouse Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warehouse Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/PHOS_WarehouseSearchCtrlTest.cls
@IsTest(SeeAllData=false)
public with sharing class PHOS_WarehouseSearchCtrlTest {
    @IsTest
    static void testapexSearchWarehouse(){
        
        List<Warehouse_Config__mdt> wareHouseData = [SELECT Id,Account_Id__c,MasterLabel,isActive__c,Send_Email__c,Creation_Status__c
                                                                FROM Warehouse_Config__mdt where MasterLabel =:'Bloomington'];
        Product2 testProd = PHOS_TestHelper.getProductMask(true);
        Warehouse_Product__c wp = new Warehouse_Product__c();
        wp.Product__c = testProd.Id;
        wp.Warehouse__c = '001t000000SKOGNAA5';
        wp.Warehouse_Code_And_SKU_Id__c = 'CV12_P-229211';
        insert wp;
        Inventory__c newInventory = new Inventory__c();
        newInventory.TX_Number__c = '61651';
        newInventory.SKU_Id__c = 'P-229211';
        newInventory.Warehouse_Code_And_SKU_Id__c = 'CV12_P-229211';
        newInventory.Remaining_Inventory__c = 100;
        newInventory.Warehouse_Product__c = wp.Id;
        insert newInventory;
        test.startTest();
        List<LookupSearchResult> result = PHOS_WarehouseSearchCtrl.apexSearchWarehouse('Bloomington','P-229211');
        test.stopTest();
        System.assertNotEquals(result.size(),0);
    }
}