codepkg/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Warehouse_Product__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Inventory__c</fullName>
        <label>Remaining Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU_Id__c</fullName>
        <description>SKU ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SKU Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse_Code__c</fullName>
        <description>Warehouse Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Warehouse Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to warehouse product.</description>
        <label>Warehouse Product</label>
        <referenceTo>Warehouse_Product__c</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <formula>Warehouse_Product__r.Warehouse__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Warehouse</label>
        <type>Text</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>MHOAC Review</fullName>
                </value>
                <value>
                    <fullName>RDMHS Review</fullName>
                </value>
                <value>
                    <fullName>CDPH Resource Request Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>CDPH Resource Analyst Review</fullName>
                </value>
                <value>
                    <fullName>Allocation Review</fullName>
                </value>
                <value>
                    <fullName>Deployment Team</fullName>
                </value>
                <value>
                    <fullName>CDPH Pharmacy Consultant Review</fullName>
                    <label>MAC Group Review</label>
                </value>
                <value>
                    <fullName>Analyst Final Review</fullName>
                </value>
                <value>
                    <fullName>Staffing in Progress</fullName>
                </value>
                <value>
                    <fullName>Unfulfilled - Referred</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled - Referred</fullName>
                </value>
                <value>
                    <fullName>Unfulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Denied</fullName>
                </value>
                <value>
                    <fullName>Fulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>CASF-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>PHOS</fullName>
        <active>true</active>
        <label>PHOS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Fulfilment_Entity_Warehouse__c</fullName>
        <label>Fulfilment Entity / Warehouse</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Filled Locally/Regionally</fullName>
                </value>
                <value>
                    <fullName>Dixon</fullName>
                </value>
                <value>
                    <fullName>CDPH Depot (NEXGEN)</fullName>
                </value>
                <value>
                    <fullName>CDPH West Sacramento (NEXGEN)</fullName>
                </value>
                <value>
                    <fullName>Personnel</fullName>
                </value>
                <value>
                    <fullName>Citrus</fullName>
                </value>
                <value>
                    <fullName>Color</fullName>
                </value>
                <value>
                    <fullName>OES Dixon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Filled__c</fullName>
        <label>Quantity Filled</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Warehouse_Info__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Warehouse SKU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <displayFormat>OP-{00000000}</displayFormat>
        <label>Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Warehouse_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allow_Zero_Fulfilled_Qty__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Zero Fulfilled Qty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Check_For_Warehouse_Validations__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true then execute logic to check remaining inventory.</description>
        <label>Check for Warehouse Validations</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Post_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Post Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Warehouse Config</label>
    <pluralLabel>Warehouse Configs</pluralLabel>
</CustomObject>

codepkg/objects/Warehouse_Product__c.object
<CustomObject>
    <description>Junction between warehouse and and Product. Mulesoft will send warehouse code and SKU code. We have flow which will populate lookup values based on it.</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_To_Warehouse_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warehouse_Code__c</fullName>
        <description>Warehouse code populate from Mulesoft. Warehouse lookup will be populated from it.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Warehouse Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse_SKU_Id__c</fullName>
        <description>SKU Id from Product</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>SKU Id from Product. Based on it Product lookup will populate</inlineHelpText>
        <label>Warehouse SKU Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Warehouse</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_To_Warehouse_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Warehouse Product</label>
    <nameField>
        <displayFormat>WP-{0000}</displayFormat>
        <label>Warehouse Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warehouse Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/Order_ProductsEditCtrl.cls
/***********************************************************************************************************************************
* Class Name   : Order_ProductsEditCtrl
* Description  : This class for get order product
* Author       : Pankaj
* Created On   : 07/31/2020
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj               07/31/2020       Initial Implementation
**************************************************************************************************************************************/

public without sharing class Order_ProductsEditCtrl {

    /***********************************************
    * Method Name : getProducts
    * Author : Pankaj
    * Inputs : -
    * Description: This method return map of all active products
    *********************************************/
    @AuraEnabled
    public static Map<String,Object> getProducts(){
        return Order_ProductHelper.getProducts();
    }

    /***********************************************
    * Method Name : getOrderProductDetails
    * Author : Pankaj
    * Inputs : String orderId, String fieldAPINames
    * Description: This method return map of order products and warehouses 
    *********************************************/
    @AuraEnabled
    public static Map<String, Object> getOrderProductDetails(String orderId, String fieldAPINames){
        Map<String,Object> returnMap = new Map<String,Object>();
        List<String> fieldAPINameList = (List<String>) JSON.deserialize(fieldAPINames, List<String>.class);
        String query = 'SELECT ' + String.join(fieldAPINameList,',') + ',Product__r.Name, Product__r.ProductCode,Product_Family__c,Product_Name__c FROM Order_Product__c WHERE Order__c =: orderId';
        List<Order_Product__c> orderItems = Database.query(query);
        System.debug('orderItems'+orderItems);
        List<Warehouse_Config__mdt> warehouseList = [select id,Enable_Post_Sent__c,DeveloperName, MasterLabel  from Warehouse_Config__mdt where Enable_Post_Sent__c = true];
        returnMap.put('Warehouse',warehouseList);
        returnMap.put('orderItems', orderItems);
        return returnMap;
    }

    /***********************************************
    * Method Name : saveOrderItems
    * Author : Pankaj
    * Inputs : Map<String, Object> paramMap
    * Description: This method insert\update\delete the order products and return map of updated order products with error message if quantities are not available 
    *********************************************/
    @AuraEnabled
    public static Map<String, Object> saveOrderItems(Map<String, Object> paramMap) {
        Map<String, Object> returnMap = new Map<String, Object>();
        List<Order_Product__c> orderItems = (List<Order_Product__c>) JSON.deserialize(String.valueOf(paramMap.get('OrderItems')),
                    List<Order_Product__c>.class);

        returnMap = checkAvailableQty(orderItems);
        Boolean hasError = (Boolean)returnMap.get('hasError');
        if(hasError == true) return returnMap;

        String orderId = (String) paramMap.get('Order__c');//OrderId

        //create order version is app is Cal OES - Public Health Ordering System
        String appName = getAppName();
        if(appName == 'Cal OES - Public Health Ordering System' || appName == 'PHOS Community User') {
            System.debug('-----Creating Order Version------'+appName);
            AppUtils.generateSnapshotInJSON(orderId);
        }

        List<String> orderItemIds = new List<String>();
        for (Order_Product__c orderItem : orderItems) {
            if(String.isNotEmpty(orderItem.Id)) {
                orderItemIds.add(orderItem.Id);
            }
            System.debug('orderItem.Quantity__c-----'+orderItem.Quantity__c);
            System.debug('orderItem.Unit_Price__c-----'+orderItem.Unit_Price__c);
            if(orderItem.Unit_Price__c != null) {
                orderItem.Total_Price__c =  orderItem.Quantity__c * orderItem.Unit_Price__c;
                orderItem.Product_Code__c = orderItem.Product__r.ProductCode;
            }
        }
        List<Order_Product__c> orderItemsToDelete = new List<Order_Product__c>();
        if (orderItemIds.size() == 0) {
            orderItemsToDelete = [SELECT Id FROM Order_Product__c WHERE Order__c=:orderId];
        } else {
            orderItemsToDelete = [SELECT Id FROM Order_Product__c WHERE Order__c =:orderId AND Id NOT IN :orderItemIds];
        }
        delete orderItemsToDelete;

        List<String> productIds = new List<String>();
        for (Order_Product__c orderItem : orderItems) {
            if (orderItem.Id==null && String.isEmpty(orderItem.Order__c)) {
                orderItem.Order__c = orderId;
            }
            if (orderItem.Unit_Price__c == null) {
                orderItem.Unit_Price__c = 0;
            }
            productIds.add(orderItem.Product__c);
        }
        upsert orderItems;
        returnMap.put('hasError', false);
        return returnMap;
    }

    /***********************************************
    * Method Name : checkAvailableQty
    * Author : Pankaj
    * Inputs : List<Order_Product__c> orderProducts
    * Description: This method checks order products quantity available in inventory and return map of updated order products with error message if conditions are satisfied 
    *********************************************/
    private static Map<String, Object> checkAvailableQty(List<Order_Product__c> orderProducts) {
        Map<String, Object> returnMap = new Map<String, Object>();
        // this flag will derive to show error on UI
        returnMap.put('hasError', false);


        /**
         * on order product we have picklist of warehouse. Grab account id and get warehouse code
        */
        Map<String,String> warehouseMap = new  Map<String,String>();
        Map<String,Boolean> warehouseQtyValidationMap = new  Map<String,Boolean>();
        Map<String,Boolean> warehouseAllowZeroFulfilledQtyMap = new  Map<String,Boolean>();
        List<Id> accountIds = new List<Id>();
        List<Warehouse_Config__mdt> warehouseConfigs = [SELECT Id,Account_Id__c,isActive__c,MasterLabel,Check_For_Warehouse_Validations__c,Allow_Zero_Fulfilled_Qty__c
                FROM Warehouse_Config__mdt WHERE isActive__c = true];
        for(Warehouse_Config__mdt tempWarehouse : warehouseConfigs) {
            accountIds.add(tempWarehouse.Account_Id__c);
        }
        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, Entity_Id__c FROM Account WHERE Id IN :accountIds]);
        for(Warehouse_Config__mdt tempWarehouse : warehouseConfigs) {
            if(accountMap.get(tempWarehouse.Account_Id__c) == null) throw new AuraHandledException('Warehouse account not found. '
                            + tempWarehouse.MasterLabel);
            warehouseMap.put(tempWarehouse.MasterLabel, accountMap.get(tempWarehouse.Account_Id__c).Entity_Id__c);
            warehouseQtyValidationMap.put(tempWarehouse.MasterLabel, tempWarehouse.Check_For_Warehouse_Validations__c);
            warehouseAllowZeroFulfilledQtyMap.put(tempWarehouse.MasterLabel, tempWarehouse.Allow_Zero_Fulfilled_Qty__c);

        }


        Map<String, Integer> remainingInventoryBySKU = new Map<String, Integer>();
        Map<String, Integer> minimumQuantityInventory = new Map<String, Integer>();
        List<Id> productIds = new List<Id>();
        for (Order_Product__c orderProduct : orderProducts) {
            productIds.add(orderProduct.Product__c);
        }
        Map<String,Boolean> skipPHOSWarehouseValidation = new Map<String,Boolean>();
        for(Product2 prodRec : [SELECT Id,Skip_PHOS_Warehouse_Validation__c FROM Product2 WHERE Id IN: productIds]){
            skipPHOSWarehouseValidation.put(prodRec.Id,prodRec.Skip_PHOS_Warehouse_Validation__c);
        }
        List<Inventory__c> inventoryList = [SELECT Id,Name,Remaining_Inventory__c,SKU_Id__c,Warehouse_Code__c,
                                            Warehouse_Product__r.Product__c,Warehouse_Product__r.Warehouse__c,Warehouse_Product__r.Warehouse_SKU_Id__c,
                                            Warehouse_Product__r.Warehouse_Code__c,Warehouse_Product__r.Product__r.Minimum_Order_Quantity__c
                                            FROM Inventory__c
                                            WHERE Warehouse_Product__r.Warehouse__c IN: accountIds];
        for (Inventory__c inventory : inventoryList) {
            //remaining inventory for SKU & Warehouse
            remainingInventoryBySKU.put(inventory.SKU_Id__c + inventory.Warehouse_Code__c,
                                        (inventory.Remaining_Inventory__c != null ? Integer.valueOf(inventory.Remaining_Inventory__c) : 0));
            //minimum order quantity for specific product
            minimumQuantityInventory.put(inventory.SKU_Id__c + inventory.Warehouse_Code__c,
                    (inventory.Warehouse_Product__r.Product__r.Minimum_Order_Quantity__c != null ? Integer.valueOf(inventory.Warehouse_Product__r.Product__r.Minimum_Order_Quantity__c) : null));
        }

        Map<Integer, String> errorByIndex = new Map<Integer, String>();
        Integer index = 0;
        for (Order_Product__c orderProduct : orderProducts) {
            errorByIndex.put(index, '');// default no error
            //if product have skip PHO SWarehouse Validation is true  then continue
            if(skipPHOSWarehouseValidation.get(orderProduct.Product__c) == true){
                index++;
                continue;
            }
            // if it is already sent then we don't need to check against remaining qty
            if(orderProduct.Status__c == 'Sent') {
                index++;
                continue;
            }
            // if Fulfilment Entity / Warehouse is blank or Quantity Filled is blank
            if(String.isBlank(orderProduct.Fulfilment_Entity_Warehouse__c) || orderProduct.Quantity_Filled__c == null) {
                index++;
                continue;
            }

            if(orderProduct.Fulfilment_Entity_Warehouse__c != null && orderProduct.Fulfilment_Entity_Warehouse__c == PHOS_Constants.FILLED_REGIONALLY_STATUS) {
                index++;
                continue;
            }

            // if Warehouse entry is missing
            if(warehouseQtyValidationMap.get(orderProduct.Fulfilment_Entity_Warehouse__c) == null && orderProduct.Fulfilment_Entity_Warehouse__c != PHOS_Constants.FILLED_REGIONALLY_STATUS) {
                errorByIndex.put(index, 'Warehouse config is missing.');
                returnMap.put('hasError', true);
                index++;
                continue;
            }

            // if check for validations is false then continue
            if(orderProduct.Fulfilment_Entity_Warehouse__c != null && warehouseQtyValidationMap.get(orderProduct.Fulfilment_Entity_Warehouse__c) == false) {
                index++;
                continue;
            }

             // if check for warehouse allow zero fulfilled Qty validations is true then continue
             if(orderProduct.Fulfilment_Entity_Warehouse__c != null && warehouseAllowZeroFulfilledQtyMap.get(orderProduct.Fulfilment_Entity_Warehouse__c) == true) {
                index++;
                continue;
            }
            
            //if Warehouse SKU is missing
            if(orderProduct.Warehouse_Info__c == null) {
                errorByIndex.put(index, 'SKU is missing for this warehouse');
                returnMap.put('hasError', true);
                index++;
                continue;
            }

            //Inventory record is missing
            if(remainingInventoryBySKU.get(orderProduct.Warehouse_Info__c + warehouseMap.get(orderProduct.Fulfilment_Entity_Warehouse__c)) == null) {
                errorByIndex.put(index, 'Inventory record not found');
                returnMap.put('hasError', true);
                index++;
                continue;
            }

            //if Quantity Filled is less than Minimum Order Quantity for Product, then Error
            if(minimumQuantityInventory.get(orderProduct.Warehouse_Info__c + warehouseMap.get(orderProduct.Fulfilment_Entity_Warehouse__c)) != null
                && (orderProduct.Quantity_Filled__c < minimumQuantityInventory.get(orderProduct.Warehouse_Info__c + warehouseMap.get(orderProduct.Fulfilment_Entity_Warehouse__c)))) {
                errorByIndex.put(index,' Minimum Order Quantity for this Product is '+ minimumQuantityInventory.get(orderProduct.Warehouse_Info__c + warehouseMap.get(orderProduct.Fulfilment_Entity_Warehouse__c)));
                returnMap.put('hasError', true);
                index++;
                continue;
            }

            //if MOD of Quantity Filled by Minimum Order Quantity for Product < 1, then Error
            if(minimumQuantityInventory.get(orderProduct.Warehouse_Info__c + warehouseMap.get(orderProduct.Fulfilment_Entity_Warehouse__c)) != null
                    && (math.mod(Integer.valueOf(orderProduct.Quantity_Filled__c), minimumQuantityInventory.get(orderProduct.Warehouse_Info__c + warehouseMap.get(orderProduct.Fulfilment_Entity_Warehouse__c))) != 0 )) {
                errorByIndex.put(index,' Case Quantity for this Product must be in increments of '+ minimumQuantityInventory.get(orderProduct.Warehouse_Info__c + warehouseMap.get(orderProduct.Fulfilment_Entity_Warehouse__c)));
                returnMap.put('hasError', true);
                index++;
                continue;
            }

            //if remaining quantity on Inventory is less than Quantity filled, give Error
            if(remainingInventoryBySKU.get(orderProduct.Warehouse_Info__c + warehouseMap.get(orderProduct.Fulfilment_Entity_Warehouse__c)) < orderProduct.Quantity_Filled__c ) {
                    errorByIndex.put(index, ' Insufficient Quantity at this Warehouse. Maximum Order Quantity for this Product is '
                                + remainingInventoryBySKU.get(orderProduct.Warehouse_Info__c + warehouseMap.get(orderProduct.Fulfilment_Entity_Warehouse__c)));
                    returnMap.put('hasError', true);
                    index++;
                    continue;
            }
            index++;
        }
        returnMap.put('errorMap', errorByIndex);
        return returnMap;
    }

    /***********************************************
    * Method Name : getFieldDetails
    * Author : Pankaj
    * Inputs : string fieldsJSON, string objectName
    * Description: This method return list of Field details for specific object using JSON fields
    *********************************************/
    @AuraEnabled
    public static List<FieldDetails> getFieldDetails(string fieldsJSON, string objectName){
        List<FieldDetails> fieldDetailsList = new List<FieldDetails>();
        fieldDetailsList = (List<FieldDetails>)JSON.deserialize(fieldsJSON, List<FieldDetails>.class);

        for(FieldDetails fieldDtl : fieldDetailsList){
            Schema.DescribeFieldResult fieldResult = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().get(fieldDtl.APIName).getDescribe();

            fieldDtl.fieldType = getFieldType(fieldResult.getType());
            if(fieldDtl.isRequired==null){
                fieldDtl.isRequired = false;
            }
            if(fieldDtl.isDisabled==null){
                fieldDtl.isDisabled = false;
            }
            if(fieldDtl.enablePostSent==null){
                fieldDtl.enablePostSent = false;
            }

            if(fieldResult.getType() ==  Schema.DisplayType.PICKLIST){
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                fieldDtl.picklistValues = new List<string>();
                for( Schema.PicklistEntry f : ple){
                    fieldDtl.picklistValues.add(f.getValue());
                }
            }
        }
        return fieldDetailsList;
    }

    //Field detail wrapper
    /***********************************************************************************************************************************
    * Class Name   : FieldDetails
    * Description  : This is wrapper class for get field details
    * Author       : Pankaj
    * Created On   : 07/31/2020
    * Modification Log:  
    * --------------------------------------------------------------------------------------------------------------------------------------
    * Developer             Date             Description 
    * ---------------------------------------------------------------------------------------------------------------------------------------
    * Pankaj               07/31/2020       Initial Implementation
    **************************************************************************************************************************************/

    public class FieldDetails{
        @AuraEnabled public string APIName;
        @AuraEnabled public string Label;
        @AuraEnabled public string fieldType;
        @AuraEnabled public string OnChangeFormula;
        @AuraEnabled public boolean isRequired = false;
        @AuraEnabled public boolean isDisabled = false;
        @AuraEnabled public boolean enablePostSent = false;
        @AuraEnabled public List<string> picklistValues = new List<string>();
    }

    /***********************************************
    * Method Name : getFieldType
    * Author : Pankaj
    * Inputs : Schema.DisplayType fieldType
    * Description: This method return string of field type
    *********************************************/
    @TestVisible
    private static string getFieldType(Schema.DisplayType fieldType ){
        if(fieldType == Schema.DisplayType.String ||
                fieldType == Schema.DisplayType.TextArea ||
                fieldType == Schema.DisplayType.Phone ||
                fieldType == Schema.DisplayType.Email ||
                fieldType == Schema.DisplayType.URL)
            return 'STRING';

        if(fieldType == Schema.DisplayType.Currency)
            return 'CURRENCY';

        if(fieldType == Schema.DisplayType.Double||
                fieldType == Schema.DisplayType.Integer)
            return 'DOUBLE';

        if(fieldType == Schema.DisplayType.Boolean)
            return 'BOOLEAN';

        if(fieldType == Schema.DisplayType.DateTime)
            return 'DATETIME';

        if(fieldType == Schema.DisplayType.Date)
            return 'DATE';

        if(fieldType == Schema.DisplayType.PICKLIST)
            return 'PICKLIST';

        if(fieldType == Schema.DisplayType.MultiPicklist)
            return 'MULTIPICKLIST';

        return 'UNKNOWN';
    }

    /***********************************************
    * Method Name : getAppName
    * Author : Pankaj
    * Inputs : -
    * Description: This method return string of app name
    *********************************************/
    public static String getAppName() {
        Profile userProfile = [Select Name from Profile where Id =: userinfo.getProfileid()];
        String profileName = userProfile.name;
        if(ApexUtils.checkCommunityUser()) {
            return 'PHOS Community User';
        }
        UserAppInfo userAppInfo = [SELECT Id, AppDefinitionId FROM UserAppInfo WHERE UserId = :UserInfo.getUserId() LIMIT 1];
        AppDefinition appDefinition = [SELECT DurableId, Label FROM AppDefinition Where DurableId = :userAppInfo.AppDefinitionId LIMIT 1];
        return appDefinition.Label;
    }
}