codepkg/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Warehouse_Product__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <formula>Warehouse_Product__r.Warehouse__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Warehouse</label>
        <type>Text</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Creator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Creator Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders(Custom) (Creator Contact)</relationshipLabel>
        <relationshipName>Orders_Custom1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Parent_Agency__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Requestor Parent Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>MHOAC Review</fullName>
                </value>
                <value>
                    <fullName>RDMHS Review</fullName>
                </value>
                <value>
                    <fullName>CDPH Resource Request Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>CDPH Resource Analyst Review</fullName>
                </value>
                <value>
                    <fullName>Allocation Review</fullName>
                </value>
                <value>
                    <fullName>Deployment Team</fullName>
                </value>
                <value>
                    <fullName>CDPH Pharmacy Consultant Review</fullName>
                    <label>MAC Group Review</label>
                </value>
                <value>
                    <fullName>Analyst Final Review</fullName>
                </value>
                <value>
                    <fullName>Staffing in Progress</fullName>
                </value>
                <value>
                    <fullName>Unfulfilled - Referred</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled - Referred</fullName>
                </value>
                <value>
                    <fullName>Unfulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Denied</fullName>
                </value>
                <value>
                    <fullName>Fulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>CASF-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Product</label>
    <nameField>
        <displayFormat>OP-{00000000}</displayFormat>
        <label>Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Creator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Creator Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Parent_Agency__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Requestor Parent Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To Store Shipment Order Number</description>
        <label>Shipment Order</label>
        <referenceTo>Shipment_Order__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Shipment_Order__c.object
<CustomObject>
    <fields>
        <fullName>Creator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Creator Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipment Orders</relationshipLabel>
        <relationshipName>Shipment_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Custom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order(To Be Deleted)</label>
        <referenceTo>Order</referenceTo>
        <relationshipName>Shipment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Parent_Agency__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Requestor Parent Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Sent to Warehouse</fullName>
                </value>
                <value>
                    <fullName>Out for Delivery</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>InTransit</fullName>
                    <isActive>false</isActive>
                    <label>InTransit</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                    <isActive>false</isActive>
                    <label>Sent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Warehouse</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipment Orders</relationshipLabel>
        <relationshipName>ShipmentWareHouse</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Shipment_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Order_Product_Shipped__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Shipped</label>
        <referenceTo>Order_Product__c</referenceTo>
        <relationshipName>Shipment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment_Order__c</referenceTo>
        <relationshipLabel>Shipment Order Line Items</relationshipLabel>
        <relationshipName>Shipment_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Sent to Warehouse</fullName>
                </value>
                <value>
                    <fullName>Out for Delivery</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                    <isActive>false</isActive>
                    <label>Sent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment Order Line Item</label>
    <nameField>
        <displayFormat>SLI-{0000}</displayFormat>
        <label>Shipment Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Warehouse_Product__c.object
<CustomObject>
    <description>Junction between warehouse and and Product. Mulesoft will send warehouse code and SKU code. We have flow which will populate lookup values based on it.</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_To_Warehouse_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Warehouse</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_To_Warehouse_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Warehouse Product</label>
    <nameField>
        <displayFormat>WP-{0000}</displayFormat>
        <label>Warehouse Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warehouse Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/ShipmentOrderTriggerHelper.cls
/***********************************************************************************************************************************
* Class Name   : ShipmentOrderTriggerHelper
* Description  : This is helper class for shipment order trigger
* Author       : Pankaj
* Created On   : 08/17/2020
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj                08/17/2020       Initial Implementation
**************************************************************************************************************************************/

public without sharing class ShipmentOrderTriggerHelper extends TriggerHelper {

    /***********************************************
    * Method Name : processAfterInsert
    * Author : Pankaj
    * Inputs : -
    * Description: This method call after records are inserted
    *********************************************/
    public override void processAfterInsert() {
        updateOrderRecords();
        shrareShipmentOrder();
    }

    /***********************************************
    * Method Name : processAfterUpdate
    * Author : Pankaj
    * Inputs : -
    * Description: This method call after records are updated
    *********************************************/
    public override void processAfterUpdate() {
        updateOrderRecords();
        updateSOLI();
        updateOrderInvetoryRecords();
        shrareShipmentOrder();
    }

    /***********************************************
    * Method Name : processBeforeInsert
    * Author : Pankaj
    * Inputs : -
    * Description: This method call before records are inserting
    *********************************************/
    public override void processBeforeInsert()  {
        insertUpdateShipmentOrder();
    }

    /***********************************************
    * Method Name : processBeforeUpdate
    * Author : Pankaj
    * Inputs : -
    * Description: This method call before records are updating
    *********************************************/
    public override void processBeforeUpdate() {
        insertUpdateShipmentOrder();
     }
 
    /***********************************************
    * Method Name : updateOrderRecords
    * Author : Pankaj
    * Inputs : -
    * Description: if status changed to ready then update order record. This is required for mulesoft integration
    *********************************************/
    private void updateOrderRecords() {
        List<Order__c> lstOrderToUpdate= new  List<Order__c>();

        Map<Id, Shipment_Order__c> oldShipmentOrders = (Map<Id, Shipment_Order__c>)Trigger.oldMap;
        for(Shipment_Order__c shipRec : (List<Shipment_Order__c>)Trigger.new ) {
            if((oldShipmentOrders == null || oldShipmentOrders.get(shipRec.Id) == null) ||
                    (oldShipmentOrders.get(shipRec.Id).Status__c != shipRec.Status__c &&  shipRec.Status__c == PHOS_Constants.SHIPMENT_ORDER_STATUS_READY)) {
        	    Order__c ordRec =new Order__c(Id=shipRec.Order_Custom__c);
                lstOrderToUpdate.add(ordRec);
            }
        }
        update lstOrderToUpdate;
    }

    /***********************************************
    * Method Name : updateSOLI
    * Author : Pankaj
    * Inputs : -
    * Description: This method update status from Shipment order to shipment order line items. Shipment order line item will update order products
    *********************************************/
    private void updateSOLI() {
        List<String> shipOrderIdList = new List<String>();
        Map<Id, Shipment_Order__c> oldShipmentOrders = (Map<Id, Shipment_Order__c>)Trigger.oldMap;
        for(Shipment_Order__c shipRec : (List<Shipment_Order__c>)Trigger.new ) {
            if (oldShipmentOrders.get(shipRec.Id).Status__c != shipRec.Status__c) {
                shipOrderIdList.add(shipRec.Id);
            }
        }

        if(shipOrderIdList.isEmpty()) return;

        List<Shipment_Order_Line_Item__c> updateSOLIList= new  List<Shipment_Order_Line_Item__c>();
        List<Shipment_Order__c> listShipOrder = [Select Id, Status__c,
                                                        (Select Id, Status__c from Shipment_Order_Line_Items__r)
                                                        from Shipment_Order__c where ID IN : shipOrderIdList];
        for(Shipment_Order__c shipRec : listShipOrder) {
            for (Shipment_Order_Line_Item__c shipOrderLI : shipRec.Shipment_Order_Line_Items__r) {
                shipOrderLI.Status__c = shipRec.Status__c;
                updateSOLIList.add(shipOrderLI);
            }
        }
        update updateSOLIList;
    }

    /***********************************************
    * Method Name : insertUpdateShipmentOrder
    * Author : Pankaj
    * Inputs : -
    * Description: This method populate creator contact and Requestor Parent Agency on shipment order on  Insert and Update
    *********************************************/
    private  void insertUpdateShipmentOrder(){
        Set<Id> orderIds = new Set<Id>();
        Map<Id, Shipment_Order__c> oldshipmentOrderMap = (Map<Id, Shipment_Order__c>)Trigger.oldMap;
        for(Shipment_Order__c newShipmentOrder :  (List<Shipment_Order__c>)Trigger.new){
            if(newShipmentOrder.Order_Custom__c != null && Trigger.isInsert){
                orderIds.add(newShipmentOrder.Order_Custom__c);
            }
            if(oldshipmentOrderMap != null && newShipmentOrder.Order_Custom__c != null && (newShipmentOrder.Order_Custom__c != oldshipmentOrderMap.get(newShipmentOrder.Id).Order_Custom__c)  && Trigger.isUpdate){
                orderIds.add(newShipmentOrder.Order_Custom__c);
            }
        }
        Map<Id,Order__c> orderMap = new Map<Id, Order__c>([SELECT Id,Creator_Contact__c,Requestor_Parent_Agency__c from Order__c WHERE Id IN:orderIds]);
          if(!orderMap.isEmpty()){
            for(Shipment_Order__c shipmentOrder :  (List<Shipment_Order__c>)Trigger.new){
                if(orderMap.get(shipmentOrder.Order_Custom__c).Requestor_Parent_Agency__c != null)
                    shipmentOrder.Requestor_Parent_Agency__c = orderMap.get(shipmentOrder.Order_Custom__c).Requestor_Parent_Agency__c;
                if(orderMap.get(shipmentOrder.Order_Custom__c).Creator_Contact__c != null)
                    shipmentOrder.Creator_Contact__c = orderMap.get(shipmentOrder.Order_Custom__c).Creator_Contact__c;
             }
          }
    }

    /***********************************************
    * Method Name : updateOrderInvetoryRecords
    * Author : Pankaj
    * Inputs : -
    * Description: This method used for update Inventory Qty record when status changed to Rejected
    *********************************************/
     private void updateOrderInvetoryRecords() {
        Set<Id> orderSet= new  Set<Id>();
        Set<Id> warehouseSet= new  Set<Id>();
        Map<Id, Shipment_Order__c> oldShipmentOrders = (Map<Id, Shipment_Order__c>)Trigger.oldMap;
        for(Shipment_Order__c shipRec : (List<Shipment_Order__c>)Trigger.new ) {
            if(shipRec.Status__c!= null && (oldShipmentOrders.get(shipRec.Id).Status__c != shipRec.Status__c) &&  
                shipRec.Status__c == PHOS_Constants.SHIPMENT_LINE_ORDER_STATUS_Rejected && shipRec.LastModifiedDate.Date() == System.today() && 
                shipRec.CreatedDate.Date() == System.today()) {
                        orderSet.add(shipRec.Id);
                        warehouseSet.add(shipRec.Warehouse__c);
            }
        }
        
        if(orderSet.size() > 0 && warehouseSet.size() > 0 ){
            Set<String> warehouseLabelSet = new  Set<String>();

            Map<String,List<Shipment_Order_Line_Item__c>> orderProductsMap = new Map<String,List<Shipment_Order_Line_Item__c>>();
            Map<Id,Inventory__c> productInventory = new Map<Id,Inventory__c>(); 
            for(Shipment_Order_Line_Item__c orderProduct : [SELECT Id,Name,Quantity__c,Order_Product_Shipped__r.Product__c,Order_Product_Shipped__r.Warehouse_Info__c
                                                            FROM Shipment_Order_Line_Item__c WHERE Shipment__c IN:orderSet]){
                    if(orderProductsMap.get(orderProduct.Order_Product_Shipped__r.Warehouse_Info__c) == null) {
                        orderProductsMap.put(orderProduct.Order_Product_Shipped__r.Warehouse_Info__c, new List<Shipment_Order_Line_Item__c>());
                    }
                    orderProductsMap.get(orderProduct.Order_Product_Shipped__r.Warehouse_Info__c).add(orderProduct);
            }    
            List<Inventory__c> updateInventoryList = new List<Inventory__c>();
            List<Inventory__c> inventoryList =[SELECT Id,Name,Remaining_Inventory__c,Warehouse_Product__r.Product__c,SKU_Id__c,
                                                Warehouse_Product__r.Warehouse__c FROM Inventory__c 
                                                WHERE Warehouse_Product__r.Warehouse__c  IN: warehouseSet 
                                                AND SKU_Id__c IN:orderProductsMap.keySet()];
            for(Inventory__c inventory :inventoryList){
                for(Shipment_Order_Line_Item__c orderProd : orderProductsMap.get(inventory.SKU_Id__c)){
                    inventory.Remaining_Inventory__c = inventory.Remaining_Inventory__c + orderProd.Quantity__c;
                    updateInventoryList.add(inventory);
                }
            }
            for(Inventory__c inventory : updateInventoryList){
                productInventory.put(inventory.Id,inventory);
            }
            if(productInventory.size() > 0){
                update productInventory.values();
            }
        }    
    }

    public static void shrareShipmentOrder(){

        Set<Id> shipmentOrderIdSet = new Set<Id>();
        if(Trigger.isUpdate) {
            for(Shipment_Order__c newOrder : (List<Shipment_Order__c>)Trigger.new){
                Shipment_Order__c oldOrder = (Shipment_Order__c)Trigger.oldMap.get(newOrder.Id);
                if(String.isNotBlank(newOrder.Creator_Contact__c)) {
                    if(oldOrder.Status__c != newOrder.Status__c  && String.isNotBlank(newOrder.Creator_Contact__c) ) {
                        shipmentOrderIdSet.add(newOrder.Id);
                    }
                }
            }
        } else if(Trigger.isInsert) {
            for(Shipment_Order__c newOrder : (List<Shipment_Order__c>)Trigger.new){
                if(String.isNotBlank(newOrder.Creator_Contact__c)) {
                    shipmentOrderIdSet.add(newOrder.Id);
                }
            }
        }
        if(shipmentOrderIdSet.size() == 0) return;

        List<Shipment_Order__c> shipmentOrderList = [SELECT Id,Creator_Contact__c,Order_Custom__c,Order_Custom__r.Account__c,Order_Custom__r.Account__r.Account_PHOS_Order_Public_Group__c,
                                                     Order_Custom__r.Account__r.ParentId,Order_Custom__r.Account__r.Parent.Account_PHOS_Order_Public_Group__c,Order_Custom__r.Account__r.Parent.ParentId,
                                                     Order_Custom__r.Account__r.Parent.Parent.Account_PHOS_Order_Public_Group__c FROM Shipment_Order__c 
                                                     WHERE Id IN : shipmentOrderIdSet]; 

        if(shipmentOrderList.size() == 0) return;

        Set<String> publicGroupdevloperNames = new Set<String>();

        for(Shipment_Order__c shipmentOrder : shipmentOrderList){
            //For region Account
           if(shipmentOrder.Order_Custom__r.Account__r.Parent.Parent.Account_PHOS_Order_Public_Group__c != null) {
            publicGroupdevloperNames.add(shipmentOrder.Order_Custom__r.Account__r.Parent.Parent.Account_PHOS_Order_Public_Group__c);
           }
           //For County Account
           if(shipmentOrder.Order_Custom__r.Account__r.Parent.Account_PHOS_Order_Public_Group__c != null) {
               publicGroupdevloperNames.add(shipmentOrder.Order_Custom__r.Account__r.Parent.Account_PHOS_Order_Public_Group__c);
           }
        }

       List<Group> GroupListById = [SELECT Id,Name,DeveloperName from Group where DeveloperName =: publicGroupdevloperNames and Type = 'Regular'];
        if(GroupListById.size() == 0) return;
       
        Map<String,Id> publicGroupMapById = new Map<String,Id>();

        for(Group grp : GroupListById ){

            publicGroupMapById.put(grp.DeveloperName, grp.Id);
        }

        List<Shipment_Order__Share> shipmentOrderShareList = new List<Shipment_Order__Share>();
       
            for(Shipment_Order__c newShipmentOrder : shipmentOrderList){

                if(newShipmentOrder.Creator_Contact__c == null) continue;
                if(newShipmentOrder.Order_Custom__r.Account__r.ParentId != null && newShipmentOrder.Order_Custom__r.Account__r.Parent.Account_PHOS_Order_Public_Group__c != null) {
                    Shipment_Order__Share cs = new Shipment_Order__Share();
                    cs.ParentId = newShipmentOrder.Id;
                    cs.UserOrGroupId = publicGroupMapById.get(newShipmentOrder.Order_Custom__r.Account__r.Parent.Account_PHOS_Order_Public_Group__c);
                    cs.AccessLevel  = 'Read';
                    cs.RowCause = Schema.Shipment_Order__Share.RowCause.Manual;
                    shipmentOrderShareList.add(cs);
                } 
                //For Region Account
               if(newShipmentOrder.Order_Custom__r.Account__r.Parent.ParentId != null && newShipmentOrder.Order_Custom__r.Account__r.Parent.Parent.Account_PHOS_Order_Public_Group__c != null) { 
                    Shipment_Order__Share cs = new Shipment_Order__Share();
                    cs.ParentId = newShipmentOrder.Id;
                    cs.UserOrGroupId = publicGroupMapById.get(newShipmentOrder.Order_Custom__r.Account__r.Parent.Parent.Account_PHOS_Order_Public_Group__c);
                    cs.AccessLevel  = 'Read';
                    cs.RowCause = Schema.Shipment_Order__Share.RowCause.Manual;
                    shipmentOrderShareList.add(cs);
                } 
            }
       

        if(shipmentOrderShareList != null && !shipmentOrderShareList.isEmpty()) {
            insert shipmentOrderShareList;
        }
    }
}