codepkg/objects/Key_Value_Store__mdt.object
<CustomObject>
    <fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Key Value Store</label>
    <pluralLabel>Key Value Stores</pluralLabel>
</CustomObject>

codepkg/objects/Page_Field__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Page Field</label>
    <pluralLabel>Page Fields</pluralLabel>
</CustomObject>

codepkg/objects/Page_Layout__mdt.object
<CustomObject>
    <label>Page Layout Config</label>
    <pluralLabel>Page Layouts</pluralLabel>
</CustomObject>

codepkg/objects/Program_Template_Page__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Template__c</fullName>
        <label>Program Template</label>
        <referenceTo>Program_Template__mdt</referenceTo>
        <relationshipLabel>Program Template Pages</relationshipLabel>
        <relationshipName>Program_Template_Pages</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Program Template Page</label>
    <pluralLabel>Program Template Pages</pluralLabel>
</CustomObject>

codepkg/classes/HMA_TestMetadataHelper.cls
@isTest(seeAllData=true)
public without sharing class HMA_TestMetadataHelper {
    public static Program_Template_Page__mdt getProgramTemplatePageMdt(String developerName) {
        Program_Template_Page__mdt programTemplatePage = [SELECT Id, DeveloperName, Program_Template__c, Active__c 
                                                            FROM Program_Template_Page__mdt WHERE DeveloperName = : developerName];
        return programTemplatePage;
    }
    public static Page_Layout__mdt getPageLayoutMdt(String developerName) {
        Page_Layout__mdt pageLayoutMdt = [SELECT Id, DeveloperName FROM Page_Layout__mdt WHERE DeveloperName =: developerName];
        return pageLayoutMdt;
    }

    public static Page_Field__mdt getPageFieldMdt(String developerName) {
        Page_Field__mdt pageFieldMdt = [SELECT Id, DeveloperName FROM Page_Field__mdt WHERE DeveloperName =: developerName];
        return pageFieldMdt;
    }

    public static Key_Value_Store__mdt getKeyValue(String developerName) {
        Key_Value_Store__mdt keyValue = [SELECT Id, DeveloperName, Text_Value__c FROM Key_Value_Store__mdt WHERE DeveloperName = :developerName];
        return keyValue;
    }
}