codepkg/objects/Key_Value_Store__mdt.object
<CustomObject>
    <fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Key Value Store</label>
    <pluralLabel>Key Value Stores</pluralLabel>
</CustomObject>

codepkg/objects/PHOS_Document_Repository__mdt.object
<CustomObject>
    <description>PHOS Document Repository</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PHOS Document Repository</label>
    <pluralLabel>PHOS Document Repositories</pluralLabel>
</CustomObject>

codepkg/classes/PA_CommunityHomeCtrl.cls
/**
* Class Name   : PA_CommunityHomeCtrl
* Description  : 
* Author       : Pankaj
* Created On   : 26/05/2021
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj             26/01/2021       Initial Implementation
*/

public with sharing class PA_CommunityHomeCtrl {
    
    /***********************************************************************************************
    * Method  Name   : getArticles
    * Description    : -
    * Return         : -
    * Inputs :
    * Author         : Pankaj
    * Created On     : 26/05/2021
    * Modification Log:  
    * -----------------------------------------------------------------------------------------------*/
    
    @AuraEnabled
    public static List<KnowledgeArticleVersion> getArticles() {
        List<KnowledgeArticleVersion> knowledgeList = [SELECT Id,KnowledgeArticleId,Language,PublishStatus,Summary,Title,UrlName
            FROM KnowledgeArticleVersion where PublishStatus = 'Online' AND Language = 'en_US' WITH DATA CATEGORY PHOS__c below PHOS_Portal__c];
        return knowledgeList;
    }

    /***********************************************************************************************
    * Method  Name   : getDatatwo
    * Description    : -
    * Return         : -
    * Inputs :
    * Author         : Pankaj
    * Created On     : 26/05/2021
    * Modification Log:  
    * -----------------------------------------------------------------------------------------------*/
   
    @AuraEnabled
    public static Map<String, Object> getDatatwo() {
        Map<String, Object> returnMap = new Map<String, Object>();
        List<PHOS_Document_Repository__mdt> docList = [SELECT DeveloperName,Id,Is_Active__c,Label,Language,MasterLabel,Sequence__c,URL__c
            FROM PHOS_Document_Repository__mdt where Is_Active__c = true Order By Sequence__c];
        returnMap.put('DocumentList',docList);
        returnMap.put('KnowledgeList',getArticles());
        returnMap.put('ReportUrl', customMetaValReportUrl());
        return returnMap;
    }

    /***********************************************************************************************
    * Method  Name   : getDatatwo
    * Description    : -
    * Return         : -
    * Inputs :
    * Author         : Pankaj
    * Created On     : 26/05/2021
    * Modification Log:  
    * -----------------------------------------------------------------------------------------------*/

    @AuraEnabled
    public static String customMetaValReportUrl(){
        String resultVal = '';
        List<Key_Value_Store__mdt> keyValStoreLst = [SELECT Text_Value__c,DeveloperName 
                                                    FROM Key_Value_Store__mdt
                                                    WHERE DeveloperName = 'PA_Report_URL'];
        System.debug('Key_Value_Store query result==='+keyValStoreLst);                                            
        if(keyValStoreLst.size() > 0){
            resultVal = keyValStoreLst[0].Text_Value__c;
        }   
        return  resultVal;                                        
    }
}