codepkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>CASF-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Order_Version__c.object
<CustomObject>
    <fields>
        <fullName>Order_Custom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Versions</relationshipLabel>
        <relationshipName>Order_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order(To Be Deleted)</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Order Versions</relationshipLabel>
        <relationshipName>Order_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Version</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Order Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/AppUtilsTest.cls
@isTest(seeAllData=false)
public class AppUtilsTest {
    @isTest public static void testGenerateSnapshotInJSON(){
        Order__c newOrder = PHOS_TestHelper.getOrder(true);
        Order_Version__c newOrderVersion = PHOS_TestHelper.getOrderVersion(false);
        newOrderVersion.Order_Custom__c = newOrder.Id;
        insert newOrderVersion;        
        String orderId =  String.valueOf(newOrder.Id);
        
        test.startTest();
        AppUtils.generateSnapshotInJSON(orderId);
        test.stopTest();
    }
    
    @isTest public static void testFetchAllEmailAddresses(){
        List<String> returnMap = new List<String>();
        String data = 'test.gmail@gmail.com';
        
        test.startTest();
        returnMap = AppUtils.fetchAllEmailAddresses(data);
        System.assert(returnMap.size()>0);
        test.stopTest();
    }
    
    @isTest public static void testGenerateSnapshotInJSONForDistributionPlan(){
        Order__c newOrder = PHOS_TestHelper.getOrder(true);
        Order_Version__c newOrderVersion = PHOS_TestHelper.getOrderVersion(false);
        newOrderVersion.Order_Custom__c = newOrder.Id;
        insert newOrderVersion;        
        String orderId =  String.valueOf(newOrder.Id);
        
        test.startTest();
        AppUtils.generateSnapshotInJSONForDistributionPlan(orderId);
        test.stopTest();
    }
}