codepkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>MHOAC Review</fullName>
                </value>
                <value>
                    <fullName>RDMHS Review</fullName>
                </value>
                <value>
                    <fullName>CDPH Resource Request Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>CDPH Resource Analyst Review</fullName>
                </value>
                <value>
                    <fullName>Allocation Review</fullName>
                </value>
                <value>
                    <fullName>Deployment Team</fullName>
                </value>
                <value>
                    <fullName>CDPH Pharmacy Consultant Review</fullName>
                    <label>MAC Group Review</label>
                </value>
                <value>
                    <fullName>Analyst Final Review</fullName>
                </value>
                <value>
                    <fullName>Staffing in Progress</fullName>
                </value>
                <value>
                    <fullName>Unfulfilled - Referred</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled - Referred</fullName>
                </value>
                <value>
                    <fullName>Unfulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Denied</fullName>
                </value>
                <value>
                    <fullName>Fulfilled - Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>CASF-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>PHOS</fullName>
        <active>true</active>
        <label>PHOS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Fulfilment_Entity_Warehouse__c</fullName>
        <label>Fulfilment Entity / Warehouse</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Filled Locally/Regionally</fullName>
                </value>
                <value>
                    <fullName>Dixon</fullName>
                </value>
                <value>
                    <fullName>CDPH Depot (NEXGEN)</fullName>
                </value>
                <value>
                    <fullName>CDPH West Sacramento (NEXGEN)</fullName>
                </value>
                <value>
                    <fullName>Personnel</fullName>
                </value>
                <value>
                    <fullName>Citrus</fullName>
                </value>
                <value>
                    <fullName>Color</fullName>
                </value>
                <value>
                    <fullName>OES Dixon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_Filled__c</fullName>
        <label>Quantity Filled</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Product</label>
    <nameField>
        <displayFormat>OP-{00000000}</displayFormat>
        <label>Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To Store Shipment Order Number</description>
        <label>Shipment Order</label>
        <referenceTo>Shipment_Order__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <recordTypes>
        <fullName>PHOS</fullName>
        <active>true</active>
        <description>PHOS record type for Shipment</description>
        <label>PHOS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Shipment_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Custom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Shipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order(To Be Deleted)</label>
        <referenceTo>Order</referenceTo>
        <relationshipName>Shipment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Sent to Warehouse</fullName>
                </value>
                <value>
                    <fullName>Out for Delivery</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>InTransit</fullName>
                    <isActive>false</isActive>
                    <label>InTransit</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                    <isActive>false</isActive>
                    <label>Sent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Warehouse</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipment Orders</relationshipLabel>
        <relationshipName>ShipmentWareHouse</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <recordTypes>
        <fullName>PHOS</fullName>
        <active>true</active>
        <label>PHOS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Shipment_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Order_Product_Shipped__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Shipped</label>
        <referenceTo>Order_Product__c</referenceTo>
        <relationshipName>Shipment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment_Order__c</referenceTo>
        <relationshipLabel>Shipment Order Line Items</relationshipLabel>
        <relationshipName>Shipment_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Sent to Warehouse</fullName>
                </value>
                <value>
                    <fullName>Out for Delivery</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                    <isActive>false</isActive>
                    <label>Sent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment Order Line Item</label>
    <nameField>
        <displayFormat>SLI-{0000}</displayFormat>
        <label>Shipment Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/ShipmentOrderTriggerHelperTest.cls
@isTest(seeAllData=false) 
public class ShipmentOrderTriggerHelperTest {
    @isTest static void testShipmentOrder() {

        Account newAccount = PHOS_TestHelper.getWarehouseAccount(true);

        Order__c orderRec = PHOS_TestHelper.getOrder(true);
        Id phosShipOrderRecordTypeId = Schema.SObjectType.Shipment_Order__c.getRecordTypeInfosByDeveloperName().get('PHOS').getRecordTypeId();
      
        List<Order_Product__c> orderItems = new List<Order_Product__c>();
        Order_Product__c orderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        orderItemgoggle.Order__c = orderRec.Id;
        orderItemgoggle.Fulfilment_Entity_Warehouse__c = 'West Sacramento';
        orderItemgoggle.Quantity_Filled__c = 10;
        //insert orderItemgoggle;
        orderItems.add(orderItemgoggle);
        Order_Product__c orderItemmask = PHOS_TestHelper.getOrderItemmask(false);
        orderItemmask.Order__c = orderRec.Id;
        orderItemmask.Fulfilment_Entity_Warehouse__c = 'West Sacramento';
        orderItemmask.Quantity_Filled__c = 10;
        orderItems.add(orderItemmask);
        insert orderItems;

        Shipment_Order__c shipmentOrder = PHOS_TestHelper.getShipmentOrder(false);
        shipmentOrder.Order_Custom__c = orderRec.Id;
        shipmentOrder.Warehouse__c = newAccount.Id;
        insert shipmentOrder;
        

        List<Shipment_Order_Line_Item__c> shipmentOrderLineItems = new List<Shipment_Order_Line_Item__c>();
        Shipment_Order_Line_Item__c shipmentOrderLineItem1 = PHOS_TestHelper.getShipmentOrderLineItem(false);
        shipmentOrderLineItem1.Order_Product_Shipped__c = orderItems[0].Name;
         shipmentOrderLineItem1.Shipment__c = shipmentOrder.Id;
        shipmentOrderLineItems.add(shipmentOrderLineItem1);
        Shipment_Order_Line_Item__c shipmentOrderLineItem2 = PHOS_TestHelper.getShipmentOrderLineItem(false);
        shipmentOrderLineItem2.Order_Product_Shipped__c = orderItems[1].Name;
        shipmentOrderLineItem2.Shipment__c = shipmentOrder.Id;
        shipmentOrderLineItems.add(shipmentOrderLineItem2);

        insert shipmentOrderLineItems;

        shipmentOrder.Status__c = 'Rejected';
        update shipmentOrder;
    }
}