codepkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Describe Mission/Tasks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>CASF-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <displayFormat>OP-{00000000}</displayFormat>
        <label>Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/OrderProductTriggerHelperTest.cls
@isTest public with sharing class OrderProductTriggerHelperTest {
    @isTest public static void processAfterInsertTest(){

        Order__c getOrder = PHOS_TestHelper.getOrder(true);
        Order_Product__c orderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        orderItemgoggle.Order__c = getOrder.Id;
        insert orderItemgoggle;
        
    }

    @isTest public static void processAfterUpdateTest(){
        Order__c getOrder = PHOS_TestHelper.getOrder(true);
        Order_Product__c orderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        orderItemgoggle.Order__c = getOrder.Id;
        insert orderItemgoggle;
        orderItemgoggle.Description__c = 'testDescription';
        upsert orderItemgoggle;
     
    }
    @isTest public static void processAfterDeleteTest(){
        Order__c getOrder = PHOS_TestHelper.getOrder(true);
        Order_Product__c orderItemgoggle = PHOS_TestHelper.getOrderItemgoggle(false);
        orderItemgoggle.Order__c = getOrder.Id;
        insert orderItemgoggle;
        orderItemgoggle.Description__c = 'testDescription';
        Delete orderItemgoggle;
        Undelete orderItemgoggle;
     
    }

}