codepkg/objects/Payment__c.object
<CustomObject>
    <description>It is child object of Payment Request.</description>
    <fields>
        <fullName>Closeout_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This self-lookup field points to the Closeout Payment due to which these individual Payments have been created per Project.</description>
        <inlineHelpText>This self-lookup field points to the Closeout Payment due to which these individual Payments have been created per Project.</inlineHelpText>
        <label>Closeout Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master record for this Payment record.</description>
        <inlineHelpText>Master record for this Payment record.</inlineHelpText>
        <label>Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transmittal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for final closeout</description>
        <label>Transmittal</label>
        <referenceTo>Transmittal__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Payment_Request__c.object
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Transmittal__c.object
<CustomObject>
    <description>To store the Transmittal of Payment request.</description>
    <fields>
        <fullName>Adjusted_For_Offset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Offset Transmittal from/on which the Amount is adjusted.</description>
        <inlineHelpText>Lookup to Offset Transmittal from/on which the Amount is adjusted.</inlineHelpText>
        <label>Adjusted For(Offset)</label>
        <referenceTo>Transmittal__c</referenceTo>
        <relationshipLabel>Transmittals</relationshipLabel>
        <relationshipName>Transmittals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentRequest__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>We have made it Lookup because we are changing the owner to Queue while sending Transmittal for Approval. And in master detail relationship, PR owner will become the owner of Transmittal well.
Payment Request to which this transmittal is related.</description>
        <inlineHelpText>Payment Request to which this transmittal is related.</inlineHelpText>
        <label>Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Transmittals</relationshipLabel>
        <relationshipName>Transmittals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transmittal</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transmittal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transmittals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/LockRecordsJob.cls
/**
 * Created by Neha on 09-03-2021.
 */

public with sharing class LockRecordsJob implements Database.Batchable<sObject>, Schedulable {
    private final String query;

    public LockRecordsJob(String query) {
        this.query = query;
    }

    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new LockRecordsJob(query));
    }

    // Database.Batchable methods
    public Database.QueryLocator start(Database.BatchableContext bc) {
        List<String> stagelist = new List<String>();
        stagelist.add('Paid');
        stagelist.add('Returned Project Payment'); 
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        List<String> prIdsToLock = new List<String>();
        List<String> transmittalIdsToLock = new List<String>();
        List<String> paymentIdsToLock = new List<String>();
        if(scope.size() > 0) {
            for(SObject sc : scope) {
                Payment_Request__c pr = (Payment_Request__c) sc;
                prIdsToLock.add(pr.Id);
                for (Transmittal__c tr : pr.Transmittals__r) {
                    transmittalIdsToLock.add(tr.Id);
                }
                /*for (Payment__c payment : pr.Payments__r) {
                    paymentIdsToLock.add(payment.Id);
                }*/
            }
            System.debug(prIdsToLock);
            System.debug(transmittalIdsToLock);
            System.debug(paymentIdsToLock);

            //ApexUtils.lockRecord(paymentIdsToLock);
            ApexUtils.lockRecord(transmittalIdsToLock);
            ApexUtils.lockRecord(prIdsToLock);
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}