codepkg/objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>ExpenditurestoDate__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Reimbursement request for the Project.</description>
        <inlineHelpText>Reimbursement request for the Project.</inlineHelpText>
        <label>Expenditures to Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FederalRetentionShare__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Federal Share Retention amount for the Project. Only visible for GPU Analyst.</description>
        <inlineHelpText>Federal Share Retention amount for the Project.
[ Federal Cost Share * Federal Retention % (  Project ) ]</inlineHelpText>
        <label>Federal Retention Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OffsetToPaymentRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Payment Request to which this Offset is provided.</description>
        <inlineHelpText>Payment Request to which this Offset is provided.</inlineHelpText>
        <label>Offset To Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <description>Type of a Payment Request</description>
        <inlineHelpText>Type of a Payment Request</inlineHelpText>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advance</fullName>
                </value>
                <value>
                    <fullName>Reimbursement</fullName>
                </value>
                <value>
                    <fullName>Offset</fullName>
                </value>
                <value>
                    <fullName>Mutual Aid</fullName>
                </value>
                <value>
                    <fullName>Final Payment</fullName>
                </value>
                <value>
                    <fullName>Returned Project Payment</fullName>
                </value>
                <value>
                    <fullName>DeObligation</fullName>
                    <isActive>false</isActive>
                    <label>De Obligation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project for which this Payment is Requested?</description>
        <inlineHelpText>Project for which this Payment is Requested?</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of Payment Request</description>
        <inlineHelpText>Stage of Payment Request</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Reviewed - Needs Information</fullName>
                </value>
                <value>
                    <fullName>Payment Processing</fullName>
                </value>
                <value>
                    <fullName>Returned Project Payment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StateRetentionShare__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Retention Share for the Project.</description>
        <inlineHelpText>State Retention Share for the Project.
[ State Cost Share * State Retention % ( Project ) ]</inlineHelpText>
        <label>State Retention Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Expenditure_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the highest amount in the Expenditures to Date field on the PR.</description>
        <inlineHelpText>This is the up-to-date Total Project Costs the Subrecipient has submitted to Cal OES.</inlineHelpText>
        <label>Cumulative Expenditures</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Federal_Retention_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Federal Retention To Date on Project</description>
        <inlineHelpText>Federal Retention To Date on Project</inlineHelpText>
        <label>Federal Retention To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The Project Stage.</description>
        <inlineHelpText>The current processing stage of the Project. (e.g. New, Obligated, Compliance Verification, Payment, etc.)</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Obligating</fullName>
                    <label>Obligated</label>
                </value>
                <value>
                    <fullName>Compliance Verification</fullName>
                </value>
                <value>
                    <fullName>Active Payment</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Deobligation</fullName>
                    <isActive>false</isActive>
                    <label>Deobligation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Retention_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Retention To Date on Project</description>
        <inlineHelpText>State Retention To Date on Project</inlineHelpText>
        <label>State Retention To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Retention_To_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Retention To Date on Project</description>
        <inlineHelpText>Total Retention To Date on Project</inlineHelpText>
        <label>Total Retention To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/UpdateExpenditureToDateOnProjectJob.cls
/**
 * Created by Sushant p on 21-04-2021.
 */
//Ticket No CaloESALS-405 and 429  To update Project fields which are Copied From highest amount in the Expenditures to Date WITH Retentions field on the PR
public with sharing class UpdateExpenditureToDateOnProjectJob implements Database.Batchable<sObject>,Schedulable, Database.Stateful {
    private final String query;

    public UpdateExpenditureToDateOnProjectJob(String query) {
        this.query = query;
    }
    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new UpdateExpenditureToDateOnProjectJob(query));
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        Set<Id> projectIds = new Set<Id>();
        List<Project__c> projectsToUpdate = new List<Project__c>();
        for(SObject sc : scope) {
            Project__c prj = (Project__c) sc;
            projectIds.add(prj.Id);
        }

        //List<Project__c> projectList =[SELECT Id FROM Project__c ];

        //for Filter using Created Date
        //Map<Id, Project__c> idToProjectWithPrsMap = new Map<Id, Project__c>([SELECT Id, Expenditure_To_Date__c, (SELECT Id, Project__c, ExpenditurestoDate__c ,FederalRetentionShare__c, StateRetentionShare__c FROM Payment_Requests__r WHERE Project__c IN :projectIds AND ExpenditurestoDate__c > 0 AND PaymentType__c = :ALS_CONSTANTS.PR_PaymentType_Reimbursement AND Stage__c != :ALS_CONSTANTS.PR_Stage_Withdrawn ORDER BY CreatedDate DESC) FROM Project__c WHERE Id IN :projectIds]);
        //fetching PR which has Amount of Expenditure to date is big as compare to other PRs on perticular Project

        //for  Filter using Expenditure to Date
        Map<Id, Project__c> idToProjectWithPrsMap = new Map<Id, Project__c>([SELECT Id,
        (SELECT Id, Stage__c, Project__c, ExpenditurestoDate__c,FederalRetentionShare__c, StateRetentionShare__c
        FROM Payment_Requests__r
        WHERE Project__c IN :projectIds
        AND ExpenditurestoDate__c > 0
        AND (PaymentType__c = :ALS_CONSTANTS.PR_PaymentType_Reimbursement OR PaymentType__c = :ALS_CONSTANTS.PR_PaymentType_FinalPayment )
        AND (Stage__c = :ALS_CONSTANTS.PR_Stage_PaymentProcessing OR Stage__c = :ALS_CONSTANTS.PR_Stage_ReturnedProjectPayment OR Stage__c = :ALS_CONSTANTS.PR_Stage_Paid )
        ORDER BY ExpenditurestoDate__c DESC limit 1)
        FROM Project__c where Id IN :projectIds]);

        for(Project__c proj : idToProjectWithPrsMap.values()){
            List<Payment_Request__c> pr = idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r;
            if(pr.size() >0){
                proj.Expenditure_To_Date__c = idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r[0].ExpenditurestoDate__c;
                proj.Federal_Retention_To_Date__c = idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r[0].FederalRetentionShare__c == null?0.00:idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r[0].FederalRetentionShare__c;
                proj.State_Retention_To_Date__c = idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r[0].StateRetentionShare__c == null?0.00:idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r[0].StateRetentionShare__c;
                proj.Total_Retention_To_Date__c = (idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r[0].FederalRetentionShare__c == null?0.00:idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r[0].FederalRetentionShare__c)+(idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r[0].StateRetentionShare__c == null?0.00:idToProjectWithPrsMap.get(proj.Id).Payment_Requests__r[0].StateRetentionShare__c);
                projectsToUpdate.add(proj);
            } else{
                proj.Expenditure_To_Date__c = 0;
                proj.Federal_Retention_To_Date__c = 0;
                proj.State_Retention_To_Date__c = 0;
                proj.Total_Retention_To_Date__c = 0;
                projectsToUpdate.add(proj);
            }
        }
        if(projectsToUpdate.size() > 0) {
            update projectsToUpdate;
        }
    }
    public void finish(Database.BatchableContext bc) {
    }
}