codepkg/objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>ApprovedFederalPaymentAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is copy of &quot;Federal Estimated payment Amount&quot;. This is used for overriding purpose.</description>
        <inlineHelpText>Copy of &quot;Federal Estimated payment Amount&quot;</inlineHelpText>
        <label>Approved Federal Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ApprovedStatePaymentAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is a copy of &quot;State Estimated Payment Amount&quot;, which is used for Overriding purpose.</description>
        <inlineHelpText>Copy of &quot;State Estimated Payment Amount&quot;.</inlineHelpText>
        <label>Approved State Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project for which this Payment is Requested?</description>
        <inlineHelpText>Project for which this Payment is Requested?</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of Payment Request</description>
        <inlineHelpText>Stage of Payment Request</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Reviewed - Needs Information</fullName>
                </value>
                <value>
                    <fullName>Payment Processing</fullName>
                </value>
                <value>
                    <fullName>Returned Project Payment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalAdminShareAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>&quot;Net Admin Amount Available&quot; of the Project.</description>
        <inlineHelpText>&quot;Net Admin Amount Available&quot; of the Project.</inlineHelpText>
        <label>Total Admin Share Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Admin_Amount_Approved__c</fullName>
        <description>Total Admin Amount Approved on the Project.</description>
        <formula>Project__r.Total_Admin_Amount_Approved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Admin Amount Approved on the Project.</inlineHelpText>
        <label>Total Admin Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Admin_Amount_Requested__c</fullName>
        <description>Total Admin Amount Requested on the Project</description>
        <formula>Project__r.Total_Admin_Amount_Requested__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Admin Amount Requested on the Project</inlineHelpText>
        <label>Total Admin Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Federal_Amount_Approved__c</fullName>
        <description>Total Federal Amount Approved on the Project.</description>
        <formula>Project__r.Total_Federal_Amount_Approved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Federal Amount Approved on the Project.</inlineHelpText>
        <label>Total Federal Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Federal_Amount_Requested__c</fullName>
        <description>Total Federal Amount Requested on the Project.</description>
        <formula>Project__r.Total_Federal_Amount_Requested__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Federal Amount Requested on the Project.</inlineHelpText>
        <label>Total Federal Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_State_Amount_Approved__c</fullName>
        <description>Total State Amount Approved on the Project.</description>
        <formula>Project__r.Total_State_Amount_Approved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total State Amount Approved on the Project.</inlineHelpText>
        <label>Total State Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_State_Amount_Requested__c</fullName>
        <description>Total State Amount Requested on the Project.</description>
        <formula>Project__r.Total_State_Amount_Requested__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total State Amount Requested on the Project.</inlineHelpText>
        <label>Total State Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The Project Stage.</description>
        <inlineHelpText>The current processing stage of the Project. (e.g. New, Obligated, Compliance Verification, Payment, etc.)</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Obligating</fullName>
                    <label>Obligated</label>
                </value>
                <value>
                    <fullName>Compliance Verification</fullName>
                </value>
                <value>
                    <fullName>Active Payment</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Deobligation</fullName>
                    <isActive>false</isActive>
                    <label>Deobligation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Admin_Amount_Approved__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Admin Amount Approved on the Project. This field is the sum of the &quot;Total Admin Share Amount&quot; of all the PRs of this Project, which is in the &quot;Payment Processing / Returned Project Payment / Paid&quot; stage.</description>
        <inlineHelpText>This field is the sum of the &quot;Total Admin Share Amount&quot; of all the PRs of this Project, which is in the &quot;Payment Processing / Returned Project Payment / Paid&quot; stage.</inlineHelpText>
        <label>Total Admin Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Admin_Amount_Requested__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Admin Amount Requested on the Project. This field is the sum of the &quot;Total Admin Share Amount&quot; of all the PRs of this Project except the one which is in the &quot;Withdrawn&quot; stage.</description>
        <inlineHelpText>This field is the sum of the &quot;Total Admin Share Amount&quot; of all the PRs of this Project except the one which is in the &quot;Withdrawn&quot; stage.</inlineHelpText>
        <label>Total Admin Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Federal_Amount_Approved__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Federal Amount Approved on the Project. This field is the sum of the &quot;Approved Federal Payment Amount&quot; of all the PRs of this Project, which is in the &quot;Payment Processing / Returned Project Payment / Paid&quot; stage.</description>
        <inlineHelpText>This field is the sum of the &quot;Approved Federal Payment Amount&quot; of all the PRs of this Project, which is in the &quot;Payment Processing / Returned Project Payment / Paid&quot; stage.</inlineHelpText>
        <label>Total Federal Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Federal_Amount_Requested__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Federal Amount Requested on the Project. This field is the sum of the &quot;Approved Federal Payment Amount&quot; of all the PRs of this Project except the one which is in the &quot;Withdrawn&quot; stage.</description>
        <inlineHelpText>This field is the sum of the &quot;Approved Federal Payment Amount&quot; of all the PRs of this Project except the one which is in the &quot;Withdrawn&quot; stage.</inlineHelpText>
        <label>Total Federal Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_State_Amount_Approved__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total State Amount Approved on the Project. This field is the sum of the &quot;Approved State Payment Amount&quot; of all the PRs of this Project, which is in the &quot;Payment Processing / Returned Project Payment / Paid&quot; stage.</description>
        <inlineHelpText>This field is the sum of the &quot;Approved State Payment Amount&quot; of all the PRs of this Project, which is in the &quot;Payment Processing / Returned Project Payment / Paid&quot; stage.</inlineHelpText>
        <label>Total State Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_State_Amount_Requested__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total State Amount Requested on the Project.This field is the sum of the &quot;Approved State Payment Amount&quot; of all the PRs of this Project except the one which is in the &quot;Withdrawn&quot; stage.</description>
        <inlineHelpText>This field is the sum of the &quot;Approved State Payment Amount&quot; of all the PRs of this Project except the one which is in the &quot;Withdrawn&quot; stage.</inlineHelpText>
        <label>Total State Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/UpdateRequestedAndApprovedAmountJob.cls
/**
 * Created by Ricky on 29-03-2021.
 */

public with sharing class UpdateRequestedAndApprovedAmountJob implements Database.Batchable<sObject>, Schedulable {
    private final String query;

    public UpdateRequestedAndApprovedAmountJob(String query) {
        this.query = query;
    }

    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new UpdateRequestedAndApprovedAmountJob(query));
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        List<Project__c> projectListToProcess = (List<Project__c>) scope;
        Set<Id> projectIds = new Set<Id>();
        for (Project__c project : projectListToProcess) {
            projectIds.add(project.Id);
        }

        List<String> stageList = new List<String>();
        stageList.add(ALS_CONSTANTS.PR_Stage_Paid);//stageList.add('Paid');
        stageList.add(ALS_CONSTANTS.PR_Stage_PaymentProcessing);//stageList.add('Payment Processing');
        stageList.add(ALS_CONSTANTS.PR_Stage_ReturnedProjectPayment);

        List<AggregateResult> approvedAmountResults = [SELECT Project__c, SUM(TotalAdminShareAmount__c)totalApprovedAdminAmount,
                SUM(ApprovedStatePaymentAmount__c) totalApprovedStateAmount, SUM(ApprovedFederalPaymentAmount__c)totalApprovedFederalAmount
        FROM Payment_Request__c WHERE Project__c IN : projectIds AND Stage__c IN : stageList GROUP BY Project__c];
        Map<Id, AggregateResult> projectIdToApprovedAmountAggregateResult = new Map<Id, AggregateResult>();
        if (approvedAmountResults.size() > 0) {
            for (AggregateResult result : approvedAmountResults) {
                Id projectId = (Id)result.get('Project__c');
                projectIdToApprovedAmountAggregateResult.put(projectId, result);
            }
        }

        List<AggregateResult> RequestedAmountResults = [SELECT Project__c, sum(TotalAdminShareAmount__c)totalRequestedAdminAmount,
                SUM(ApprovedStatePaymentAmount__c) totalRequestedStateAmount, SUM(ApprovedFederalPaymentAmount__c)totalRequestedFederalAmount
        FROM Payment_Request__c WHERE Project__c IN : projectIds AND Stage__c !=: ALS_CONSTANTS.PR_Stage_Withdrawn GROUP BY Project__c];

        Map<Id, AggregateResult> projectIdToRequestedAmountAggregateResult = new Map<Id, AggregateResult>();
        if (RequestedAmountResults.size() > 0) {
            for (AggregateResult result : RequestedAmountResults) {
                Id projectId = (Id)result.get('Project__c');
                projectIdToRequestedAmountAggregateResult.put(projectId, result);
            }
        }

        for (Project__c projectToProcess : projectListToProcess) {
            //Updating Requested Payment Amount on Project...
            AggregateResult requestedAmountResult = projectIdToRequestedAmountAggregateResult?.get(projectToProcess.Id);
            Decimal totalRequestedAdminAmount = (Decimal) requestedAmountResult?.get('totalRequestedAdminAmount') == null? 0.00 : (Decimal) requestedAmountResult?.get('totalRequestedAdminAmount');
            Decimal totalRequestedStateAmount = (Decimal) requestedAmountResult?.get('totalRequestedStateAmount') == null? 0.00 : (Decimal) requestedAmountResult?.get('totalRequestedStateAmount');
            Decimal totalRequestedFederalAmount = (Decimal) requestedAmountResult?.get('totalRequestedFederalAmount') == null? 0.00 : (Decimal) requestedAmountResult?.get('totalRequestedFederalAmount');
            projectToProcess.Total_Admin_Amount_Requested__c = totalRequestedAdminAmount==null? 0.00 :totalRequestedAdminAmount;
            projectToProcess.Total_State_Amount_Requested__c = ((totalRequestedStateAmount==null? 0.00 :totalRequestedStateAmount) - (totalRequestedAdminAmount==null? 0.00 :totalRequestedAdminAmount));
            projectToProcess.Total_Federal_Amount_Requested__c = totalRequestedFederalAmount==null? 0.00 :totalRequestedFederalAmount;

            //Updating Approved Payment Amount on Project...
            AggregateResult approvedAmountResult = projectIdToApprovedAmountAggregateResult?.get(projectToProcess.Id);
            Decimal totalApprovedAdminAmount = (Decimal) approvedAmountResult?.get('totalApprovedAdminAmount') == null? 0.00 : (Decimal) approvedAmountResult?.get('totalApprovedAdminAmount');
            Decimal totalApprovedStateAmount = (Decimal) approvedAmountResult?.get('totalApprovedStateAmount') == null? 0.00 : (Decimal) approvedAmountResult?.get('totalApprovedStateAmount');
            Decimal totalApprovedFederalAmount = (Decimal) approvedAmountResult?.get('totalApprovedFederalAmount') == null? 0.00 : (Decimal) approvedAmountResult?.get('totalApprovedFederalAmount');
            projectToProcess.Total_Admin_Amount_Approved__c = totalApprovedAdminAmount==null? 0.00 :totalApprovedAdminAmount;
            projectToProcess.Total_State_Amount_Approved__c = ((totalApprovedStateAmount==null? 0.00 :totalApprovedStateAmount) - (totalApprovedAdminAmount==null? 0.00 :totalApprovedAdminAmount));
            projectToProcess.Total_Federal_Amount_Approved__c = totalApprovedFederalAmount==null? 0.00 :totalApprovedFederalAmount;
        }

        update projectListToProcess;
    }

    public void finish(Database.BatchableContext bc) {
    }
}