codepkg/objects/Pre_Application__c.object
<CustomObject>
    <fields>
        <fullName>Current_Stage__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
                <value>
                    <fullName>Analyst Review</fullName>
                </value>
                <value>
                    <fullName>Request for Information</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Manager Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HMANOI_EditRequestCtrlTest.cls
@isTest(seeAllData=false)
public with sharing class HMANOI_EditRequestCtrlTest {
    @isTest 
    static void testGetInitData(){
        Pre_Application__c PreApplication = HMA_TestHelper.getPreApplication(true);
        PreApplication.Status__c ='Pending Review';
        PreApplication.Current_Stage__c ='Record Submitted';
        update PreApplication;
        string preAppId = String.valueOf(PreApplication.Id);       
        test.startTest();
        Map<String, Object> returnMap = HMANOI_EditRequestCtrl.getInitData(preAppId);
        test.stopTest();
        system.assert(returnMap.size()>0);
    }
    @isTest 
    static void testGetInitData1(){
        Pre_Application__c PreApplication = HMA_TestHelper.getPreApplication(true);
        PreApplication.Status__c ='Analyst Review';
        update PreApplication;
        string preAppId = String.valueOf(PreApplication.Id);       
        test.startTest();
        Map<String, Object> returnMap = HMANOI_EditRequestCtrl.getInitData(preAppId);
        test.stopTest();
        system.assert(returnMap.size()>0);
    }
}