codepkg/objects/Pre_Application__c.object
<CustomObject>
    <fields>
        <fullName>Current_Stage__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
                <value>
                    <fullName>Analyst Review</fullName>
                </value>
                <value>
                    <fullName>Request for Information</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Review</fullName>
                    <isActive>false</isActive>
                    <label>Pending Manager Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/HMANOI_EditRequestCtrl.cls
/***********************************************************************************************************************************
* Class Name   : HMANOI_EditRequestCtrl
* Description  : This class for get data to HMA NOI Edit Request
* Author       : Pankaj
* Created On   : 07/12/2020
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Pankaj              07/12/2020       Initial Implementation
**************************************************************************************************************************************/

public without sharing class HMANOI_EditRequestCtrl {
    
    /***********************************************
    * Method Name : getInitData
    * Author : Pankaj
    * Inputs : String preAppId
    * Description: This method return map of Object
    *********************************************/
    @AuraEnabled
    public static Map<String, Object> getInitData(String preAppId) {
        Boolean isEdit;
        Map<String, Object> returnMap  = new Map<String, Object>();
        Pre_Application__c preApp = [Select id, Current_Stage__c,Status__c from Pre_Application__c where Id =: preAppId];
        if(preApp.Status__c == 'Draft' || preApp.Status__c == 'Pending Review') {
            isEdit = true;
            returnMap.put('isEdit', isEdit);
            if(preApp.Current_Stage__c == 'Record Submitted') {
                preApp.Current_Stage__c = 'GeneralInfo';
            }
            returnMap.put('currentStage', preApp.Current_Stage__c);
        }else {
            isEdit = false;
            returnMap.put('isEdit', isEdit);
            returnMap.put('currentStage', preApp.Current_Stage__c);
        }
        return returnMap;
    }
}