codepkg/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Master_Label_Program_Name__c</fullName>
        <description>Internal</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This Field is Used in Custom Implementation and must not be changed without informing the Administrator.</inlineHelpText>
        <label>Program Name(Master Label)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Name, Derives from Disaster Grant/FO.</description>
        <inlineHelpText>The grant program from which the Project originates. This field is used for reporting.</inlineHelpText>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <description>The Federal State Assigned Project Number - FDSR or PA State Project Number.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Project Identifer (PW/DSR/PJ/PL)</inlineHelpText>
        <label>Project (PW/DSR/PJ/PL)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/REAL_UpdateProgPrefixOnProjectNumJob.cls
/***********************************************************************************************************************************
* Class Name   : REAL_UpdateProgPrefixOnProjectNumJob
* Description  : This batch job is created append the Program prefix to project Number for PA Programs.
* Author       : Ricky
* Created On   : 04/08/2021
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer             Date             Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Ricky              17/07/2021       Initial Implementation
**************************************************************************************************************************************/

public with sharing class REAL_UpdateProgPrefixOnProjectNumJob implements Database.Batchable<SObject>, Schedulable {
    private final String query;

    public REAL_UpdateProgPrefixOnProjectNumJob(String query) {
        this.query = query;
    }

    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new REAL_UpdateProgPrefixOnProjectNumJob(query));
    }

    // Database.Batchable methods
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        TriggerHelper.skipTrigger = true;
        List<Project__c> projectWithPrimaryAuthorizedAgentList = (List<Project__c>) scope;
        List<Project__c> projectToUpdateList = new List<Project__c>();

        for (Project__c project : projectWithPrimaryAuthorizedAgentList) {
            if (project.Project_Number__c != null) {
                if (project.Program_Name__r.Master_Label_Program_Name__c == ALS_CONSTANTS.Program_CDAA) {
                    if (!project.Project_Number__c.startsWith('DSR')) {
                        project.Project_Number__c = 'DSR-'+project.Project_Number__c;
                        projectToUpdateList.add(project);
                    }
                }
                else if (project.Program_Name__r.Master_Label_Program_Name__c == ALS_CONSTANTS.Program_PA_Federal
                        || project.Program_Name__r.Master_Label_Program_Name__c == ALS_CONSTANTS.Program_PA_FMAG) {
                    if (!project.Project_Number__c.startsWith('PW')) {
                        project.Project_Number__c = 'PW-'+project.Project_Number__c;
                        projectToUpdateList.add(project);
                    }
                }
            }
        }
        if (projectToUpdateList?.size() > 0) {
            update projectToUpdateList;
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}