codepkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>FEMA_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The FEMA Cost Share for this Project. The values are inherited from the Program Cost Share.</description>
        <inlineHelpText>Percentage of the Project Amount ($) that will be paid by FEMA.  Equal to the Federal Share ($) divided by the Project Amount ($).</inlineHelpText>
        <label>FEMA Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Federal_Project_Award__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Federal Amount awarded to the Project.</description>
        <inlineHelpText>This is the Total Amount of money FEMA has awarded for this Project.</inlineHelpText>
        <label>Federal Project Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FundingSource__c</fullName>
        <description>Funding Source of the Project.</description>
        <inlineHelpText>Select &quot;Federal Only,&quot; &quot;State Only,&quot; or &quot;Federal and State&quot; according to Subrecipient, Incident, and Category eligibility.</inlineHelpText>
        <label>Funding Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Federal and State</fullName>
                </value>
                <value>
                    <fullName>Federal Only</fullName>
                </value>
                <value>
                    <fullName>State Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Project_Award__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total State Amount awarded to the Project.</description>
        <inlineHelpText>This is the portion of Total Project Award that the State will award to the Subrecipient.</inlineHelpText>
        <label>State Project Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Share__c</fullName>
        <defaultValue>0</defaultValue>
        <description>State Share Cost Component only applies to Non Disaster Grants or PA Projects</description>
        <inlineHelpText>Percentage of the Project Amount ($) that was not covered by FEMA that will be paid out by Cal OES as CDAA funds.</inlineHelpText>
        <label>State Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Project_Award__c</fullName>
        <description>The Total Amount Awarded by FEMA for the cost of the project.</description>
        <inlineHelpText>This is the total cost of the approved Project. Any cost share percentage calculations start from this value.</inlineHelpText>
        <label>Total Project Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/updateStateFederalAwardOfProjectJob.cls
/**
 * Created by Ricky on 12-05-2021.
 */

public with sharing class updateStateFederalAwardOfProjectJob implements Database.Batchable<sObject>, Schedulable {
    private final String query;

    public updateStateFederalAwardOfProjectJob(String query) {
        this.query = query;
    }

    // Schedulable method
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new updateStateFederalAwardOfProjectJob(query));
    }

    // Database.Batchable methods
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Project__c> projectList = (List<Project__c>)scope;
        List<Project__c> projectToUpdateList = new List<Project__c>();
        for (Project__c projectToProcess : projectList) {
            Decimal totalProjectAward = projectToProcess.Total_Project_Award__c == null ? 0.00 : projectToProcess.Total_Project_Award__c;
            Decimal stateSharePercentage = projectToProcess.State_Share__c == null ? 0.00 : projectToProcess.State_Share__c;
            Decimal femaSharePercentage = projectToProcess.FEMA_Share__c == null ? 0.00 : projectToProcess.FEMA_Share__c;
            if (projectToProcess.FundingSource__c != null) {
                if(projectToProcess.FundingSource__c == ALS_CONSTANTS.Project_FundingSource_FederalAndState
                        || projectToProcess.FundingSource__c == ALS_CONSTANTS.Project_FundingSource_FederalOnly) {
                    projectToProcess.Federal_Project_Award__c = (totalProjectAward * femaSharePercentage)/100;
                }
                if(projectToProcess.FundingSource__c == ALS_CONSTANTS.Project_FundingSource_FederalAndState
                        || projectToProcess.FundingSource__c == ALS_CONSTANTS.Project_FundingSource_StateOnly) {
                    projectToProcess.State_Project_Award__c = (totalProjectAward * stateSharePercentage)/100;
                }
                projectToUpdateList.add(projectToProcess);
            }
        }

        if(projectToUpdateList.size() > 0) {
            update projectToUpdateList;
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}