codepkg/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Shipment_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To Store Shipment Order Number</description>
        <label>Shipment Order</label>
        <referenceTo>Shipment_Order__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Shipment_Order__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Sent to Warehouse</fullName>
                </value>
                <value>
                    <fullName>Out for Delivery</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>InTransit</fullName>
                    <isActive>false</isActive>
                    <label>InTransit</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                    <isActive>false</isActive>
                    <label>Sent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Shipment_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment_Order__c</referenceTo>
        <relationshipLabel>Shipment Order Line Items</relationshipLabel>
        <relationshipName>Shipment_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Sent to Warehouse</fullName>
                </value>
                <value>
                    <fullName>Out for Delivery</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                    <isActive>false</isActive>
                    <label>Sent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment Order Line Item</label>
    <nameField>
        <displayFormat>SLI-{0000}</displayFormat>
        <label>Shipment Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/ShipmentLineItemTriggerHelperTest.cls
@isTest(seeAllData=false) 
public class ShipmentLineItemTriggerHelperTest {
    @isTest static void testShipmentLineItem() {
     //  List<Shipment_Order_Line_Item__c> shipmentOrderLineItems = new List<Shipment_Order_Line_Item__c>();
        test.startTest();
        
        Shipment_Order__c shipmentOrder = PHOS_TestHelper.getShipmentOrder(true);
        Shipment_Order_Line_Item__c shipmentOrderLineItem1 = PHOS_TestHelper.getShipmentOrderLineItem(false);
        shipmentOrderLineItem1.Status__c = PHOS_Constants.SHIPMENT_LINE_ORDER_STATUS_READY;
        shipmentOrderLineItem1.Shipment__c = shipmentOrder.Id;
        
        insert shipmentOrderLineItem1;
       
		shipmentOrderLineItem1.Status__c =PHOS_Constants.SHIPMENT_LINE_ORDER_STATUS_Rejected;        
        update shipmentOrderLineItem1;
        test.stopTest();   
    }
}