codepkg/objects/Support_Resource__c.object
<CustomObject>
    <fields>
        <fullName>As_of_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>As of Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <label>Support Resource</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Support Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/DIP_SupportResourcesDetailCtrlTest.cls
/**
 * Created by Admin on 14-05-2020.
 */
@IsTest
private  class DIP_SupportResourcesDetailCtrlTest {
    @IsTest
    static void testBehavior() {
        Test.startTest();

        Support_Resource__c testItem = new Support_Resource__c();
        testItem.Description__c = 'this is a test Resource';
        testItem.Is_Active__c = true;
        testItem.As_of_Date__c = System.now().date();
        insert testItem;

        Map<String,Object> resultMap = (Map<String,Object>) DIP_SupportResourcesDetailCtrl.getSupportResources();

        Support_Resource__c testItemAnother = (Support_Resource__c)resultMap.get('SupportResources');

        System.assert(testItemAnother.Id ==testItem.Id);

        Test.stopTest();
    }
}