codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alameda, County of</fullName>
                </value>
                <value>
                    <fullName>Alpine, County of</fullName>
                </value>
                <value>
                    <fullName>Amador, County of</fullName>
                </value>
                <value>
                    <fullName>Butte, County of</fullName>
                </value>
                <value>
                    <fullName>Calaveras, County of</fullName>
                </value>
                <value>
                    <fullName>Colusa, County of</fullName>
                </value>
                <value>
                    <fullName>Contra Costa, County of</fullName>
                </value>
                <value>
                    <fullName>Del Norte, County of</fullName>
                </value>
                <value>
                    <fullName>El Dorado, County of</fullName>
                </value>
                <value>
                    <fullName>Fresno, County of</fullName>
                </value>
                <value>
                    <fullName>Glenn, County of</fullName>
                </value>
                <value>
                    <fullName>Humboldt, County of</fullName>
                </value>
                <value>
                    <fullName>Imperial, County of</fullName>
                </value>
                <value>
                    <fullName>Inyo, County of</fullName>
                </value>
                <value>
                    <fullName>Kern, County of</fullName>
                </value>
                <value>
                    <fullName>Kings, County of</fullName>
                </value>
                <value>
                    <fullName>Lake, County of</fullName>
                </value>
                <value>
                    <fullName>Lassen, County of</fullName>
                </value>
                <value>
                    <fullName>Los Angeles, County of</fullName>
                </value>
                <value>
                    <fullName>Madera, County of</fullName>
                </value>
                <value>
                    <fullName>Marin, County of</fullName>
                </value>
                <value>
                    <fullName>Mariposa, County of</fullName>
                </value>
                <value>
                    <fullName>Mendocino, County of</fullName>
                </value>
                <value>
                    <fullName>Merced, County of</fullName>
                </value>
                <value>
                    <fullName>Modoc, County of</fullName>
                </value>
                <value>
                    <fullName>Mono, County of</fullName>
                </value>
                <value>
                    <fullName>Monterey, County of</fullName>
                </value>
                <value>
                    <fullName>Napa, County of</fullName>
                </value>
                <value>
                    <fullName>Nevada, County of</fullName>
                </value>
                <value>
                    <fullName>Orange, County of</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Tribal</fullName>
                </value>
                <value>
                    <fullName>Special District</fullName>
                </value>
                <value>
                    <fullName>Courts</fullName>
                </value>
                <value>
                    <fullName>Fire Agency</fullName>
                </value>
                <value>
                    <fullName>MARS Paying Entity</fullName>
                </value>
                <value>
                    <fullName>Federal Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CountyUserReigstrationCtrlTest.cls
@IsTest(SeeAllData=false)
public class CountyUserReigstrationCtrlTest {
	@testSetup
    public static void setup(){
        
        Account acc = new Account();
        acc.Name  = '01 - Alameda';
        acc.Queue_Name__c = 'RDMHS_Region_11';
        insert acc;
        Account acc1 = new Account();
        acc1.Name  = 'State 1';
        acc1.Entity_Type__c = 'State Agency';
        insert acc1;
        
        Group grp = new Group(Name='RDMHS Region 11',Type='Queue', DeveloperName='RDMHS_Region_11');
        insert grp;
        
        QueueSobject mappingObject = new QueueSobject(QueueId = grp.Id, SobjectType = 'User_Registration__c');
        User usr = [Select id from User where Id = :UserInfo.getUserId()];
		System.RunAs(usr){
        insert mappingObject;
        }
        
        /*Group testGroup = new Group(Name='RDMHS Region 11', DeveloperName='RDMHS_Region_11', Type='Queue');
		insert testGroup;*/
        
		User_Registration__c userReg = new User_Registration__c();
        userReg.First_Name__c = 'Test';
        userReg.Last_Name__c = 'User';
        userReg.Phone__c = '123456789';
        userReg.Email__c = 'test@test.com';
        userReg.County__c = '01 - Alameda';
        userReg.Status__c = 'Pending for Approval';
        userReg.Entity_Type__c = 'County';
        insert userReg;
    }
    
    @IsTest
    public static void test1() {
        
        Test.startTest();
        //CountyUserReigstrationCtrl.createUserRegistrationRequest('Test','User','test@test.com','123456789','County','01 - Alameda','','','');
        CountyUserReigstrationCtrl.getStateAgencies();
        CountyUserReigstrationCtrl.apexSearchStateAgency('01 - Alameda',null);
        Test.stopTest();
    }
}