codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <description>This field is used in MARS application to determine the access level they want for each agency</description>
        <inlineHelpText>User&apos;s access level</inlineHelpText>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Registrations</relationshipLabel>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Tribal</fullName>
                </value>
                <value>
                    <fullName>Special District</fullName>
                </value>
                <value>
                    <fullName>Courts</fullName>
                </value>
                <value>
                    <fullName>Fire Agency</fullName>
                </value>
                <value>
                    <fullName>MARS Paying Entity</fullName>
                </value>
                <value>
                    <fullName>Federal Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fire_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for users who wants to register as a contact for fire agencies. MARS app uses this field the most.</description>
        <label>Fire Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Fire Agency</value>
            </filterItems>
            <infoMessage>Please choose the Fire Agency (MARS Application)</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations (Fire Agency)</relationshipLabel>
        <relationshipName>User_Registrations6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <recordTypes>
        <fullName>MARS</fullName>
        <active>true</active>
        <description>This recordtype is used for MARS Application access requests</description>
        <label>MARS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Registration</fullName>
        <active>true</active>
        <label>Registration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/MARS_Agency_Personnel_Ctrl.cls
public without sharing class MARS_Agency_Personnel_Ctrl {


    @AuraEnabled(cacheable=true)

    public static List<AccountContactRelation> getAgenciesUsersList(String accountId) {

        List<AccountContactRelation> agencyAdminList = 
        [SELECT  Id, Relationship_Strength__c, AccountId, Account.Name, 
        ContactId, Contact.FirstName, Contact.LastName,Contact.Phone, Contact.Email, IsActive 
        FROM AccountContactRelation WHERE AccountId =: accountId ];

        return agencyAdminList;

    }


    @AuraEnabled(cacheable=true)

    public static List<User_Registration__c> getPendingAgenciesUsersList(String accountId) {

        
        List<User_Registration__c> agencyPendingList = 
        [SELECT Id, First_Name__c, Last_Name__c, Access_Level__c, Email__c, Phone__c, Fire_Agency__c, Contact_Name__r.Phone 
        FROM User_Registration__c 
        WHERE
        (Status__c = 'App Requested' or Status__c = 'Access Level Change Requested' or Status__c = 'Additional Agency Requested') and (Fire_Agency__c =: accountId )];

        return agencyPendingList;

    }

    @AuraEnabled(cacheable=true)

    public static AggregateResult[]  getPendingAgenciesUsersCount(String accountId) {

        
        AggregateResult[] agencyPendingList = 
        [SELECT COUNT(Id)  
        FROM User_Registration__c 
        WHERE
        (Status__c = 'App Requested' or Status__c = 'Access Level Change Requested' or Status__c = 'Additional Agency Requested') and (Fire_Agency__c =: accountId )];


        return agencyPendingList;

    }



    @AuraEnabled
    public static void submitUserAccessChangeRequest(string accessLevel, string accountId, string contactId){
        try {


            string newAccessLevel;

            if(accessLevel == 'Primary')
            {
                newAccessLevel='Secondary';
            }

            if(accessLevel == 'Secondary')
            {
                newAccessLevel='Primary';
            }


            //GET User Id from Contact Id
            User userChange = [SELECT Id,FirstName,LastName,Email FROM User WHERE  ContactId =: contactId LIMIT 1];           
            Group recordOwner = [SELECT Id, DeveloperName FROM Group WHERE DeveloperName ='MARS_User_Request_Approval'];
            User_Registration__c registration = new User_Registration__c();
            registration.RecordtypeId = Schema.SObjectType.User_Registration__c.getRecordTypeInfosByDeveloperName().get('MARS').getRecordTypeId();
            registration.First_Name__c =  userChange.FirstName;
            registration.Last_Name__c = userChange.LastName;
            registration.Email__c = userChange.Email;
            registration.Fire_Agency__c = accountId;
            registration.Status__c = 'Access Level Change Requested';
            registration.Entity_Type__c = 'Fire Agency';
            registration.Access_Level__c = newAccessLevel;
            registration.Contact_Name__c = contactId;
            registration.User__c = userChange.Id; 
            //registration.OwnerId = '00G35000001WF88'; //To-Do Query the Queue and get the Id
            registration.OwnerId = userChange.Id;
            insert registration;

            registration.Status__c = 'Access Level Change Approved';

            update registration;


            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void submitUserAccessApproveRequest(string userregid){
        try {



            User_Registration__c ur = [SELECT Id, Status__c
                                                    FROM User_Registration__c
                                                    WHERE Id = :userregid
                                                     LIMIT 1];


            string newAccessLevel;

            if(ur.Status__c == 'App Requested')
            {
                newAccessLevel='App Approved';
            }

            if(ur.Status__c == 'Access Level Change Requested')
            {
                newAccessLevel='Access Level Change Approved';
            }

              ur.Status__c = newAccessLevel;

            update ur;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void submitUserAccessRejectRequest(string userregid){
        try {

            User_Registration__c ur = [SELECT Id, Status__c
                                                    FROM User_Registration__c
                                                    WHERE Id = :userregid
                                                     LIMIT 1];

              string newAccessLevel;

              if(ur.Status__c == 'App Requested')
              {
                  newAccessLevel='App Rejected';
              }
  
              if(ur.Status__c == 'Access Level Change Requested')
              {
                  newAccessLevel='Access Level Change Rejected';
              }
  
                ur.Status__c = newAccessLevel;


            update ur;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void submitRemoveUserAccessRequest(string accessLevel, string accountId, string contactId){
        try {


            AccountContactRelation acr = [SELECT Id, AccountId, ContactId, Relationship_Strength__c 
                                                    FROM AccountContactRelation
                                                    WHERE AccountId = :accountId
                                                    AND ContactId = :contactId LIMIT 1];

              acr.IsActive = false;
            update acr;                                 

           
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void submitAddUserAccessRequest(string accessLevel, string accountId, string contactId){
        try {


            AccountContactRelation acr = [SELECT Id, AccountId, ContactId, Relationship_Strength__c 
                                                    FROM AccountContactRelation
                                                    WHERE AccountId = :accountId
                                                    AND ContactId = :contactId LIMIT 1];

              acr.IsActive = true;
            update acr;                                 

           
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled public static Boolean getRelationshipStrength(String accountId) {
        User userRec = [ SELECT Id, ContactId FROM User WHERE Id
                        =:UserInfo.getUserId() LIMIT 1 ];
        AccountContactRelation acr = [
            SELECT Id,
            Relationship_Strength__c FROM AccountContactRelation WHERE ContactId
            =:userRec.ContactId AND AccountId
            =:accountId LIMIT 1
        ];
        return acr.Relationship_Strength__c == 'Primary';
    }


}