codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alameda, County of</fullName>
                </value>
                <value>
                    <fullName>Alpine, County of</fullName>
                </value>
                <value>
                    <fullName>Amador, County of</fullName>
                </value>
                <value>
                    <fullName>Butte, County of</fullName>
                </value>
                <value>
                    <fullName>Calaveras, County of</fullName>
                </value>
                <value>
                    <fullName>Colusa, County of</fullName>
                </value>
                <value>
                    <fullName>Contra Costa, County of</fullName>
                </value>
                <value>
                    <fullName>Del Norte, County of</fullName>
                </value>
                <value>
                    <fullName>El Dorado, County of</fullName>
                </value>
                <value>
                    <fullName>Fresno, County of</fullName>
                </value>
                <value>
                    <fullName>Glenn, County of</fullName>
                </value>
                <value>
                    <fullName>Humboldt, County of</fullName>
                </value>
                <value>
                    <fullName>Imperial, County of</fullName>
                </value>
                <value>
                    <fullName>Inyo, County of</fullName>
                </value>
                <value>
                    <fullName>Kern, County of</fullName>
                </value>
                <value>
                    <fullName>Kings, County of</fullName>
                </value>
                <value>
                    <fullName>Lake, County of</fullName>
                </value>
                <value>
                    <fullName>Lassen, County of</fullName>
                </value>
                <value>
                    <fullName>Los Angeles, County of</fullName>
                </value>
                <value>
                    <fullName>Madera, County of</fullName>
                </value>
                <value>
                    <fullName>Marin, County of</fullName>
                </value>
                <value>
                    <fullName>Mariposa, County of</fullName>
                </value>
                <value>
                    <fullName>Mendocino, County of</fullName>
                </value>
                <value>
                    <fullName>Merced, County of</fullName>
                </value>
                <value>
                    <fullName>Modoc, County of</fullName>
                </value>
                <value>
                    <fullName>Mono, County of</fullName>
                </value>
                <value>
                    <fullName>Monterey, County of</fullName>
                </value>
                <value>
                    <fullName>Napa, County of</fullName>
                </value>
                <value>
                    <fullName>Nevada, County of</fullName>
                </value>
                <value>
                    <fullName>Orange, County of</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Tribal</fullName>
                </value>
                <value>
                    <fullName>Special District</fullName>
                </value>
                <value>
                    <fullName>Courts</fullName>
                </value>
                <value>
                    <fullName>Fire Agency</fullName>
                </value>
                <value>
                    <fullName>MARS Paying Entity</fullName>
                </value>
                <value>
                    <fullName>Federal Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Federal_Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Federal Tax ID #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Governmental_Entity__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Non-Governmental Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <recordTypes>
        <fullName>PHOS</fullName>
        <active>true</active>
        <label>PHOS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/UserRegistrationHelperTest.cls
@isTest(SeeAllData=true)
public class UserRegistrationHelperTest {
	
    /*@IsTest
    public static void test1() {
        Test.startTest();

        Account acc = new Account();
        acc.Name  = 'Alameda, County of';
        acc.Queue_Name__c = 'RDMHS_Region_11';
        insert acc;

        Contact c = new Contact(LastName = 'Contact Last Name', AccountId = acc.id);
        insert c;

        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='PHOS Customer Community Plus Login User'].id; 
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@appssm111ssirio.com';   
        user.CommunityNickname = 'testcccUser123';
        user.Alias = 't1';
        user.Email = 'no1111@emakkkkkil.com';
        user.IsActive = true;
        user.ContactId = c.Id;
 
        insert user;
            System.RunAs(user) {
                User_Registration__c userReg = new User_Registration__c();
                userReg.First_Name__c = 'Test';
                userReg.Last_Name__c = 'User';
                userReg.Phone__c = '123456789';
                userReg.Email__c = 'test@111test.com';
                userReg.County__c = 'Alameda, County of';
                userReg.Status__c = 'Pending for Approval';
                userReg.Entity_Type__c= 'County';
                insert userReg;
                User_Registration__c userReg1 = new User_Registration__c();
                userReg1.Id = userReg.Id;
                userReg1.Status__c = 'Approved';
                update userReg1;
            }
        Test.stopTest();
    }*/
    @IsTest
    public static void test2() {
        Test.startTest();

        Account acc = new Account();
        acc.Name  = 'SOC OPS';
        acc.Queue_Name__c = 'RDMHS_Region_11';
        insert acc;

        Contact c = new Contact(LastName = 'Contact Last Name1', AccountId = acc.id);
        insert c;

        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='PHOS Customer Community Plus Login User'].id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@aqqqqp11rio.com';   
        user.CommunityNickname = 'testssjjsUser123';
        user.Alias = 't1';
        user.Email = 'no1122qq@eaaaamail.com';
        user.IsActive = true;
        user.ContactId = c.Id;
 
        insert user;
            System.RunAs(user) {
                User_Registration__c userReg = new User_Registration__c();
                userReg.First_Name__c = 'Test';
                userReg.Last_Name__c = 'User';
                userReg.Phone__c = '123456789';
                userReg.Email__c = 'test@111tesmmmt.com';
                userReg.County__c = 'Alameda, County of';
                userReg.Status__c = 'Pending for Approval';
                userReg.Entity_Type__c= 'Non-Governmental Entity';
                userReg.Non_Governmental_Entity__c= 'nnncnnnn';
				userReg.Federal_Tax_ID__c = '332222321143212';
                insert userReg;
                User_Registration__c userReg1 = new User_Registration__c();
                userReg1.Id = userReg.Id;
                userReg1.Status__c = 'Approved';
                update userReg1;
            }
        Test.stopTest();
    }
    @IsTest
    public static void test3() {
        Test.startTest();

        Account acc = new Account();
        acc.Name  = 'SOC OPS';
        acc.Queue_Name__c = 'SOC_OPS';
        insert acc;

        Contact c = new Contact(LastName = 'Contact Last Name2', AccountId = acc.id);
        insert c;

        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='PHOS Customer Community Plus Login User'].id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@aqqq111qp11rio.com';   
        user.CommunityNickname = 'tests111sjjsUser123';
        user.Alias = 't1';
        user.Email = 'no1111122qq@eaaaamail.com';
        user.IsActive = true;
        user.ContactId = c.Id;
 
        insert user;
            System.RunAs(user) {
                User_Registration__c userReg = new User_Registration__c();
                userReg.First_Name__c = 'Test';
                userReg.Last_Name__c = 'User';
                userReg.Phone__c = '123456789';
                userReg.Email__c = 'test@111tcccesmmmt.com';
                userReg.County__c = 'Alameda, County of';
                userReg.Status__c = 'Pending for Approval';
                userReg.Entity_Type__c= 'Non-Governmental Entity';
                userReg.Non_Governmental_Entity__c= 'nnncnnnn';
				userReg.Federal_Tax_ID__c = '33222232112';
                insert userReg;
                User_Registration__c userReg1 = new User_Registration__c();
                userReg1.Id = userReg.Id;
                userReg1.Status__c = 'Rejected';
                update userReg1;
            }
        Test.stopTest();
    }
}