codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <description>This field is used in MARS application to determine the access level they want for each agency</description>
        <inlineHelpText>User&apos;s access level</inlineHelpText>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Tribal</fullName>
                </value>
                <value>
                    <fullName>Special District</fullName>
                </value>
                <value>
                    <fullName>Courts</fullName>
                </value>
                <value>
                    <fullName>Fire Agency</fullName>
                </value>
                <value>
                    <fullName>MARS Paying Entity</fullName>
                </value>
                <value>
                    <fullName>Federal Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fire_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for users who wants to register as a contact for fire agencies. MARS app uses this field the most.</description>
        <label>Fire Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Fire Agency</value>
            </filterItems>
            <infoMessage>Please choose the Fire Agency (MARS Application)</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations (Fire Agency)</relationshipLabel>
        <relationshipName>User_Registrations6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <recordTypes>
        <fullName>MARS</fullName>
        <active>true</active>
        <description>This recordtype is used for MARS Application access requests</description>
        <label>MARS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/MARS_UserAgencyAccess_Ctrl_Test.cls
@isTest
private class MARS_UserAgencyAccess_Ctrl_Test {
    @testSetup
    static void createRecData(){     
        Account acc = new Account();
        acc.Name = 'testing';
        insert acc;
        
        Account acct = new Account();
        acct.Name = 'test case';
        acct.MACS_ID__c = '112211';
        acct.Chief_Name__c = 'testname';
        acct.BillingCity = 'Sacramento';
        acct.Entity_Type__c = 'Fire Agency';
        insert acct;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'test';
        insert con;
        
        AccountContactRelation acr = new AccountContactRelation();
        acr.AccountId = acct.Id;
        acr.ContactId = con.Id;
        acr.Relationship_Strength__c = 'Primary';
        insert acr;
        
        User_Registration__c usrReg = new User_Registration__c();
        usrReg.RecordTypeId = Schema.SObjectType.User_Registration__c.getRecordTypeInfosByName().get('MARS').getRecordTypeId();
        usrReg.Fire_Agency__c = acct.id;
        usrReg.Access_Level__c = 'Primary';
        usrReg.Status__c = 'Requested';
        usrReg.First_Name__c = 'testrecord';
        insert usrReg;
        
        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='CalOES Portal User'].id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@aqqqqp11rio.com';   
        user.CommunityNickname = 'testssjjsUser123';
        user.Alias = 't1';
        user.Email = 'no1122qq@eaaaamail.com';
        user.IsActive = true;
        user.ContactId = con.Id;
        insert user;
    }
    
    @isTest
    static void test(){
        Account acct = [SELECT Id FROM Account WHERE Name = 'test case'];
        User u = [SELECT Id FROM User WHERE FirstName = 'first'];
        User_Registration__c userReg = [SELECT Id, User__c FROM User_Registration__c WHERE First_Name__c = 'testrecord'];
        userReg.User__c = u.Id;
        update userReg;
        
        List<String> selId = new List<String>{'abc', 'bcd', 'cde'};
        
        System.runAs(u){
            MARS_UserAgencyAccess_Ctrl.getAgenciesList();
            MARS_UserAgencyAccess_Ctrl.submitNewAgencyAccessRequest('Primary', acct.Id);
            MARS_UserAgencyAccess_Ctrl.submitChangeAgencyAccessRequest('Primary', acct.Id);
            MARS_UserAgencyAccess_Ctrl.apexSearchFireAgency('test case', selId);
        }
    }
}