codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>State Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Governmental Entity</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Tribal</fullName>
                </value>
                <value>
                    <fullName>Special District</fullName>
                </value>
                <value>
                    <fullName>Courts</fullName>
                </value>
                <value>
                    <fullName>Fire Agency</fullName>
                </value>
                <value>
                    <fullName>MARS Paying Entity</fullName>
                </value>
                <value>
                    <fullName>Federal Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Mailing_Address_Different__c</fullName>
        <label>Is Mailing Address Different?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Translation_Language__c</fullName>
        <label>Translation Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en_US</fullName>
                    <label>English</label>
                </value>
                <value>
                    <fullName>es</fullName>
                    <label>Espanol</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Household_Number__c</fullName>
        <description>Unique Household Number generated for the Account When the very first member has registered to HH_Community.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique Household Number generated for the Account When the very first member has registered to HH_Community.</inlineHelpText>
        <label>Unique Household Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/CommunityRegistrationCtrlTest.cls
@IsTest(SeeAllData=true)
public class CommunityRegistrationCtrlTest {
    
    @IsTest
    public static void searchAccountTest1() {
        Test.startTest();
        Account stateAccount = PHOS_TestHelper.accountWithEntityType(true, 'State Agency');
        CommunityRegistrationCtrl.apexSearchStateAgency('NewTest', null);
        Test.stopTest();
    }
    @IsTest
    public static void searchAccountTest2() {
        Test.startTest();
        Account cityAccount = PHOS_TestHelper.accountWithEntityType(true, 'City');
        CommunityRegistrationCtrl.apexSearchCity('NewTest', null);
        Test.stopTest();
    }
    @IsTest
    public static void searchAccountTest3() {
        Test.startTest();
        Account tribalAccount = PHOS_TestHelper.accountWithEntityType(true, 'Tribal');
        CommunityRegistrationCtrl.apexSearchTribal('NewTest', null);
        Test.stopTest();
    }
    @IsTest
    public static void searchAccountTest4() {
        Test.startTest();
        Account specialDistrictAccount = PHOS_TestHelper.accountWithEntityType(true, 'Special District');
        CommunityRegistrationCtrl.apexSearchSpecialDistrict('NewTest', null);
        Test.stopTest();
    }
    @IsTest
    public static void searchAccountTest5() {
        Test.startTest();
        Account courtsAccount = PHOS_TestHelper.accountWithEntityType(true, 'Courts');
        CommunityRegistrationCtrl.apexSearchCourts('NewTest', null);
        Test.stopTest();
    }
    @IsTest
    public static void searchAccountTest6() {
        Test.startTest();
        Account facilityAccount = PHOS_TestHelper.accountWithEntityType(true, 'Health Care Facility');
        CommunityRegistrationCtrl.apexSearchFacility('NewTest', null);
        Test.stopTest();
    }
    @IsTest
    public static void createUserRegistrationRequestTest() {
        Test.startTest();
        User_Registration__c userReg = PHOS_TestHelper.getUserRegistration(false);
        userReg.Email__c = 'test12345@test.com';
        String userRegStr = JSON.serialize(userReg);
        CommunityRegistrationCtrl.createUserRegistration(userRegStr);
        User_Registration__c userRec = [Select Id, Email__c, Entity_Type__c from User_Registration__c where Email__c ='test12345@test.com'];
        System.assert(userRec.Id != null);
        Test.stopTest();
    }
    
    @IsTest
    public static void createHHUserRegistrationRequestTestEN() {
        Test.startTest();
        User_Registration__c userReg = PHOS_TestHelper.getUserRegistration(false);
        userReg.Email__c = 'test12345@test.com';
        userReg.Translation_Language__c ='en_US';
        userReg.RecordTypeId = Schema.SObjectType.User_Registration__c.getRecordTypeInfosByDeveloperName().get(System.Label.HH_RecordType_API_Name_HH_Registration).getRecordTypeId();
        userReg.Is_Mailing_Address_Different__c = HH_CONSTANTS.PickList_No;
        String userRegStr = JSON.serialize(userReg);
        CommunityRegistrationCtrl.createUserRegistration(userRegStr);
        User_Registration__c userRec = [Select Id, Email__c, Entity_Type__c from User_Registration__c where Email__c ='test12345@test.com'];
        System.assert(userRec.Id != null);
        Test.stopTest();
    }

        @IsTest
    public static void createHHUserRegistrationRequestTestES() {
        Test.startTest();
        User_Registration__c userReg = PHOS_TestHelper.getUserRegistration(false);
        userReg.Email__c = 'test12345@test.com';
        userReg.Translation_Language__c ='es';
        userReg.Unique_Household_Number__c = '4fqd4';
        userReg.RecordTypeId = Schema.SObjectType.User_Registration__c.getRecordTypeInfosByDeveloperName().get(System.Label.HH_RecordType_API_Name_HH_Registration).getRecordTypeId();
        String userRegStr = JSON.serialize(userReg);
        CommunityRegistrationCtrl.createUserRegistration(userRegStr);
        User_Registration__c userRec = [Select Id, Email__c, Entity_Type__c from User_Registration__c where Email__c ='test12345@test.com'];
        System.assert(userRec.Id != null);
        Test.stopTest();
    }
}