codepkg/objects/User_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Fire_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for users who wants to register as a contact for fire agencies. MARS app uses this field the most.</description>
        <label>Fire Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Entity_Type__c</field>
                <operation>equals</operation>
                <value>Fire Agency</value>
            </filterItems>
            <infoMessage>Please choose the Fire Agency (MARS Application)</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Registrations (Fire Agency)</relationshipLabel>
        <relationshipName>User_Registrations6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Approved</fullName>
                </value>
                <value>
                    <fullName>App Requested</fullName>
                </value>
                <value>
                    <fullName>App Rejected</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verification Pending</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Requested</fullName>
                </value>
                <value>
                    <fullName>Agency Change Requested</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Approved</fullName>
                </value>
                <value>
                    <fullName>Additional Agency Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Level Change Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Registration</label>
    <nameField>
        <displayFormat>UR-{0}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

codepkg/classes/MARS_Agency_Personnel_Ctrl_Test.cls
@IsTest
private class MARS_Agency_Personnel_Ctrl_Test {
    @testSetup
    static void createAccountRecord(){
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Account acct = new Account();
        acct.Name = 'Testing';
        insert acct;
        
        Contact con = new Contact();
        con.FirstName = 'contact';
        con.LastName = 'test';
        con.AccountId = acc.Id;
        insert con;
        
        User_Registration__c usr = new User_Registration__c();
        usr.First_Name__c = 'test';
        usr.Status__c = 'Access Level Change Requested';
        usr.Fire_Agency__c = acc.Id;
        insert usr;
        
        usr.State__c = 'App Requested';
        update usr;
        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='CalOES Portal User'].id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@aqqqqp11rio.com';   
        user.CommunityNickname = 'testssjjsUser123';
        user.Alias = 't1';
        user.Email = 'no1122qq@eaaaamail.com';
        user.IsActive = true;
        user.ContactId = con.Id;
        insert user;
        
        AccountContactRelation acr = new AccountContactRelation();
        acr.AccountId = acct.Id;
        acr.ContactId = con.Id;
        acr.Relationship_Strength__c = 'Strong';
        insert acr;
    }
    
    @IsTest
    static void getAgenciesUsersListTest(){
        Account acc = [SELECT Id, Name FROM Account WHERE Name = 'Test' LIMIT 1];
        Account accts = [SELECT Id, Name FROM Account WHERE Name = 'Testing' LIMIT 1];
        Contact con = [SELECT Id, LastName FROM Contact WHERE LastName = 'test' LIMIT 1];
        User u = [SELECT Id, AccountId FROM User WHERE FirstName = 'first' LIMIT 1];
        User_Registration__c usrId = [SELECT Id, First_Name__c FROM User_Registration__c WHERE First_Name__c = 'test' LIMIT 1]; 
        AccountContactRelation accCon = [SELECT Id, AccountId FROM AccountContactRelation WHERE AccountId = :accts.Id LIMIT 1];

        System.runAs(u){
            MARS_Agency_Personnel_Ctrl personnelCtrl = new MARS_Agency_Personnel_Ctrl();
            MARS_Agency_Personnel_Ctrl.getAgenciesUsersList(acc.Id);
            MARS_Agency_Personnel_Ctrl.getPendingAgenciesUsersList(acc.Id);
            MARS_Agency_Personnel_Ctrl.getPendingAgenciesUsersCount(acc.Id);
            MARS_Agency_Personnel_Ctrl.submitUserAccessChangeRequest('Primary', acc.Id, con.Id);
            MARS_Agency_Personnel_Ctrl.submitUserAccessChangeRequest('Secondary', acc.Id, con.Id);
            MARS_Agency_Personnel_Ctrl.submitRemoveUserAccessRequest('Primary', acc.Id, con.Id);
            MARS_Agency_Personnel_Ctrl.submitAddUserAccessRequest('Primary', acc.Id, con.Id);
            MARS_Agency_Personnel_Ctrl.submitUserAccessRejectRequest(usrId.Id);
            MARS_Agency_Personnel_Ctrl.submitUserAccessApproveRequest(usrId.Id);
            MARS_Agency_Personnel_Ctrl.getRelationshipStrength(accCon.AccountId);   
        }
    }
}