codepkg/objects/Work_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Project_Plan_Duration_In_Months__c</fullName>
        <defaultValue>00</defaultValue>
        <label>Project / Plan Duration (In Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Work Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/HMA_WorkScheduleTriggerHandler.cls
public without sharing class HMA_WorkScheduleTriggerHandler extends TriggerHandler implements TriggerInterface {
    public HMA_WorkScheduleTriggerHandler() {

    }
    public override void beforeTrigger() {
    }

    public override void beforeInsert() {
        
    } 
    public override void afterInsert() {
        
    }
    public override void beforeUpdate() {
        checkProjectPlanDuration();             // This method used for Displaing error message when Project/Plan Duration exceed 36 months.
    } 
    public override void afterUpdate() {

    }

    public static void checkProjectPlanDuration() {
        for(Work_Schedule__c ws : (List<Work_Schedule__c>) Trigger.New) {
            if(ws.Project_Plan_Duration_In_Months__c > 36) {
                ws.addError('Project/Plan Duration should not exceed 36 months. ');
            }
        }
    }
}